#!/usr/bin/env python3
"""Differential test for uds_mode22_data_getter_53b28_responder (0x55020) — pure straight-line lift, 8 bytes.
Auto-generated by tools/gen_c_lift.py — not human-verified.
Compares a Python spec_mirror against the sh2emu oracle (which runs the
actual ROM bytes) over 2000 random inputs.
Run from repo root: python3 c/tests/test_uds_mode22_data_getter_53b28_responder_55020.py
"""
import os, random, sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.join(ROOT, "tools"))
from sh2emu import SH2
from c_lift_ops import s8, s16, s32

ROM = os.path.join(ROOT, "roms", "stock", "60E1D400.bin")
ENTRY = 0x55020
RAW = bytes.fromhex("00 09 6E 03 60 EC 88 01")
SEED = 42
N = 2000

def spec_mirror(r4, r5, r6, r7):
    r = [0] * 16
    r[4], r[5], r[6], r[7] = r4 & 0xFFFFFFFF, r5 & 0xFFFFFFFF, r6 & 0xFFFFFFFF, r7 & 0xFFFFFFFF
    T = 0; Q = 0; M = 0; mach = 0; macl = 0; pr = 0xEEEE0000
    ns = {"r": r, "T": T, "Q": Q, "M": M, "mach": mach, "macl": macl, "pr": pr,
          "s8": s8, "s16": s16, "s32": s32}
    # 0x055020: op 0x0009
    
    # 0x055022: op 0x6E03
    r[14] = r[0]
    # 0x055024: op 0x60EC
    r[0] = r[14] & 0xFF
    # 0x055026: op 0x8801
    T = 1 if s32(r[0]) == s8(0x01) else 0
    return ns["r"][0] & 0xFFFFFFFF

def run(cpu, a, b, c_, d):
    # run at the original ROM entry; overlay a synthetic rts(0x000B)+nop
    # right after the pure span so PC-relative literal pools stay intact.
    # pr defaults to SENT -> emulator returns r0.
    end = ENTRY + len(RAW)
    ram = {end: 0x00, end + 1: 0x0B, end + 2: 0x00, end + 3: 0x09}
    return cpu.call(ENTRY, r4=a, r5=b, r6=c_, r7=d, ram=ram)

def main():
    rnd = random.Random(SEED)
    cpu = SH2(open(ROM, "rb").read())
    for _ in range(N):
        a = rnd.randint(0, 0xFFFFFFFF)
        b = rnd.randint(0, 0xFFFFFFFF)
        c_ = rnd.randint(0, 0xFFFFFFFF)
        d = rnd.randint(0, 0xFFFFFFFF)
        exp = spec_mirror(a, b, c_, d)
        got = run(cpu, a, b, c_, d)
        if got != exp:
            print("MISMATCH args=(%08X %08X %08X %08X) mirror=%08X emu=%08X" % (a,b,c_,d,exp,got))
            sys.exit(1)
    print("PASS 2000/2000")

if __name__ == "__main__":
    main()
