#!/usr/bin/env python3
"""Differential test for immo_comm_confirm_counter_c292 (0x36B3E) — v3 lift (branches + delay slots), 152 bytes.
Auto-generated by tools/gen_c_lift_v3.py — not human-verified.
Compares a Python pc-interpreter spec_mirror against the sh2emu oracle
(which runs the actual ROM bytes) over 2000 random inputs: deterministic RAM
prefill around the literal addresses plus a synthetic 0x400-byte stack at
STACK_BASE.  Branch cond is sampled on T BEFORE the delay slot (as sh2emu);
cases where either side leaves the modeled span / exceeds max_steps are
skipped (StepLimitExceeded -> skip).
Run from repo root: python3 c/tests/test_immo_comm_confirm_counter_c292_36b3e.py
"""
import os, random, sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.join(ROOT, "tools"))
from sh2emu import SH2, StepLimitExceeded
from c_lift_ops import s8, s16, s32

ROM = os.path.join(ROOT, "roms", "stock", "60E1D400.bin")
ROM_BYTES = open(ROM, "rb").read()
ENTRY = 0x36B3E
RAW = bytes.fromhex("32 33 8D 0C 00 09 63 41 63 3D D2 2E 33 20 8F 03 00 09 61 50 71 01 25 10 63 41 73 01 24 31 62 61 30 2C D3 29 30 EC 26 01 27 39 61 41 47 19 61 1D 61 17 62 7D 31 23 8D 03 00 09 62 50 72 01 25 20 62 DC 63 41 6D DC 37 3C 37 CC 24 71 6C CC 63 61 4D 18 4C 18 3C 2C 2C 3A 62 EC 26 C1 3D 2C 63 41 2D 3A 6D D7 24 D1 62 50 2E 2A 25 E0 D5 18 63 61 63 3D 62 41 43 28 62 2D 33 2C 61 33 21 18 8F 06 25 32 D1 13 63 12 D0 13 62 02 22 3B 25 22 4F 26 6C F6 6D F6 00 0B 6E F6")
SEED = 0
N = 2000
MAXSTEPS = 100000
STACK_BASE = 0xFFFFD000
STACK_TOP = STACK_BASE + 0x400
STACK_OFFS = (0x400, 0x404, 0x408, 0x40C)
SEED_OFFS = (0x400,)   # lds.l pr/macl/mach slots seeded with the return sentinel
RAM_MIN = 0xFFFFC278
RAM_MAX = 0xFFFFC2E0
SPAN_END = 0x36BD6
SENT = 0x36BD6     # stop-sentinel, placed past the literal pool

_WRITES = []

def _rd(ram, a):
    a &= 0xFFFFFFFF
    v = ram.get(a)
    if v is not None:
        return v
    return ROM_BYTES[a] if a < len(ROM_BYTES) else 0

def _rdw(ram, a, n):
    a &= 0xFFFFFFFF
    return int.from_bytes(bytes(_rd(ram, (a + i) & 0xFFFFFFFF) for i in range(n)), "big")

def _wrw(ram, a, n, v):
    a &= 0xFFFFFFFF
    for i in range(n):
        ad = (a + i) & 0xFFFFFFFF
        ram[ad] = (v >> (8 * (n - 1 - i))) & 0xFF
        _WRITES.append(ad)

CODE = {
    0x36b3e: {"kind": 'reg', "py": 'T = 1 if s32(r[2]) >= s32(r[3]) else 0', "slot_py": None, "target": None, "cond": None},
    0x36b40: {"kind": "branch", "py": None, "slot_py": '', "target": 0x36b5c, "cond": 'T'},
    0x36b44: {"kind": 'mem', "py": 'r[3] = s16(_rdw(ram, r[4], 2))', "slot_py": None, "target": None, "cond": None},
    0x36b46: {"kind": 'reg', "py": 'r[3] = r[3] & 0xFFFF', "slot_py": None, "target": None, "cond": None},
    0x36b48: {"kind": 'reg', "py": 'r[2] = 0x0000FFFF', "slot_py": None, "target": None, "cond": None},
    0x36b4a: {"kind": 'reg', "py": 'T = 1 if r[3] == r[2] else 0', "slot_py": None, "target": None, "cond": None},
    0x36b4c: {"kind": "branch", "py": None, "slot_py": '', "target": 0x36b56, "cond": 'notT'},
    0x36b50: {"kind": 'mem', "py": 'r[1] = s8(_rdw(ram, r[5], 1))', "slot_py": None, "target": None, "cond": None},
    0x36b52: {"kind": 'reg', "py": 'r[1] = (r[1] + s8(0x01)) & 0xFFFFFFFF', "slot_py": None, "target": None, "cond": None},
    0x36b54: {"kind": 'mem', "py": '_wrw(ram, r[5], 1, r[1])', "slot_py": None, "target": None, "cond": None},
    0x36b56: {"kind": 'mem', "py": 'r[3] = s16(_rdw(ram, r[4], 2))', "slot_py": None, "target": None, "cond": None},
    0x36b58: {"kind": 'reg', "py": 'r[3] = (r[3] + s8(0x01)) & 0xFFFFFFFF', "slot_py": None, "target": None, "cond": None},
    0x36b5a: {"kind": 'mem', "py": '_wrw(ram, r[4], 2, r[3])', "slot_py": None, "target": None, "cond": None},
    0x36b5c: {"kind": 'mem', "py": 'r[2] = s16(_rdw(ram, r[6], 2))', "slot_py": None, "target": None, "cond": None},
    0x36b5e: {"kind": 'reg', "py": 'r[0] = (r[0] + r[2]) & 0xFFFFFFFF', "slot_py": None, "target": None, "cond": None},
    0x36b60: {"kind": 'reg', "py": 'r[3] = 0x00FFFF00', "slot_py": None, "target": None, "cond": None},
    0x36b62: {"kind": 'reg', "py": 'r[0] = (r[0] + r[14]) & 0xFFFFFFFF', "slot_py": None, "target": None, "cond": None},
    0x36b64: {"kind": 'mem', "py": '_wrw(ram, r[6], 2, r[0])', "slot_py": None, "target": None, "cond": None},
    0x36b66: {"kind": 'reg', "py": 'r[7] = (r[7] & r[3]) & 0xFFFFFFFF', "slot_py": None, "target": None, "cond": None},
    0x36b68: {"kind": 'mem', "py": 'r[1] = s16(_rdw(ram, r[4], 2))', "slot_py": None, "target": None, "cond": None},
    0x36b6a: {"kind": 'reg', "py": 'r[7] = (r[7] >> 8) & 0xFFFFFFFF', "slot_py": None, "target": None, "cond": None},
    0x36b6c: {"kind": 'reg', "py": 'r[1] = r[1] & 0xFFFF', "slot_py": None, "target": None, "cond": None},
    0x36b6e: {"kind": 'reg', "py": 'r[1] = (~r[1]) & 0xFFFFFFFF', "slot_py": None, "target": None, "cond": None},
    0x36b70: {"kind": 'reg', "py": 'r[2] = r[7] & 0xFFFF', "slot_py": None, "target": None, "cond": None},
    0x36b72: {"kind": 'reg', "py": 'T = 1 if s32(r[1]) >= s32(r[2]) else 0', "slot_py": None, "target": None, "cond": None},
    0x36b74: {"kind": "branch", "py": None, "slot_py": '', "target": 0x36b7e, "cond": 'T'},
    0x36b78: {"kind": 'mem', "py": 'r[2] = s8(_rdw(ram, r[5], 1))', "slot_py": None, "target": None, "cond": None},
    0x36b7a: {"kind": 'reg', "py": 'r[2] = (r[2] + s8(0x01)) & 0xFFFFFFFF', "slot_py": None, "target": None, "cond": None},
    0x36b7c: {"kind": 'mem', "py": '_wrw(ram, r[5], 1, r[2])', "slot_py": None, "target": None, "cond": None},
    0x36b7e: {"kind": 'reg', "py": 'r[2] = r[13] & 0xFF', "slot_py": None, "target": None, "cond": None},
    0x36b80: {"kind": 'mem', "py": 'r[3] = s16(_rdw(ram, r[4], 2))', "slot_py": None, "target": None, "cond": None},
    0x36b82: {"kind": 'reg', "py": 'r[13] = r[13] & 0xFF', "slot_py": None, "target": None, "cond": None},
    0x36b84: {"kind": 'reg', "py": 'r[7] = (r[7] + r[3]) & 0xFFFFFFFF', "slot_py": None, "target": None, "cond": None},
    0x36b86: {"kind": 'reg', "py": 'r[7] = (r[7] + r[12]) & 0xFFFFFFFF', "slot_py": None, "target": None, "cond": None},
    0x36b88: {"kind": 'mem', "py": '_wrw(ram, r[4], 2, r[7])', "slot_py": None, "target": None, "cond": None},
    0x36b8a: {"kind": 'reg', "py": 'r[12] = r[12] & 0xFF', "slot_py": None, "target": None, "cond": None},
    0x36b8c: {"kind": 'mem', "py": 'r[3] = s16(_rdw(ram, r[6], 2))', "slot_py": None, "target": None, "cond": None},
    0x36b8e: {"kind": 'reg', "py": 'r[13] = (r[13] << 8) & 0xFFFFFFFF', "slot_py": None, "target": None, "cond": None},
    0x36b90: {"kind": 'reg', "py": 'r[12] = (r[12] << 8) & 0xFFFFFFFF', "slot_py": None, "target": None, "cond": None},
    0x36b92: {"kind": 'reg', "py": 'r[12] = (r[12] + r[2]) & 0xFFFFFFFF', "slot_py": None, "target": None, "cond": None},
    0x36b94: {"kind": 'reg', "py": 'r[12] = (r[12] ^ r[3]) & 0xFFFFFFFF', "slot_py": None, "target": None, "cond": None},
    0x36b96: {"kind": 'reg', "py": 'r[2] = r[14] & 0xFF', "slot_py": None, "target": None, "cond": None},
    0x36b98: {"kind": 'mem', "py": '_wrw(ram, r[6], 2, r[12])', "slot_py": None, "target": None, "cond": None},
    0x36b9a: {"kind": 'reg', "py": 'r[13] = (r[13] + r[2]) & 0xFFFFFFFF', "slot_py": None, "target": None, "cond": None},
    0x36b9c: {"kind": 'mem', "py": 'r[3] = s16(_rdw(ram, r[4], 2))', "slot_py": None, "target": None, "cond": None},
    0x36b9e: {"kind": 'reg', "py": 'r[13] = (r[13] ^ r[3]) & 0xFFFFFFFF', "slot_py": None, "target": None, "cond": None},
    0x36ba0: {"kind": 'reg', "py": 'r[13] = (~r[13]) & 0xFFFFFFFF', "slot_py": None, "target": None, "cond": None},
    0x36ba2: {"kind": 'mem', "py": '_wrw(ram, r[4], 2, r[13])', "slot_py": None, "target": None, "cond": None},
    0x36ba4: {"kind": 'mem', "py": 'r[2] = s8(_rdw(ram, r[5], 1))', "slot_py": None, "target": None, "cond": None},
    0x36ba6: {"kind": 'reg', "py": 'r[14] = (r[14] ^ r[2]) & 0xFFFFFFFF', "slot_py": None, "target": None, "cond": None},
    0x36ba8: {"kind": 'mem', "py": '_wrw(ram, r[5], 1, r[14])', "slot_py": None, "target": None, "cond": None},
    0x36baa: {"kind": 'reg', "py": 'r[5] = 0xFFFFC278', "slot_py": None, "target": None, "cond": None},
    0x36bac: {"kind": 'mem', "py": 'r[3] = s16(_rdw(ram, r[6], 2))', "slot_py": None, "target": None, "cond": None},
    0x36bae: {"kind": 'reg', "py": 'r[3] = r[3] & 0xFFFF', "slot_py": None, "target": None, "cond": None},
    0x36bb0: {"kind": 'mem', "py": 'r[2] = s16(_rdw(ram, r[4], 2))', "slot_py": None, "target": None, "cond": None},
    0x36bb2: {"kind": 'reg', "py": 'r[3] = (r[3] << 16) & 0xFFFFFFFF', "slot_py": None, "target": None, "cond": None},
    0x36bb4: {"kind": 'reg', "py": 'r[2] = r[2] & 0xFFFF', "slot_py": None, "target": None, "cond": None},
    0x36bb6: {"kind": 'reg', "py": 'r[3] = (r[3] + r[2]) & 0xFFFFFFFF', "slot_py": None, "target": None, "cond": None},
    0x36bb8: {"kind": 'reg', "py": 'r[1] = r[3]', "slot_py": None, "target": None, "cond": None},
    0x36bba: {"kind": 'reg', "py": 'T = 1 if (r[1] & r[1]) == 0 else 0', "slot_py": None, "target": None, "cond": None},
    0x36bbc: {"kind": "branch", "py": None, "slot_py": '_wrw(ram, 0xFFFFC278, 4, r[3])', "target": 0x36bcc, "cond": 'notT'},
    0x36bc0: {"kind": 'reg', "py": 'r[1] = 0xFFFFC2E0', "slot_py": None, "target": None, "cond": None},
    0x36bc2: {"kind": 'mem', "py": 'r[3] = _rdw(ram, 0xFFFFC2E0, 4)', "slot_py": None, "target": None, "cond": None},
    0x36bc4: {"kind": 'reg', "py": 'r[0] = 0xFFFFC2DC', "slot_py": None, "target": None, "cond": None},
    0x36bc6: {"kind": 'mem', "py": 'r[2] = _rdw(ram, 0xFFFFC2DC, 4)', "slot_py": None, "target": None, "cond": None},
    0x36bc8: {"kind": 'reg', "py": 'r[2] = (r[2] | r[3]) & 0xFFFFFFFF', "slot_py": None, "target": None, "cond": None},
    0x36bca: {"kind": 'mem', "py": '_wrw(ram, 0xFFFFC278, 4, r[2])', "slot_py": None, "target": None, "cond": None},
    0x36bcc: {"kind": 'mem', "py": 'pr = _rdw(ram, STACK_BASE + 0x400, 4)\nsp = (sp + 4) & 0xFFFFFFFF', "slot_py": None, "target": None, "cond": None},
    0x36bce: {"kind": 'mem', "py": 'r[12] = _rdw(ram, STACK_BASE + 0x404, 4)\nsp = (sp + 4) & 0xFFFFFFFF', "slot_py": None, "target": None, "cond": None},
    0x36bd0: {"kind": 'mem', "py": 'r[13] = _rdw(ram, STACK_BASE + 0x408, 4)\nsp = (sp + 4) & 0xFFFFFFFF', "slot_py": None, "target": None, "cond": None},
    0x36bd2: {"kind": "ret", "py": None, "slot_py": 'r[14] = _rdw(ram, STACK_BASE + 0x40C, 4)\nsp = (sp + 4) & 0xFFFFFFFF', "target": None, "cond": None},}

def spec_mirror(r4, r5, r6, r7, ram, gbr=0):
    """pc-interpreter over CODE; returns ("RET", regs, writes, ram, pr) or
    ("SKIP"/"ERR", detail).  Every instruction is the mapper py fragment
    exec'd in a shared ns (registers/T/ram/writes follow sh2emu)."""
    global _WRITES
    _WRITES[:] = []
    r = [0] * 16
    r[4], r[5], r[6], r[7] = r4 & 0xFFFFFFFF, r5 & 0xFFFFFFFF, r6 & 0xFFFFFFFF, r7 & 0xFFFFFFFF
    r[15] = STACK_TOP & 0xFFFFFFFF
    ns = {"r": r, "T": 0, "Q": 0, "M": 0, "mach": 0, "macl": 0, "pr": 0xEEEE0000,
          "sr": 0x000000F0,  # sh2emu call() default (independent of T)
          "s8": s8, "s16": s16, "s32": s32, "ram": ram, "sp": r[15],
          "gbr": gbr & 0xFFFFFFFF,
          "local": {off: _rdw(ram, STACK_BASE + off, 4) for off in STACK_OFFS},
          "_rdw": _rdw, "_wrw": _wrw, "STACK_BASE": STACK_BASE}
    pc = ENTRY
    steps = 0
    while True:
        steps += 1
        if steps > MAXSTEPS:
            return ("SKIP", None)
        inst = CODE.get(pc)
        if inst is None:
            return ("ERR", pc)
        kind = inst["kind"]
        if kind == "branch":
            t = ns["T"]
            cond = inst["cond"]
            taken = True
            if cond == "T":
                taken = (t == 1)
            elif cond == "notT":
                taken = (t == 0)
            slot_py = inst["slot_py"]
            if slot_py:
                exec(slot_py, ns)
            if taken:
                pc = inst["target"]
            elif slot_py is not None:
                pc = pc + 4            # delayed: slot at P+2 already ran
            else:
                pc = pc + 2            # non-delayed bt/bf
        elif kind == "dynbranch":
            slot_py = inst["slot_py"]
            if slot_py:
                exec(slot_py, ns)
            if inst["set_pr"]:
                ns["pr"] = (pc + 4) & 0xFFFFFFFF
            pc = (pc + 4 + ns["r"][inst["reg"]]) & 0xFFFFFFFF
        elif kind == "ret":
            slot_py = inst["slot_py"]
            if slot_py:
                exec(slot_py, ns)
            r[15] = ns["sp"] & 0xFFFFFFFF
            return ("RET", [x & 0xFFFFFFFF for x in r], _WRITES, ram, ns["pr"] & 0xFFFFFFFF,
                    ns["macl"] & 0xFFFFFFFF, ns["mach"] & 0xFFFFFFFF)
        else:
            py = inst["py"]
            if py:
                exec(py, ns)
            pc = pc + 2

def run(cpu, ram, a, b, c_, d, gbr=0):
    ram = dict(ram)
    ram[SENT] = 0x00; ram[SENT + 1] = 0x0B; ram[SENT + 2] = 0x00; ram[SENT + 3] = 0x09
    cpu.call(ENTRY, r4=a, r5=b, r6=c_, r7=d, ram=ram, regs={15: STACK_TOP, "gbr": gbr},
             max_steps=MAXSTEPS)
    out = dict(cpu.ram)
    for i in range(4):
        out.pop(SENT + i, None)
    return (cpu.r[0] & 0xFFFFFFFF, [x & 0xFFFFFFFF for x in cpu.r], out,
            cpu.pr & 0xFFFFFFFF, cpu.macl & 0xFFFFFFFF,
            cpu.mach & 0xFFFFFFFF)

def main():
    rnd = random.Random(SEED)
    cpu = SH2(ROM_BYTES)
    skipped = 0
    for caso in range(N):
        ram = {}
        if RAM_MIN is not None:
            for a in range(RAM_MIN - 0x400, RAM_MAX + 0x401):
                ram[a] = (a * 0x9E3779B1 + caso * 0x10003) & 0xFF
        for a in range(STACK_BASE, STACK_BASE + 0x400):
            ram[a] = (a * 0x9E3779B1 + caso * 0x10003) & 0xFF
        for off in SEED_OFFS:
            for i in range(4):
                ram[STACK_BASE + off + i] = (0xEEEE0000 >> (8 * (3 - i))) & 0xFF
        a = rnd.randint(0, 0xFFFFFFFF)
        b = rnd.randint(0, 0xFFFFFFFF)
        c_ = rnd.randint(0, 0xFFFFFFFF)
        d = rnd.randint(0, 0xFFFFFFFF)
        gbr = rnd.randint(0, 0xFFFFFFFF)
        m = spec_mirror(a, b, c_, d, dict(ram), gbr)
        if m[0] != "RET":
            skipped += 1
            continue
        try:
            g = run(cpu, ram, a, b, c_, d, gbr)
        except (StepLimitExceeded, NotImplementedError, RuntimeError):
            skipped += 1
            continue
        _, exp_regs, _, exp_ram, exp_pr, exp_macl, exp_mach = m
        _, got_regs, got_ram, got_pr, got_macl, got_mach = g
        for i in range(16):
            if exp_regs[i] != got_regs[i]:
                print("MISMATCH case=%d reg=r%d mirror=%08X emu=%08X" % (caso, i, exp_regs[i], got_regs[i]))
                sys.exit(1)
        if exp_pr != got_pr:
            print("MISMATCH case=%d reg=pr mirror=%08X emu=%08X" % (caso, exp_pr, got_pr))
            sys.exit(1)
        if exp_macl != got_macl:
            print("MISMATCH case=%d reg=macl mirror=%08X emu=%08X" % (caso, exp_macl, got_macl))
            sys.exit(1)
        if exp_mach != got_mach:
            print("MISMATCH case=%d reg=mach mirror=%08X emu=%08X" % (caso, exp_mach, got_mach))
            sys.exit(1)
        for ad in sorted(set(exp_ram) | set(got_ram)):
            if any(STACK_BASE + off <= ad < STACK_BASE + off + 4 for off in SEED_OFFS):
                continue
            if exp_ram.get(ad, 0) != got_ram.get(ad, 0):
                print("MISMATCH case=%d addr=0x%08X mirror=%02X emu=%02X" % (caso, ad, exp_ram.get(ad, 0), got_ram.get(ad, 0)))
                sys.exit(1)
    ok = N - skipped
    if skipped > 200 or ok == 0:
        print("FAIL %d/%d (skipped=%d)" % (ok, N, skipped))
        sys.exit(1)
    print("PASS %d/%d (skipped=%d)" % (ok, N, skipped))

if __name__ == "__main__":
    main()
