#!/usr/bin/env python3
"""Differential test for FUN_0004c8d0 (0x4C8D0) — v3 lift (branches + delay slots), 164 bytes.
Auto-generated by tools/gen_c_lift_v3.py — not human-verified.
Compares a Python pc-interpreter spec_mirror against the sh2emu oracle
(which runs the actual ROM bytes) over 500 random inputs: deterministic RAM
prefill around the literal addresses plus a synthetic 0x400-byte stack at
STACK_BASE.  Branch cond is sampled on T BEFORE the delay slot (as sh2emu);
cases where either side leaves the modeled span / exceeds max_steps are
skipped (StepLimitExceeded -> skip).
Run from repo root: python3 c/tests/test_FUN_0004c8d0_4c8d0.py
"""
import os, random, sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.join(ROOT, "tools"))
from sh2emu import SH2, StepLimitExceeded
from c_lift_ops import s8, s16, s32

ROM = os.path.join(ROOT, "roms", "stock", "60E0FC00.bin")
ROM_BYTES = open(ROM, "rb").read()
ENTRY = 0x4C8D0
RAW = bytes.fromhex("2F E6 93 45 97 45 65 30 DE 24 66 5C 60 63 88 01 8F 10 E4 00 61 E0 21 18 8F 03 00 09 E0 01 A0 0A 27 00 92 37 D3 1E 61 20 60 30 31 00 8F 03 00 09 A0 01 27 40 27 40 60 63 97 2D 88 01 8D 0F 00 09 93 2A 60 30 60 0C 88 01 8F 0B 00 09 90 1F 60 00 C8 80 00 29 70 FF 60 0B 88 01 8F 02 00 09 A0 10 27 40 60 E0 60 0C 88 01 8F 03 00 09 E2 01 A0 08 27 20 93 12 D0 0A 61 30 62 00 31 20 8F 01 00 09 27 40 2E 50 00 0B 6E F6 CD BC CD A6 CD A4 CD B2 CD BA CD B7 CD A8 CD B8 CF 4B CD AA FF FF CD D0 00 07 B8 10")
SEED = 42
N = 500
MAXSTEPS = 100000
STACK_BASE = 0xFFFFD000
STACK_TOP = STACK_BASE + 0x400
STACK_OFFS = (0x3FC,)
SEED_OFFS = (())   # lds.l pr/macl/mach slots seeded with the return sentinel
RAM_MIN = 0xFFFFCDA8
RAM_MAX = 0xFFFFCF4B
SPAN_END = 0x4C974
SENT = 0x4C974     # stop-sentinel, placed past the literal pool

_WRITES = []

def _rd(ram, a):
    a &= 0xFFFFFFFF
    v = ram.get(a)
    if v is not None:
        return v
    return ROM_BYTES[a] if a < len(ROM_BYTES) else 0

def _rdw(ram, a, n):
    a &= 0xFFFFFFFF
    return int.from_bytes(bytes(_rd(ram, (a + i) & 0xFFFFFFFF) for i in range(n)), "big")

def _wrw(ram, a, n, v):
    a &= 0xFFFFFFFF
    for i in range(n):
        ad = (a + i) & 0xFFFFFFFF
        ram[ad] = (v >> (8 * (n - 1 - i))) & 0xFF
        _WRITES.append(ad)

CODE = {
    0x4c8d0: {"kind": 'mem', "py": 'local[0x3FC] = r[14]\n_wrw(ram, STACK_BASE + 0x3FC, 4, r[14])\nsp = (sp - 4) & 0xFFFFFFFF', "slot_py": None, "target": None, "cond": None},
    0x4c8d2: {"kind": 'reg', "py": 'r[3] = 0xFFFFCDBA', "slot_py": None, "target": None, "cond": None},
    0x4c8d4: {"kind": 'reg', "py": 'r[7] = 0xFFFFCDB7', "slot_py": None, "target": None, "cond": None},
    0x4c8d6: {"kind": 'mem', "py": 'r[5] = s8(_rdw(ram, 0xFFFFCDBA, 1))', "slot_py": None, "target": None, "cond": None},
    0x4c8d8: {"kind": 'reg', "py": 'r[14] = 0xFFFFCDD0', "slot_py": None, "target": None, "cond": None},
    0x4c8da: {"kind": 'reg', "py": 'r[6] = r[5] & 0xFF', "slot_py": None, "target": None, "cond": None},
    0x4c8dc: {"kind": 'reg', "py": 'r[0] = r[6]', "slot_py": None, "target": None, "cond": None},
    0x4c8de: {"kind": 'reg', "py": 'T = 1 if s32(r[0]) == s8(0x01) else 0', "slot_py": None, "target": None, "cond": None},
    0x4c8e0: {"kind": "branch", "py": None, "slot_py": 'r[4] = s8(0x00)', "target": 0x4c904, "cond": 'notT'},
    0x4c8e4: {"kind": 'mem', "py": 'r[1] = s8(_rdw(ram, 0xFFFFCDD0, 1))', "slot_py": None, "target": None, "cond": None},
    0x4c8e6: {"kind": 'reg', "py": 'T = 1 if (r[1] & r[1]) == 0 else 0', "slot_py": None, "target": None, "cond": None},
    0x4c8e8: {"kind": "branch", "py": None, "slot_py": '', "target": 0x4c8f2, "cond": 'notT'},
    0x4c8ec: {"kind": 'reg', "py": 'r[0] = s8(0x01)', "slot_py": None, "target": None, "cond": None},
    0x4c8ee: {"kind": "branch", "py": None, "slot_py": '_wrw(ram, 0xFFFFCDB7, 1, r[0])', "target": 0x4c906, "cond": 'always'},
    0x4c8f2: {"kind": 'reg', "py": 'r[2] = 0xFFFFCDA8', "slot_py": None, "target": None, "cond": None},
    0x4c8f4: {"kind": 'reg', "py": 'r[3] = 0x0007B810', "slot_py": None, "target": None, "cond": None},
    0x4c8f6: {"kind": 'mem', "py": 'r[1] = s8(_rdw(ram, 0xFFFFCDA8, 1))', "slot_py": None, "target": None, "cond": None},
    0x4c8f8: {"kind": 'mem', "py": 'r[0] = s8(_rdw(ram, 0x0007B810, 1))', "slot_py": None, "target": None, "cond": None},
    0x4c8fa: {"kind": 'reg', "py": 'T = 1 if r[1] == r[0] else 0', "slot_py": None, "target": None, "cond": None},
    0x4c8fc: {"kind": "branch", "py": None, "slot_py": '', "target": 0x4c906, "cond": 'notT'},
    0x4c900: {"kind": "branch", "py": None, "slot_py": '_wrw(ram, 0xFFFFCDB7, 1, r[4])', "target": 0x4c906, "cond": 'always'},
    0x4c904: {"kind": 'mem', "py": '_wrw(ram, r[7], 1, r[4])', "slot_py": None, "target": None, "cond": None},
    0x4c906: {"kind": 'reg', "py": 'r[0] = r[6]', "slot_py": None, "target": None, "cond": None},
    0x4c908: {"kind": 'reg', "py": 'r[7] = 0xFFFFCDB8', "slot_py": None, "target": None, "cond": None},
    0x4c90a: {"kind": 'reg', "py": 'T = 1 if s32(r[0]) == s8(0x01) else 0', "slot_py": None, "target": None, "cond": None},
    0x4c90c: {"kind": "branch", "py": None, "slot_py": '', "target": 0x4c92e, "cond": 'T'},
    0x4c910: {"kind": 'reg', "py": 'r[3] = 0xFFFFCF4B', "slot_py": None, "target": None, "cond": None},
    0x4c912: {"kind": 'mem', "py": 'r[0] = s8(_rdw(ram, 0xFFFFCF4B, 1))', "slot_py": None, "target": None, "cond": None},
    0x4c914: {"kind": 'reg', "py": 'r[0] = r[0] & 0xFF', "slot_py": None, "target": None, "cond": None},
    0x4c916: {"kind": 'reg', "py": 'T = 1 if s32(r[0]) == s8(0x01) else 0', "slot_py": None, "target": None, "cond": None},
    0x4c918: {"kind": "branch", "py": None, "slot_py": '', "target": 0x4c932, "cond": 'notT'},
    0x4c91c: {"kind": 'reg', "py": 'r[0] = 0xFFFFCDB2', "slot_py": None, "target": None, "cond": None},
    0x4c91e: {"kind": 'mem', "py": 'r[0] = s8(_rdw(ram, 0xFFFFCDB2, 1))', "slot_py": None, "target": None, "cond": None},
    0x4c920: {"kind": 'reg', "py": 'T = 1 if (r[0] & 0x80) == 0 else 0', "slot_py": None, "target": None, "cond": None},
    0x4c922: {"kind": 'reg', "py": 'r[0] = T;', "slot_py": None, "target": None, "cond": None},
    0x4c924: {"kind": 'reg', "py": 'r[0] = (r[0] + s8(0xFF)) & 0xFFFFFFFF', "slot_py": None, "target": None, "cond": None},
    0x4c926: {"kind": 'reg', "py": 'r[0] = (-r[0]) & 0xFFFFFFFF', "slot_py": None, "target": None, "cond": None},
    0x4c928: {"kind": 'reg', "py": 'T = 1 if s32(r[0]) == s8(0x01) else 0', "slot_py": None, "target": None, "cond": None},
    0x4c92a: {"kind": "branch", "py": None, "slot_py": '', "target": 0x4c932, "cond": 'notT'},
    0x4c92e: {"kind": "branch", "py": None, "slot_py": '_wrw(ram, 0xFFFFCDB8, 1, r[4])', "target": 0x4c952, "cond": 'always'},
    0x4c932: {"kind": 'mem', "py": 'r[0] = s8(_rdw(ram, r[14], 1))', "slot_py": None, "target": None, "cond": None},
    0x4c934: {"kind": 'reg', "py": 'r[0] = r[0] & 0xFF', "slot_py": None, "target": None, "cond": None},
    0x4c936: {"kind": 'reg', "py": 'T = 1 if s32(r[0]) == s8(0x01) else 0', "slot_py": None, "target": None, "cond": None},
    0x4c938: {"kind": "branch", "py": None, "slot_py": '', "target": 0x4c942, "cond": 'notT'},
    0x4c93c: {"kind": 'reg', "py": 'r[2] = s8(0x01)', "slot_py": None, "target": None, "cond": None},
    0x4c93e: {"kind": "branch", "py": None, "slot_py": '_wrw(ram, 0xFFFFCDB8, 1, r[2])', "target": 0x4c952, "cond": 'always'},
    0x4c942: {"kind": 'reg', "py": 'r[3] = 0xFFFFCDAA', "slot_py": None, "target": None, "cond": None},
    0x4c944: {"kind": 'reg', "py": 'r[0] = 0x0007B810', "slot_py": None, "target": None, "cond": None},
    0x4c946: {"kind": 'mem', "py": 'r[1] = s8(_rdw(ram, 0xFFFFCDAA, 1))', "slot_py": None, "target": None, "cond": None},
    0x4c948: {"kind": 'mem', "py": 'r[2] = s8(_rdw(ram, 0x0007B810, 1))', "slot_py": None, "target": None, "cond": None},
    0x4c94a: {"kind": 'reg', "py": 'T = 1 if r[1] == r[2] else 0', "slot_py": None, "target": None, "cond": None},
    0x4c94c: {"kind": "branch", "py": None, "slot_py": '', "target": 0x4c952, "cond": 'notT'},
    0x4c950: {"kind": 'mem', "py": '_wrw(ram, 0xFFFFCDB8, 1, r[4])', "slot_py": None, "target": None, "cond": None},
    0x4c952: {"kind": 'mem', "py": '_wrw(ram, r[14], 1, r[5])', "slot_py": None, "target": None, "cond": None},
    0x4c954: {"kind": "ret", "py": None, "slot_py": 'r[14] = _rdw(ram, STACK_BASE + 0x3FC, 4)\nsp = (sp + 4) & 0xFFFFFFFF', "target": None, "cond": None},
    0x4c958: {"kind": 'mem', "py": '_wrw(ram, (gbr + r[0]), 1, _rdw(ram, (gbr + r[0]), 1) & 0xBC)', "slot_py": None, "target": None, "cond": None},
    0x4c95a: {"kind": 'mem', "py": '_wrw(ram, (gbr + r[0]), 1, _rdw(ram, (gbr + r[0]), 1) & 0xA6)', "slot_py": None, "target": None, "cond": None},
    0x4c95c: {"kind": 'mem', "py": '_wrw(ram, (gbr + r[0]), 1, _rdw(ram, (gbr + r[0]), 1) & 0xA4)', "slot_py": None, "target": None, "cond": None},}

def spec_mirror(r4, r5, r6, r7, ram, gbr=0):
    """pc-interpreter over CODE; returns ("RET", regs, writes, ram, pr) or
    ("SKIP"/"ERR", detail).  Every instruction is the mapper py fragment
    exec'd in a shared ns (registers/T/ram/writes follow sh2emu)."""
    global _WRITES
    _WRITES[:] = []
    r = [0] * 16
    r[4], r[5], r[6], r[7] = r4 & 0xFFFFFFFF, r5 & 0xFFFFFFFF, r6 & 0xFFFFFFFF, r7 & 0xFFFFFFFF
    r[15] = STACK_TOP & 0xFFFFFFFF
    ns = {"r": r, "T": 0, "Q": 0, "M": 0, "mach": 0, "macl": 0, "pr": 0xEEEE0000,
          "sr": 0x000000F0,  # sh2emu call() default (independent of T)
          "s8": s8, "s16": s16, "s32": s32, "ram": ram, "sp": r[15],
          "gbr": gbr & 0xFFFFFFFF,
          "local": {off: _rdw(ram, STACK_BASE + off, 4) for off in STACK_OFFS},
          "_rdw": _rdw, "_wrw": _wrw, "STACK_BASE": STACK_BASE}
    pc = ENTRY
    steps = 0
    while True:
        steps += 1
        if steps > MAXSTEPS:
            return ("SKIP", None)
        inst = CODE.get(pc)
        if inst is None:
            return ("ERR", pc)
        kind = inst["kind"]
        if kind == "branch":
            t = ns["T"]
            cond = inst["cond"]
            taken = True
            if cond == "T":
                taken = (t == 1)
            elif cond == "notT":
                taken = (t == 0)
            slot_py = inst["slot_py"]
            if slot_py:
                exec(slot_py, ns)
            if taken:
                pc = inst["target"]
            elif slot_py is not None:
                pc = pc + 4            # delayed: slot at P+2 already ran
            else:
                pc = pc + 2            # non-delayed bt/bf
        elif kind == "dynbranch":
            slot_py = inst["slot_py"]
            if slot_py:
                exec(slot_py, ns)
            if inst["set_pr"]:
                ns["pr"] = (pc + 4) & 0xFFFFFFFF
            pc = (pc + 4 + ns["r"][inst["reg"]]) & 0xFFFFFFFF
        elif kind == "ret":
            slot_py = inst["slot_py"]
            if slot_py:
                exec(slot_py, ns)
            r[15] = ns["sp"] & 0xFFFFFFFF
            return ("RET", [x & 0xFFFFFFFF for x in r], _WRITES, ram, ns["pr"] & 0xFFFFFFFF,
                    ns["macl"] & 0xFFFFFFFF, ns["mach"] & 0xFFFFFFFF)
        else:
            py = inst["py"]
            if py:
                exec(py, ns)
            pc = pc + 2

def run(cpu, ram, a, b, c_, d, gbr=0):
    ram = dict(ram)
    ram[SENT] = 0x00; ram[SENT + 1] = 0x0B; ram[SENT + 2] = 0x00; ram[SENT + 3] = 0x09
    cpu.call(ENTRY, r4=a, r5=b, r6=c_, r7=d, ram=ram, regs={15: STACK_TOP, "gbr": gbr},
             max_steps=MAXSTEPS)
    out = dict(cpu.ram)
    for i in range(4):
        out.pop(SENT + i, None)
    return (cpu.r[0] & 0xFFFFFFFF, [x & 0xFFFFFFFF for x in cpu.r], out,
            cpu.pr & 0xFFFFFFFF, cpu.macl & 0xFFFFFFFF,
            cpu.mach & 0xFFFFFFFF)

def main():
    rnd = random.Random(SEED)
    cpu = SH2(ROM_BYTES)
    skipped = 0
    for caso in range(N):
        ram = {}
        if RAM_MIN is not None:
            for a in range(RAM_MIN - 0x400, RAM_MAX + 0x401):
                ram[a] = (a * 0x9E3779B1 + caso * 0x10003) & 0xFF
        for a in range(STACK_BASE, STACK_BASE + 0x400):
            ram[a] = (a * 0x9E3779B1 + caso * 0x10003) & 0xFF
        for off in SEED_OFFS:
            for i in range(4):
                ram[STACK_BASE + off + i] = (0xEEEE0000 >> (8 * (3 - i))) & 0xFF
        a = rnd.randint(0, 0xFFFFFFFF)
        b = rnd.randint(0, 0xFFFFFFFF)
        c_ = rnd.randint(0, 0xFFFFFFFF)
        d = rnd.randint(0, 0xFFFFFFFF)
        gbr = rnd.randint(0, 0xFFFFFFFF)
        m = spec_mirror(a, b, c_, d, dict(ram), gbr)
        if m[0] != "RET":
            skipped += 1
            continue
        try:
            g = run(cpu, ram, a, b, c_, d, gbr)
        except (StepLimitExceeded, NotImplementedError, RuntimeError):
            skipped += 1
            continue
        _, exp_regs, _, exp_ram, exp_pr, exp_macl, exp_mach = m
        _, got_regs, got_ram, got_pr, got_macl, got_mach = g
        for i in range(16):
            if exp_regs[i] != got_regs[i]:
                print("MISMATCH case=%d reg=r%d mirror=%08X emu=%08X" % (caso, i, exp_regs[i], got_regs[i]))
                sys.exit(1)
        if exp_pr != got_pr:
            print("MISMATCH case=%d reg=pr mirror=%08X emu=%08X" % (caso, exp_pr, got_pr))
            sys.exit(1)
        if exp_macl != got_macl:
            print("MISMATCH case=%d reg=macl mirror=%08X emu=%08X" % (caso, exp_macl, got_macl))
            sys.exit(1)
        if exp_mach != got_mach:
            print("MISMATCH case=%d reg=mach mirror=%08X emu=%08X" % (caso, exp_mach, got_mach))
            sys.exit(1)
        for ad in sorted(set(exp_ram) | set(got_ram)):
            if any(STACK_BASE + off <= ad < STACK_BASE + off + 4 for off in SEED_OFFS):
                continue
            if exp_ram.get(ad, 0) != got_ram.get(ad, 0):
                print("MISMATCH case=%d addr=0x%08X mirror=%02X emu=%02X" % (caso, ad, exp_ram.get(ad, 0), got_ram.get(ad, 0)))
                sys.exit(1)
    ok = N - skipped
    if skipped > 200 or ok == 0:
        print("FAIL %d/%d (skipped=%d)" % (ok, N, skipped))
        sys.exit(1)
    print("PASS %d/%d (skipped=%d)" % (ok, N, skipped))

if __name__ == "__main__":
    main()
