/* ROM: 60E0FC00 | Address: 0x13B4A | Size: 20 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST caller (CFG).
 * jsr/bsr -> s->pr=<ret>; <delay slot>; f_<callee>(s);
 * jmp (tail) -> <delay slot>; f_<callee>(s); return;
 * jump table -> switch (s->rN) { case <addr>: goto L_<addr>; }
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_2404(ST *s);
void caller_13B4A(ST *s)
{
    uint32_t local_3fc = 0;
    uint32_t fr5 = 0;
    uint32_t fr6 = 0;
    /* 0x013B4A: sts.l pr,@-r15 */
    local_3fc = s->pr;
    /* 0x013B4C: op 0xD31A */
    s->r[3] = 0x000785ACu;
    /* 0x013B4E: fmov.s @r3,fr6 */
    fr6 = *(volatile uint32_t*)0x000785AC; /* ROM */
    /* 0x013B50: op 0xD21A */
    s->r[2] = 0x000785A8u;
    /* 0x013B52: op 0xD118 */
    s->r[1] = 0x00002404u;
    /* 0x013B54: jsr @r1 */
    s->pr = 0x00013B58;
    fr5 = *(volatile uint32_t*)0x000785A8; /* ROM */
    f_2404(s);
    /* 0x013B58: lds.l @r15+,pr */
    s->pr = local_3fc;
    /* 0x013B5A: rts */
    /* 0x013B5C: op 0x0009 */
    
    return;
    return; /* fallthrough */
}
