/* ROM: 60E1D400 | Address: 0x5405C | Size: 76 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST caller (CFG).
 * jsr/bsr -> s->pr=<ret>; <delay slot>; f_<callee>(s);
 * jmp (tail) -> <delay slot>; f_<callee>(s); return;
 * jump table -> switch (s->rN) { case <addr>: goto L_<addr>; }
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_24C0(ST *s);
void f_3EE58(ST *s);
void caller_5405C(ST *s)
{
    uint32_t local_3fc = 0;
    uint32_t local_400 = 0;
    uint32_t local_404 = 0;
    uint32_t fr0 = 0;
    uint32_t fr3 = 0;
    uint32_t fr4 = 0;
    uint32_t fr5 = 0;
    /* 0x05405C: sts.l pr,@-r15 */
    local_3fc = s->pr;
    /* 0x05405E: fldi0 fr5 */
    fr5 = 0u;
    /* 0x054060: op 0x932A */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0x0000C532u;
    /* 0x054062: fldi1 fr4 */
    fr4 = 0x3F800000u;
    /* 0x054064: op 0xD216 */
    s->r[2] = 0x000024C0u;
    /* 0x054066: jsr @r2 */
    s->pr = 0x0005406A;
    uint32_t t2 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)0xFFFFC532; /* RAM 0xFFFFC532 */
    s->r[4] = t2;
    f_24C0(s);
    /* 0x05406A: op 0x9326 */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0x0000D048u;
    /* 0x05406C: mov.w @r3,r4 */
    uint32_t t4 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)s->r[3]; /* RAM 0xFFFFD048 */
    s->r[4] = t4;
    /* 0x05406E: op 0x644D */
    s->r[4] = s->r[4] & 0xFFFFu;
    /* 0x054070: op 0x4415 */
    s->T = ((int32_t)s->r[4] > 0) ? 1u : 0u;
    /* 0x054072: bf.s 0x054080 */
    /* 0x054074: fmov fr0,fr4 */
    fr4 = fr0;
    if (!s->T) goto L_54080;
    /* 0x054076: op 0xE500 */
    s->r[5] = (uint32_t)(int32_t)(int8_t)0x00;
    /* 0x054078: op 0x9420 */
    s->r[4] = (uint32_t)(int32_t)(int16_t)0x00008FE4u;
    /* 0x05407A: op 0xD112 */
    s->r[1] = 0x0003EE58u;
    /* 0x05407C: jmp @r1 (tail) */
    s->pr = local_3fc;
    f_3EE58(s);
    return;
    L_54080: ;
    /* 0x054080: op 0xD211 */
    s->r[2] = 0x0007D954u;
    /* 0x054082: fmov.s @r2,fr3 */
    fr3 = *(volatile uint32_t*)0x0007D954; /* ROM */
    /* 0x054084: fcmp/gt fr3,fr4 */
    { union { uint32_t u; float f; } _a, _b; _a.u = fr4; _b.u = fr3; s->T = (_a.f > _b.f) ? 1u : 0u; }
    /* 0x054086: bt.s 0x054098 */
    /* 0x054088: op 0x0009 */
    
    if (s->T) goto L_54098;
    /* 0x05408A: op 0xD110 */
    s->r[1] = 0x0007D950u;
    /* 0x05408C: op 0x9317 */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0xFFu;
    /* 0x05408E: mov.b @r1,r0 */
    uint32_t t6 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)s->r[1]; /* ROM */
    s->r[0] = t6;
    /* 0x054090: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x054092: op 0x3030 */
    s->T = (s->r[0] == s->r[3]) ? 1u : 0u;
    /* 0x054094: bf.s 0x0540A2 */
    /* 0x054096: op 0x0009 */
    
    if (!s->T) goto L_540A2;
    L_54098: ;
    /* 0x054098: op 0x9410 */
    s->r[4] = (uint32_t)(int32_t)(int16_t)0x00008FE4u;
    /* 0x05409A: op 0xE501 */
    s->r[5] = (uint32_t)(int32_t)(int8_t)0x01;
    /* 0x05409C: op 0xD309 */
    s->r[3] = 0x0003EE58u;
    /* 0x05409E: jmp @r3 (tail) */
    s->pr = local_400;
    f_3EE58(s);
    return;
    L_540A2: ;
    /* 0x0540A2: lds.l @r15+,pr */
    s->pr = local_404;
    /* 0x0540A4: rts */
    /* 0x0540A6: op 0x0009 */
    
    return;
    return; /* fallthrough */
}
