/* ROM: 60E1D400 | Address: 0x5F220 | Size: 150 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST caller (CFG).
 * jsr/bsr -> s->pr=<ret>; <delay slot>; f_<callee>(s);
 * jmp (tail) -> <delay slot>; f_<callee>(s); return;
 * jump table -> switch (s->rN) { case <addr>: goto L_<addr>; }
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_2460(ST *s);
void caller_5F220(ST *s)
{
    uint32_t local_3f0 = 0;
    uint32_t local_3f4 = 0;
    uint32_t local_3f8 = 0;
    uint32_t local_3fc = 0;
    uint32_t fr2 = 0;
    uint32_t fr3 = 0;
    /* 0x05F220: mov.l r14,@-r15 */
    local_3fc = s->r[14];
    /* 0x05F222: mov.l r13,@-r15 */
    local_3f8 = s->r[13];
    /* 0x05F224: mov.l r12,@-r15 */
    local_3f4 = s->r[12];
    /* 0x05F226: sts.l pr,@-r15 */
    local_3f0 = s->pr;
    /* 0x05F228: op 0x9346 */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0x0000AAE0u;
    /* 0x05F22A: mov.b @r3,r5 */
    uint32_t t2 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFAAE0; /* RAM 0xFFFFAAE0 */
    s->r[5] = t2;
    /* 0x05F22C: op 0xD628 */
    s->r[6] = 0xFFFFD3E0u;
    /* 0x05F22E: op 0x605C */
    s->r[0] = s->r[5] & 0xFFu;
    /* 0x05F230: op 0x9243 */
    s->r[2] = (uint32_t)(int32_t)(int16_t)0x0000C71Cu;
    /* 0x05F232: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x05F234: op 0xDC24 */
    s->r[12] = 0xFFFFD3EBu;
    /* 0x05F236: fmov.s @r2,fr3 */
    fr3 = *(volatile uint32_t*)0xFFFFC71C; /* RAM 0xFFFFC71C */
    /* 0x05F238: fmov.s fr3,@r6 */
    *(volatile uint32_t*)(s->r[6] + 0) = fr3;
    /* 0x05F23A: op 0xDD26 */
    s->r[13] = 0xFFFFD3E6u;
    /* 0x05F23C: op 0xDE21 */
    s->r[14] = 0xFFFFD3E4u;
    /* 0x05F23E: bf.s 0x05F27A */
    /* 0x05F240: mov.w @r13,r4 */
    uint32_t t4 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)0xFFFFD3E6; /* RAM 0xFFFFD3E6 */
    s->r[4] = t4;
    if (!s->T) goto L_5F27A;
    /* 0x05F242: op 0xD125 */
    s->r[1] = 0x00060304u;
    /* 0x05F244: fmov.s @r6,fr2 */
    fr2 = *(volatile uint32_t*)(s->r[6] + 0);
    /* 0x05F246: fmov.s @r1,fr3 */
    fr3 = *(volatile uint32_t*)0x00060304; /* ROM */
    /* 0x05F248: fcmp/gt fr2,fr3 */
    { union { uint32_t u; float f; } _a, _b; _a.u = fr3; _b.u = fr2; s->T = (_a.f > _b.f) ? 1u : 0u; }
    /* 0x05F24A: bf.s 0x05F274 */
    /* 0x05F24C: op 0x0009 */
    
    if (!s->T) goto L_5F274;
    /* 0x05F24E: op 0xD323 */
    s->r[3] = 0x00002460u;
    /* 0x05F250: jsr @r3 */
    s->pr = 0x0005F254;
    s->r[5] = (uint32_t)(int32_t)(int8_t)0x01;
    f_2460(s);
    /* 0x05F254: mov.w r0,@r13 */
    *(volatile uint16_t*)0xFFFFD3E6 = s->r[0]; /* RAM 0xFFFFD3E6 */
    /* 0x05F256: op 0xE319 */
    s->r[3] = (uint32_t)(int32_t)(int8_t)0x19;
    /* 0x05F258: mov.w @r13,r2 */
    uint32_t t6 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)0xFFFFD3E6; /* RAM 0xFFFFD3E6 */
    s->r[2] = t6;
    /* 0x05F25A: op 0x622D */
    s->r[2] = s->r[2] & 0xFFFFu;
    /* 0x05F25C: op 0x3233 */
    s->T = ((int32_t)s->r[2] >= (int32_t)s->r[3]) ? 1u : 0u;
    /* 0x05F25E: bf.s 0x05F274 */
    /* 0x05F260: op 0x0009 */
    
    if (!s->T) goto L_5F274;
    /* 0x05F262: op 0xE100 */
    s->r[1] = (uint32_t)(int32_t)(int8_t)0x00;
    /* 0x05F264: mov.w r1,@r13 */
    *(volatile uint16_t*)0xFFFFD3E6 = s->r[1]; /* RAM 0xFFFFD3E6 */
    /* 0x05F266: mov.w @r14,r2 */
    uint32_t t8 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)0xFFFFD3E4; /* RAM 0xFFFFD3E4 */
    s->r[2] = t8;
    /* 0x05F268: op 0x2228 */
    s->T = ((s->r[2] & s->r[2]) == 0u) ? 1u : 0u;
    /* 0x05F26A: bt.s 0x05F274 */
    /* 0x05F26C: op 0x0009 */
    
    if (s->T) goto L_5F274;
    /* 0x05F26E: mov.w @r14,r0 */
    uint32_t t10 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)0xFFFFD3E4; /* RAM 0xFFFFD3E4 */
    s->r[0] = t10;
    /* 0x05F270: op 0x70FF */
    s->r[0] = s->r[0] + (uint32_t)(int32_t)(int8_t)0xFF;
    /* 0x05F272: mov.w r0,@r14 */
    *(volatile uint16_t*)0xFFFFD3E4 = s->r[0]; /* RAM 0xFFFFD3E4 */
    L_5F274: ;
    /* 0x05F274: op 0xE301 */
    s->r[3] = (uint32_t)(int32_t)(int8_t)0x01;
    /* 0x05F276: bra 0x05F2AC */
    /* 0x05F278: mov.b r3,@r12 */
    *(volatile uint8_t*)0xFFFFD3EB = s->r[3]; /* RAM 0xFFFFD3EB */
    goto L_5F2AC;
    L_5F27A: ;
    /* 0x05F27A: op 0x644D */
    s->r[4] = s->r[4] & 0xFFFFu;
    /* 0x05F27C: op 0x2448 */
    s->T = ((s->r[4] & s->r[4]) == 0u) ? 1u : 0u;
    /* 0x05F27E: bt.s 0x05F296 */
    /* 0x05F280: op 0x0009 */
    
    if (s->T) goto L_5F296;
    /* 0x05F282: op 0xD110 */
    s->r[1] = 0xFFFFD3E4u;
    /* 0x05F284: mov.w @r1,r0 */
    uint32_t t12 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)0xFFFFD3E4; /* RAM 0xFFFFD3E4 */
    s->r[0] = t12;
    /* 0x05F286: op 0x2008 */
    s->T = ((s->r[0] & s->r[0]) == 0u) ? 1u : 0u;
    /* 0x05F288: bt.s 0x05F296 */
    /* 0x05F28A: op 0x0009 */
    
    if (s->T) goto L_5F296;
    /* 0x05F28C: op 0xE200 */
    s->r[2] = (uint32_t)(int32_t)(int8_t)0x00;
    /* 0x05F28E: mov.w r2,@r13 */
    *(volatile uint16_t*)0xFFFFD3E6 = s->r[2]; /* RAM 0xFFFFD3E6 */
    /* 0x05F290: mov.w @r14,r3 */
    uint32_t t14 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)0xFFFFD3E4; /* RAM 0xFFFFD3E4 */
    s->r[3] = t14;
    /* 0x05F292: op 0x73FF */
    s->r[3] = s->r[3] + (uint32_t)(int32_t)(int8_t)0xFF;
    /* 0x05F294: mov.w r3,@r14 */
    *(volatile uint16_t*)0xFFFFD3E4 = s->r[3]; /* RAM 0xFFFFD3E4 */
    L_5F296: ;
    /* 0x05F296: mov.w @r14,r2 */
    uint32_t t16 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)0xFFFFD3E4; /* RAM 0xFFFFD3E4 */
    s->r[2] = t16;
    /* 0x05F298: op 0x910D */
    s->r[1] = (uint32_t)(int32_t)(int16_t)0x0000D3DCu;
    /* 0x05F29A: mov.w @r1,r3 */
    uint32_t t18 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)0xFFFFD3DC; /* RAM 0xFFFFD3DC */
    s->r[3] = t18;
    /* 0x05F29C: op 0x3232 */
    s->T = (s->r[2] >= s->r[3]) ? 1u : 0u;
    /* 0x05F29E: bt.s 0x05F2A8 */
    /* 0x05F2A0: op 0x0009 */
    
    if (s->T) goto L_5F2A8;
    /* 0x05F2A2: op 0xE202 */
    s->r[2] = (uint32_t)(int32_t)(int8_t)0x02;
    /* 0x05F2A4: bra 0x05F2AC */
    /* 0x05F2A6: mov.b r2,@r12 */
    *(volatile uint8_t*)0xFFFFD3EB = s->r[2]; /* RAM 0xFFFFD3EB */
    goto L_5F2AC;
    L_5F2A8: ;
    /* 0x05F2A8: op 0xE003 */
    s->r[0] = (uint32_t)(int32_t)(int8_t)0x03;
    /* 0x05F2AA: mov.b r0,@r12 */
    *(volatile uint8_t*)0xFFFFD3EB = s->r[0]; /* RAM 0xFFFFD3EB */
    L_5F2AC: ;
    /* 0x05F2AC: lds.l @r15+,pr */
    s->pr = local_3f0;
    /* 0x05F2AE: mov.l @r15+,r12 */
    s->r[12] = local_3f4;
    /* 0x05F2B0: mov.l @r15+,r13 */
    s->r[13] = local_3f8;
    /* 0x05F2B2: rts */
    /* 0x05F2B4: mov.l @r15+,r14 */
    s->r[14] = local_3fc;
    return;
    return; /* fallthrough */
}
