/* ROM: 60E1D400 | Address: 0x2DD88 | Size: 30 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST caller (CFG).
 * jsr/bsr -> s->pr=<ret>; <delay slot>; f_<callee>(s);
 * jmp (tail) -> <delay slot>; f_<callee>(s); return;
 * jump table -> switch (s->rN) { case <addr>: goto L_<addr>; }
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_23B0(ST *s);
void caller_2DD88(ST *s)
{
    uint32_t local_3fc = 0;
    uint32_t fr0 = 0;
    uint32_t fr4 = 0;
    uint32_t fr5 = 0;
    uint32_t fr6 = 0;
    uint32_t fr7 = 0;
    /* 0x02DD88: sts.l pr,@-r15 */
    local_3fc = s->pr;
    /* 0x02DD8A: op 0xC70B */
    s->r[0] = 0x0002DDB8u;
    /* 0x02DD8C: op 0xD30B */
    s->r[3] = 0x00076B30u;
    /* 0x02DD8E: fmov.s @r0,fr7 */
    fr7 = *(volatile uint32_t*)0x0002DDB8; /* ROM */
    /* 0x02DD90: fmov.s @r3,fr6 */
    fr6 = *(volatile uint32_t*)0x00076B30; /* ROM */
    /* 0x02DD92: op 0x9209 */
    s->r[2] = (uint32_t)(int32_t)(int16_t)0x0000BD38u;
    /* 0x02DD94: op 0xD107 */
    s->r[1] = 0xFFFFBD3Cu;
    /* 0x02DD96: fmov.s @r2,fr5 */
    fr5 = *(volatile uint32_t*)0xFFFFBD38; /* RAM 0xFFFFBD38 */
    /* 0x02DD98: op 0xD309 */
    s->r[3] = 0x000023B0u;
    /* 0x02DD9A: jsr @r3 */
    s->pr = 0x0002DD9E;
    fr4 = *(volatile uint32_t*)0xFFFFBD3C; /* RAM 0xFFFFBD3C */
    f_23B0(s);
    /* 0x02DD9E: op 0x9203 */
    s->r[2] = (uint32_t)(int32_t)(int16_t)0x0000BD38u;
    /* 0x02DDA0: lds.l @r15+,pr */
    s->pr = local_3fc;
    /* 0x02DDA2: rts */
    /* 0x02DDA4: fmov.s fr0,@r2 */
    *(volatile uint32_t*)0xFFFFBD38 = fr0; /* RAM 0xFFFFBD38 */
    return;
    return; /* fallthrough */
}
