/* ROM: 60E1D400 | Address: 0x331F4 | Size: 140 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST caller (CFG).
 * jsr/bsr -> s->pr=<ret>; <delay slot>; f_<callee>(s);
 * jmp (tail) -> <delay slot>; f_<callee>(s); return;
 * jump table -> switch (s->rN) { case <addr>: goto L_<addr>; }
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_2460(ST *s);
void caller_331F4(ST *s)
{
    uint32_t local_3f8 = 0;
    uint32_t local_3fc = 0;
    /* 0x0331F4: mov.l r14,@-r15 */
    local_3fc = s->r[14];
    /* 0x0331F6: op 0xE601 */
    s->r[6] = (uint32_t)(int32_t)(int8_t)0x01;
    /* 0x0331F8: op 0x9246 */
    s->r[2] = (uint32_t)(int32_t)(int16_t)0x0000C01Du;
    /* 0x0331FA: op 0xE500 */
    s->r[5] = (uint32_t)(int32_t)(int8_t)0x00;
    /* 0x0331FC: op 0x9343 */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0x0000BCA2u;
    /* 0x0331FE: sts.l pr,@-r15 */
    local_3f8 = s->pr;
    /* 0x033200: mov.b @r3,r7 */
    uint32_t t2 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFBCA2; /* RAM 0xFFFFBCA2 */
    s->r[7] = t2;
    /* 0x033202: mov.b @r2,r0 */
    uint32_t t4 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFC01D; /* RAM 0xFFFFC01D */
    s->r[0] = t4;
    /* 0x033204: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x033206: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x033208: bf.s 0x033218 */
    /* 0x03320A: op 0x647C */
    s->r[4] = s->r[7] & 0xFFu;
    if (!s->T) goto L_33218;
    /* 0x03320C: op 0x2448 */
    s->T = ((s->r[4] & s->r[4]) == 0u) ? 1u : 0u;
    /* 0x03320E: bf.s 0x03321C */
    /* 0x033210: op 0x0009 */
    
    if (!s->T) goto L_3321C;
    /* 0x033212: op 0xD122 */
    s->r[1] = 0xFFFFC037u;
    /* 0x033214: bra 0x03321C */
    /* 0x033216: mov.b r6,@r1 */
    *(volatile uint8_t*)0xFFFFC037 = s->r[6]; /* RAM 0xFFFFC037 */
    goto L_3321C;
    L_33218: ;
    /* 0x033218: op 0xD020 */
    s->r[0] = 0xFFFFC037u;
    /* 0x03321A: mov.b r5,@r0 */
    *(volatile uint8_t*)0xFFFFC037 = s->r[5]; /* RAM 0xFFFFC037 */
    L_3321C: ;
    /* 0x03321C: op 0x9735 */
    s->r[7] = (uint32_t)(int32_t)(int16_t)0x0000C021u;
    /* 0x03321E: op 0x9331 */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0x0000BD59u;
    /* 0x033220: mov.b @r3,r0 */
    uint32_t t6 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFBD59; /* RAM 0xFFFFBD59 */
    s->r[0] = t6;
    /* 0x033222: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x033224: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x033226: bf.s 0x03325A */
    /* 0x033228: op 0x0009 */
    
    if (!s->T) goto L_3325A;
    /* 0x03322A: op 0x922D */
    s->r[2] = (uint32_t)(int32_t)(int16_t)0x0000C01Du;
    /* 0x03322C: mov.b @r2,r1 */
    uint32_t t8 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFC01D; /* RAM 0xFFFFC01D */
    s->r[1] = t8;
    /* 0x03322E: op 0x2118 */
    s->T = ((s->r[1] & s->r[1]) == 0u) ? 1u : 0u;
    /* 0x033230: bt.s 0x033240 */
    /* 0x033232: op 0x0009 */
    
    if (s->T) goto L_33240;
    /* 0x033234: op 0xD119 */
    s->r[1] = 0xFFFFC037u;
    /* 0x033236: mov.b @r1,r0 */
    uint32_t t10 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFC037; /* RAM 0xFFFFC037 */
    s->r[0] = t10;
    /* 0x033238: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x03323A: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x03323C: bf.s 0x03325A */
    /* 0x03323E: op 0x0009 */
    
    if (!s->T) goto L_3325A;
    L_33240: ;
    /* 0x033240: op 0xD317 */
    s->r[3] = 0xFFFFC02Au;
    /* 0x033242: mov.w @r3,r2 */
    uint32_t t12 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)0xFFFFC02A; /* RAM 0xFFFFC02A */
    s->r[2] = t12;
    /* 0x033244: op 0xD017 */
    s->r[0] = 0x00078D06u;
    /* 0x033246: mov.w @r0,r1 */
    uint32_t t14 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)0x00078D06; /* ROM */
    s->r[1] = t14;
    /* 0x033248: op 0x3210 */
    s->T = (s->r[2] == s->r[1]) ? 1u : 0u;
    /* 0x03324A: bf.s 0x03325A */
    /* 0x03324C: op 0x0009 */
    
    if (!s->T) goto L_3325A;
    /* 0x03324E: op 0x6043 */
    s->r[0] = s->r[4];
    /* 0x033250: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x033252: bf.s 0x03325A */
    /* 0x033254: op 0x0009 */
    
    if (!s->T) goto L_3325A;
    /* 0x033256: bra 0x033262 */
    /* 0x033258: mov.b r6,@r7 */
    *(volatile uint8_t*)0xFFFFC021 = s->r[6]; /* RAM 0xFFFFC021 */
    goto L_33262;
    L_3325A: ;
    /* 0x03325A: op 0x2448 */
    s->T = ((s->r[4] & s->r[4]) == 0u) ? 1u : 0u;
    /* 0x03325C: bf.s 0x033262 */
    /* 0x03325E: op 0x0009 */
    
    if (!s->T) goto L_33262;
    /* 0x033260: mov.b r5,@r7 */
    *(volatile uint8_t*)0xFFFFC021 = s->r[5]; /* RAM 0xFFFFC021 */
    L_33262: ;
    /* 0x033262: op 0x6043 */
    s->r[0] = s->r[4];
    /* 0x033264: op 0xDE0E */
    s->r[14] = 0xFFFFC02Au;
    /* 0x033266: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x033268: bf.s 0x033278 */
    /* 0x03326A: op 0x0009 */
    
    if (!s->T) goto L_33278;
    /* 0x03326C: op 0xD20A */
    s->r[2] = 0x00002460u;
    /* 0x03326E: op 0xE501 */
    s->r[5] = (uint32_t)(int32_t)(int8_t)0x01;
    /* 0x033270: jsr @r2 */
    s->pr = 0x00033274;
    uint32_t t16 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)0xFFFFC02A; /* RAM 0xFFFFC02A */
    s->r[4] = t16;
    f_2460(s);
    /* 0x033274: bra 0x03327A */
    /* 0x033276: mov.w r0,@r14 */
    *(volatile uint16_t*)0xFFFFC02A = s->r[0]; /* RAM 0xFFFFC02A */
    goto L_3327A;
    L_33278: ;
    /* 0x033278: mov.w r5,@r14 */
    *(volatile uint16_t*)0xFFFFC02A = s->r[5]; /* RAM 0xFFFFC02A */
    L_3327A: ;
    /* 0x03327A: lds.l @r15+,pr */
    s->pr = local_3f8;
    /* 0x03327C: rts */
    /* 0x03327E: mov.l @r15+,r14 */
    s->r[14] = local_3fc;
    return;
    return; /* fallthrough */
}
