/* ROM: 60E1D400 | Address: 0x1A040 | Size: 38 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST caller (CFG).
 * jsr/bsr -> s->pr=<ret>; <delay slot>; f_<callee>(s);
 * jmp (tail) -> <delay slot>; f_<callee>(s); return;
 * jump table -> switch (s->rN) { case <addr>: goto L_<addr>; }
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_23F4(ST *s);
void caller_1A040(ST *s)
{
    uint32_t local_3fc = 0;
    uint32_t fr0 = 0;
    uint32_t fr4 = 0;
    uint32_t fr5 = 0;
    /* 0x01A040: sts.l pr,@-r15 */
    local_3fc = s->pr;
    /* 0x01A042: op 0xD33D */
    s->r[3] = 0xFFFF9EECu;
    /* 0x01A044: op 0x9171 */
    s->r[1] = (uint32_t)(int32_t)(int16_t)0x0000AA4Cu;
    /* 0x01A046: mov.w @r3,r2 */
    uint32_t t2 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)0xFFFF9EEC; /* RAM 0xFFFF9EEC */
    s->r[2] = t2;
    /* 0x01A048: op 0xD03C */
    s->r[0] = 0xFFFFA112u;
    /* 0x01A04A: mov.w r2,@r1 */
    *(volatile uint16_t*)0xFFFFAA4C = s->r[2]; /* RAM 0xFFFFAA4C */
    /* 0x01A04C: mov.w @r0,r3 */
    uint32_t t4 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)0xFFFFA112; /* RAM 0xFFFFA112 */
    s->r[3] = t4;
    /* 0x01A04E: op 0xD23C */
    s->r[2] = 0xFFFFAA58u;
    /* 0x01A050: op 0xD13C */
    s->r[1] = 0xFFFFA108u;
    /* 0x01A052: mov.w r3,@r2 */
    *(volatile uint16_t*)0xFFFFAA58 = s->r[3]; /* RAM 0xFFFFAA58 */
    /* 0x01A054: fmov.s @r1,fr5 */
    fr5 = *(volatile uint32_t*)0xFFFFA108; /* RAM 0xFFFFA108 */
    /* 0x01A056: op 0xD33C */
    s->r[3] = 0x0006FA20u;
    /* 0x01A058: op 0xD23C */
    s->r[2] = 0x000023F4u;
    /* 0x01A05A: jsr @r2 */
    s->pr = 0x0001A05E;
    fr4 = *(volatile uint32_t*)0x0006FA20; /* ROM */
    f_23F4(s);
    /* 0x01A05E: op 0x9160 */
    s->r[1] = (uint32_t)(int32_t)(int16_t)0x0000AA20u;
    /* 0x01A060: lds.l @r15+,pr */
    s->pr = local_3fc;
    /* 0x01A062: rts */
    /* 0x01A064: fmov.s fr0,@r1 */
    *(volatile uint32_t*)0xFFFFAA20 = fr0; /* RAM 0xFFFFAA20 */
    return;
    return; /* fallthrough */
}
