/* ROM: 60E1D400 | Address: 0xE470 | Size: 34 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST caller (CFG).
 * jsr/bsr -> s->pr=<ret>; <delay slot>; f_<callee>(s);
 * jmp (tail) -> <delay slot>; f_<callee>(s); return;
 * jump table -> switch (s->rN) { case <addr>: goto L_<addr>; }
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_2460(ST *s);
void caller_E470(ST *s)
{
    uint32_t local_3fc = 0;
    /* 0x00E470: sts.l pr,@-r15 */
    local_3fc = s->pr;
    /* 0x00E472: op 0x9343 */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0x0000A428u;
    /* 0x00E474: mov.b @r3,r0 */
    uint32_t t2 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFA428; /* RAM 0xFFFFA428 */
    s->r[0] = t2;
    /* 0x00E476: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x00E478: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x00E47A: bf.s 0x00E48C */
    /* 0x00E47C: op 0x0009 */
    
    if (!s->T) goto L_E48C;
    /* 0x00E47E: op 0xE501 */
    s->r[5] = (uint32_t)(int32_t)(int8_t)0x01;
    /* 0x00E480: op 0x913D */
    s->r[1] = (uint32_t)(int32_t)(int16_t)0x0000A420u;
    /* 0x00E482: op 0xD221 */
    s->r[2] = 0x00002460u;
    /* 0x00E484: jsr @r2 */
    s->pr = 0x0000E488;
    uint32_t t4 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)0xFFFFA420; /* RAM 0xFFFFA420 */
    s->r[4] = t4;
    f_2460(s);
    /* 0x00E488: op 0x9339 */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0x0000A420u;
    /* 0x00E48A: mov.w r0,@r3 */
    *(volatile uint16_t*)0xFFFFA420 = s->r[0]; /* RAM 0xFFFFA420 */
    L_E48C: ;
    /* 0x00E48C: lds.l @r15+,pr */
    s->pr = local_3fc;
    /* 0x00E48E: rts */
    /* 0x00E490: op 0x0009 */
    
    return;
    return; /* fallthrough */
}
