/* ROM: 60E0FC00 | Address: 0x2FE00 | Size: 20 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST caller (CFG).
 * jsr/bsr -> s->pr=<ret>; <delay slot>; f_<callee>(s);
 * jmp (tail) -> <delay slot>; f_<callee>(s); return;
 * jump table -> switch (s->rN) { case <addr>: goto L_<addr>; }
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_2FD48(ST *s);
void f_300A8(ST *s);
void f_300B0(ST *s);
void caller_2FE00(ST *s)
{
    uint32_t local_3fc = 0;
    /* 0x02FE00: sts.l pr,@-r15 */
    local_3fc = s->pr;
    /* 0x02FE02: op 0xD316 */
    s->r[3] = 0x000300A8u;
    /* 0x02FE04: jsr @r3 */
    s->pr = 0x0002FE08;
    
    f_300A8(s);
    /* 0x02FE08: op 0xD215 */
    s->r[2] = 0x000300B0u;
    /* 0x02FE0A: jsr @r2 */
    s->pr = 0x0002FE0E;
    
    f_300B0(s);
    /* 0x02FE0E: op 0xD315 */
    s->r[3] = 0x0002FD48u;
    /* 0x02FE10: jmp @r3 (tail) */
    s->pr = local_3fc;
    f_2FD48(s);
    return;
    return; /* fallthrough */
}
