/* ROM: 60E1D400 | Address: 0x28F04 | Size: 66 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST caller (CFG).
 * jsr/bsr -> s->pr=<ret>; <delay slot>; f_<callee>(s);
 * jmp (tail) -> <delay slot>; f_<callee>(s); return;
 * jump table -> switch (s->rN) { case <addr>: goto L_<addr>; }
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_23E4(ST *s);
void f_2460(ST *s);
void caller_28F04(ST *s)
{
    uint32_t local_3f8 = 0;
    uint32_t local_3fc = 0;
    uint32_t fr0 = 0;
    uint32_t fr3 = 0;
    uint32_t fr4 = 0;
    uint32_t fr5 = 0;
    /* 0x028F04: mov.l r14,@-r15 */
    local_3fc = s->r[14];
    /* 0x028F06: sts.l pr,@-r15 */
    local_3f8 = s->pr;
    /* 0x028F08: op 0x9322 */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0x0000A41Cu;
    /* 0x028F0A: mov.b @r3,r1 */
    uint32_t t2 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFA41C; /* RAM 0xFFFFA41C */
    s->r[1] = t2;
    /* 0x028F0C: op 0x2118 */
    s->T = ((s->r[1] & s->r[1]) == 0u) ? 1u : 0u;
    /* 0x028F0E: bf.s 0x028F40 */
    /* 0x028F10: op 0x0009 */
    
    if (!s->T) goto L_28F40;
    /* 0x028F12: op 0xD519 */
    s->r[5] = 0x00008000u;
    /* 0x028F14: op 0x9E1A */
    s->r[14] = (uint32_t)(int32_t)(int16_t)0x0000BAC4u;
    /* 0x028F16: mov.w @r14,r4 */
    uint32_t t4 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)0xFFFFBAC4; /* RAM 0xFFFFBAC4 */
    s->r[4] = t4;
    /* 0x028F18: op 0x614D */
    s->r[1] = s->r[4] & 0xFFFFu;
    /* 0x028F1A: op 0x3153 */
    s->T = ((int32_t)s->r[1] >= (int32_t)s->r[5]) ? 1u : 0u;
    /* 0x028F1C: bt.s 0x028F2A */
    /* 0x028F1E: op 0x0009 */
    
    if (s->T) goto L_28F2A;
    /* 0x028F20: op 0xD116 */
    s->r[1] = 0x00002460u;
    /* 0x028F22: jsr @r1 */
    s->pr = 0x00028F26;
    s->r[5] = (uint32_t)(int32_t)(int8_t)0x01;
    f_2460(s);
    /* 0x028F26: bra 0x028F2C */
    /* 0x028F28: mov.w r0,@r14 */
    *(volatile uint16_t*)0xFFFFBAC4 = s->r[0]; /* RAM 0xFFFFBAC4 */
    goto L_28F2C;
    L_28F2A: ;
    /* 0x028F2A: mov.w r5,@r14 */
    *(volatile uint16_t*)0xFFFFBAC4 = s->r[5]; /* RAM 0xFFFFBAC4 */
    L_28F2C: ;
    /* 0x028F2C: op 0x9311 */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0x0000B6F0u;
    /* 0x028F2E: fmov.s @r3,fr3 */
    fr3 = *(volatile uint32_t*)0xFFFFB6F0; /* RAM 0xFFFFB6F0 */
    /* 0x028F30: op 0x9210 */
    s->r[2] = (uint32_t)(int32_t)(int16_t)0x0000B6ECu;
    /* 0x028F32: fmov.s @r2,fr4 */
    fr4 = *(volatile uint32_t*)0xFFFFB6EC; /* RAM 0xFFFFB6EC */
    /* 0x028F34: op 0xD112 */
    s->r[1] = 0x000023E4u;
    /* 0x028F36: fsub fr3,fr4 */
    { union { uint32_t u; float f; } _a, _b, _r; _a.u = fr4; _b.u = fr3; _r.f = _a.f - _b.f; fr4 = _r.u; }
    /* 0x028F38: jsr @r1 */
    s->pr = 0x00028F3C;
    fr5 = 0u;
    f_23E4(s);
    /* 0x028F3C: op 0xD308 */
    s->r[3] = 0xFFFFBAD4u;
    /* 0x028F3E: fmov.s fr0,@r3 */
    *(volatile uint32_t*)0xFFFFBAD4 = fr0; /* RAM 0xFFFFBAD4 */
    L_28F40: ;
    /* 0x028F40: lds.l @r15+,pr */
    s->pr = local_3f8;
    /* 0x028F42: rts */
    /* 0x028F44: mov.l @r15+,r14 */
    s->r[14] = local_3fc;
    return;
    return; /* fallthrough */
}
