/* ROM: 60E0FC00 | Address: 0x21C66 | Size: 314 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST caller (CFG).
 * jsr/bsr -> s->pr=<ret>; <delay slot>; f_<callee>(s);
 * jmp (tail) -> <delay slot>; f_<callee>(s); return;
 * jump table -> switch (s->rN) { case <addr>: goto L_<addr>; }
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_3920(ST *s);
void f_3934(ST *s);
void f_205AC(ST *s);
void f_34A4A(ST *s);
void caller_21C66(ST *s)
{
    uint32_t local_3f8 = 0;
    uint32_t local_3fc = 0;
    /* 0x021C66: sts.l pr,@-r15 */
    local_3fc = s->pr;
    /* 0x021C68: op 0xD306 */
    s->r[3] = 0x00003920u;
    /* 0x021C6A: op 0x7FFC */
    s->r[15] = s->r[15] + (uint32_t)(int32_t)(int8_t)0xFC;
    /* 0x021C6C: jsr @r3 */
    s->pr = 0x00021C70;
    s->r[4] = (uint32_t)(int32_t)(int8_t)0x10;
    f_3920(s);
    /* 0x021C70: op 0xD349 */
    s->r[3] = 0x000205ACu;
    /* 0x021C72: jsr @r3 */
    s->pr = 0x00021C76;
    local_3f8 = s->r[0];
    f_205AC(s);
    /* 0x021C76: op 0xD249 */
    s->r[2] = 0x00034A4Au;
    /* 0x021C78: jsr @r2 */
    s->pr = 0x00021C7C;
    
    f_34A4A(s);
    /* 0x021C7C: mov.l @r15+,r4 */
    s->r[4] = local_3f8;
    /* 0x021C7E: op 0xD305 */
    s->r[3] = 0x00003934u;
    /* 0x021C80: jmp @r3 (tail) */
    s->pr = local_3fc;
    f_3934(s);
    return;
    return; /* fallthrough */
}
