/* ROM: 60E1D400 | Address: 0xD90C | Size: 38 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST caller (CFG).
 * jsr/bsr -> s->pr=<ret>; <delay slot>; f_<callee>(s);
 * jmp (tail) -> <delay slot>; f_<callee>(s); return;
 * jump table -> switch (s->rN) { case <addr>: goto L_<addr>; }
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void caller_D90C(ST *s)
{
    /* 0x00D90C: op 0xE703 */
    s->r[7] = (uint32_t)(int32_t)(int8_t)0x03;
    /* 0x00D90E: op 0x6343 */
    s->r[3] = s->r[4];
    /* 0x00D910: op 0x2378 */
    s->T = ((s->r[3] & s->r[7]) == 0u) ? 1u : 0u;
    /* 0x00D912: bf.s 0x00D92C */
    /* 0x00D914: op 0xE600 */
    s->r[6] = (uint32_t)(int32_t)(int8_t)0x00;
    if (!s->T) goto L_D92C;
    /* 0x00D916: op 0x3456 */
    s->T = (s->r[4] > s->r[5]) ? 1u : 0u;
    /* 0x00D918: bt.s 0x00D92C */
    /* 0x00D91A: op 0x0009 */
    
    if (s->T) goto L_D92C;
    /* 0x00D91C: op 0x6053 */
    s->r[0] = s->r[5];
    /* 0x00D91E: op 0x2079 */
    s->r[0] &= s->r[7];
    /* 0x00D920: op 0x8803 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x03) ? 1u : 0u;
    /* 0x00D922: bt.s 0x00D92E */
    /* 0x00D924: op 0x0009 */
    
    if (s->T) goto L_D92E;
    /* 0x00D926: op 0x3450 */
    s->T = (s->r[4] == s->r[5]) ? 1u : 0u;
    /* 0x00D928: bt.s 0x00D92E */
    /* 0x00D92A: op 0x0009 */
    
    if (s->T) goto L_D92E;
    L_D92C: ;
    /* 0x00D92C: op 0xE601 */
    s->r[6] = (uint32_t)(int32_t)(int8_t)0x01;
    L_D92E: ;
    /* 0x00D92E: rts */
    /* 0x00D930: op 0x6063 */
    s->r[0] = s->r[6];
    return;
    return; /* fallthrough */
}
