/* ROM: 60E1D400 | Address: 0x5616E | Size: 22 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST caller (CFG).
 * jsr/bsr -> s->pr=<ret>; <delay slot>; f_<callee>(s);
 * jmp (tail) -> <delay slot>; f_<callee>(s); return;
 * jump table -> switch (s->rN) { case <addr>: goto L_<addr>; }
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_2490(ST *s);
void caller_5616E(ST *s)
{
    uint32_t local_3fc = 0;
    uint32_t fr4 = 0;
    uint32_t fr5 = 0;
    uint32_t fr6 = 0;
    /* 0x05616E: fldi0 fr6 */
    fr6 = 0u;
    /* 0x056170: op 0xC73A */
    s->r[0] = 0x0005625Cu;
    /* 0x056172: sts.l pr,@-r15 */
    local_3fc = s->pr;
    /* 0x056174: op 0x9358 */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0x0000B600u;
    /* 0x056176: fmov.s @r3,fr4 */
    fr4 = *(volatile uint32_t*)0xFFFFB600; /* RAM 0xFFFFB600 */
    /* 0x056178: op 0xD22F */
    s->r[2] = 0x00002490u;
    /* 0x05617A: jsr @r2 */
    s->pr = 0x0005617E;
    fr5 = *(volatile uint32_t*)0x0005625C; /* ROM */
    f_2490(s);
    /* 0x05617E: lds.l @r15+,pr */
    s->pr = local_3fc;
    /* 0x056180: rts */
    /* 0x056182: op 0x0009 */
    
    return;
    return; /* fallthrough */
}
