/* ROM: 60E1D400 | Address: 0x540D4 | Size: 56 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST caller (CFG).
 * jsr/bsr -> s->pr=<ret>; <delay slot>; f_<callee>(s);
 * jmp (tail) -> <delay slot>; f_<callee>(s); return;
 * jump table -> switch (s->rN) { case <addr>: goto L_<addr>; }
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_3EE58(ST *s);
void caller_540D4(ST *s)
{
    /* 0x0540D4: op 0x935A */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0x0000D201u;
    /* 0x0540D6: mov.b @r3,r0 */
    uint32_t t2 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFD201; /* RAM 0xFFFFD201 */
    s->r[0] = t2;
    /* 0x0540D8: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x0540DA: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x0540DC: bf.s 0x0540E8 */
    /* 0x0540DE: op 0x0009 */
    
    if (!s->T) goto L_540E8;
    /* 0x0540E0: op 0x9455 */
    s->r[4] = (uint32_t)(int32_t)(int16_t)0x00008FE8u;
    /* 0x0540E2: op 0xD12D */
    s->r[1] = 0x0003EE58u;
    /* 0x0540E4: jmp @r1 (tail) */
    s->r[5] = (uint32_t)(int32_t)(int8_t)0x00;
    f_3EE58(s);
    return;
    L_540E8: ;
    /* 0x0540E8: op 0x9252 */
    s->r[2] = (uint32_t)(int32_t)(int16_t)0x0000D1CCu;
    /* 0x0540EA: mov.b @r2,r0 */
    uint32_t t4 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFD1CC; /* RAM 0xFFFFD1CC */
    s->r[0] = t4;
    /* 0x0540EC: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x0540EE: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x0540F0: bt.s 0x054100 */
    /* 0x0540F2: op 0x0009 */
    
    if (s->T) goto L_54100;
    /* 0x0540F4: op 0x914D */
    s->r[1] = (uint32_t)(int32_t)(int16_t)0x0000C5B3u;
    /* 0x0540F6: mov.b @r1,r0 */
    uint32_t t6 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFC5B3; /* RAM 0xFFFFC5B3 */
    s->r[0] = t6;
    /* 0x0540F8: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x0540FA: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x0540FC: bf.s 0x054108 */
    /* 0x0540FE: op 0x0009 */
    
    if (!s->T) goto L_54108;
    L_54100: ;
    /* 0x054100: op 0x9445 */
    s->r[4] = (uint32_t)(int32_t)(int16_t)0x00008FE8u;
    /* 0x054102: op 0xD225 */
    s->r[2] = 0x0003EE58u;
    /* 0x054104: jmp @r2 (tail) */
    s->r[5] = (uint32_t)(int32_t)(int8_t)0x01;
    f_3EE58(s);
    return;
    L_54108: ;
    /* 0x054108: rts */
    /* 0x05410A: op 0x0009 */
    
    return;
    return; /* fallthrough */
}
