/* ROM: 60E1D400 | Address: 0x4AD96 | Size: 84 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST caller (CFG).
 * jsr/bsr -> s->pr=<ret>; <delay slot>; f_<callee>(s);
 * jmp (tail) -> <delay slot>; f_<callee>(s); return;
 * jump table -> switch (s->rN) { case <addr>: goto L_<addr>; }
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_23B0(ST *s);
void f_2460(ST *s);
void caller_4AD96(ST *s)
{
    uint32_t local_3f8 = 0;
    uint32_t local_3fc = 0;
    uint32_t fr0 = 0;
    uint32_t fr4 = 0;
    uint32_t fr5 = 0;
    uint32_t fr6 = 0;
    uint32_t fr7 = 0;
    /* 0x04AD96: mov.l r14,@-r15 */
    local_3fc = s->r[14];
    /* 0x04AD98: sts.l pr,@-r15 */
    local_3f8 = s->pr;
    /* 0x04AD9A: op 0xDE21 */
    s->r[14] = 0xFFFFCDCAu;
    /* 0x04AD9C: op 0xD221 */
    s->r[2] = 0xFFFFCDF2u;
    /* 0x04AD9E: mov.w @r14,r3 */
    uint32_t t2 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)0xFFFFCDCA; /* RAM 0xFFFFCDCA */
    s->r[3] = t2;
    /* 0x04ADA0: op 0xD11C */
    s->r[1] = 0xFFFFCDDCu;
    /* 0x04ADA2: mov.w r3,@r2 */
    *(volatile uint16_t*)0xFFFFCDF2 = s->r[3]; /* RAM 0xFFFFCDF2 */
    /* 0x04ADA4: mov.b @r1,r0 */
    uint32_t t4 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFCDDC; /* RAM 0xFFFFCDDC */
    s->r[0] = t4;
    /* 0x04ADA6: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x04ADA8: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x04ADAA: bf.s 0x04ADE0 */
    /* 0x04ADAC: op 0x0009 */
    
    if (!s->T) goto L_4ADE0;
    /* 0x04ADAE: op 0xC71E */
    s->r[0] = 0x0004AE28u;
    /* 0x04ADB0: op 0xD31E */
    s->r[3] = 0x0007C658u;
    /* 0x04ADB2: fmov.s @r0,fr7 */
    fr7 = *(volatile uint32_t*)0x0004AE28; /* ROM */
    /* 0x04ADB4: fmov.s @r3,fr6 */
    fr6 = *(volatile uint32_t*)0x0007C658; /* ROM */
    /* 0x04ADB6: op 0x921B */
    s->r[2] = (uint32_t)(int32_t)(int16_t)0x0000CDB8u;
    /* 0x04ADB8: op 0x911B */
    s->r[1] = (uint32_t)(int32_t)(int16_t)0x0000B0E4u;
    /* 0x04ADBA: fmov.s @r2,fr5 */
    fr5 = *(volatile uint32_t*)0xFFFFCDB8; /* RAM 0xFFFFCDB8 */
    /* 0x04ADBC: op 0xD31C */
    s->r[3] = 0x000023B0u;
    /* 0x04ADBE: jsr @r3 */
    s->pr = 0x0004ADC2;
    fr4 = *(volatile uint32_t*)0xFFFFB0E4; /* RAM 0xFFFFB0E4 */
    f_23B0(s);
    /* 0x04ADC2: op 0xE501 */
    s->r[5] = (uint32_t)(int32_t)(int8_t)0x01;
    /* 0x04ADC4: op 0xD31B */
    s->r[3] = 0xFFFFCDC8u;
    /* 0x04ADC6: op 0x9213 */
    s->r[2] = (uint32_t)(int32_t)(int16_t)0x0000CDB8u;
    /* 0x04ADC8: fmov.s fr0,@r2 */
    *(volatile uint32_t*)0xFFFFCDB8 = fr0; /* RAM 0xFFFFCDB8 */
    /* 0x04ADCA: op 0xD11B */
    s->r[1] = 0x00002460u;
    /* 0x04ADCC: jsr @r1 */
    s->pr = 0x0004ADD0;
    uint32_t t6 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)0xFFFFCDC8; /* RAM 0xFFFFCDC8 */
    s->r[4] = t6;
    f_2460(s);
    /* 0x04ADD0: op 0xD218 */
    s->r[2] = 0xFFFFCDC8u;
    /* 0x04ADD2: op 0xE501 */
    s->r[5] = (uint32_t)(int32_t)(int8_t)0x01;
    /* 0x04ADD4: op 0xD318 */
    s->r[3] = 0x00002460u;
    /* 0x04ADD6: mov.w r0,@r2 */
    *(volatile uint16_t*)0xFFFFCDC8 = s->r[0]; /* RAM 0xFFFFCDC8 */
    /* 0x04ADD8: jsr @r3 */
    s->pr = 0x0004ADDC;
    uint32_t t8 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)0xFFFFCDCA; /* RAM 0xFFFFCDCA */
    s->r[4] = t8;
    f_2460(s);
    /* 0x04ADDC: bra 0x04ADE4 */
    /* 0x04ADDE: mov.w r0,@r14 */
    *(volatile uint16_t*)0xFFFFCDCA = s->r[0]; /* RAM 0xFFFFCDCA */
    goto L_4ADE4;
    L_4ADE0: ;
    /* 0x04ADE0: op 0xE300 */
    s->r[3] = (uint32_t)(int32_t)(int8_t)0x00;
    /* 0x04ADE2: mov.w r3,@r14 */
    *(volatile uint16_t*)0xFFFFCDCA = s->r[3]; /* RAM 0xFFFFCDCA */
    L_4ADE4: ;
    /* 0x04ADE4: lds.l @r15+,pr */
    s->pr = local_3f8;
    /* 0x04ADE6: rts */
    /* 0x04ADE8: mov.l @r15+,r14 */
    s->r[14] = local_3fc;
    return;
    return; /* fallthrough */
}
