/* ROM: 60E0FC00 | Address: 0x107F4 | Size: 20 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v7.py — ST (shared state) ABI,
 * leaf callee library (c/lib/f_<hex>.c). Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_107F4(ST *s)
{
    /* 0x0107F4: op 0xD268 */
    s->r[2] = 0xFFE20000u;
    /* 0x0107F6: op 0x6353 */
    s->r[3] = s->r[5];
    /* 0x0107F8: op 0x3348 */
    s->r[3] = s->r[3] - s->r[4];
    /* 0x0107FA: op 0x6433 */
    s->r[4] = s->r[3];
    /* 0x0107FC: op 0x3427 */
    s->T = ((int32_t)s->r[4] > (int32_t)s->r[2]) ? 1u : 0u;
    /* 0x0107FE: bt.s 0x010806 */
    /* 0x010800: op 0x0009 */
    
    if (s->T) goto L_10806;
    /* 0x010802: op 0xD166 */
    s->r[1] = 0x01680000u;
    /* 0x010804: op 0x341C */
    s->r[4] = s->r[4] + s->r[1];
    L_10806: ;
    /* 0x010806: rts */
    /* 0x010808: op 0x6043 */
    s->r[0] = s->r[4];
    return;
    return; /* fallthrough */
}
