/* ROM: 60E0FC00 | Address: 0x11C72 | Size: 48 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v7.py — ST (shared state) ABI,
 * leaf callee library (c/lib/f_<hex>.c). Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, vbr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_11C72(ST *s)
{
    uint32_t local_3f8 = 0;
    uint32_t local_3fc = 0;
    /* 0x011C72: sts.l pr,@-r15 */
    local_3fc = s->pr;
    /* 0x011C74: op 0xD34F */
    s->r[3] = 0x00003920u;
    /* 0x011C76: op 0x7FFC */
    s->r[15] = s->r[15] + (uint32_t)(int32_t)(int8_t)0xFC;
    /* 0x011C78: jsr @r3 */
    /* 0x011C7A: op 0xE410 */
    s->r[4] = (uint32_t)(int32_t)(int8_t)0x10;
    /* 0x011C7C: op 0xD34E */
    s->r[3] = 0x0001A478u;
    /* 0x011C7E: jsr @r3 */
    /* 0x011C80: mov.l r0,@r15 */
    local_3f8 = s->r[0];
    /* 0x011C82: op 0xD24E */
    s->r[2] = 0x0001410Eu;
    /* 0x011C84: jsr @r2 */
    /* 0x011C86: op 0x0009 */
    
    /* 0x011C88: op 0xD34D */
    s->r[3] = 0x00039040u;
    /* 0x011C8A: jsr @r3 */
    /* 0x011C8C: op 0x0009 */
    
    /* 0x011C8E: op 0xD24D */
    s->r[2] = 0x00021730u;
    /* 0x011C90: jsr @r2 */
    /* 0x011C92: op 0x0009 */
    
    /* 0x011C94: op 0xD34C */
    s->r[3] = 0x00029108u;
    /* 0x011C96: jsr @r3 */
    /* 0x011C98: op 0x0009 */
    
    /* 0x011C9A: mov.l @r15+,r4 */
    s->r[4] = local_3f8;
    /* 0x011C9C: op 0xD34B */
    s->r[3] = 0x00003934u;
    /* 0x011C9E: jmp @r3 (tail) */
    /* 0x011CA0: lds.l @r15+,pr */
    s->pr = local_3fc;
    return; /* fallthrough */
}
