/* ROM: 60E0FC00 | Address: 0x11B9A | Size: 92 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST callee (CFG).
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_1AA9C(ST *s);
void f_21DE2(ST *s);
void f_2AB10(ST *s);
void f_31C16(ST *s);
void f_3A10A(ST *s);
void f_3E3F8(ST *s);
void f_52DE4(ST *s);
void f_578FE(ST *s);
void f_5891A(ST *s);
void f_5C664(ST *s);
void f_5CE70(ST *s);
void f_5CF54(ST *s);
void f_5CFF0(ST *s);
void f_5E54C(ST *s);
void f_5EBEC(ST *s);
void f_11B9A(ST *s)
{
    uint32_t local_3fc = 0;
    /* 0x011B9A: sts.l pr,@-r15 */
    local_3fc = s->pr;
    /* 0x011B9C: op 0xD36B */
    s->r[3] = 0x000578FEu;
    /* 0x011B9E: jsr @r3 */
    s->pr = 0x00011BA2;
    
    f_578FE(s);
    /* 0x011BA2: op 0xD26B */
    s->r[2] = 0x0005891Au;
    /* 0x011BA4: jsr @r2 */
    s->pr = 0x00011BA8;
    
    f_5891A(s);
    /* 0x011BA8: op 0xD36A */
    s->r[3] = 0x0005C664u;
    /* 0x011BAA: jsr @r3 */
    s->pr = 0x00011BAE;
    
    f_5C664(s);
    /* 0x011BAE: op 0xD26A */
    s->r[2] = 0x0005CF54u;
    /* 0x011BB0: jsr @r2 */
    s->pr = 0x00011BB4;
    
    f_5CF54(s);
    /* 0x011BB4: op 0xD369 */
    s->r[3] = 0x0005CE70u;
    /* 0x011BB6: jsr @r3 */
    s->pr = 0x00011BBA;
    
    f_5CE70(s);
    /* 0x011BBA: op 0xD269 */
    s->r[2] = 0x00052DE4u;
    /* 0x011BBC: jsr @r2 */
    s->pr = 0x00011BC0;
    
    f_52DE4(s);
    /* 0x011BC0: op 0xD368 */
    s->r[3] = 0x0005CFF0u;
    /* 0x011BC2: jsr @r3 */
    s->pr = 0x00011BC6;
    
    f_5CFF0(s);
    /* 0x011BC6: op 0xD268 */
    s->r[2] = 0x0001AA9Cu;
    /* 0x011BC8: jsr @r2 */
    s->pr = 0x00011BCC;
    
    f_1AA9C(s);
    /* 0x011BCC: op 0xD367 */
    s->r[3] = 0x0003A10Au;
    /* 0x011BCE: jsr @r3 */
    s->pr = 0x00011BD2;
    
    f_3A10A(s);
    /* 0x011BD2: op 0xD267 */
    s->r[2] = 0x00021DE2u;
    /* 0x011BD4: jsr @r2 */
    s->pr = 0x00011BD8;
    
    f_21DE2(s);
    /* 0x011BD8: op 0xD366 */
    s->r[3] = 0x00031C16u;
    /* 0x011BDA: jsr @r3 */
    s->pr = 0x00011BDE;
    
    f_31C16(s);
    /* 0x011BDE: op 0xD266 */
    s->r[2] = 0x0002AB10u;
    /* 0x011BE0: jsr @r2 */
    s->pr = 0x00011BE4;
    
    f_2AB10(s);
    /* 0x011BE4: op 0xD365 */
    s->r[3] = 0x0005E54Cu;
    /* 0x011BE6: jsr @r3 */
    s->pr = 0x00011BEA;
    
    f_5E54C(s);
    /* 0x011BEA: op 0xD265 */
    s->r[2] = 0x0005EBECu;
    /* 0x011BEC: jsr @r2 */
    s->pr = 0x00011BF0;
    
    f_5EBEC(s);
    /* 0x011BF0: op 0xD364 */
    s->r[3] = 0x0003E3F8u;
    /* 0x011BF2: jmp @r3 (tail) */
    s->pr = local_3fc;
    f_3E3F8(s);
    return;
    return; /* fallthrough */
}
