/* ROM: 60E0FC00 | Address: 0x1253C | Size: 58 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST callee (CFG).
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_23E4(ST *s);
void f_1253C(ST *s)
{
    uint32_t local_3fc = 0;
    uint32_t fr0 = 0;
    uint32_t fr1 = 0;
    uint32_t fr12 = 0;
    uint32_t fr2 = 0;
    uint32_t fr3 = 0;
    uint32_t fr4 = 0;
    uint32_t fr5 = 0;
    /* 0x01253C: fmov.s fr12,@-r15 (rt-base) */
    s->r[15] -= 4;
    *(volatile uint32_t*)s->r[15] = fr12;
    /* 0x01253E: sts.l pr,@-r15 */
    local_3fc = s->pr;
    /* 0x012540: op 0x9262 */
    s->r[2] = (uint32_t)(int32_t)(int16_t)0x0000A69Cu;
    /* 0x012542: fmov.s @r2,fr3 */
    fr3 = *(volatile uint32_t*)0xFFFFA69C; /* RAM 0xFFFFA69C */
    /* 0x012544: op 0x9161 */
    s->r[1] = (uint32_t)(int32_t)(int16_t)0x0000A724u;
    /* 0x012546: fmov.s @r1,fr2 */
    fr2 = *(volatile uint32_t*)0xFFFFA724; /* RAM 0xFFFFA724 */
    /* 0x012548: op 0x9360 */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0x0000C8A0u;
    /* 0x01254A: fsub fr3,fr2 */
    { union { uint32_t u; float f; } _a, _b, _r; _a.u = fr2; _b.u = fr3; _r.f = _a.f - _b.f; fr2 = _r.u; }
    /* 0x01254C: op 0x915F */
    s->r[1] = (uint32_t)(int32_t)(int16_t)0x0000A750u;
    /* 0x01254E: fmov fr2,fr12 */
    fr12 = fr2;
    /* 0x012550: fmov.s @r3,fr5 */
    fr5 = *(volatile uint32_t*)0xFFFFC8A0; /* RAM 0xFFFFC8A0 */
    /* 0x012552: op 0xD338 */
    s->r[3] = 0x000023E4u;
    /* 0x012554: jsr @r3 */
    s->pr = 0x00012558;
    fr4 = *(volatile uint32_t*)0xFFFFA750; /* RAM 0xFFFFA750 */
    f_23E4(s);
    /* 0x012558: op 0x935A */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0x0000A5E4u;
    /* 0x01255A: fsub fr0,fr12 */
    { union { uint32_t u; float f; } _a, _b, _r; _a.u = fr12; _b.u = fr0; _r.f = _a.f - _b.f; fr12 = _r.u; }
    /* 0x01255C: op 0x9259 */
    s->r[2] = (uint32_t)(int32_t)(int16_t)0x0000B2E4u;
    /* 0x01255E: fmov.s @r3,fr3 */
    fr3 = *(volatile uint32_t*)0xFFFFA5E4; /* RAM 0xFFFFA5E4 */
    /* 0x012560: fmov.s @r2,fr2 */
    fr2 = *(volatile uint32_t*)0xFFFFB2E4; /* RAM 0xFFFFB2E4 */
    /* 0x012562: fadd fr3,fr12 */
    { union { uint32_t u; float f; } _a, _b, _r; _a.u = fr12; _b.u = fr3; _r.f = _a.f + _b.f; fr12 = _r.u; }
    /* 0x012564: op 0x9156 */
    s->r[1] = (uint32_t)(int32_t)(int16_t)0x0000A660u;
    /* 0x012566: fadd fr2,fr12 */
    { union { uint32_t u; float f; } _a, _b, _r; _a.u = fr12; _b.u = fr2; _r.f = _a.f + _b.f; fr12 = _r.u; }
    /* 0x012568: op 0xD333 */
    s->r[3] = 0xFFFFA644u;
    /* 0x01256A: fmov.s @r1,fr1 */
    fr1 = *(volatile uint32_t*)0xFFFFA660; /* RAM 0xFFFFA660 */
    /* 0x01256C: fsub fr1,fr12 */
    { union { uint32_t u; float f; } _a, _b, _r; _a.u = fr12; _b.u = fr1; _r.f = _a.f - _b.f; fr12 = _r.u; }
    /* 0x01256E: fmov.s fr12,@r3 */
    *(volatile uint32_t*)0xFFFFA644 = fr12; /* RAM 0xFFFFA644 */
    /* 0x012570: lds.l @r15+,pr */
    s->pr = local_3fc;
    /* 0x012572: rts */
    /* 0x012574: fmov.s @r15+,fr12 (rt-base) */
    fr12 = *(volatile uint32_t*)s->r[15];
    s->r[15] = s->r[15] + 4;
    return;
    return; /* fallthrough */
}
