/* ROM: 60E1D400 | Address: 0x1251A | Size: 16 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v7.py — ST (shared state) ABI,
 * leaf callee library (c/lib/f_<hex>.c). Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_1251A(ST *s)
{
    uint32_t fr3 = 0;
    /* 0x01251A: op 0xD335 */
    s->r[3] = 0x0006E3D8u;
    /* 0x01251C: op 0xD235 */
    s->r[2] = 0xFFFFA64Cu;
    /* 0x01251E: fmov.s @r3,fr3 */
    fr3 = *(volatile uint32_t*)0x0006E3D8; /* ROM */
    /* 0x012520: fmov.s fr3,@r2 */
    *(volatile uint32_t*)0xFFFFA64C = fr3; /* RAM 0xFFFFA64C */
    /* 0x012522: op 0xD135 */
    s->r[1] = 0x0006E40Cu;
    /* 0x012524: op 0xD035 */
    s->r[0] = 0xFFFFA65Cu;
    /* 0x012526: fmov.s @r1,fr3 */
    fr3 = *(volatile uint32_t*)0x0006E40C; /* ROM */
    /* 0x012528: rts */
    /* 0x01252A: fmov.s fr3,@r0 */
    *(volatile uint32_t*)0xFFFFA65C = fr3; /* RAM 0xFFFFA65C */
    return;
    return; /* fallthrough */
}
