/* ROM: 60E0FC00 | Address: 0x1461A | Size: 6 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v7.py — ST (shared state) ABI,
 * leaf callee library (c/lib/f_<hex>.c). Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_1461A(ST *s)
{
    /* 0x01461A: op 0xD324 */
    s->r[3] = 0x0001367Eu;
    /* 0x01461C: jmp @r3 (tail) */
    /* 0x01461E: op 0x0009 */
    
    return; /* fallthrough */
}
