/* ROM: 60E0FC00 | Address: 0x140E2 | Size: 44 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v7.py — ST (shared state) ABI,
 * leaf callee library (c/lib/f_<hex>.c). Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, vbr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_140E2(ST *s)
{
    uint32_t local_400 = 0;
    /* 0x0140E2: op 0x0009 */
    
    /* 0x0140E4: op 0xD22E */
    s->r[2] = 0x000127CCu;
    /* 0x0140E6: jsr @r2 */
    /* 0x0140E8: op 0x0009 */
    
    /* 0x0140EA: op 0xD32E */
    s->r[3] = 0x00042404u;
    /* 0x0140EC: jsr @r3 */
    /* 0x0140EE: op 0x0009 */
    
    /* 0x0140F0: op 0xD22D */
    s->r[2] = 0x00012180u;
    /* 0x0140F2: jsr @r2 */
    /* 0x0140F4: op 0x0009 */
    
    /* 0x0140F6: op 0xD32D */
    s->r[3] = 0x00018F3Cu;
    /* 0x0140F8: jsr @r3 */
    /* 0x0140FA: op 0x0009 */
    
    /* 0x0140FC: op 0xD22C */
    s->r[2] = 0x0002C374u;
    /* 0x0140FE: jsr @r2 */
    /* 0x014100: op 0x0009 */
    
    /* 0x014102: op 0xD32C */
    s->r[3] = 0x0001024Cu;
    /* 0x014104: jsr @r3 */
    /* 0x014106: op 0x0009 */
    
    /* 0x014108: op 0xD22B */
    s->r[2] = 0x0004B894u;
    /* 0x01410A: jmp @r2 (tail) */
    /* 0x01410C: lds.l @r15+,pr */
    s->pr = local_400;
    return; /* fallthrough */
}
