/* ROM: 60E0FC00 | Address: 0x1624 | Size: 48 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST callee (CFG).
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_1150(ST *s);
void f_1624(ST *s)
{
    uint32_t local_3f0 = 0;
    uint32_t local_3f8 = 0;
    uint32_t local_3fc = 0;
    /* 0x001624: mov.l r14,@-r15 */
    local_3fc = s->r[14];
    /* 0x001626: op 0xE330 */
    s->r[3] = (uint32_t)(int32_t)(int8_t)0x30;
    /* 0x001628: sts.l pr,@-r15 */
    local_3f8 = s->pr;
    /* 0x00162A: op 0xE501 */
    s->r[5] = (uint32_t)(int32_t)(int8_t)0x01;
    /* 0x00162C: op 0x7FF8 */
    s->r[15] = s->r[15] + (uint32_t)(int32_t)(int8_t)0xF8;
    /* 0x00162E: mov r15,r14 (frame pointer) */
    s->r[14] = s->r[15];
    /* 0x001630: mov.b r3,@r14 */
    local_3f0 = s->r[3];
    /* 0x001632: op 0xE708 */
    s->r[7] = (uint32_t)(int32_t)(int8_t)0x08;
    /* 0x001634: op 0xE600 */
    s->r[6] = (uint32_t)(int32_t)(int8_t)0x00;
    /* 0x001636: op 0xE401 */
    s->r[4] = (uint32_t)(int32_t)(int8_t)0x01;
    /* 0x001638: op 0x34EC */
    s->r[4] = s->r[4] + s->r[14];
    L_163A: ;
    /* 0x00163A: op 0x7501 */
    s->r[5] = s->r[5] + (uint32_t)(int32_t)(int8_t)0x01;
    /* 0x00163C: mov.b r6,@r4 */
    *(volatile uint8_t*)s->r[4] = s->r[6];
    /* 0x00163E: op 0x625C */
    s->r[2] = s->r[5] & 0xFFu;
    /* 0x001640: op 0x3273 */
    s->T = ((int32_t)s->r[2] >= (int32_t)s->r[7]) ? 1u : 0u;
    /* 0x001642: bf.s 0x00163A */
    /* 0x001644: op 0x7401 */
    s->r[4] = s->r[4] + (uint32_t)(int32_t)(int8_t)0x01;
    if (!s->T) goto L_163A;
    /* 0x001646: op 0x923F */
    s->r[2] = (uint32_t)(int32_t)(int16_t)0x00001150u;
    /* 0x001648: jsr @r2 */
    s->pr = 0x0000164C;
    s->r[4] = s->r[14];
    f_1150(s);
    /* 0x00164C: op 0x7F08 */
    s->r[15] = s->r[15] + (uint32_t)(int32_t)(int8_t)0x08;
    /* 0x00164E: lds.l @r15+,pr */
    s->pr = local_3f8;
    /* 0x001650: rts */
    /* 0x001652: mov.l @r15+,r14 */
    s->r[14] = local_3fc;
    return;
    return; /* fallthrough */
}
