/* ROM: 60E0FC00 | Address: 0x169B8 | Size: 48 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v7.py — ST (shared state) ABI,
 * leaf callee library (c/lib/f_<hex>.c). Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, vbr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_169B8(ST *s)
{
    /* 0x0169B8: op 0x9230 */
    s->r[2] = (uint32_t)(int32_t)(int16_t)0x0000DFA0u;
    /* 0x0169BA: mov.b @r2,r3 */
    uint32_t t2 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFDFA0; /* RAM 0xFFFFDFA0 */
    s->r[3] = t2;
    /* 0x0169BC: op 0x2338 */
    s->T = ((s->r[3] & s->r[3]) == 0u) ? 1u : 0u;
    /* 0x0169BE: bf.s 0x0169E6 */
    /* 0x0169C0: op 0x0009 */
    
    if (!s->T) goto L_169E6;
    /* 0x0169C2: op 0xE028 */
    s->r[0] = (uint32_t)(int32_t)(int8_t)0x28;
    /* 0x0169C4: op 0x912C */
    s->r[1] = (uint32_t)(int32_t)(int16_t)0xA5u;
    /* 0x0169C6: op 0x942A */
    s->r[4] = (uint32_t)(int32_t)(int16_t)0x0000DF70u;
    /* 0x0169C8: mov.b @(r0,r4),r3 */
    uint32_t t4 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)(0xFFFFDF70 + s->r[0]); /* RAM 0xFFFFDF70 */
    s->r[3] = t4;
    /* 0x0169CA: op 0x633C */
    s->r[3] = s->r[3] & 0xFFu;
    /* 0x0169CC: op 0x3310 */
    s->T = (s->r[3] == s->r[1]) ? 1u : 0u;
    /* 0x0169CE: bf.s 0x0169E6 */
    /* 0x0169D0: op 0x0009 */
    
    if (!s->T) goto L_169E6;
    /* 0x0169D2: op 0xE023 */
    s->r[0] = (uint32_t)(int32_t)(int8_t)0x23;
    /* 0x0169D4: mov.b @(r0,r4),r0 */
    uint32_t t6 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)(0xFFFFDF70 + s->r[0]); /* RAM 0xFFFFDF70 */
    s->r[0] = t6;
    /* 0x0169D6: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x0169D8: op 0xC970 */
    s->r[0] &= 0x70u;
    /* 0x0169DA: op 0x8830 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x30) ? 1u : 0u;
    /* 0x0169DC: bf.s 0x0169E6 */
    /* 0x0169DE: op 0x0009 */
    
    if (!s->T) goto L_169E6;
    /* 0x0169E0: op 0xD210 */
    s->r[2] = 0x00016820u;
    /* 0x0169E2: jmp @r2 (tail) */
    /* 0x0169E4: op 0xE402 */
    s->r[4] = (uint32_t)(int32_t)(int8_t)0x02;
    L_169E6: ;
    /* 0x0169E6: rts */
    /* 0x0169E8: op 0x0009 */
    
    return;
    return; /* fallthrough */
}
