/* ROM: 60E0FC00 | Address: 0x172C2 | Size: 428 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST callee (CFG).
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_23B0(ST *s);
void f_2460(ST *s);
void f_3E0AC(ST *s);
void f_172C2(ST *s)
{
    uint32_t local_3e4 = 0;
    uint32_t local_3e8 = 0;
    uint32_t local_3ec = 0;
    uint32_t local_3f0 = 0;
    uint32_t local_3f4 = 0;
    uint32_t local_3f8 = 0;
    uint32_t local_3fc = 0;
    uint32_t fr0 = 0;
    uint32_t fr1 = 0;
    uint32_t fr2 = 0;
    uint32_t fr3 = 0;
    uint32_t fr4 = 0;
    uint32_t fr5 = 0;
    uint32_t fr6 = 0;
    uint32_t fr7 = 0;
    /* 0x0172C2: mov.l r14,@-r15 */
    local_3fc = s->r[14];
    /* 0x0172C4: mov.l r13,@-r15 */
    local_3f8 = s->r[13];
    /* 0x0172C6: mov.l r12,@-r15 */
    local_3f4 = s->r[12];
    /* 0x0172C8: mov.l r11,@-r15 */
    local_3f0 = s->r[11];
    /* 0x0172CA: mov.l r10,@-r15 */
    local_3ec = s->r[10];
    /* 0x0172CC: mov.l r9,@-r15 */
    local_3e8 = s->r[9];
    /* 0x0172CE: sts.l pr,@-r15 */
    local_3e4 = s->pr;
    /* 0x0172D0: op 0x934A */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0x0000B586u;
    /* 0x0172D2: mov.b @r3,r4 */
    uint32_t t2 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFB586; /* RAM 0xFFFFB586 */
    s->r[4] = t2;
    /* 0x0172D4: op 0x9249 */
    s->r[2] = (uint32_t)(int32_t)(int16_t)0x0000B594u;
    /* 0x0172D6: fmov.s @r2,fr4 */
    fr4 = *(volatile uint32_t*)0xFFFFB594; /* RAM 0xFFFFB594 */
    /* 0x0172D8: op 0xDC2C */
    s->r[12] = 0xFFFFA92Bu;
    /* 0x0172DA: op 0x9047 */
    s->r[0] = (uint32_t)(int32_t)(int16_t)0x0000A426u;
    /* 0x0172DC: op 0xD22C */
    s->r[2] = 0x00077B56u;
    /* 0x0172DE: mov.w @r0,r1 */
    uint32_t t4 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)0xFFFFA426; /* RAM 0xFFFFA426 */
    s->r[1] = t4;
    /* 0x0172E0: mov.w @r2,r3 */
    uint32_t t6 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)s->r[2]; /* ROM */
    s->r[3] = t6;
    /* 0x0172E2: op 0x3136 */
    s->T = (s->r[1] > s->r[3]) ? 1u : 0u;
    /* 0x0172E4: bf.s 0x017350 */
    /* 0x0172E6: op 0xEE00 */
    s->r[14] = (uint32_t)(int32_t)(int8_t)0x00;
    if (!s->T) goto L_17350;
    /* 0x0172E8: op 0xD32A */
    s->r[3] = 0x00077BACu;
    /* 0x0172EA: fmov.s @r3,fr3 */
    fr3 = *(volatile uint32_t*)0x00077BAC; /* ROM */
    /* 0x0172EC: op 0x923F */
    s->r[2] = (uint32_t)(int32_t)(int16_t)0x0000ADA8u;
    /* 0x0172EE: fmov.s @r2,fr2 */
    fr2 = *(volatile uint32_t*)0xFFFFADA8; /* RAM 0xFFFFADA8 */
    /* 0x0172F0: fcmp/gt fr3,fr2 */
    { union { uint32_t u; float f; } _a, _b; _a.u = fr2; _b.u = fr3; s->T = (_a.f > _b.f) ? 1u : 0u; }
    /* 0x0172F2: bf.s 0x017350 */
    /* 0x0172F4: op 0x0009 */
    
    if (!s->T) goto L_17350;
    /* 0x0172F6: op 0xD128 */
    s->r[1] = 0x00077BB0u;
    /* 0x0172F8: fmov.s @r1,fr1 */
    fr1 = *(volatile uint32_t*)0x00077BB0; /* ROM */
    /* 0x0172FA: fcmp/gt fr1,fr4 */
    { union { uint32_t u; float f; } _a, _b; _a.u = fr4; _b.u = fr1; s->T = (_a.f > _b.f) ? 1u : 0u; }
    /* 0x0172FC: bf.s 0x017350 */
    /* 0x0172FE: op 0x0009 */
    
    if (!s->T) goto L_17350;
    /* 0x017300: op 0xD326 */
    s->r[3] = 0x00077BB4u;
    /* 0x017302: fmov.s @r3,fr3 */
    fr3 = *(volatile uint32_t*)0x00077BB4; /* ROM */
    /* 0x017304: fcmp/gt fr4,fr3 */
    { union { uint32_t u; float f; } _a, _b; _a.u = fr3; _b.u = fr4; s->T = (_a.f > _b.f) ? 1u : 0u; }
    /* 0x017306: bf.s 0x017350 */
    /* 0x017308: op 0x0009 */
    
    if (!s->T) goto L_17350;
    /* 0x01730A: op 0xD225 */
    s->r[2] = 0x00077BB8u;
    /* 0x01730C: op 0x9130 */
    s->r[1] = (uint32_t)(int32_t)(int16_t)0x0000A9FCu;
    /* 0x01730E: fmov.s @r2,fr2 */
    fr2 = *(volatile uint32_t*)0x00077BB8; /* ROM */
    /* 0x017310: fmov.s @r1,fr0 */
    fr0 = *(volatile uint32_t*)0xFFFFA9FC; /* RAM 0xFFFFA9FC */
    /* 0x017312: fcmp/gt fr2,fr0 */
    { union { uint32_t u; float f; } _a, _b; _a.u = fr0; _b.u = fr2; s->T = (_a.f > _b.f) ? 1u : 0u; }
    /* 0x017314: bf.s 0x017350 */
    /* 0x017316: op 0x0009 */
    
    if (!s->T) goto L_17350;
    /* 0x017318: op 0xD322 */
    s->r[3] = 0x00077BBCu;
    /* 0x01731A: fmov.s @r3,fr3 */
    fr3 = *(volatile uint32_t*)0x00077BBC; /* ROM */
    /* 0x01731C: op 0x9229 */
    s->r[2] = (uint32_t)(int32_t)(int16_t)0x0000AE40u;
    /* 0x01731E: fmov.s @r2,fr2 */
    fr2 = *(volatile uint32_t*)0xFFFFAE40; /* RAM 0xFFFFAE40 */
    /* 0x017320: fcmp/gt fr3,fr2 */
    { union { uint32_t u; float f; } _a, _b; _a.u = fr2; _b.u = fr3; s->T = (_a.f > _b.f) ? 1u : 0u; }
    /* 0x017322: bf.s 0x017350 */
    /* 0x017324: op 0x0009 */
    
    if (!s->T) goto L_17350;
    /* 0x017326: op 0xD120 */
    s->r[1] = 0x00077BC0u;
    /* 0x017328: op 0x9324 */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0x0000AD78u;
    /* 0x01732A: fmov.s @r1,fr3 */
    fr3 = *(volatile uint32_t*)0x00077BC0; /* ROM */
    /* 0x01732C: fmov.s @r3,fr1 */
    fr1 = *(volatile uint32_t*)0xFFFFAD78; /* RAM 0xFFFFAD78 */
    /* 0x01732E: fcmp/gt fr3,fr1 */
    { union { uint32_t u; float f; } _a, _b; _a.u = fr1; _b.u = fr3; s->T = (_a.f > _b.f) ? 1u : 0u; }
    /* 0x017330: bf.s 0x017350 */
    /* 0x017332: op 0x0009 */
    
    if (!s->T) goto L_17350;
    /* 0x017334: op 0x634C */
    s->r[3] = s->r[4] & 0xFFu;
    /* 0x017336: op 0x2338 */
    s->T = ((s->r[3] & s->r[3]) == 0u) ? 1u : 0u;
    /* 0x017338: bf.s 0x017350 */
    /* 0x01733A: op 0x0009 */
    
    if (!s->T) goto L_17350;
    /* 0x01733C: op 0xD21B */
    s->r[2] = 0xFFFFA944u;
    /* 0x01733E: mov.w @r2,r1 */
    uint32_t t8 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)s->r[2]; /* RAM 0xFFFFA944 */
    s->r[1] = t8;
    /* 0x017340: op 0xD01B */
    s->r[0] = 0x00077B5Eu;
    /* 0x017342: mov.w @r0,r3 */
    uint32_t t10 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)s->r[0]; /* ROM */
    s->r[3] = t10;
    /* 0x017344: op 0x3132 */
    s->T = (s->r[1] >= s->r[3]) ? 1u : 0u;
    /* 0x017346: bf.s 0x017350 */
    /* 0x017348: op 0x0009 */
    
    if (!s->T) goto L_17350;
    /* 0x01734A: op 0xE201 */
    s->r[2] = (uint32_t)(int32_t)(int8_t)0x01;
    /* 0x01734C: bra 0x017352 */
    /* 0x01734E: mov.b r2,@r12 */
    *(volatile uint8_t*)0xFFFFA92B = s->r[2]; /* RAM 0xFFFFA92B */
    goto L_17352;
    L_17352: ;
    /* 0x017352: op 0x644C */
    s->r[4] = s->r[4] & 0xFFu;
    /* 0x017354: op 0xD917 */
    s->r[9] = 0x00002460u;
    /* 0x017356: op 0x2448 */
    s->T = ((s->r[4] & s->r[4]) == 0u) ? 1u : 0u;
    /* 0x017358: op 0xDD14 */
    s->r[13] = 0xFFFFA944u;
    /* 0x01735A: bf.s 0x0173B8 */
    /* 0x01735C: op 0x0009 */
    
    if (!s->T) goto L_173B8;
    /* 0x01735E: op 0xE501 */
    s->r[5] = (uint32_t)(int32_t)(int8_t)0x01;
    /* 0x017360: jsr @r9 */
    s->pr = 0x00017364;
    uint32_t t12 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)0xFFFFA944; /* RAM 0xFFFFA944 */
    s->r[4] = t12;
    f_2460(s);
    /* 0x017364: bra 0x0173BA */
    /* 0x017366: mov.w r0,@r13 */
    *(volatile uint16_t*)0xFFFFA944 = s->r[0]; /* RAM 0xFFFFA944 */
    goto L_173BA;
    L_173BA: ;
    /* 0x0173BA: op 0x9277 */
    s->r[2] = (uint32_t)(int32_t)(int16_t)0x0000C0D8u;
    /* 0x0173BC: op 0x9377 */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0x0000C0DCu;
    /* 0x0173BE: fmov.s @r2,fr4 */
    fr4 = *(volatile uint32_t*)0xFFFFC0D8; /* RAM 0xFFFFC0D8 */
    /* 0x0173C0: op 0xDB3C */
    s->r[11] = 0xFFFFA8ECu;
    /* 0x0173C2: mov.b @r12,r1 */
    uint32_t t14 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFA92B; /* RAM 0xFFFFA92B */
    s->r[1] = t14;
    /* 0x0173C4: op 0x2118 */
    s->T = ((s->r[1] & s->r[1]) == 0u) ? 1u : 0u;
    /* 0x0173C6: bf.s 0x0173D0 */
    /* 0x0173C8: fmov.s @r3,fr5 */
    fr5 = *(volatile uint32_t*)0xFFFFC0DC; /* RAM 0xFFFFC0DC */
    if (!s->T) goto L_173D0;
    /* 0x0173CA: fldi1 fr3 */
    fr3 = 0x3F800000u;
    /* 0x0173CC: bra 0x0173E8 */
    /* 0x0173CE: fmov.s fr3,@r11 */
    *(volatile uint32_t*)0xFFFFA8EC = fr3; /* RAM 0xFFFFA8EC */
    goto L_173E8;
    L_173E8: ;
    /* 0x0173E8: op 0xDA37 */
    s->r[10] = 0xFFFFA946u;
    /* 0x0173EA: op 0xDC38 */
    s->r[12] = 0xFFFFA93Cu;
    /* 0x0173EC: op 0xDD38 */
    s->r[13] = 0xFFFFA92Cu;
    /* 0x0173EE: op 0xD339 */
    s->r[3] = 0x00077BC8u;
    /* 0x0173F0: fmov.s @r11,fr2 */
    fr2 = *(volatile uint32_t*)0xFFFFA8EC; /* RAM 0xFFFFA8EC */
    /* 0x0173F2: fmov.s @r3,fr3 */
    fr3 = *(volatile uint32_t*)0x00077BC8; /* ROM */
    /* 0x0173F4: fcmp/gt fr2,fr3 */
    { union { uint32_t u; float f; } _a, _b; _a.u = fr3; _b.u = fr2; s->T = (_a.f > _b.f) ? 1u : 0u; }
    /* 0x0173F8: op 0x0009 */
    
    /* 0x0173FA: mov.w @r12,r1 */
    uint32_t t16 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)s->r[12]; /* RAM 0xFFFFA93C */
    s->r[1] = t16;
    /* 0x0173FC: op 0xD036 */
    s->r[0] = 0x00077B60u;
    /* 0x0173FE: mov.w @r0,r2 */
    uint32_t t18 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)s->r[0]; /* ROM */
    s->r[2] = t18;
    /* 0x017400: op 0x3122 */
    s->T = (s->r[1] >= s->r[2]) ? 1u : 0u;
    /* 0x017402: bf.s 0x017422 */
    /* 0x017404: op 0x0009 */
    
    if (!s->T) goto L_17422;
    /* 0x017406: op 0xD230 */
    s->r[2] = 0xFFFFA946u;
    /* 0x017408: op 0xD034 */
    s->r[0] = 0x00077B62u;
    /* 0x01740A: mov.w @r2,r1 */
    uint32_t t20 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)s->r[2]; /* RAM 0xFFFFA946 */
    s->r[1] = t20;
    /* 0x01740C: mov.w @r0,r3 */
    uint32_t t22 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)s->r[0]; /* ROM */
    s->r[3] = t22;
    /* 0x01740E: op 0x3132 */
    s->T = (s->r[1] >= s->r[3]) ? 1u : 0u;
    /* 0x017410: bt.s 0x017422 */
    /* 0x017412: op 0x0009 */
    
    if (s->T) goto L_17422;
    /* 0x017414: op 0xE501 */
    s->r[5] = (uint32_t)(int32_t)(int8_t)0x01;
    /* 0x017416: jsr @r9 */
    s->pr = 0x0001741A;
    uint32_t t24 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)0xFFFFA946; /* RAM 0xFFFFA946 */
    s->r[4] = t24;
    f_2460(s);
    /* 0x01741A: op 0xE201 */
    s->r[2] = (uint32_t)(int32_t)(int8_t)0x01;
    /* 0x01741C: mov.w r0,@r10 */
    *(volatile uint16_t*)0xFFFFA946 = s->r[0]; /* RAM 0xFFFFA946 */
    /* 0x01741E: bra 0x017424 */
    /* 0x017420: mov.b r2,@r13 */
    *(volatile uint8_t*)s->r[13] = s->r[2]; /* RAM 0xFFFFA92C */
    goto L_17424;
    L_17424: ;
    /* 0x017424: op 0xE501 */
    s->r[5] = (uint32_t)(int32_t)(int8_t)0x01;
    /* 0x017426: jsr @r9 */
    s->pr = 0x0001742A;
    uint32_t t26 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)s->r[12]; /* RAM 0xFFFFA93C */
    s->r[4] = t26;
    f_2460(s);
    /* 0x01742A: bra 0x017434 */
    /* 0x01742C: mov.w r0,@r12 */
    *(volatile uint16_t*)s->r[12] = s->r[0]; /* RAM 0xFFFFA93C */
    goto L_17434;
    L_17434: ;
    /* 0x017434: op 0xD42A */
    s->r[4] = 0xFFFFA8F0u;
    /* 0x017436: mov.b @r13,r0 */
    uint32_t t28 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)s->r[13]; /* RAM 0xFFFFA92C */
    s->r[0] = t28;
    /* 0x017438: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x01743A: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x01743C: bf.s 0x017448 */
    /* 0x01743E: op 0x0009 */
    
    if (!s->T) goto L_17448;
    /* 0x017440: op 0xD328 */
    s->r[3] = 0x00077BCCu;
    /* 0x017442: fmov.s @r3,fr3 */
    fr3 = *(volatile uint32_t*)0x00077BCC; /* ROM */
    /* 0x017444: bra 0x01745E */
    /* 0x017446: fmov.s fr3,@r4 */
    *(volatile uint32_t*)(s->r[4] + 0) = fr3;
    goto L_1745E;
    L_1745E: ;
    /* 0x01745E: lds.l @r15+,pr */
    s->pr = local_3e4;
    /* 0x017460: mov.l @r15+,r9 */
    s->r[9] = local_3e8;
    /* 0x017462: mov.l @r15+,r10 */
    s->r[10] = local_3ec;
    /* 0x017464: mov.l @r15+,r11 */
    s->r[11] = local_3f0;
    /* 0x017466: mov.l @r15+,r12 */
    s->r[12] = local_3f4;
    /* 0x017468: mov.l @r15+,r13 */
    s->r[13] = local_3f8;
    /* 0x01746A: rts */
    /* 0x01746C: mov.l @r15+,r14 */
    s->r[14] = local_3fc;
    return;
    L_17448: ;
    /* 0x017448: op 0xD227 */
    s->r[2] = 0x00077BD0u;
    /* 0x01744A: fldi0 fr2 */
    fr2 = 0u;
    /* 0x01744C: fmov.s @r4,fr4 */
    fr4 = *(volatile uint32_t*)(s->r[4] + 0);
    /* 0x01744E: fmov.s @r2,fr3 */
    fr3 = *(volatile uint32_t*)0x00077BD0; /* ROM */
    /* 0x017450: fsub fr3,fr4 */
    { union { uint32_t u; float f; } _a, _b, _r; _a.u = fr4; _b.u = fr3; _r.f = _a.f - _b.f; fr4 = _r.u; }
    /* 0x017452: fcmp/gt fr4,fr2 */
    { union { uint32_t u; float f; } _a, _b; _a.u = fr2; _b.u = fr4; s->T = (_a.f > _b.f) ? 1u : 0u; }
    /* 0x017454: bt.s 0x01745C */
    /* 0x017456: op 0x0009 */
    
    if (s->T) goto L_1745C;
    /* 0x017458: bra 0x01745E */
    /* 0x01745A: fmov.s fr4,@r4 */
    *(volatile uint32_t*)(s->r[4] + 0) = fr4;
    goto L_1745E;
    L_1745C: ;
    /* 0x01745C: fmov.s fr2,@r4 */
    *(volatile uint32_t*)(s->r[4] + 0) = fr2;
    L_17422: ;
    /* 0x017422: mov.b r14,@r13 */
    *(volatile uint8_t*)s->r[13] = s->r[14]; /* RAM 0xFFFFA92C */
    L_173D0: ;
    /* 0x0173D0: op 0xD139 */
    s->r[1] = 0x0003E0ACu;
    /* 0x0173D2: jsr @r1 */
    s->pr = 0x000173D6;
    
    f_3E0AC(s);
    /* 0x0173D6: fmov fr0,fr4 */
    fr4 = fr0;
    /* 0x0173D8: op 0xC738 */
    s->r[0] = 0x000174BCu;
    /* 0x0173DA: fmov.s @r0,fr7 */
    fr7 = *(volatile uint32_t*)0x000174BC; /* ROM */
    /* 0x0173DC: op 0xD338 */
    s->r[3] = 0x00077BC4u;
    /* 0x0173DE: fmov.s @r3,fr6 */
    fr6 = *(volatile uint32_t*)0x00077BC4; /* ROM */
    /* 0x0173E0: op 0xD238 */
    s->r[2] = 0x000023B0u;
    /* 0x0173E2: jsr @r2 */
    s->pr = 0x000173E6;
    fr5 = *(volatile uint32_t*)0xFFFFA8EC; /* RAM 0xFFFFA8EC */
    f_23B0(s);
    /* 0x0173E6: fmov.s fr0,@r11 */
    *(volatile uint32_t*)0xFFFFA8EC = fr0; /* RAM 0xFFFFA8EC */
    L_173B8: ;
    /* 0x0173B8: mov.w r14,@r13 */
    *(volatile uint16_t*)s->r[13] = s->r[14]; /* RAM 0xFFFFA944 */
    L_17350: ;
    /* 0x017350: mov.b r14,@r12 */
    *(volatile uint8_t*)s->r[12] = s->r[14]; /* RAM 0xFFFFA92B */
    return; /* fallthrough */
}
