/* ROM: 60E1D400 | Address: 0x1BFD2 | Size: 80 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST callee (CFG).
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_3EEFE(ST *s);
void f_3EFEA(ST *s);
void f_1BFD2(ST *s)
{
    uint32_t local_3f8 = 0;
    uint32_t local_3fc = 0;
    /* 0x01BFD2: mov.l r14,@-r15 */
    local_3fc = s->r[14];
    /* 0x01BFD4: sts.l pr,@-r15 */
    local_3f8 = s->pr;
    /* 0x01BFD6: op 0xDE37 */
    s->r[14] = 0x0003EFEAu;
    /* 0x01BFD8: op 0x944B */
    s->r[4] = (uint32_t)(int32_t)(int16_t)0x000080A4u;
    /* 0x01BFDA: jsr @r14 */
    s->pr = 0x0001BFDE;
    
    f_3EFEA(s);
    /* 0x01BFDE: op 0x944A */
    s->r[4] = (uint32_t)(int32_t)(int16_t)0x000080ACu;
    /* 0x01BFE0: jsr @r14 */
    s->pr = 0x0001BFE4;
    
    f_3EFEA(s);
    /* 0x01BFE4: op 0x944B */
    s->r[4] = (uint32_t)(int32_t)(int16_t)0x000080B4u;
    /* 0x01BFE6: jsr @r14 */
    s->pr = 0x0001BFEA;
    
    f_3EFEA(s);
    /* 0x01BFEA: op 0x9449 */
    s->r[4] = (uint32_t)(int32_t)(int16_t)0x000080BCu;
    /* 0x01BFEC: jsr @r14 */
    s->pr = 0x0001BFF0;
    
    f_3EFEA(s);
    /* 0x01BFF0: op 0xD431 */
    s->r[4] = 0xFFFF80CCu;
    /* 0x01BFF2: jsr @r14 */
    s->pr = 0x0001BFF6;
    
    f_3EFEA(s);
    /* 0x01BFF6: op 0xD426 */
    s->r[4] = 0xFFFF80D4u;
    /* 0x01BFF8: jsr @r14 */
    s->pr = 0x0001BFFC;
    
    f_3EFEA(s);
    /* 0x01BFFC: op 0xD426 */
    s->r[4] = 0xFFFF80DCu;
    /* 0x01BFFE: jsr @r14 */
    s->pr = 0x0001C002;
    
    f_3EFEA(s);
    /* 0x01C002: op 0xDE2E */
    s->r[14] = 0x0003EEFEu;
    /* 0x01C004: op 0x9431 */
    s->r[4] = (uint32_t)(int32_t)(int16_t)0x000080C4u;
    /* 0x01C006: jsr @r14 */
    s->pr = 0x0001C00A;
    
    f_3EEFE(s);
    /* 0x01C00A: op 0x9431 */
    s->r[4] = (uint32_t)(int32_t)(int16_t)0x000080C6u;
    /* 0x01C00C: jsr @r14 */
    s->pr = 0x0001C010;
    
    f_3EEFE(s);
    /* 0x01C010: op 0x9437 */
    s->r[4] = (uint32_t)(int32_t)(int16_t)0x000080C8u;
    /* 0x01C012: jsr @r14 */
    s->pr = 0x0001C016;
    
    f_3EEFE(s);
    /* 0x01C016: op 0x9429 */
    s->r[4] = (uint32_t)(int32_t)(int16_t)0x000080CAu;
    /* 0x01C018: jsr @r14 */
    s->pr = 0x0001C01C;
    
    f_3EEFE(s);
    /* 0x01C01C: lds.l @r15+,pr */
    s->pr = local_3f8;
    /* 0x01C01E: rts */
    /* 0x01C020: mov.l @r15+,r14 */
    s->r[14] = local_3fc;
    return;
    return; /* fallthrough */
}
