/* ROM: 60E0FC00 | Address: 0x1E4C | Size: 36 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v7.py — ST (shared state) ABI,
 * leaf callee library (c/lib/f_<hex>.c). Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_1E4C(ST *s)
{
    /* 0x001E4C: mov.b @(0x1,r4),r0 */
    uint32_t t2 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)(s->r[4] + 1);
    s->r[0] = t2;
    /* 0x001E4E: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x001E50: mov.b @r4,r2 */
    uint32_t t4 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)s->r[4];
    s->r[2] = t4;
    /* 0x001E52: op 0x4028 */
    s->r[0] = (s->r[0] << 16);
    /* 0x001E54: op 0x6303 */
    s->r[3] = s->r[0];
    /* 0x001E56: op 0x622C */
    s->r[2] = s->r[2] & 0xFFu;
    /* 0x001E58: mov.b @(0x2,r4),r0 */
    uint32_t t6 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)(s->r[4] + 2);
    s->r[0] = t6;
    /* 0x001E5A: op 0x4228 */
    s->r[2] = (s->r[2] << 16);
    /* 0x001E5C: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x001E5E: op 0x4018 */
    s->r[0] = (s->r[0] << 8);
    /* 0x001E60: op 0x330C */
    s->r[3] = s->r[3] + s->r[0];
    /* 0x001E62: op 0x4218 */
    s->r[2] = (s->r[2] << 8);
    /* 0x001E64: mov.b @(0x3,r4),r0 */
    uint32_t t8 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)(s->r[4] + 3);
    s->r[0] = t8;
    /* 0x001E66: op 0x332C */
    s->r[3] = s->r[3] + s->r[2];
    /* 0x001E68: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x001E6A: op 0x6433 */
    s->r[4] = s->r[3];
    /* 0x001E6C: op 0x340C */
    s->r[4] = s->r[4] + s->r[0];
    /* 0x001E6E: rts */
    /* 0x001E70: op 0x6043 */
    s->r[0] = s->r[4];
    return;
    return; /* fallthrough */
}
