/* ROM: 60E0FC00 | Address: 0x219EE | Size: 66 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST callee (CFG).
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, vbr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_21EFE(ST *s);
void f_219EE(ST *s)
{
    /* 0x0219EE: op 0x9EE2 */
    s->r[14] = (uint32_t)(int32_t)(int16_t)0x00007FFCu;
    /* 0x0219F0: mov.b r0,@(r0+r0) (rt-base) */
    *(volatile uint8_t*)(s->r[0] + s->r[0]) = s->r[0];
    /* 0x0219F2: bra 0x021EFE (tail) */
    /* 0x0219F4: op 0x0001 */
    /* delay slot 0x0001 — opaque */
     { /* f_21EFE: callee lib not generated — early return */ return; }
    return; /* fallthrough */
}
