/* ROM: 60E0FC00 | Address: 0x21DFA | Size: 14 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v7.py — ST (shared state) ABI,
 * leaf callee library (c/lib/f_<hex>.c). Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, vbr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_21DFA(ST *s)
{
    uint32_t local_3fc = 0;
    /* 0x021DFA: sts.l pr,@-r15 */
    local_3fc = s->pr;
    /* 0x021DFC: op 0xD314 */
    s->r[3] = 0x0001EAE8u;
    /* 0x021DFE: jsr @r3 */
    /* 0x021E00: op 0x0009 */
    
    /* 0x021E02: op 0xD214 */
    s->r[2] = 0x0001F5C4u;
    /* 0x021E04: jmp @r2 (tail) */
    /* 0x021E06: lds.l @r15+,pr */
    s->pr = local_3fc;
    return; /* fallthrough */
}
