/* ROM: 60E0FC00 | Address: 0x22BBA | Size: 70 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST callee (CFG).
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_3920(ST *s);
void f_3934(ST *s);
void f_22C00(ST *s);
void f_22D20(ST *s);
void f_22E7C(ST *s);
void f_25D26(ST *s);
void f_22BBA(ST *s)
{
    uint32_t local_3f8 = 0;
    uint32_t local_3fc = 0;
    /* 0x022BBA: sts.l pr,@-r15 */
    local_3fc = s->pr;
    /* 0x022BBC: op 0xD30A */
    s->r[3] = 0x00003920u;
    /* 0x022BBE: op 0x7FFC */
    s->r[15] = s->r[15] + (uint32_t)(int32_t)(int8_t)0xFC;
    /* 0x022BC0: jsr @r3 */
    s->pr = 0x00022BC4;
    s->r[4] = (uint32_t)(int32_t)(int8_t)0x10;
    f_3920(s);
    /* 0x022BC4: op 0xD309 */
    s->r[3] = 0x00022C00u;
    /* 0x022BC6: jsr @r3 */
    s->pr = 0x00022BCA;
    local_3f8 = s->r[0];
    f_22C00(s);
    /* 0x022BCA: op 0xD209 */
    s->r[2] = 0x00022D20u;
    /* 0x022BCC: jsr @r2 */
    s->pr = 0x00022BD0;
    
    f_22D20(s);
    /* 0x022BD0: op 0xD308 */
    s->r[3] = 0x00022E7Cu;
    /* 0x022BD2: jsr @r3 */
    s->pr = 0x00022BD6;
    
    f_22E7C(s);
    /* 0x022BD6: op 0xD208 */
    s->r[2] = 0x00025D26u;
    /* 0x022BD8: jsr @r2 */
    s->pr = 0x00022BDC;
    
    f_25D26(s);
    /* 0x022BDC: mov.l @r15+,r4 */
    s->r[4] = local_3f8;
    /* 0x022BDE: op 0xD307 */
    s->r[3] = 0x00003934u;
    /* 0x022BE0: jmp @r3 (tail) */
    s->pr = local_3fc;
    f_3934(s);
    return;
    return; /* fallthrough */
}
