/* ROM: 60E0FC00 | Address: 0x239C | Size: 18 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v7.py — ST (shared state) ABI,
 * leaf callee library (c/lib/f_<hex>.c). Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, vbr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_239C(ST *s)
{
    /* 0x00239C: op 0xE500 */
    s->r[5] = (uint32_t)(int32_t)(int8_t)0x00;
    /* 0x00239E: op 0x4408 */
    s->r[4] = (s->r[4] << 2);
    /* 0x0023A0: op 0x4400 */
    s->T = (s->r[4] >> 31) & 1u; s->r[4] = (s->r[4] << 1);
    /* 0x0023A2: op 0x3542 */
    s->T = (s->r[5] >= s->r[4]) ? 1u : 0u;
    /* 0x0023A4: bt 0x0023AC */
    if (s->T) goto L_23AC;
    L_23A6: ;
    /* 0x0023A6: op 0x7501 */
    s->r[5] = s->r[5] + (uint32_t)(int32_t)(int8_t)0x01;
    /* 0x0023A8: op 0x3542 */
    s->T = (s->r[5] >= s->r[4]) ? 1u : 0u;
    /* 0x0023AA: bf 0x0023A6 */
    if (!s->T) goto L_23A6;
    L_23AC: ;
    /* 0x0023AC: rts */
    /* 0x0023AE: op 0x0009 */
    
    return;
    return; /* fallthrough */
}
