/* ROM: 60E0FC00 | Address: 0x24C9E | Size: 160 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST callee (CFG).
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, vbr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_25708(ST *s);
void f_24C9E(ST *s)
{
    uint32_t local_400 = 0;
    uint32_t local_404 = 0;
    uint32_t local_408 = 0;
    uint32_t local_40c = 0;
    uint32_t fr0 = 0;
    uint32_t fr1 = 0;
    uint32_t fr2 = 0;
    uint32_t fr3 = 0;
    /* 0x024C9E: bsr 0x25708 */
    /* 0x024CA0: op 0xB534 */
    s->pr = 0x00024CA2;
    /* delay slot 0xB534 — opaque */
    f_25708(s);
    /* 0x024CA2: op 0x9170 */
    s->r[1] = (uint32_t)(int32_t)(int16_t)0x0000B534u;
    /* 0x024CA4: mov.b r13,@r1 */
    *(volatile uint8_t*)0xFFFFB534 = s->r[13]; /* RAM 0xFFFFB534 */
    /* 0x024CA6: jsr @r14 (runtime) */
    /* 0x024CA8: op 0x0009 */
    
    s->pr = 0x00024CAA;
    ((void(*)(ST*))s->r[14])(s);
    /* 0x024CAA: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x024CAC: op 0x2008 */
    s->T = ((s->r[0] & s->r[0]) == 0u) ? 1u : 0u;
    /* 0x024CAE: bf.s 0x024CB8 */
    /* 0x024CB0: op 0xE441 */
    s->r[4] = (uint32_t)(int32_t)(int8_t)0x41;
    if (!s->T) goto L_24CB8;
    /* 0x024CB2: op 0x9269 */
    s->r[2] = (uint32_t)(int32_t)(int16_t)0x0000B535u;
    /* 0x024CB4: bra 0x024CBC */
    /* 0x024CB6: mov.b r12,@r2 */
    *(volatile uint8_t*)0xFFFFB535 = s->r[12]; /* RAM 0xFFFFB535 */
    goto L_24CBC;
    L_24CBC: ;
    /* 0x024CBC: jsr @r14 (runtime) */
    /* 0x024CBE: op 0x0009 */
    
    s->pr = 0x00024CC0;
    ((void(*)(ST*))s->r[14])(s);
    /* 0x024CC0: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x024CC2: op 0x2008 */
    s->T = ((s->r[0] & s->r[0]) == 0u) ? 1u : 0u;
    /* 0x024CC4: bf.s 0x024D02 */
    /* 0x024CC6: op 0x0009 */
    
    if (!s->T) goto L_24D02;
    /* 0x024CC8: op 0x935F */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0x0000B46Eu;
    /* 0x024CCA: mov.b @r3,r2 */
    uint32_t t2 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFB46E; /* RAM 0xFFFFB46E */
    s->r[2] = t2;
    /* 0x024CCC: op 0x2228 */
    s->T = ((s->r[2] & s->r[2]) == 0u) ? 1u : 0u;
    /* 0x024CCE: bt.s 0x024CEE */
    /* 0x024CD0: op 0x0009 */
    
    if (s->T) goto L_24CEE;
    /* 0x024CD2: op 0xD135 */
    s->r[1] = 0x0007B800u;
    /* 0x024CD4: op 0x905A */
    s->r[0] = (uint32_t)(int32_t)(int16_t)0x0000B594u;
    /* 0x024CD6: fmov.s @r1,fr3 */
    fr3 = *(volatile uint32_t*)0x0007B800; /* ROM */
    /* 0x024CD8: fmov.s @r0,fr2 */
    fr2 = *(volatile uint32_t*)0xFFFFB594; /* RAM 0xFFFFB594 */
    /* 0x024CDA: fcmp/gt fr2,fr3 */
    { union { uint32_t u; float f; } _a, _b; _a.u = fr3; _b.u = fr2; s->T = (_a.f > _b.f) ? 1u : 0u; }
    /* 0x024CDC: bt.s 0x024CEE */
    /* 0x024CDE: op 0x0009 */
    
    if (s->T) goto L_24CEE;
    /* 0x024CE0: op 0xD332 */
    s->r[3] = 0x0007B804u;
    /* 0x024CE2: fmov.s @r3,fr1 */
    fr1 = *(volatile uint32_t*)0x0007B804; /* ROM */
    /* 0x024CE4: op 0x9253 */
    s->r[2] = (uint32_t)(int32_t)(int16_t)0x0000B45Cu;
    /* 0x024CE6: fmov.s @r2,fr0 */
    fr0 = *(volatile uint32_t*)0xFFFFB45C; /* RAM 0xFFFFB45C */
    /* 0x024CE8: fcmp/gt fr0,fr1 */
    { union { uint32_t u; float f; } _a, _b; _a.u = fr1; _b.u = fr0; s->T = (_a.f > _b.f) ? 1u : 0u; }
    /* 0x024CEA: bt.s 0x024D02 */
    /* 0x024CEC: op 0x0009 */
    
    if (s->T) goto L_24D02;
    L_24CEE: ;
    /* 0x024CEE: op 0xD130 */
    s->r[1] = 0x0007B808u;
    /* 0x024CF0: op 0x904E */
    s->r[0] = (uint32_t)(int32_t)(int16_t)0x0000AA34u;
    /* 0x024CF2: fmov.s @r1,fr3 */
    fr3 = *(volatile uint32_t*)0x0007B808; /* ROM */
    /* 0x024CF4: fmov.s @r0,fr2 */
    fr2 = *(volatile uint32_t*)0xFFFFAA34; /* RAM 0xFFFFAA34 */
    /* 0x024CF6: fcmp/gt fr3,fr2 */
    { union { uint32_t u; float f; } _a, _b; _a.u = fr2; _b.u = fr3; s->T = (_a.f > _b.f) ? 1u : 0u; }
    /* 0x024CF8: bt.s 0x024D02 */
    /* 0x024CFA: op 0x0009 */
    
    if (s->T) goto L_24D02;
    /* 0x024CFC: op 0x9249 */
    s->r[2] = (uint32_t)(int32_t)(int16_t)0x0000B536u;
    /* 0x024CFE: bra 0x024D06 */
    /* 0x024D00: mov.b r12,@r2 */
    *(volatile uint8_t*)s->r[2] = s->r[12]; /* RAM 0xFFFFB536 */
    goto L_24D06;
    L_24D06: ;
    /* 0x024D06: op 0x9445 */
    s->r[4] = (uint32_t)(int32_t)(int16_t)0x0000B537u;
    /* 0x024D08: op 0x9345 */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0x0000B489u;
    /* 0x024D0A: mov.b @r3,r0 */
    uint32_t t4 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)s->r[3]; /* RAM 0xFFFFB489 */
    s->r[0] = t4;
    /* 0x024D0C: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x024D0E: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x024D10: bt.s 0x024D20 */
    /* 0x024D12: op 0x0009 */
    
    if (s->T) goto L_24D20;
    /* 0x024D14: op 0x9240 */
    s->r[2] = (uint32_t)(int32_t)(int16_t)0x0000CFD9u;
    /* 0x024D16: mov.b @r2,r0 */
    uint32_t t6 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)s->r[2]; /* RAM 0xFFFFCFD9 */
    s->r[0] = t6;
    /* 0x024D18: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x024D1A: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x024D1C: bf.s 0x024D24 */
    /* 0x024D1E: op 0x0009 */
    
    if (!s->T) goto L_24D24;
    L_24D20: ;
    /* 0x024D20: bra 0x024D26 */
    /* 0x024D22: mov.b r13,@r4 */
    *(volatile uint8_t*)s->r[4] = s->r[13]; /* RAM 0xFFFFB537 */
    goto L_24D26;
    L_24D26: ;
    /* 0x024D26: op 0x9338 */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0x0000BD68u;
    /* 0x024D28: mov.b @r3,r2 */
    uint32_t t8 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)s->r[3]; /* RAM 0xFFFFBD68 */
    s->r[2] = t8;
    /* 0x024D2A: op 0x2228 */
    s->T = ((s->r[2] & s->r[2]) == 0u) ? 1u : 0u;
    /* 0x024D2C: bf.s 0x024D34 */
    /* 0x024D2E: op 0x0009 */
    
    if (!s->T) goto L_24D34;
    /* 0x024D30: op 0x9034 */
    s->r[0] = (uint32_t)(int32_t)(int16_t)0x0000B568u;
    /* 0x024D32: mov.b r13,@r0 */
    *(volatile uint8_t*)s->r[0] = s->r[13]; /* RAM 0xFFFFB568 */
    L_24D34: ;
    /* 0x024D34: lds.l @r15+,pr */
    s->pr = local_400;
    /* 0x024D36: mov.l @r15+,r12 */
    s->r[12] = local_404;
    /* 0x024D38: mov.l @r15+,r13 */
    s->r[13] = local_408;
    /* 0x024D3A: rts */
    /* 0x024D3C: mov.l @r15+,r14 */
    s->r[14] = local_40c;
    return;
    L_24D24: ;
    /* 0x024D24: mov.b r12,@r4 */
    *(volatile uint8_t*)s->r[4] = s->r[12]; /* RAM 0xFFFFB537 */
    L_24D02: ;
    /* 0x024D02: op 0x9146 */
    s->r[1] = (uint32_t)(int32_t)(int16_t)0x0000B536u;
    /* 0x024D04: mov.b r13,@r1 */
    *(volatile uint8_t*)s->r[1] = s->r[13]; /* RAM 0xFFFFB536 */
    L_24CB8: ;
    /* 0x024CB8: op 0x9166 */
    s->r[1] = (uint32_t)(int32_t)(int16_t)0x0000B535u;
    /* 0x024CBA: mov.b r13,@r1 */
    *(volatile uint8_t*)s->r[1] = s->r[13]; /* RAM 0xFFFFB535 */
    return; /* fallthrough */
}
