/* ROM: 60E1D400 | Address: 0x25DAA | Size: 48 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST callee (CFG).
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_2404(ST *s);
void f_25DAA(ST *s)
{
    uint32_t local_3f8 = 0;
    uint32_t local_3fc = 0;
    uint32_t fr0 = 0;
    uint32_t fr3 = 0;
    uint32_t fr4 = 0;
    uint32_t fr5 = 0;
    uint32_t fr6 = 0;
    /* 0x025DAA: mov.l r14,@-r15 */
    local_3fc = s->r[14];
    /* 0x025DAC: sts.l pr,@-r15 */
    local_3f8 = s->pr;
    /* 0x025DAE: op 0x9E14 */
    s->r[14] = (uint32_t)(int32_t)(int16_t)0x0000B5B8u;
    /* 0x025DB0: op 0xD30F */
    s->r[3] = 0xFFFFB5D4u;
    /* 0x025DB2: fmov.s @r3,fr0 */
    fr0 = *(volatile uint32_t*)0xFFFFB5D4; /* RAM 0xFFFFB5D4 */
    /* 0x025DB4: fmov.s @r14,fr3 */
    fr3 = *(volatile uint32_t*)0xFFFFB5B8; /* RAM 0xFFFFB5B8 */
    /* 0x025DB6: fsub fr0,fr3 */
    { union { uint32_t u; float f; } _a, _b, _r; _a.u = fr3; _b.u = fr0; _r.f = _a.f - _b.f; fr3 = _r.u; }
    /* 0x025DB8: fmov.s @r14,fr4 */
    fr4 = *(volatile uint32_t*)0xFFFFB5B8; /* RAM 0xFFFFB5B8 */
    /* 0x025DBA: op 0xD218 */
    s->r[2] = 0x00075174u;
    /* 0x025DBC: op 0xC718 */
    s->r[0] = 0x00025E20u;
    /* 0x025DBE: fmov.s @r2,fr0 */
    fr0 = *(volatile uint32_t*)0x00075174; /* ROM */
    /* 0x025DC0: fmov.s @r0,fr6 */
    fr6 = *(volatile uint32_t*)0x00025E20; /* ROM */
    /* 0x025DC2: fmac fr0,fr3,fr4 */
    { union { uint32_t u; float f; } _a, _b, _c, _r; _a.u = fr0; _b.u = fr3; _c.u = fr4; _r.f = (float)((double)_a.f * (double)_b.f + (double)_c.f); fr4 = _r.u; }
    /* 0x025DC4: op 0xD117 */
    s->r[1] = 0x00002404u;
    /* 0x025DC6: jsr @r1 */
    s->pr = 0x00025DCA;
    fr5 = 0u;
    f_2404(s);
    /* 0x025DCA: op 0x930A */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0x0000B5CCu;
    /* 0x025DCC: fmov.s fr0,@r3 */
    *(volatile uint32_t*)0xFFFFB5CC = fr0; /* RAM 0xFFFFB5CC */
    /* 0x025DCE: fmov.s @r14,fr3 */
    fr3 = *(volatile uint32_t*)0xFFFFB5B8; /* RAM 0xFFFFB5B8 */
    /* 0x025DD0: op 0xD207 */
    s->r[2] = 0xFFFFB5D4u;
    /* 0x025DD2: fmov.s fr3,@r2 */
    *(volatile uint32_t*)0xFFFFB5D4 = fr3; /* RAM 0xFFFFB5D4 */
    /* 0x025DD4: lds.l @r15+,pr */
    s->pr = local_3f8;
    /* 0x025DD6: rts */
    /* 0x025DD8: mov.l @r15+,r14 */
    s->r[14] = local_3fc;
    return;
    return; /* fallthrough */
}
