/* ROM: 60E0FC00 | Address: 0x25862 | Size: 20 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v7.py — ST (shared state) ABI,
 * leaf callee library (c/lib/f_<hex>.c). Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_25862(ST *s)
{
    /* 0x025862: op 0x934D */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0x0000CCA0u;
    /* 0x025864: mov.b @r3,r0 */
    uint32_t t2 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFCCA0; /* RAM 0xFFFFCCA0 */
    s->r[0] = t2;
    /* 0x025866: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x025868: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x02586A: bf.s 0x025874 */
    /* 0x02586C: op 0x0009 */
    
    if (!s->T) goto L_25874;
    /* 0x02586E: op 0xE101 */
    s->r[1] = (uint32_t)(int32_t)(int8_t)0x01;
    /* 0x025870: op 0x9247 */
    s->r[2] = (uint32_t)(int32_t)(int16_t)0x0000B5B5u;
    /* 0x025872: mov.b r1,@r2 */
    *(volatile uint8_t*)0xFFFFB5B5 = s->r[1]; /* RAM 0xFFFFB5B5 */
    L_25874: ;
    /* 0x025874: rts */
    /* 0x025876: op 0x0009 */
    
    return;
    return; /* fallthrough */
}
