/* ROM: 60E0FC00 | Address: 0x2664A | Size: 1098 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST callee (CFG).
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, vbr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_2068(ST *s);
void f_23E4(ST *s);
void f_23F4(ST *s);
void f_2440(ST *s);
void f_2478(ST *s);
void f_5B394(ST *s);
void f_2664A(ST *s)
{
    uint32_t local_400 = 0;
    uint32_t local_404 = 0;
    uint32_t local_408 = 0;
    uint32_t local_40c = 0;
    uint32_t local_410 = 0;
    uint32_t local_414 = 0;
    uint32_t local_418 = 0;
    uint32_t local_41c = 0;
    uint32_t local_420 = 0;
    uint32_t local_424 = 0;
    uint32_t fr0 = 0;
    uint32_t fr1 = 0;
    uint32_t fr12 = 0;
    uint32_t fr13 = 0;
    uint32_t fr14 = 0;
    uint32_t fr15 = 0;
    uint32_t fr2 = 0;
    uint32_t fr3 = 0;
    uint32_t fr4 = 0;
    uint32_t fr5 = 0;
    uint32_t fr6 = 0;
    /* 0x02664A: op 0x2228 */
    s->T = ((s->r[2] & s->r[2]) == 0u) ? 1u : 0u;
    /* 0x02664C: bt.s 0x02668C */
    /* 0x02664E: op 0x0009 */
    
    if (s->T) goto L_2668C;
    /* 0x026650: op 0x913A */
    s->r[1] = (uint32_t)(int32_t)(int16_t)0x0000B5FEu;
    /* 0x026652: mov.b @r1,r0 */
    uint32_t t2 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFB5FE; /* RAM 0xFFFFB5FE */
    s->r[0] = t2;
    /* 0x026654: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x026656: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x026658: bt.s 0x02668C */
    /* 0x02665A: op 0x0009 */
    
    if (s->T) goto L_2668C;
    /* 0x02665C: op 0x9235 */
    s->r[2] = (uint32_t)(int32_t)(int16_t)0x0000B5FCu;
    /* 0x02665E: mov.b @r2,r0 */
    uint32_t t4 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFB5FC; /* RAM 0xFFFFB5FC */
    s->r[0] = t4;
    /* 0x026660: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x026662: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x026664: bt.s 0x02668C */
    /* 0x026666: op 0x0009 */
    
    if (s->T) goto L_2668C;
    /* 0x026668: op 0x9330 */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0x0000B5FDu;
    /* 0x02666A: mov.b @r3,r0 */
    uint32_t t6 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFB5FD; /* RAM 0xFFFFB5FD */
    s->r[0] = t6;
    /* 0x02666C: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x02666E: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x026670: bt.s 0x02668C */
    /* 0x026672: op 0x0009 */
    
    if (s->T) goto L_2668C;
    /* 0x026674: op 0x922B */
    s->r[2] = (uint32_t)(int32_t)(int16_t)0x0000C5EAu;
    /* 0x026676: mov.b @r2,r0 */
    uint32_t t8 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)s->r[2]; /* RAM 0xFFFFC5EA */
    s->r[0] = t8;
    /* 0x026678: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x02667A: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x02667C: bt.s 0x02668C */
    /* 0x02667E: op 0x0009 */
    
    if (s->T) goto L_2668C;
    /* 0x026680: op 0x9326 */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0x0000C5DBu;
    /* 0x026682: mov.b @r3,r0 */
    uint32_t t10 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)s->r[3]; /* RAM 0xFFFFC5DB */
    s->r[0] = t10;
    /* 0x026684: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x026686: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x026688: bf.s 0x026690 */
    /* 0x02668A: op 0x0009 */
    
    if (!s->T) goto L_26690;
    L_2668C: ;
    /* 0x02668C: bra 0x026692 */
    /* 0x02668E: mov.b r13,@r5 */
    *(volatile uint8_t*)s->r[5] = s->r[13];
    goto L_26692;
    L_26692: ;
    /* 0x026692: op 0x9418 */
    s->r[4] = (uint32_t)(int32_t)(int16_t)0x0000B660u;
    /* 0x026694: op 0x9B1D */
    s->r[11] = (uint32_t)(int32_t)(int16_t)0x0000B667u;
    /* 0x026696: mov.b @r11,r0 */
    uint32_t t12 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFB667; /* RAM 0xFFFFB667 */
    s->r[0] = t12;
    /* 0x026698: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x02669A: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x02669C: bf.s 0x0266DC */
    /* 0x02669E: op 0x0009 */
    
    if (!s->T) goto L_266DC;
    /* 0x0266A0: op 0xC70C */
    s->r[0] = 0x000266D4u;
    /* 0x0266A2: fmov.s @r0,fr3 */
    fr3 = *(volatile uint32_t*)0x000266D4; /* ROM */
    /* 0x0266A4: fcmp/gt fr3,fr14 */
    { union { uint32_t u; float f; } _a, _b; _a.u = fr14; _b.u = fr3; s->T = (_a.f > _b.f) ? 1u : 0u; }
    /* 0x0266A6: bt.s 0x0266DC */
    /* 0x0266A8: op 0x0009 */
    
    if (s->T) goto L_266DC;
    /* 0x0266AA: mov.w @r4,r5 */
    uint32_t t14 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)0xFFFFB660; /* RAM 0xFFFFB660 */
    s->r[5] = t14;
    /* 0x0266AC: op 0x625D */
    s->r[2] = s->r[5] & 0xFFFFu;
    /* 0x0266AE: op 0x4215 */
    s->T = ((int32_t)s->r[2] > 0) ? 1u : 0u;
    /* 0x0266B0: bf.s 0x0266E0 */
    /* 0x0266B2: op 0x0009 */
    
    if (!s->T) goto L_266E0;
    /* 0x0266B4: op 0xD208 */
    s->r[2] = 0x0000FFFFu;
    /* 0x0266B6: op 0x352C */
    s->r[5] = s->r[5] + s->r[2];
    /* 0x0266B8: bra 0x0266E0 */
    /* 0x0266BA: mov.w r5,@r4 */
    *(volatile uint16_t*)0xFFFFB660 = s->r[5]; /* RAM 0xFFFFB660 */
    goto L_266E0;
    L_266E0: ;
    /* 0x0266E0: op 0xD929 */
    s->r[9] = 0x00002068u;
    /* 0x0266E2: op 0x934B */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0x0000B610u;
    /* 0x0266E4: op 0xD429 */
    s->r[4] = 0x00068AE4u;
    /* 0x0266E6: jsr @r9 */
    /* 0x0266E8: fmov.s @r3,fr4 */
    s->pr = 0x000266EA;
    fr4 = *(volatile uint32_t*)0xFFFFB610; /* RAM 0xFFFFB610 */
    f_2068(s);
    /* 0x0266EA: fmov fr0,fr15 */
    fr15 = fr0;
    /* 0x0266EC: op 0x9246 */
    s->r[2] = (uint32_t)(int32_t)(int16_t)0x0000B610u;
    /* 0x0266EE: op 0xD428 */
    s->r[4] = 0x00068B20u;
    /* 0x0266F0: jsr @r9 */
    /* 0x0266F2: fmov.s @r2,fr4 */
    s->pr = 0x000266F4;
    fr4 = *(volatile uint32_t*)0xFFFFB610; /* RAM 0xFFFFB610 */
    f_2068(s);
    /* 0x0266F4: op 0x9342 */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0x0000B610u;
    /* 0x0266F6: fmov fr0,fr12 */
    fr12 = fr0;
    /* 0x0266F8: op 0xD426 */
    s->r[4] = 0x00068B34u;
    /* 0x0266FA: jsr @r9 */
    /* 0x0266FC: fmov.s @r3,fr4 */
    s->pr = 0x000266FE;
    fr4 = *(volatile uint32_t*)0xFFFFB610; /* RAM 0xFFFFB610 */
    f_2068(s);
    /* 0x0266FE: fmov fr0,fr3 */
    fr3 = fr0;
    /* 0x026700: mov.b @(0x4,r15),r0 */
    s->r[0] = (uint32_t)(int32_t)(int8_t)(local_404 & 0xFFu);
    /* 0x026702: fmov fr15,fr4 */
    fr4 = fr15;
    /* 0x026704: fsub fr12,fr4 */
    { union { uint32_t u; float f; } _a, _b, _r; _a.u = fr4; _b.u = fr12; _r.f = _a.f - _b.f; fr4 = _r.u; }
    /* 0x026706: fmov fr15,fr5 */
    fr5 = fr15;
    /* 0x026708: op 0x6A03 */
    s->r[10] = s->r[0];
    /* 0x02670A: op 0x6AAC */
    s->r[10] = s->r[10] & 0xFFu;
    /* 0x02670C: op 0x60A3 */
    s->r[0] = s->r[10];
    /* 0x02670E: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x026710: bf.s 0x026722 */
    /* 0x026712: fsub fr3,fr5 */
    { union { uint32_t u; float f; } _a, _b, _r; _a.u = fr5; _b.u = fr3; _r.f = _a.f - _b.f; fr5 = _r.u; }
    if (!s->T) goto L_26722;
    /* 0x026714: op 0x9333 */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0x0000B680u;
    /* 0x026716: op 0xE104 */
    s->r[1] = (uint32_t)(int32_t)(int8_t)0x04;
    /* 0x026718: mov.b @r3,r2 */
    uint32_t t16 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)s->r[3]; /* RAM 0xFFFFB680 */
    s->r[2] = t16;
    /* 0x02671A: op 0x622C */
    s->r[2] = s->r[2] & 0xFFu;
    /* 0x02671C: op 0x3213 */
    s->T = ((int32_t)s->r[2] >= (int32_t)s->r[1]) ? 1u : 0u;
    /* 0x02671E: bf.s 0x026776 */
    /* 0x026720: op 0x0009 */
    
    if (!s->T) goto L_26776;
    L_26722: ;
    /* 0x026722: op 0x932D */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0x0000B666u;
    /* 0x026724: mov.b @r3,r0 */
    uint32_t t18 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)s->r[3]; /* RAM 0xFFFFB666 */
    s->r[0] = t18;
    /* 0x026726: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x026728: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x02672A: bt.s 0x026776 */
    /* 0x02672C: op 0x0009 */
    
    if (s->T) goto L_26776;
    /* 0x02672E: op 0x9228 */
    s->r[2] = (uint32_t)(int32_t)(int16_t)0x0000AD7Cu;
    /* 0x026730: mov.b @r2,r0 */
    uint32_t t20 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)s->r[2]; /* RAM 0xFFFFAD7C */
    s->r[0] = t20;
    /* 0x026732: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x026734: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x026736: bt.s 0x026776 */
    /* 0x026738: op 0x0009 */
    
    if (s->T) goto L_26776;
    /* 0x02673A: op 0x60CC */
    s->r[0] = s->r[12] & 0xFFu;
    /* 0x02673C: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x02673E: bf.s 0x02674A */
    /* 0x026740: op 0x0009 */
    
    if (!s->T) goto L_2674A;
    /* 0x026742: op 0x608C */
    s->r[0] = s->r[8] & 0xFFu;
    /* 0x026744: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x026746: bt.s 0x026776 */
    /* 0x026748: op 0x0009 */
    
    if (s->T) goto L_26776;
    L_2674A: ;
    /* 0x02674A: op 0xD313 */
    s->r[3] = 0x00074AE4u;
    /* 0x02674C: fmov.s @r3,fr3 */
    fr3 = *(volatile uint32_t*)0x00074AE4; /* ROM */
    /* 0x02674E: fcmp/gt fr14,fr3 */
    { union { uint32_t u; float f; } _a, _b; _a.u = fr3; _b.u = fr14; s->T = (_a.f > _b.f) ? 1u : 0u; }
    /* 0x026750: bt.s 0x026776 */
    /* 0x026752: op 0x0009 */
    
    if (s->T) goto L_26776;
    /* 0x026754: op 0xD211 */
    s->r[2] = 0x00074AECu;
    /* 0x026756: fmov.s @r2,fr2 */
    fr2 = *(volatile uint32_t*)0x00074AEC; /* ROM */
    /* 0x026758: op 0x9114 */
    s->r[1] = (uint32_t)(int32_t)(int16_t)0x0000B648u;
    /* 0x02675A: fmov.s @r1,fr1 */
    fr1 = *(volatile uint32_t*)0xFFFFB648; /* RAM 0xFFFFB648 */
    /* 0x02675C: fcmp/gt fr1,fr2 */
    { union { uint32_t u; float f; } _a, _b; _a.u = fr2; _b.u = fr1; s->T = (_a.f > _b.f) ? 1u : 0u; }
    /* 0x02675E: bt.s 0x026776 */
    /* 0x026760: op 0x0009 */
    
    if (s->T) goto L_26776;
    /* 0x026762: op 0xD30F */
    s->r[3] = 0x00074AF4u;
    /* 0x026764: op 0x900F */
    s->r[0] = (uint32_t)(int32_t)(int16_t)0x0000B5F0u;
    /* 0x026766: fmov.s @r3,fr3 */
    fr3 = *(volatile uint32_t*)0x00074AF4; /* ROM */
    /* 0x026768: fmov.s @r0,fr0 */
    fr0 = *(volatile uint32_t*)0xFFFFB5F0; /* RAM 0xFFFFB5F0 */
    /* 0x02676A: fcmp/gt fr0,fr3 */
    { union { uint32_t u; float f; } _a, _b; _a.u = fr3; _b.u = fr0; s->T = (_a.f > _b.f) ? 1u : 0u; }
    /* 0x02676C: bf.s 0x026776 */
    /* 0x02676E: op 0x0009 */
    
    if (!s->T) goto L_26776;
    /* 0x026770: fcmp/gt fr13,fr5 */
    { union { uint32_t u; float f; } _a, _b; _a.u = fr5; _b.u = fr13; s->T = (_a.f > _b.f) ? 1u : 0u; }
    /* 0x026772: bf.s 0x0267A4 */
    /* 0x026774: op 0x0009 */
    
    if (!s->T) goto L_267A4;
    L_26776: ;
    /* 0x026776: bra 0x0267DE */
    /* 0x026778: mov.b r14,@r11 */
    *(volatile uint8_t*)0xFFFFB667 = s->r[14]; /* RAM 0xFFFFB667 */
    goto L_267DE;
    L_267DE: ;
    /* 0x0267DE: op 0x60A3 */
    s->r[0] = s->r[10];
    /* 0x0267E0: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x0267E2: bf.s 0x026814 */
    /* 0x0267E4: op 0x0009 */
    
    if (!s->T) goto L_26814;
    /* 0x0267E6: op 0xE104 */
    s->r[1] = (uint32_t)(int32_t)(int8_t)0x04;
    /* 0x0267E8: op 0x9243 */
    s->r[2] = (uint32_t)(int32_t)(int16_t)0x0000B680u;
    /* 0x0267EA: mov.b @r2,r3 */
    uint32_t t22 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)s->r[2]; /* RAM 0xFFFFB680 */
    s->r[3] = t22;
    /* 0x0267EC: op 0x633C */
    s->r[3] = s->r[3] & 0xFFu;
    /* 0x0267EE: op 0x3313 */
    s->T = ((int32_t)s->r[3] >= (int32_t)s->r[1]) ? 1u : 0u;
    /* 0x0267F0: bf.s 0x026814 */
    /* 0x0267F2: op 0x0009 */
    
    if (!s->T) goto L_26814;
    /* 0x0267F4: op 0x608C */
    s->r[0] = s->r[8] & 0xFFu;
    /* 0x0267F6: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x0267F8: bf.s 0x026814 */
    /* 0x0267FA: op 0x0009 */
    
    if (!s->T) goto L_26814;
    /* 0x0267FC: op 0x933C */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0x0000B666u;
    /* 0x0267FE: mov.b @r3,r0 */
    uint32_t t24 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)s->r[3]; /* RAM 0xFFFFB666 */
    s->r[0] = t24;
    /* 0x026800: op 0x2008 */
    s->T = ((s->r[0] & s->r[0]) == 0u) ? 1u : 0u;
    /* 0x026802: bf.s 0x026814 */
    /* 0x026804: op 0x0009 */
    
    if (!s->T) goto L_26814;
    /* 0x026806: op 0x60CC */
    s->r[0] = s->r[12] & 0xFFu;
    /* 0x026808: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x02680A: bf.s 0x026814 */
    /* 0x02680C: op 0x0009 */
    
    if (!s->T) goto L_26814;
    /* 0x02680E: op 0x9334 */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0x0000B668u;
    /* 0x026810: bra 0x026818 */
    /* 0x026812: mov.b r13,@r3 */
    *(volatile uint8_t*)s->r[3] = s->r[13]; /* RAM 0xFFFFB668 */
    goto L_26818;
    L_26818: ;
    /* 0x026818: op 0x9830 */
    s->r[8] = (uint32_t)(int32_t)(int16_t)0x0000B669u;
    /* 0x02681A: mov.b @r8,r3 */
    uint32_t t26 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFB669; /* RAM 0xFFFFB669 */
    s->r[3] = t26;
    /* 0x02681C: op 0x922F */
    s->r[2] = (uint32_t)(int32_t)(int16_t)0x0000B689u;
    /* 0x02681E: mov.b r3,@r2 */
    *(volatile uint8_t*)s->r[2] = s->r[3]; /* RAM 0xFFFFB689 */
    /* 0x026820: mov.b @r11,r1 */
    uint32_t t28 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFB667; /* RAM 0xFFFFB667 */
    s->r[1] = t28;
    /* 0x026822: op 0x2118 */
    s->T = ((s->r[1] & s->r[1]) == 0u) ? 1u : 0u;
    /* 0x026824: bf.s 0x026836 */
    /* 0x026826: op 0x0009 */
    
    if (!s->T) goto L_26836;
    /* 0x026828: op 0x9327 */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0x0000B668u;
    /* 0x02682A: mov.b @r3,r0 */
    uint32_t t30 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)s->r[3]; /* RAM 0xFFFFB668 */
    s->r[0] = t30;
    /* 0x02682C: op 0x2008 */
    s->T = ((s->r[0] & s->r[0]) == 0u) ? 1u : 0u;
    /* 0x02682E: bf.s 0x026836 */
    /* 0x026830: op 0x0009 */
    
    if (!s->T) goto L_26836;
    /* 0x026832: bra 0x026838 */
    /* 0x026834: mov.b r13,@r8 */
    *(volatile uint8_t*)0xFFFFB669 = s->r[13]; /* RAM 0xFFFFB669 */
    goto L_26838;
    L_26838: ;
    /* 0x026838: op 0x9C1C */
    s->r[12] = (uint32_t)(int32_t)(int16_t)0x0000B648u;
    /* 0x02683A: op 0x60A3 */
    s->r[0] = s->r[10];
    /* 0x02683C: mov.b @r8,r4 */
    uint32_t t32 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFB669; /* RAM 0xFFFFB669 */
    s->r[4] = t32;
    /* 0x02683E: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x026840: bf.s 0x026858 */
    /* 0x026842: op 0x644C */
    s->r[4] = s->r[4] & 0xFFu;
    if (!s->T) goto L_26858;
    /* 0x026844: op 0x9215 */
    s->r[2] = (uint32_t)(int32_t)(int16_t)0x0000B680u;
    /* 0x026846: op 0xE104 */
    s->r[1] = (uint32_t)(int32_t)(int8_t)0x04;
    /* 0x026848: mov.b @r2,r3 */
    uint32_t t34 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)s->r[2]; /* RAM 0xFFFFB680 */
    s->r[3] = t34;
    /* 0x02684A: op 0x633C */
    s->r[3] = s->r[3] & 0xFFu;
    /* 0x02684C: op 0x3313 */
    s->T = ((int32_t)s->r[3] >= (int32_t)s->r[1]) ? 1u : 0u;
    /* 0x02684E: bt.s 0x026858 */
    /* 0x026850: op 0x0009 */
    
    if (s->T) goto L_26858;
    /* 0x026852: op 0xD30D */
    s->r[3] = 0x00074AF8u;
    /* 0x026854: bra 0x02686E */
    /* 0x026856: fmov.s @r3,fr3 */
    fr3 = *(volatile uint32_t*)0x00074AF8; /* ROM */
    goto L_2686E;
    L_2686E: ;
    /* 0x02686E: bra 0x0268DA */
    /* 0x026870: fmov.s fr3,@r12 */
    *(volatile uint32_t*)0xFFFFB648 = fr3; /* RAM 0xFFFFB648 */
    goto L_268DA;
    L_268DA: ;
    /* 0x0268DA: op 0x9C51 */
    s->r[12] = (uint32_t)(int32_t)(int16_t)0x0000B654u;
    /* 0x0268DC: op 0x9351 */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0x0000B610u;
    /* 0x0268DE: op 0x924E */
    s->r[2] = (uint32_t)(int32_t)(int16_t)0x0000B668u;
    /* 0x0268E0: mov.b @r2,r0 */
    uint32_t t36 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)s->r[2]; /* RAM 0xFFFFB668 */
    s->r[0] = t36;
    /* 0x0268E2: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x0268E4: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x0268E6: bf.s 0x026908 */
    /* 0x0268E8: fmov.s @r3,fr4 */
    fr4 = *(volatile uint32_t*)0xFFFFB610; /* RAM 0xFFFFB610 */
    if (!s->T) goto L_26908;
    /* 0x0268EA: op 0xD42E */
    s->r[4] = 0x00068B48u;
    /* 0x0268EC: jsr @r9 */
    /* 0x0268EE: op 0x0009 */
    s->pr = 0x000268F0;
    
    f_2068(s);
    /* 0x0268F0: fmov.s @r12,fr3 */
    fr3 = *(volatile uint32_t*)0xFFFFB654; /* RAM 0xFFFFB654 */
    /* 0x0268F2: fmov fr0,fr14 */
    fr14 = fr0;
    /* 0x0268F4: op 0xD32C */
    s->r[3] = 0x00074B08u;
    /* 0x0268F6: fmov.s @r3,fr4 */
    fr4 = *(volatile uint32_t*)0x00074B08; /* ROM */
    /* 0x0268F8: op 0xD226 */
    s->r[2] = 0x000023F4u;
    /* 0x0268FA: fadd fr3,fr4 */
    { union { uint32_t u; float f; } _a, _b, _r; _a.u = fr4; _b.u = fr3; _r.f = _a.f + _b.f; fr4 = _r.u; }
    /* 0x0268FC: jsr @r2 */
    /* 0x0268FE: fmov fr15,fr5 */
    s->pr = 0x00026900;
    fr5 = fr15;
    f_23F4(s);
    /* 0x026900: fmov fr0,fr4 */
    fr4 = fr0;
    /* 0x026902: fadd fr14,fr4 */
    { union { uint32_t u; float f; } _a, _b, _r; _a.u = fr4; _b.u = fr14; _r.f = _a.f + _b.f; fr4 = _r.u; }
    /* 0x026904: bra 0x02695C */
    /* 0x026906: fmov.s fr4,@r12 */
    *(volatile uint32_t*)0xFFFFB654 = fr4; /* RAM 0xFFFFB654 */
    goto L_2695C;
    L_2695C: ;
    /* 0x02695C: op 0x9B14 */
    s->r[11] = (uint32_t)(int32_t)(int16_t)0x0000B5E8u;
    /* 0x02695E: op 0xC716 */
    s->r[0] = 0x000269B8u;
    /* 0x026960: fmov.s @r12,fr5 */
    fr5 = *(volatile uint32_t*)0xFFFFB654; /* RAM 0xFFFFB654 */
    /* 0x026962: fmov.s @r0,fr6 */
    fr6 = *(volatile uint32_t*)0x000269B8; /* ROM */
    /* 0x026964: op 0xD315 */
    s->r[3] = 0x00002440u;
    /* 0x026966: jsr @r3 */
    /* 0x026968: fmov.s @r11,fr4 */
    s->pr = 0x0002696A;
    fr4 = *(volatile uint32_t*)0xFFFFB5E8; /* RAM 0xFFFFB5E8 */
    f_2440(s);
    /* 0x02696A: op 0x6603 */
    s->r[6] = s->r[0];
    /* 0x02696C: op 0xD514 */
    s->r[5] = 0xFFFFB66Bu;
    /* 0x02696E: mov.b @r15,r4 */
    s->r[4] = (uint32_t)(int32_t)(int8_t)(local_400 & 0xFFu);
    /* 0x026970: op 0x644C */
    s->r[4] = s->r[4] & 0xFFu;
    /* 0x026972: op 0x6043 */
    s->r[0] = s->r[4];
    /* 0x026974: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x026976: bf.s 0x0269C4 */
    /* 0x026978: op 0x0009 */
    
    if (!s->T) goto L_269C4;
    /* 0x02697A: bra 0x0269CE */
    /* 0x02697C: mov.b r13,@r5 */
    *(volatile uint8_t*)0xFFFFB66B = s->r[13]; /* RAM 0xFFFFB66B */
    goto L_269CE;
    L_269CE: ;
    /* 0x0269CE: op 0x9D50 */
    s->r[13] = (uint32_t)(int32_t)(int16_t)0x0000B66Cu;
    /* 0x0269D0: op 0xD329 */
    s->r[3] = 0x000749EDu;
    /* 0x0269D2: mov.b @r3,r2 */
    uint32_t t38 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)s->r[3]; /* ROM */
    s->r[2] = t38;
    /* 0x0269D4: op 0x2228 */
    s->T = ((s->r[2] & s->r[2]) == 0u) ? 1u : 0u;
    /* 0x0269D6: bf.s 0x026A36 */
    /* 0x0269D8: fmov.s @r12,fr15 */
    fr15 = *(volatile uint32_t*)0xFFFFB654; /* RAM 0xFFFFB654 */
    if (!s->T) goto L_26A36;
    /* 0x0269DA: op 0x6043 */
    s->r[0] = s->r[4];
    /* 0x0269DC: fmov.s @r11,fr14 */
    fr14 = *(volatile uint32_t*)0xFFFFB5E8; /* RAM 0xFFFFB5E8 */
    /* 0x0269DE: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x0269E0: op 0xD226 */
    s->r[2] = 0x00074B10u;
    /* 0x0269E2: bf.s 0x026A06 */
    /* 0x0269E4: fmov.s @r2,fr13 */
    fr13 = *(volatile uint32_t*)0x00074B10; /* ROM */
    if (!s->T) goto L_26A06;
    /* 0x0269E6: op 0xD026 */
    s->r[0] = 0x00074B14u;
    /* 0x0269E8: fmov.s @r0,fr5 */
    fr5 = *(volatile uint32_t*)0x00074B14; /* ROM */
    /* 0x0269EA: fcmp/gt fr14,fr5 */
    { union { uint32_t u; float f; } _a, _b; _a.u = fr5; _b.u = fr14; s->T = (_a.f > _b.f) ? 1u : 0u; }
    /* 0x0269EC: bt.s 0x0269FC */
    /* 0x0269EE: op 0x0009 */
    
    if (s->T) goto L_269FC;
    /* 0x0269F0: op 0xD124 */
    s->r[1] = 0x000023E4u;
    /* 0x0269F2: fmov fr14,fr4 */
    fr4 = fr14;
    /* 0x0269F4: jsr @r1 */
    /* 0x0269F6: fsub fr13,fr4 */
    s->pr = 0x000269F8;
    { union { uint32_t u; float f; } _a, _b, _r; _a.u = fr4; _b.u = fr13; _r.f = _a.f - _b.f; fr4 = _r.u; }
    f_23E4(s);
    /* 0x0269F8: bra 0x026A02 */
    /* 0x0269FA: op 0x0009 */
    
    goto L_26A02;
    L_26A02: ;
    /* 0x026A02: bra 0x026A38 */
    /* 0x026A04: fmov.s fr0,@r13 */
    *(volatile uint32_t*)0xFFFFB66C = fr0; /* RAM 0xFFFFB66C */
    goto L_26A38;
    L_26A38: ;
    /* 0x026A38: op 0xD314 */
    s->r[3] = 0x0005B394u;
    /* 0x026A3A: jsr @r3 */
    /* 0x026A3C: fmov.s @r13,fr4 */
    s->pr = 0x00026A3E;
    fr4 = *(volatile uint32_t*)0xFFFFB66C; /* RAM 0xFFFFB66C */
    f_5B394(s);
    /* 0x026A3E: op 0x60A3 */
    s->r[0] = s->r[10];
    /* 0x026A40: op 0x9D18 */
    s->r[13] = (uint32_t)(int32_t)(int16_t)0x0000B680u;
    /* 0x026A42: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x026A44: bf.s 0x026A54 */
    /* 0x026A46: fmov.s fr0,@r11 */
    *(volatile uint32_t*)0xFFFFB5E8 = fr0; /* RAM 0xFFFFB5E8 */
    if (!s->T) goto L_26A54;
    /* 0x026A48: op 0xD311 */
    s->r[3] = 0x00002478u;
    /* 0x026A4A: op 0xE501 */
    s->r[5] = (uint32_t)(int32_t)(int8_t)0x01;
    /* 0x026A4C: jsr @r3 */
    /* 0x026A4E: mov.b @r13,r4 */
    s->pr = 0x00026A50;
    uint32_t t40 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)s->r[13]; /* RAM 0xFFFFB680 */
    s->r[4] = t40;
    f_2478(s);
    /* 0x026A50: bra 0x026A56 */
    /* 0x026A52: mov.b r0,@r13 */
    *(volatile uint8_t*)s->r[13] = s->r[0]; /* RAM 0xFFFFB680 */
    goto L_26A56;
    L_26A56: ;
    /* 0x026A56: op 0x7F08 */
    s->r[15] = s->r[15] + (uint32_t)(int32_t)(int8_t)0x08;
    /* 0x026A58: lds.l @r15+,pr */
    s->pr = local_408;
    /* 0x026A5A: fmov.s @r15+,fr12 (rt-base) */
    fr12 = *(volatile uint32_t*)s->r[15];
    s->r[15] = s->r[15] + 4;
    /* 0x026A5C: fmov.s @r15+,fr13 (rt-base) */
    fr13 = *(volatile uint32_t*)s->r[15];
    s->r[15] = s->r[15] + 4;
    /* 0x026A5E: fmov.s @r15+,fr14 (rt-base) */
    fr14 = *(volatile uint32_t*)s->r[15];
    s->r[15] = s->r[15] + 4;
    /* 0x026A60: fmov.s @r15+,fr15 (rt-base) */
    fr15 = *(volatile uint32_t*)s->r[15];
    s->r[15] = s->r[15] + 4;
    /* 0x026A62: mov.l @r15+,r8 */
    s->r[8] = local_40c;
    /* 0x026A64: mov.l @r15+,r9 */
    s->r[9] = local_410;
    /* 0x026A66: mov.l @r15+,r10 */
    s->r[10] = local_414;
    /* 0x026A68: mov.l @r15+,r11 */
    s->r[11] = local_418;
    /* 0x026A6A: mov.l @r15+,r12 */
    s->r[12] = local_41c;
    /* 0x026A6C: mov.l @r15+,r13 */
    s->r[13] = local_420;
    /* 0x026A6E: rts */
    /* 0x026A70: mov.l @r15+,r14 */
    s->r[14] = local_424;
    return;
    L_26A54: ;
    /* 0x026A54: mov.b r14,@r13 */
    *(volatile uint8_t*)s->r[13] = s->r[14]; /* RAM 0xFFFFB680 */
    L_269FC: ;
    /* 0x0269FC: op 0xD122 */
    s->r[1] = 0x000023F4u;
    /* 0x0269FE: jsr @r1 */
    /* 0x026A00: fmov fr15,fr4 */
    s->pr = 0x00026A02;
    fr4 = fr15;
    f_23F4(s);
    L_26A06: ;
    /* 0x026A06: mov.b @r5,r0 */
    uint32_t t42 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)s->r[5]; /* RAM 0xFFFFB66B */
    s->r[0] = t42;
    /* 0x026A08: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x026A0A: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x026A0C: bf.s 0x026A32 */
    /* 0x026A0E: op 0x0009 */
    
    if (!s->T) goto L_26A32;
    /* 0x026A10: fcmp/gt fr14,fr15 */
    { union { uint32_t u; float f; } _a, _b; _a.u = fr15; _b.u = fr14; s->T = (_a.f > _b.f) ? 1u : 0u; }
    /* 0x026A12: bf.s 0x026A24 */
    /* 0x026A14: op 0x0009 */
    
    if (!s->T) goto L_26A24;
    /* 0x026A16: fmov fr15,fr5 */
    fr5 = fr15;
    /* 0x026A18: op 0xD11B */
    s->r[1] = 0x000023F4u;
    /* 0x026A1A: fmov fr14,fr4 */
    fr4 = fr14;
    /* 0x026A1C: jsr @r1 */
    /* 0x026A1E: fadd fr13,fr4 */
    s->pr = 0x00026A20;
    { union { uint32_t u; float f; } _a, _b, _r; _a.u = fr4; _b.u = fr13; _r.f = _a.f + _b.f; fr4 = _r.u; }
    f_23F4(s);
    /* 0x026A20: bra 0x026A2E */
    /* 0x026A22: op 0x0009 */
    
    goto L_26A2E;
    L_26A2E: ;
    /* 0x026A2E: bra 0x026A38 */
    /* 0x026A30: fmov.s fr0,@r13 */
    *(volatile uint32_t*)0xFFFFB66C = fr0; /* RAM 0xFFFFB66C */
    goto L_26A38;
    L_26A24: ;
    /* 0x026A24: op 0xD117 */
    s->r[1] = 0x000023E4u;
    /* 0x026A26: fmov fr15,fr5 */
    fr5 = fr15;
    /* 0x026A28: fmov fr14,fr4 */
    fr4 = fr14;
    /* 0x026A2A: jsr @r1 */
    /* 0x026A2C: fsub fr13,fr4 */
    s->pr = 0x00026A2E;
    { union { uint32_t u; float f; } _a, _b, _r; _a.u = fr4; _b.u = fr13; _r.f = _a.f - _b.f; fr4 = _r.u; }
    f_23E4(s);
    L_26A32: ;
    /* 0x026A32: bra 0x026A38 */
    /* 0x026A34: fmov.s fr15,@r13 */
    *(volatile uint32_t*)0xFFFFB66C = fr15; /* RAM 0xFFFFB66C */
    goto L_26A38;
    L_26A36: ;
    /* 0x026A36: fmov.s fr15,@r13 */
    *(volatile uint32_t*)0xFFFFB66C = fr15; /* RAM 0xFFFFB66C */
    L_269C4: ;
    /* 0x0269C4: op 0x666C */
    s->r[6] = s->r[6] & 0xFFu;
    /* 0x0269C6: op 0x2668 */
    s->T = ((s->r[6] & s->r[6]) == 0u) ? 1u : 0u;
    /* 0x0269C8: bf.s 0x0269CE */
    /* 0x0269CA: op 0x0009 */
    
    if (!s->T) goto L_269CE;
    /* 0x0269CC: mov.b r14,@r5 */
    *(volatile uint8_t*)s->r[5] = s->r[14]; /* RAM 0xFFFFB66B */
    L_26908: ;
    /* 0x026908: mov.b @r8,r0 */
    uint32_t t44 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)s->r[8]; /* RAM 0xFFFFB669 */
    s->r[0] = t44;
    /* 0x02690A: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x02690C: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x02690E: bf.s 0x026936 */
    /* 0x026910: op 0x0009 */
    
    if (!s->T) goto L_26936;
    /* 0x026912: op 0x9137 */
    s->r[1] = (uint32_t)(int32_t)(int16_t)0x0000B66Au;
    /* 0x026914: mov.b @r1,r0 */
    uint32_t t46 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)s->r[1]; /* RAM 0xFFFFB66A */
    s->r[0] = t46;
    /* 0x026916: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x026918: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x02691A: bf.s 0x026932 */
    /* 0x02691C: op 0x0009 */
    
    if (!s->T) goto L_26932;
    /* 0x02691E: op 0x9332 */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0x0000B688u;
    /* 0x026920: mov.b @r3,r0 */
    uint32_t t48 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)s->r[3]; /* RAM 0xFFFFB688 */
    s->r[0] = t48;
    /* 0x026922: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x026924: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x026926: bf.s 0x026932 */
    /* 0x026928: op 0x0009 */
    
    if (!s->T) goto L_26932;
    /* 0x02692A: op 0xD320 */
    s->r[3] = 0x00074A54u;
    /* 0x02692C: fmov.s @r3,fr3 */
    fr3 = *(volatile uint32_t*)0x00074A54; /* ROM */
    /* 0x02692E: bra 0x02695C */
    /* 0x026930: fmov.s fr3,@r12 */
    *(volatile uint32_t*)0xFFFFB654 = fr3; /* RAM 0xFFFFB654 */
    goto L_2695C;
    L_26932: ;
    /* 0x026932: bra 0x02695C */
    /* 0x026934: fmov.s fr15,@r12 */
    *(volatile uint32_t*)0xFFFFB654 = fr15; /* RAM 0xFFFFB654 */
    goto L_2695C;
    L_26936: ;
    /* 0x026936: mov.b @r11,r0 */
    uint32_t t50 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)s->r[11]; /* RAM 0xFFFFB667 */
    s->r[0] = t50;
    /* 0x026938: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x02693A: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x02693C: bf.s 0x02695C */
    /* 0x02693E: op 0x0009 */
    
    if (!s->T) goto L_2695C;
    /* 0x026940: op 0xD41B */
    s->r[4] = 0x00068B5Cu;
    /* 0x026942: jsr @r9 */
    /* 0x026944: op 0x0009 */
    s->pr = 0x00026946;
    
    f_2068(s);
    /* 0x026946: fmov fr0,fr14 */
    fr14 = fr0;
    /* 0x026948: op 0xD31A */
    s->r[3] = 0x00074B0Cu;
    /* 0x02694A: fmov.s @r3,fr3 */
    fr3 = *(volatile uint32_t*)0x00074B0C; /* ROM */
    /* 0x02694C: fmov.s @r12,fr4 */
    fr4 = *(volatile uint32_t*)0xFFFFB654; /* RAM 0xFFFFB654 */
    /* 0x02694E: fsub fr3,fr4 */
    { union { uint32_t u; float f; } _a, _b, _r; _a.u = fr4; _b.u = fr3; _r.f = _a.f - _b.f; fr4 = _r.u; }
    /* 0x026950: op 0xD213 */
    s->r[2] = 0x000023E4u;
    /* 0x026952: jsr @r2 */
    /* 0x026954: fmov fr15,fr5 */
    s->pr = 0x00026956;
    fr5 = fr15;
    f_23E4(s);
    /* 0x026956: fmov fr0,fr4 */
    fr4 = fr0;
    /* 0x026958: fsub fr14,fr4 */
    { union { uint32_t u; float f; } _a, _b, _r; _a.u = fr4; _b.u = fr14; _r.f = _a.f - _b.f; fr4 = _r.u; }
    /* 0x02695A: fmov.s fr4,@r12 */
    *(volatile uint32_t*)0xFFFFB654 = fr4; /* RAM 0xFFFFB654 */
    L_26858: ;
    /* 0x026858: op 0x6043 */
    s->r[0] = s->r[4];
    /* 0x02685A: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x02685C: bf.s 0x026890 */
    /* 0x02685E: op 0x0009 */
    
    if (!s->T) goto L_26890;
    /* 0x026860: op 0x930D */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0x0000B689u;
    /* 0x026862: mov.b @r3,r2 */
    uint32_t t52 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)s->r[3]; /* RAM 0xFFFFB689 */
    s->r[2] = t52;
    /* 0x026864: op 0x2228 */
    s->T = ((s->r[2] & s->r[2]) == 0u) ? 1u : 0u;
    /* 0x026866: bf.s 0x026890 */
    /* 0x026868: op 0x0009 */
    
    if (!s->T) goto L_26890;
    /* 0x02686A: op 0xD108 */
    s->r[1] = 0x00074AFCu;
    /* 0x02686C: fmov.s @r1,fr3 */
    fr3 = *(volatile uint32_t*)0x00074AFC; /* ROM */
    L_26890: ;
    /* 0x026890: op 0x6043 */
    s->r[0] = s->r[4];
    /* 0x026892: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x026894: bf.s 0x0268A2 */
    /* 0x026896: fmov.s @r12,fr4 */
    fr4 = *(volatile uint32_t*)0xFFFFB648; /* RAM 0xFFFFB648 */
    if (!s->T) goto L_268A2;
    /* 0x026898: op 0xD33C */
    s->r[3] = 0x00074AE4u;
    /* 0x02689A: fmov.s @r3,fr3 */
    fr3 = *(volatile uint32_t*)0x00074AE4; /* ROM */
    /* 0x02689C: fcmp/gt fr14,fr3 */
    { union { uint32_t u; float f; } _a, _b; _a.u = fr3; _b.u = fr14; s->T = (_a.f > _b.f) ? 1u : 0u; }
    /* 0x02689E: bf.s 0x0268AE */
    /* 0x0268A0: op 0x0009 */
    
    if (!s->T) goto L_268AE;
    L_268A2: ;
    /* 0x0268A2: op 0x926C */
    s->r[2] = (uint32_t)(int32_t)(int16_t)0x0000B668u;
    /* 0x0268A4: mov.b @r2,r0 */
    uint32_t t54 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)s->r[2]; /* RAM 0xFFFFB668 */
    s->r[0] = t54;
    /* 0x0268A6: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x0268A8: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x0268AA: bf.s 0x0268C0 */
    /* 0x0268AC: op 0x0009 */
    
    if (!s->T) goto L_268C0;
    L_268AE: ;
    /* 0x0268AE: fmov fr4,fr3 */
    fr3 = fr4;
    /* 0x0268B0: op 0xD337 */
    s->r[3] = 0x00074B00u;
    /* 0x0268B2: fmov.s @r3,fr4 */
    fr4 = *(volatile uint32_t*)0x00074B00; /* ROM */
    /* 0x0268B4: op 0xD237 */
    s->r[2] = 0x000023F4u;
    /* 0x0268B6: fadd fr3,fr4 */
    { union { uint32_t u; float f; } _a, _b, _r; _a.u = fr4; _b.u = fr3; _r.f = _a.f + _b.f; fr4 = _r.u; }
    /* 0x0268B8: jsr @r2 */
    /* 0x0268BA: fldi0 fr5 */
    s->pr = 0x000268BC;
    fr5 = 0u;
    f_23F4(s);
    /* 0x0268BC: bra 0x0268DA */
    /* 0x0268BE: fmov.s fr0,@r12 */
    *(volatile uint32_t*)0xFFFFB648 = fr0; /* RAM 0xFFFFB648 */
    goto L_268DA;
    L_268C0: ;
    /* 0x0268C0: mov.b @r11,r0 */
    uint32_t t56 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)s->r[11]; /* RAM 0xFFFFB667 */
    s->r[0] = t56;
    /* 0x0268C2: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x0268C4: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x0268C6: bf.s 0x0268DA */
    /* 0x0268C8: op 0x0009 */
    
    if (!s->T) goto L_268DA;
    /* 0x0268CA: op 0xD333 */
    s->r[3] = 0x00074B04u;
    /* 0x0268CC: op 0xC733 */
    s->r[0] = 0x0002699Cu;
    /* 0x0268CE: fmov.s @r3,fr3 */
    fr3 = *(volatile uint32_t*)0x00074B04; /* ROM */
    /* 0x0268D0: op 0xD233 */
    s->r[2] = 0x000023E4u;
    /* 0x0268D2: fsub fr3,fr4 */
    { union { uint32_t u; float f; } _a, _b, _r; _a.u = fr4; _b.u = fr3; _r.f = _a.f - _b.f; fr4 = _r.u; }
    /* 0x0268D4: jsr @r2 */
    /* 0x0268D6: fmov.s @r0,fr5 */
    s->pr = 0x000268D8;
    fr5 = *(volatile uint32_t*)0x0002699C; /* ROM */
    f_23E4(s);
    /* 0x0268D8: fmov.s fr0,@r12 */
    *(volatile uint32_t*)0xFFFFB648 = fr0; /* RAM 0xFFFFB648 */
    L_26836: ;
    /* 0x026836: mov.b r14,@r8 */
    *(volatile uint8_t*)s->r[8] = s->r[14]; /* RAM 0xFFFFB669 */
    L_26814: ;
    /* 0x026814: op 0x9131 */
    s->r[1] = (uint32_t)(int32_t)(int16_t)0x0000B668u;
    /* 0x026816: mov.b r14,@r1 */
    *(volatile uint8_t*)s->r[1] = s->r[14]; /* RAM 0xFFFFB668 */
    L_267A4: ;
    /* 0x0267A4: op 0x60A3 */
    s->r[0] = s->r[10];
    /* 0x0267A6: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x0267A8: bf.s 0x026814 */
    /* 0x0267AA: op 0x0009 */
    
    if (!s->T) goto L_26814;
    /* 0x0267AC: op 0x9361 */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0x0000B680u;
    /* 0x0267AE: op 0xE104 */
    s->r[1] = (uint32_t)(int32_t)(int8_t)0x04;
    /* 0x0267B0: mov.b @r3,r2 */
    uint32_t t58 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)s->r[3]; /* RAM 0xFFFFB680 */
    s->r[2] = t58;
    /* 0x0267B2: op 0x622C */
    s->r[2] = s->r[2] & 0xFFu;
    /* 0x0267B4: op 0x3213 */
    s->T = ((int32_t)s->r[2] >= (int32_t)s->r[1]) ? 1u : 0u;
    /* 0x0267B6: bf.s 0x0267DE */
    /* 0x0267B8: op 0x0009 */
    
    if (!s->T) goto L_267DE;
    /* 0x0267BA: op 0xD231 */
    s->r[2] = 0x00074AE8u;
    /* 0x0267BC: op 0x935A */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0x0000B648u;
    /* 0x0267BE: fmov.s @r2,fr3 */
    fr3 = *(volatile uint32_t*)0x00074AE8; /* ROM */
    /* 0x0267C0: fmov.s @r3,fr2 */
    fr2 = *(volatile uint32_t*)0xFFFFB648; /* RAM 0xFFFFB648 */
    /* 0x0267C2: fcmp/gt fr2,fr3 */
    { union { uint32_t u; float f; } _a, _b; _a.u = fr3; _b.u = fr2; s->T = (_a.f > _b.f) ? 1u : 0u; }
    /* 0x0267C4: bt.s 0x0267DE */
    /* 0x0267C6: op 0x0009 */
    
    if (s->T) goto L_267DE;
    /* 0x0267C8: op 0xD02E */
    s->r[0] = 0x00074AF0u;
    /* 0x0267CA: fmov.s @r0,fr1 */
    fr1 = *(volatile uint32_t*)0x00074AF0; /* ROM */
    /* 0x0267CC: op 0x9353 */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0x0000B5F0u;
    /* 0x0267CE: fmov.s @r3,fr0 */
    fr0 = *(volatile uint32_t*)0xFFFFB5F0; /* RAM 0xFFFFB5F0 */
    /* 0x0267D0: fcmp/gt fr0,fr1 */
    { union { uint32_t u; float f; } _a, _b; _a.u = fr1; _b.u = fr0; s->T = (_a.f > _b.f) ? 1u : 0u; }
    /* 0x0267D2: bf.s 0x0267DE */
    /* 0x0267D4: op 0x0009 */
    
    if (!s->T) goto L_267DE;
    /* 0x0267D6: fcmp/gt fr13,fr4 */
    { union { uint32_t u; float f; } _a, _b; _a.u = fr4; _b.u = fr13; s->T = (_a.f > _b.f) ? 1u : 0u; }
    /* 0x0267D8: bt.s 0x0267DE */
    /* 0x0267DA: op 0x0009 */
    
    if (s->T) goto L_267DE;
    /* 0x0267DC: mov.b r13,@r11 */
    *(volatile uint8_t*)s->r[11] = s->r[13]; /* RAM 0xFFFFB667 */
    L_266DC: ;
    /* 0x0266DC: op 0x924D */
    s->r[2] = (uint32_t)(int32_t)(int16_t)0x00000124u;
    /* 0x0266DE: mov.w r2,@r4 */
    *(volatile uint16_t*)s->r[4] = s->r[2]; /* RAM 0xFFFFB660 */
    L_26690: ;
    /* 0x026690: mov.b r14,@r5 */
    *(volatile uint8_t*)s->r[5] = s->r[14];
    return; /* fallthrough */
}
