/* ROM: 60E0FC00 | Address: 0x276EC | Size: 20 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST callee (CFG).
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_2068(ST *s);
void f_276EC(ST *s)
{
    uint32_t local_3fc = 0;
    uint32_t fr0 = 0;
    uint32_t fr4 = 0;
    /* 0x0276EC: sts.l pr,@-r15 */
    local_3fc = s->pr;
    /* 0x0276EE: op 0x9243 */
    s->r[2] = (uint32_t)(int32_t)(int16_t)0x0000B594u;
    /* 0x0276F0: op 0xD426 */
    s->r[4] = 0x00068BD8u;
    /* 0x0276F2: op 0xD327 */
    s->r[3] = 0x00002068u;
    /* 0x0276F4: jsr @r3 */
    s->pr = 0x000276F8;
    fr4 = *(volatile uint32_t*)0xFFFFB594; /* RAM 0xFFFFB594 */
    f_2068(s);
    /* 0x0276F8: op 0x923F */
    s->r[2] = (uint32_t)(int32_t)(int16_t)0x0000B6D8u;
    /* 0x0276FA: lds.l @r15+,pr */
    s->pr = local_3fc;
    /* 0x0276FC: rts */
    /* 0x0276FE: fmov.s fr0,@r2 */
    *(volatile uint32_t*)0xFFFFB6D8 = fr0; /* RAM 0xFFFFB6D8 */
    return;
    return; /* fallthrough */
}
