/* ROM: 60E0FC00 | Address: 0x284D6 | Size: 376 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST callee (CFG).
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_2500(ST *s);
void f_383F8(ST *s);
void f_38610(ST *s);
void f_3E0DC(ST *s);
void f_3E1F8(ST *s);
void f_3E258(ST *s);
void f_284D6(ST *s)
{
    uint32_t local_3e0 = 0;
    uint32_t local_3e4 = 0;
    uint32_t local_3e8 = 0;
    uint32_t local_3ec = 0;
    uint32_t local_3f0 = 0;
    uint32_t local_3f4 = 0;
    uint32_t local_3f8 = 0;
    uint32_t local_3fc = 0;
    uint32_t local_400 = 0;
    uint32_t local_404 = 0;
    uint32_t local_408 = 0;
    uint32_t local_40c = 0;
    uint32_t local_410 = 0;
    uint32_t fr0 = 0;
    uint32_t fr12 = 0;
    uint32_t fr13 = 0;
    uint32_t fr14 = 0;
    uint32_t fr15 = 0;
    uint32_t fr4 = 0;
    uint32_t fr5 = 0;
    /* 0x0284D6: mov.l r14,@-r15 */
    local_3fc = s->r[14];
    /* 0x0284D8: mov.l r13,@-r15 */
    local_3f8 = s->r[13];
    /* 0x0284DA: mov.l r12,@-r15 */
    local_3f4 = s->r[12];
    /* 0x0284DC: mov.l r11,@-r15 */
    local_3f0 = s->r[11];
    /* 0x0284DE: mov.l r10,@-r15 */
    local_3ec = s->r[10];
    /* 0x0284E0: mov.l r9,@-r15 */
    local_3e8 = s->r[9];
    /* 0x0284E2: mov.l r8,@-r15 */
    local_3e4 = s->r[8];
    /* 0x0284E4: fmov.s fr15,@-r15 (rt-base) */
    s->r[15] -= 4;
    *(volatile uint32_t*)s->r[15] = fr15;
    /* 0x0284E6: fmov.s fr14,@-r15 (rt-base) */
    s->r[15] -= 4;
    *(volatile uint32_t*)s->r[15] = fr14;
    /* 0x0284E8: fmov.s fr13,@-r15 (rt-base) */
    s->r[15] -= 4;
    *(volatile uint32_t*)s->r[15] = fr13;
    /* 0x0284EA: fmov.s fr12,@-r15 (rt-base) */
    s->r[15] -= 4;
    *(volatile uint32_t*)s->r[15] = fr12;
    /* 0x0284EC: op 0xD12F */
    s->r[1] = 0xFFFFBA5Fu;
    /* 0x0284EE: sts.l pr,@-r15 */
    local_3e0 = s->pr;
    /* 0x0284F0: op 0x7FE8 */
    s->r[15] = s->r[15] + (uint32_t)(int32_t)(int8_t)0xE8;
    /* 0x0284F2: mov.b @r1,r2 */
    uint32_t t2 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFBA5F; /* RAM 0xFFFFBA5F */
    s->r[2] = t2;
    /* 0x0284F4: op 0x2228 */
    s->T = ((s->r[2] & s->r[2]) == 0u) ? 1u : 0u;
    /* 0x0284F6: bf.s 0x028506 */
    /* 0x0284F8: op 0x0009 */
    
    if (!s->T) goto L_28506;
    /* 0x0284FA: op 0x9350 */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0x0000C6B0u;
    /* 0x0284FC: mov.b @r3,r0 */
    uint32_t t4 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFC6B0; /* RAM 0xFFFFC6B0 */
    s->r[0] = t4;
    /* 0x0284FE: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x028500: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x028502: bt.s 0x028528 */
    /* 0x028504: op 0x0009 */
    
    if (s->T) goto L_28528;
    L_28506: ;
    /* 0x028506: op 0xD22A */
    s->r[2] = 0xFFFFBA5Eu;
    /* 0x028508: mov.b @r2,r3 */
    uint32_t t6 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFBA5E; /* RAM 0xFFFFBA5E */
    s->r[3] = t6;
    /* 0x02850A: op 0x2338 */
    s->T = ((s->r[3] & s->r[3]) == 0u) ? 1u : 0u;
    /* 0x02850C: bt.s 0x028514 */
    /* 0x02850E: op 0x0009 */
    
    if (s->T) goto L_28514;
    /* 0x028510: bra 0x02862C */
    /* 0x028512: op 0x0009 */
    
    goto L_2862C;
    L_2862C: ;
    /* 0x02862C: op 0xD218 */
    s->r[2] = 0xFFFFBA5Fu;
    /* 0x02862E: op 0xE301 */
    s->r[3] = (uint32_t)(int32_t)(int8_t)0x01;
    /* 0x028630: mov.b r3,@r2 */
    *(volatile uint8_t*)s->r[2] = s->r[3]; /* RAM 0xFFFFBA5F */
    /* 0x028632: op 0x7F18 */
    s->r[15] = s->r[15] + (uint32_t)(int32_t)(int8_t)0x18;
    /* 0x028634: lds.l @r15+,pr */
    s->pr = local_3e0;
    /* 0x028636: fmov.s @r15+,fr12 (rt-base) */
    fr12 = *(volatile uint32_t*)s->r[15];
    s->r[15] = s->r[15] + 4;
    /* 0x028638: fmov.s @r15+,fr13 (rt-base) */
    fr13 = *(volatile uint32_t*)s->r[15];
    s->r[15] = s->r[15] + 4;
    /* 0x02863A: fmov.s @r15+,fr14 (rt-base) */
    fr14 = *(volatile uint32_t*)s->r[15];
    s->r[15] = s->r[15] + 4;
    /* 0x02863C: fmov.s @r15+,fr15 (rt-base) */
    fr15 = *(volatile uint32_t*)s->r[15];
    s->r[15] = s->r[15] + 4;
    /* 0x02863E: mov.l @r15+,r8 */
    s->r[8] = local_3e4;
    /* 0x028640: mov.l @r15+,r9 */
    s->r[9] = local_3e8;
    /* 0x028642: mov.l @r15+,r10 */
    s->r[10] = local_3ec;
    /* 0x028644: mov.l @r15+,r11 */
    s->r[11] = local_3f0;
    /* 0x028646: mov.l @r15+,r12 */
    s->r[12] = local_3f4;
    /* 0x028648: mov.l @r15+,r13 */
    s->r[13] = local_3f8;
    /* 0x02864A: rts */
    /* 0x02864C: mov.l @r15+,r14 */
    s->r[14] = local_3fc;
    return;
    L_28514: ;
    /* 0x028514: op 0x9444 */
    s->r[4] = (uint32_t)(int32_t)(int16_t)0x00008684u;
    /* 0x028516: op 0xD327 */
    s->r[3] = 0x0003E0DCu;
    /* 0x028518: jsr @r3 */
    s->pr = 0x0002851C;
    s->r[5] = (uint32_t)(int32_t)(int8_t)0x00;
    f_3E0DC(s);
    /* 0x02851C: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x02851E: op 0x2008 */
    s->T = ((s->r[0] & s->r[0]) == 0u) ? 1u : 0u;
    /* 0x028520: bt.s 0x028528 */
    /* 0x028522: op 0x0009 */
    
    if (s->T) goto L_28528;
    /* 0x028524: bra 0x02862C */
    /* 0x028526: op 0x0009 */
    
    goto L_2862C;
    L_28528: ;
    /* 0x028528: op 0xD323 */
    s->r[3] = 0x000383F8u;
    /* 0x02852A: op 0xE544 */
    s->r[5] = (uint32_t)(int32_t)(int8_t)0x44;
    /* 0x02852C: jsr @r3 */
    s->pr = 0x00028530;
    s->r[4] = (uint32_t)(int32_t)(int8_t)0x20;
    f_383F8(s);
    /* 0x028530: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x028532: op 0x2008 */
    s->T = ((s->r[0] & s->r[0]) == 0u) ? 1u : 0u;
    /* 0x028534: bf.s 0x02862C */
    /* 0x028536: op 0x0009 */
    
    if (!s->T) goto L_2862C;
    /* 0x028538: op 0xDC20 */
    s->r[12] = 0x0003E1F8u;
    /* 0x02853A: op 0x9432 */
    s->r[4] = (uint32_t)(int32_t)(int16_t)0x00008682u;
    /* 0x02853C: jsr @r12 */
    s->pr = 0x00028540;
    s->r[5] = (uint32_t)(int32_t)(int8_t)0x01;
    f_3E1F8(s);
    /* 0x028540: op 0xD21F */
    s->r[2] = 0xFFFF8130u;
    /* 0x028542: fldi1 fr12 */
    fr12 = 0x3F800000u;
    /* 0x028544: op 0xD822 */
    s->r[8] = 0x0003E258u;
    /* 0x028546: op 0xEB00 */
    s->r[11] = (uint32_t)(int32_t)(int8_t)0x00;
    /* 0x028548: op 0xD11E */
    s->r[1] = 0xFFFF8570u;
    /* 0x02854A: op 0x64F3 */
    s->r[4] = s->r[15];
    /* 0x02854C: op 0x60B3 */
    s->r[0] = s->r[11];
    /* 0x02854E: op 0x6DB3 */
    s->r[13] = s->r[11];
    /* 0x028550: mov.w r0,@(0x10,r15) */
    local_410 = s->r[0];
    /* 0x028552: op 0x6EB3 */
    s->r[14] = s->r[11];
    /* 0x028554: op 0xC71C */
    s->r[0] = 0x000285C8u;
    /* 0x028556: op 0x6AB3 */
    s->r[10] = s->r[11];
    /* 0x028558: op 0x7414 */
    s->r[4] = s->r[4] + (uint32_t)(int32_t)(int8_t)0x14;
    /* 0x02855A: op 0x6343 */
    s->r[3] = s->r[4];
    /* 0x02855C: mov.l r3,@(0xC,r15) */
    local_40c = s->r[3];
    /* 0x02855E: op 0x7401 */
    s->r[4] = s->r[4] + (uint32_t)(int32_t)(int8_t)0x01;
    /* 0x028560: mov.l r4,@r15 */
    local_400 = s->r[4];
    /* 0x028562: mov.l r2,@(0x4,r15) */
    local_404 = s->r[2];
    /* 0x028564: mov.l r1,@(0x8,r15) */
    local_408 = s->r[1];
    /* 0x028566: fmov.s @r0,fr13 */
    fr13 = *(volatile uint32_t*)0x000285C8; /* ROM */
    /* 0x028568: op 0xC718 */
    s->r[0] = 0x000285CCu;
    /* 0x02856A: fmov.s @r0,fr14 */
    fr14 = *(volatile uint32_t*)0x000285CC; /* ROM */
    L_2856C: ;
    /* 0x02856C: op 0xD319 */
    s->r[3] = 0x00038610u;
    /* 0x02856E: op 0x64A3 */
    s->r[4] = s->r[10];
    /* 0x028570: op 0x7420 */
    s->r[4] = s->r[4] + (uint32_t)(int32_t)(int8_t)0x20;
    /* 0x028572: op 0xE602 */
    s->r[6] = (uint32_t)(int32_t)(int8_t)0x02;
    /* 0x028574: jsr @r3 */
    s->pr = 0x00028578;
    s->r[5] = local_40c;
    f_38610(s);
    /* 0x028578: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x02857A: op 0x2008 */
    s->T = ((s->r[0] & s->r[0]) == 0u) ? 1u : 0u;
    /* 0x02857C: bf.s 0x02860C */
    /* 0x02857E: op 0x0009 */
    
    if (!s->T) goto L_2860C;
    /* 0x028580: mov.l @(0xC,r15),r4 */
    s->r[4] = local_40c;
    /* 0x028582: fmov fr13,fr5 */
    fr5 = fr13;
    /* 0x028584: op 0xD314 */
    s->r[3] = 0x00002500u;
    /* 0x028586: fmov fr14,fr4 */
    fr4 = fr14;
    /* 0x028588: jsr @r3 */
    s->pr = 0x0002858C;
    uint32_t t8 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)s->r[4];
    s->r[4] = t8;
    f_2500(s);
    /* 0x02858C: mov.l @r15,r2 */
    s->r[2] = local_400;
    /* 0x02858E: mov.b @r2,r3 (rt-base) */
    uint32_t t9 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)s->r[2];
    s->r[3] = t9;
    /* 0x028590: op 0x9208 */
    s->r[2] = (uint32_t)(int32_t)(int16_t)0xFFu;
    /* 0x028592: op 0x633C */
    s->r[3] = s->r[3] & 0xFFu;
    /* 0x028594: op 0x3320 */
    s->T = (s->r[3] == s->r[2]) ? 1u : 0u;
    /* 0x028596: bf.s 0x0285DC */
    /* 0x028598: fmov fr0,fr15 */
    fr15 = fr0;
    if (!s->T) goto L_285DC;
    /* 0x02859A: bra 0x0285E0 */
    /* 0x02859C: op 0x69B3 */
    s->r[9] = s->r[11];
    goto L_285E0;
    L_285E0: ;
    /* 0x0285E0: mov.l @(0x4,r15),r4 */
    s->r[4] = local_404;
    /* 0x0285E2: fmov fr15,fr4 */
    fr4 = fr15;
    /* 0x0285E4: jsr @r8 */
    s->pr = 0x000285E8;
    s->r[4] = s->r[4] + s->r[14];
    f_3E258(s);
    /* 0x0285E8: mov.l @(0x8,r15),r4 */
    s->r[4] = local_408;
    /* 0x0285EA: op 0x6593 */
    s->r[5] = s->r[9];
    /* 0x0285EC: jsr @r12 */
    s->pr = 0x000285F0;
    s->r[4] = s->r[4] + s->r[13];
    f_3E1F8(s);
    /* 0x0285F0: mov.l @(0x4,r15),r4 */
    s->r[4] = local_404;
    /* 0x0285F2: fmul fr12,fr15 */
    { union { uint32_t u; float f; } _a, _b, _r; _a.u = fr15; _b.u = fr12; _r.f = _a.f * _b.f; fr15 = _r.u; }
    /* 0x0285F4: op 0x9347 */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0x00000220u;
    /* 0x0285F6: op 0x34EC */
    s->r[4] = s->r[4] + s->r[14];
    /* 0x0285F8: fmov fr15,fr4 */
    fr4 = fr15;
    /* 0x0285FA: fneg fr4 */
    fr4 = fr4 ^ 0x80000000u;
    /* 0x0285FC: jsr @r8 */
    s->pr = 0x00028600;
    s->r[4] = s->r[4] + s->r[3];
    f_3E258(s);
    /* 0x028600: mov.l @(0x8,r15),r4 */
    s->r[4] = local_408;
    /* 0x028602: op 0x6593 */
    s->r[5] = s->r[9];
    /* 0x028604: op 0x9340 */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0x88u;
    /* 0x028606: op 0x34DC */
    s->r[4] = s->r[4] + s->r[13];
    /* 0x028608: jsr @r12 */
    s->pr = 0x0002860C;
    s->r[4] = s->r[4] + s->r[3];
    f_3E1F8(s);
    L_2860C: ;
    /* 0x02860C: mov.w @(0x10,r15),r0 */
    s->r[0] = (uint32_t)(int32_t)(int16_t)(local_410 & 0xFFFFu);
    /* 0x02860E: op 0x7D02 */
    s->r[13] = s->r[13] + (uint32_t)(int32_t)(int8_t)0x02;
    /* 0x028610: op 0x7001 */
    s->r[0] = s->r[0] + (uint32_t)(int32_t)(int8_t)0x01;
    /* 0x028612: op 0x7E08 */
    s->r[14] = s->r[14] + (uint32_t)(int32_t)(int8_t)0x08;
    /* 0x028614: mov.w r0,@(0x10,r15) */
    local_410 = s->r[0];
    /* 0x028616: op 0xE322 */
    s->r[3] = (uint32_t)(int32_t)(int8_t)0x22;
    /* 0x028618: op 0x600D */
    s->r[0] = s->r[0] & 0xFFFFu;
    /* 0x02861A: op 0x3033 */
    s->T = ((int32_t)s->r[0] >= (int32_t)s->r[3]) ? 1u : 0u;
    /* 0x02861C: bf.s 0x02856C */
    /* 0x02861E: op 0x7A02 */
    s->r[10] = s->r[10] + (uint32_t)(int32_t)(int8_t)0x02;
    if (!s->T) goto L_2856C;
    /* 0x028620: op 0x9433 */
    s->r[4] = (uint32_t)(int32_t)(int16_t)0x00008682u;
    /* 0x028622: jsr @r12 */
    s->pr = 0x00028626;
    s->r[5] = (uint32_t)(int32_t)(int8_t)0x00;
    f_3E1F8(s);
    /* 0x028626: op 0x9431 */
    s->r[4] = (uint32_t)(int32_t)(int16_t)0x00008684u;
    /* 0x028628: jsr @r12 */
    s->pr = 0x0002862C;
    s->r[5] = (uint32_t)(int32_t)(int8_t)0x01;
    f_3E1F8(s);
    L_285DC: ;
    /* 0x0285DC: mov.l @r15,r9 */
    s->r[9] = local_400;
    /* 0x0285DE: mov.b @r9,r9 (rt-base) */
    uint32_t t10 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)s->r[9];
    s->r[9] = t10;
    return; /* fallthrough */
}
