/* ROM: 60E0FC00 | Address: 0x29474 | Size: 42 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v7.py — ST (shared state) ABI,
 * leaf callee library (c/lib/f_<hex>.c). Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_29474(ST *s)
{
    /* 0x029474: op 0x9162 */
    s->r[1] = (uint32_t)(int32_t)(int16_t)0x0000CFD9u;
    /* 0x029476: mov.b @r1,r0 */
    uint32_t t2 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFCFD9; /* RAM 0xFFFFCFD9 */
    s->r[0] = t2;
    /* 0x029478: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x02947A: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x02947C: bf.s 0x02949C */
    /* 0x02947E: op 0x0009 */
    
    if (!s->T) goto L_2949C;
    /* 0x029480: op 0x935D */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0x0000A41Cu;
    /* 0x029482: mov.b @r3,r0 */
    uint32_t t4 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFA41C; /* RAM 0xFFFFA41C */
    s->r[0] = t4;
    /* 0x029484: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x029486: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x029488: bf.s 0x02949C */
    /* 0x02948A: op 0x0009 */
    
    if (!s->T) goto L_2949C;
    /* 0x02948C: op 0x9354 */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0x0000BAD4u;
    /* 0x02948E: op 0xE101 */
    s->r[1] = (uint32_t)(int32_t)(int8_t)0x01;
    /* 0x029490: op 0x9051 */
    s->r[0] = (uint32_t)(int32_t)(int16_t)0x0000BAD8u;
    /* 0x029492: op 0xE400 */
    s->r[4] = (uint32_t)(int32_t)(int8_t)0x00;
    /* 0x029494: op 0x9251 */
    s->r[2] = (uint32_t)(int32_t)(int16_t)0x0000BAD6u;
    /* 0x029496: mov.w r4,@r3 */
    *(volatile uint16_t*)0xFFFFBAD4 = s->r[4]; /* RAM 0xFFFFBAD4 */
    /* 0x029498: mov.w r4,@r2 */
    *(volatile uint16_t*)0xFFFFBAD6 = s->r[4]; /* RAM 0xFFFFBAD6 */
    /* 0x02949A: mov.b r1,@r0 */
    *(volatile uint8_t*)0xFFFFBAD8 = s->r[1]; /* RAM 0xFFFFBAD8 */
    L_2949C: ;
    /* 0x02949C: rts */
    /* 0x02949E: op 0x0009 */
    
    return;
    return; /* fallthrough */
}
