/* ROM: 60E0FC00 | Address: 0x2A1E4 | Size: 128 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST callee (CFG).
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_2404(ST *s);
void f_2440(ST *s);
void f_24D0(ST *s);
void f_2A1E4(ST *s)
{
    uint32_t local_3f8 = 0;
    uint32_t local_3fc = 0;
    uint32_t fr0 = 0;
    uint32_t fr14 = 0;
    uint32_t fr15 = 0;
    uint32_t fr2 = 0;
    uint32_t fr3 = 0;
    uint32_t fr4 = 0;
    uint32_t fr5 = 0;
    uint32_t fr6 = 0;
    /* 0x02A1E4: mov.l r14,@-r15 */
    local_3fc = s->r[14];
    /* 0x02A1E6: fmov.s fr15,@-r15 (rt-base) */
    s->r[15] -= 4;
    *(volatile uint32_t*)s->r[15] = fr15;
    /* 0x02A1E8: fmov.s fr14,@-r15 (rt-base) */
    s->r[15] -= 4;
    *(volatile uint32_t*)s->r[15] = fr14;
    /* 0x02A1EA: fldi0 fr15 */
    fr15 = 0u;
    /* 0x02A1EC: op 0xC72A */
    s->r[0] = 0x0002A298u;
    /* 0x02A1EE: fmov fr15,fr5 */
    fr5 = fr15;
    /* 0x02A1F0: op 0x9344 */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0x0000BB58u;
    /* 0x02A1F2: sts.l pr,@-r15 */
    local_3f8 = s->pr;
    /* 0x02A1F4: fmov.s @r0,fr6 */
    fr6 = *(volatile uint32_t*)0x0002A298; /* ROM */
    /* 0x02A1F6: op 0xD229 */
    s->r[2] = 0x00002440u;
    /* 0x02A1F8: jsr @r2 */
    s->pr = 0x0002A1FC;
    fr4 = *(volatile uint32_t*)0xFFFFBB58; /* RAM 0xFFFFBB58 */
    f_2440(s);
    /* 0x02A1FC: op 0x9E40 */
    s->r[14] = (uint32_t)(int32_t)(int16_t)0x0000BB53u;
    /* 0x02A1FE: op 0x6403 */
    s->r[4] = s->r[0];
    /* 0x02A200: op 0x933F */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0x0000BB5Cu;
    /* 0x02A202: mov.b @r3,r0 */
    uint32_t t2 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)s->r[3]; /* RAM 0xFFFFBB5C */
    s->r[0] = t2;
    /* 0x02A204: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x02A206: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x02A208: bf.s 0x02A212 */
    /* 0x02A20A: op 0x0009 */
    
    if (!s->T) goto L_2A212;
    /* 0x02A20C: op 0x913A */
    s->r[1] = (uint32_t)(int32_t)(int16_t)0xFFu;
    /* 0x02A20E: bra 0x02A21E */
    /* 0x02A210: op 0x0009 */
    
    goto L_2A21E;
    L_2A21E: ;
    /* 0x02A21E: bra 0x02A25A */
    /* 0x02A220: mov.b r1,@r14 */
    *(volatile uint8_t*)0xFFFFBB53 = s->r[1]; /* RAM 0xFFFFBB53 */
    goto L_2A25A;
    L_2A25A: ;
    /* 0x02A25A: lds.l @r15+,pr */
    s->pr = local_3f8;
    /* 0x02A25C: fmov.s @r15+,fr14 (rt-base) */
    fr14 = *(volatile uint32_t*)s->r[15];
    s->r[15] = s->r[15] + 4;
    /* 0x02A25E: fmov.s @r15+,fr15 (rt-base) */
    fr15 = *(volatile uint32_t*)s->r[15];
    s->r[15] = s->r[15] + 4;
    /* 0x02A260: rts */
    /* 0x02A262: mov.l @r15+,r14 */
    s->r[14] = local_3fc;
    return;
    L_2A212: ;
    /* 0x02A212: op 0x922C */
    s->r[2] = (uint32_t)(int32_t)(int16_t)0x0000A428u;
    /* 0x02A214: mov.b @r2,r0 */
    uint32_t t4 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)s->r[2]; /* RAM 0xFFFFA428 */
    s->r[0] = t4;
    /* 0x02A216: op 0x2008 */
    s->T = ((s->r[0] & s->r[0]) == 0u) ? 1u : 0u;
    /* 0x02A218: bf.s 0x02A222 */
    /* 0x02A21A: op 0x0009 */
    
    if (!s->T) goto L_2A222;
    /* 0x02A21C: op 0xE100 */
    s->r[1] = (uint32_t)(int32_t)(int8_t)0x00;
    L_2A222: ;
    /* 0x02A222: op 0x644C */
    s->r[4] = s->r[4] & 0xFFu;
    /* 0x02A224: op 0x2448 */
    s->T = ((s->r[4] & s->r[4]) == 0u) ? 1u : 0u;
    /* 0x02A226: bt.s 0x02A256 */
    /* 0x02A228: op 0x0009 */
    
    if (s->T) goto L_2A256;
    /* 0x02A22A: op 0xC717 */
    s->r[0] = 0x0002A288u;
    /* 0x02A22C: op 0x9126 */
    s->r[1] = (uint32_t)(int32_t)(int16_t)0x0000BB58u;
    /* 0x02A22E: fmov.s @r0,fr14 */
    fr14 = *(volatile uint32_t*)0x0002A288; /* ROM */
    /* 0x02A230: fmov.s @r1,fr3 */
    fr3 = *(volatile uint32_t*)0xFFFFBB58; /* RAM 0xFFFFBB58 */
    /* 0x02A232: op 0x9328 */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0x0000BCE4u;
    /* 0x02A234: fmov.s @r3,fr2 */
    fr2 = *(volatile uint32_t*)0xFFFFBCE4; /* RAM 0xFFFFBCE4 */
    /* 0x02A236: fdiv fr3,fr2 */
    { union { uint32_t u; float f; } _a, _b, _r; _a.u = fr2; _b.u = fr3; _r.f = _a.f / _b.f; fr2 = _r.u; }
    /* 0x02A238: fmov fr2,fr2 */
    fr2 = fr2;
    /* 0x02A23A: fmov fr2,fr4 */
    fr4 = fr2;
    /* 0x02A23C: op 0xD213 */
    s->r[2] = 0x00002404u;
    /* 0x02A23E: fmul fr14,fr4 */
    { union { uint32_t u; float f; } _a, _b, _r; _a.u = fr4; _b.u = fr14; _r.f = _a.f * _b.f; fr4 = _r.u; }
    /* 0x02A240: fmov fr14,fr6 */
    fr6 = fr14;
    /* 0x02A242: jsr @r2 */
    s->pr = 0x0002A246;
    fr5 = fr15;
    f_2404(s);
    /* 0x02A246: fmov fr0,fr4 */
    fr4 = fr0;
    /* 0x02A248: op 0xC711 */
    s->r[0] = 0x0002A290u;
    /* 0x02A24A: fmov fr15,fr6 */
    fr6 = fr15;
    /* 0x02A24C: op 0xD311 */
    s->r[3] = 0x000024D0u;
    /* 0x02A24E: jsr @r3 */
    s->pr = 0x0002A252;
    fr5 = *(volatile uint32_t*)0x0002A290; /* ROM */
    f_24D0(s);
    /* 0x02A252: bra 0x02A25A */
    /* 0x02A254: mov.b r0,@r14 */
    *(volatile uint8_t*)0xFFFFBB53 = s->r[0]; /* RAM 0xFFFFBB53 */
    goto L_2A25A;
    L_2A256: ;
    /* 0x02A256: op 0x9112 */
    s->r[1] = (uint32_t)(int32_t)(int16_t)0xFEu;
    /* 0x02A258: mov.b r1,@r14 */
    *(volatile uint8_t*)0xFFFFBB53 = s->r[1]; /* RAM 0xFFFFBB53 */
    return; /* fallthrough */
}
