/* ROM: 60E0FC00 | Address: 0x2A3E2 | Size: 42 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST callee (CFG).
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_2A414(ST *s);
void f_2A454(ST *s);
void f_2A3E2(ST *s)
{
    uint32_t local_3f8 = 0;
    uint32_t local_3fc = 0;
    /* 0x02A3E2: mov.l r14,@-r15 */
    local_3fc = s->r[14];
    /* 0x02A3E4: sts.l pr,@-r15 */
    local_3f8 = s->pr;
    /* 0x02A3E6: op 0xDE3F */
    s->r[14] = 0xFFFFBB94u;
    /* 0x02A3E8: mov.w @r14,r3 */
    uint32_t t2 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)0xFFFFBB94; /* RAM 0xFFFFBB94 */
    s->r[3] = t2;
    /* 0x02A3EA: op 0x7301 */
    s->r[3] = s->r[3] + (uint32_t)(int32_t)(int8_t)0x01;
    /* 0x02A3EC: mov.w r3,@r14 */
    *(volatile uint16_t*)0xFFFFBB94 = s->r[3]; /* RAM 0xFFFFBB94 */
    /* 0x02A3EE: op 0xE302 */
    s->r[3] = (uint32_t)(int32_t)(int8_t)0x02;
    /* 0x02A3F0: mov.w @r14,r2 */
    uint32_t t4 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)0xFFFFBB94; /* RAM 0xFFFFBB94 */
    s->r[2] = t4;
    /* 0x02A3F2: op 0x622D */
    s->r[2] = s->r[2] & 0xFFFFu;
    /* 0x02A3F4: op 0x3233 */
    s->T = ((int32_t)s->r[2] >= (int32_t)s->r[3]) ? 1u : 0u;
    /* 0x02A3F6: bf.s 0x02A406 */
    /* 0x02A3F8: op 0x0009 */
    
    if (!s->T) goto L_2A406;
    /* 0x02A3FA: bsr 0x2A454 */
    s->pr = 0x0002A3FE;
    
    f_2A454(s);
    /* 0x02A3FE: bsr 0x2A414 */
    s->pr = 0x0002A402;
    
    f_2A414(s);
    /* 0x02A402: op 0xE100 */
    s->r[1] = (uint32_t)(int32_t)(int8_t)0x00;
    /* 0x02A404: mov.w r1,@r14 */
    *(volatile uint16_t*)0xFFFFBB94 = s->r[1]; /* RAM 0xFFFFBB94 */
    L_2A406: ;
    /* 0x02A406: lds.l @r15+,pr */
    s->pr = local_3f8;
    /* 0x02A408: rts */
    /* 0x02A40A: mov.l @r15+,r14 */
    s->r[14] = local_3fc;
    return;
    return; /* fallthrough */
}
