/* ROM: 60E0FC00 | Address: 0x2B974 | Size: 8 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v7.py — ST (shared state) ABI,
 * leaf callee library (c/lib/f_<hex>.c). Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, vbr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_2B974(ST *s)
{
    /* 0x02B974: op 0xD20F */
    s->r[2] = 0x0006D480u;
    /* 0x02B976: mov.b @r2,r3 */
    uint32_t t2 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0x0006D480; /* ROM */
    s->r[3] = t2;
    /* 0x02B978: op 0x910A */
    s->r[1] = (uint32_t)(int32_t)(int16_t)0x0000BBE4u;
    /* 0x02B97A: rts */
    /* 0x02B97C: mov.b r3,@r1 */
    *(volatile uint8_t*)0xFFFFBBE4 = s->r[3]; /* RAM 0xFFFFBBE4 */
    return;
    return; /* fallthrough */
}
