/* ROM: 60E1D400 | Address: 0x2B1C6 | Size: 30 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST callee (CFG).
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_3920(ST *s);
void f_3934(ST *s);
void f_4C8C2(ST *s);
void f_4C9C0(ST *s);
void f_2B1C6(ST *s)
{
    uint32_t local_3f8 = 0;
    uint32_t local_3fc = 0;
    /* 0x02B1C6: sts.l pr,@-r15 */
    local_3fc = s->pr;
    /* 0x02B1C8: op 0xD329 */
    s->r[3] = 0x00003920u;
    /* 0x02B1CA: op 0x7FFC */
    s->r[15] = s->r[15] + (uint32_t)(int32_t)(int8_t)0xFC;
    /* 0x02B1CC: jsr @r3 */
    s->pr = 0x0002B1D0;
    s->r[4] = (uint32_t)(int32_t)(int8_t)0x10;
    f_3920(s);
    /* 0x02B1D0: op 0xD34E */
    s->r[3] = 0x0004C8C2u;
    /* 0x02B1D2: jsr @r3 */
    s->pr = 0x0002B1D6;
    local_3f8 = s->r[0];
    f_4C8C2(s);
    /* 0x02B1D6: op 0xD24E */
    s->r[2] = 0x0004C9C0u;
    /* 0x02B1D8: jsr @r2 */
    s->pr = 0x0002B1DC;
    
    f_4C9C0(s);
    /* 0x02B1DC: mov.l @r15+,r4 */
    s->r[4] = local_3f8;
    /* 0x02B1DE: op 0xD327 */
    s->r[3] = 0x00003934u;
    /* 0x02B1E0: jmp @r3 (tail) */
    s->pr = local_3fc;
    f_3934(s);
    return;
    return; /* fallthrough */
}
