/* ROM: 60E0FC00 | Address: 0x2CD9C | Size: 44 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST callee (CFG).
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_2CD9C(ST *s)
{
    /* 0x02CD9C: op 0x9320 */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0x0000B580u;
    /* 0x02CD9E: mov.b @r3,r0 */
    uint32_t t2 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFB580; /* RAM 0xFFFFB580 */
    s->r[0] = t2;
    /* 0x02CDA0: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x02CDA2: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x02CDA4: bf.s 0x02CDB8 */
    /* 0x02CDA6: op 0xE500 */
    s->r[5] = (uint32_t)(int32_t)(int8_t)0x00;
    if (!s->T) goto L_2CDB8;
    /* 0x02CDA8: op 0x921B */
    s->r[2] = (uint32_t)(int32_t)(int16_t)0x0000B586u;
    /* 0x02CDAA: mov.b @r2,r0 */
    uint32_t t4 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFB586; /* RAM 0xFFFFB586 */
    s->r[0] = t4;
    /* 0x02CDAC: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x02CDAE: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x02CDB0: bt.s 0x02CDB8 */
    /* 0x02CDB2: op 0x0009 */
    
    if (s->T) goto L_2CDB8;
    /* 0x02CDB4: bra 0x02CDBA */
    /* 0x02CDB6: op 0xE40F */
    s->r[4] = (uint32_t)(int32_t)(int8_t)0x0F;
    goto L_2CDBA;
    L_2CDBA: ;
    /* 0x02CDBA: op 0x644C */
    s->r[4] = s->r[4] & 0xFFu;
    /* 0x02CDBC: op 0xD20C */
    s->r[2] = 0xFFFFBC95u;
    /* 0x02CDBE: op 0x4408 */
    s->r[4] = (s->r[4] << 2);
    /* 0x02CDC0: op 0x4408 */
    s->r[4] = (s->r[4] << 2);
    /* 0x02CDC2: op 0x740F */
    s->r[4] = s->r[4] + (uint32_t)(int32_t)(int8_t)0x0F;
    /* 0x02CDC4: rts */
    /* 0x02CDC6: mov.b r4,@r2 */
    *(volatile uint8_t*)s->r[2] = s->r[4]; /* RAM 0xFFFFBC95 */
    return;
    L_2CDB8: ;
    /* 0x02CDB8: op 0x6453 */
    s->r[4] = s->r[5];
    return; /* fallthrough */
}
