/* ROM: 60E0FC00 | Address: 0x2EBEE | Size: 30 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST callee (CFG).
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_3920(ST *s);
void f_3934(ST *s);
void f_2E604(ST *s);
void f_2E63A(ST *s);
void f_2EBEE(ST *s)
{
    uint32_t local_3f8 = 0;
    uint32_t local_3fc = 0;
    /* 0x02EBEE: sts.l pr,@-r15 */
    local_3fc = s->pr;
    /* 0x02EBF0: op 0xD30F */
    s->r[3] = 0x00003920u;
    /* 0x02EBF2: op 0x7FFC */
    s->r[15] = s->r[15] + (uint32_t)(int32_t)(int8_t)0xFC;
    /* 0x02EBF4: jsr @r3 */
    s->pr = 0x0002EBF8;
    s->r[4] = (uint32_t)(int32_t)(int8_t)0x10;
    f_3920(s);
    /* 0x02EBF8: op 0xD30B */
    s->r[3] = 0x0002E63Au;
    /* 0x02EBFA: jsr @r3 */
    s->pr = 0x0002EBFE;
    local_3f8 = s->r[0];
    f_2E63A(s);
    /* 0x02EBFE: op 0xD20B */
    s->r[2] = 0x0002E604u;
    /* 0x02EC00: jsr @r2 */
    s->pr = 0x0002EC04;
    
    f_2E604(s);
    /* 0x02EC04: mov.l @r15+,r4 */
    s->r[4] = local_3f8;
    /* 0x02EC06: op 0xD30D */
    s->r[3] = 0x00003934u;
    /* 0x02EC08: jmp @r3 (tail) */
    s->pr = local_3fc;
    f_3934(s);
    return;
    return; /* fallthrough */
}
