/* ROM: 60E0FC00 | Address: 0x32E3E | Size: 14 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST callee (CFG).
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_32E4C(ST *s);
void f_32E98(ST *s);
void f_32EA2(ST *s);
void f_32E3E(ST *s)
{
    uint32_t local_3fc = 0;
    /* 0x032E3E: sts.l pr,@-r15 */
    local_3fc = s->pr;
    /* 0x032E40: bsr 0x32E4C */
    s->pr = 0x00032E44;
    
    f_32E4C(s);
    /* 0x032E44: bsr 0x32E98 */
    s->pr = 0x00032E48;
    
    f_32E98(s);
    /* 0x032E48: bra 0x032EA2 (tail) */
    s->pr = local_3fc;
     { f_32EA2(s); return; }
    return; /* fallthrough */
}
