/* ROM: 60E1D400 | Address: 0x34CDE | Size: 26 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v7.py — ST (shared state) ABI,
 * leaf callee library (c/lib/f_<hex>.c). Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_34CDE(ST *s)
{
    /* 0x034CDE: op 0x930F */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0x0000BB54u;
    /* 0x034CE0: op 0xD512 */
    s->r[5] = 0xFFFFC124u;
    /* 0x034CE2: mov.b @r3,r4 */
    uint32_t t2 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFBB54; /* RAM 0xFFFFBB54 */
    s->r[4] = t2;
    /* 0x034CE4: mov.b @r5,r1 */
    uint32_t t4 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFC124; /* RAM 0xFFFFC124 */
    s->r[1] = t4;
    /* 0x034CE6: op 0x624C */
    s->r[2] = s->r[4] & 0xFFu;
    /* 0x034CE8: op 0x611C */
    s->r[1] = s->r[1] & 0xFFu;
    /* 0x034CEA: op 0x3210 */
    s->T = (s->r[2] == s->r[1]) ? 1u : 0u;
    /* 0x034CEC: bt.s 0x034CF6 */
    /* 0x034CEE: op 0x0009 */
    
    if (s->T) goto L_34CF6;
    /* 0x034CF0: op 0xD20A */
    s->r[2] = 0xFFFFC127u;
    /* 0x034CF2: op 0xE101 */
    s->r[1] = (uint32_t)(int32_t)(int8_t)0x01;
    /* 0x034CF4: mov.b r1,@r2 */
    *(volatile uint8_t*)0xFFFFC127 = s->r[1]; /* RAM 0xFFFFC127 */
    L_34CF6: ;
    /* 0x034CF6: rts */
    /* 0x034CF8: mov.b r4,@r5 */
    *(volatile uint8_t*)0xFFFFC124 = s->r[4]; /* RAM 0xFFFFC124 */
    return;
    return; /* fallthrough */
}
