/* ROM: 60E0FC00 | Address: 0x3D4 | Size: 10 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v7.py — ST (shared state) ABI,
 * leaf callee library (c/lib/f_<hex>.c). Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_3D4(ST *s)
{
    /* 0x0003D4: op 0x9216 */
    s->r[2] = (uint32_t)(int32_t)(int16_t)0x0000DFB6u;
    /* 0x0003D6: op 0xE300 */
    s->r[3] = (uint32_t)(int32_t)(int8_t)0x00;
    /* 0x0003D8: op 0x9112 */
    s->r[1] = (uint32_t)(int32_t)(int16_t)0x0000DFB4u;
    /* 0x0003DA: mov.w r3,@r2 */
    *(volatile uint16_t*)0xFFFFDFB6 = s->r[3]; /* RAM 0xFFFFDFB6 */
    /* 0x0003DC: rts */
    /* 0x0003DE: mov.w r3,@r1 */
    *(volatile uint16_t*)0xFFFFDFB4 = s->r[3]; /* RAM 0xFFFFDFB4 */
    return;
    return; /* fallthrough */
}
