/* ROM: 60E0FC00 | Address: 0x3ED02 | Size: 40 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST callee (CFG).
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, vbr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_3ED02(ST *s)
{
    uint32_t fr2 = 0;
    uint32_t fr3 = 0;
    uint32_t fr4 = 0;
    /* 0x03ED02: op 0x9339 */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0x0000C640u;
    /* 0x03ED04: op 0x943B */
    s->r[4] = (uint32_t)(int32_t)(int16_t)0x0000C64Bu;
    /* 0x03ED06: fmov.s @r3,fr4 */
    fr4 = *(volatile uint32_t*)0xFFFFC640; /* RAM 0xFFFFC640 */
    /* 0x03ED08: op 0xD227 */
    s->r[2] = 0x00079CACu;
    /* 0x03ED0A: fmov.s @r2,fr3 */
    fr3 = *(volatile uint32_t*)0x00079CAC; /* ROM */
    /* 0x03ED0C: fcmp/gt fr4,fr3 */
    { union { uint32_t u; float f; } _a, _b; _a.u = fr3; _b.u = fr4; s->T = (_a.f > _b.f) ? 1u : 0u; }
    /* 0x03ED0E: bf.s 0x03ED18 */
    /* 0x03ED10: op 0x0009 */
    
    if (!s->T) goto L_3ED18;
    /* 0x03ED12: op 0xE000 */
    s->r[0] = (uint32_t)(int32_t)(int8_t)0x00;
    /* 0x03ED14: bra 0x03ED26 */
    /* 0x03ED16: mov.b r0,@r4 */
    *(volatile uint8_t*)0xFFFFC64B = s->r[0]; /* RAM 0xFFFFC64B */
    goto L_3ED26;
    L_3ED26: ;
    /* 0x03ED26: rts */
    /* 0x03ED28: op 0x0009 */
    
    return;
    L_3ED18: ;
    /* 0x03ED18: op 0xD124 */
    s->r[1] = 0x00079CA8u;
    /* 0x03ED1A: fmov.s @r1,fr2 */
    fr2 = *(volatile uint32_t*)0x00079CA8; /* ROM */
    /* 0x03ED1C: fcmp/gt fr2,fr4 */
    { union { uint32_t u; float f; } _a, _b; _a.u = fr4; _b.u = fr2; s->T = (_a.f > _b.f) ? 1u : 0u; }
    /* 0x03ED1E: bf.s 0x03ED26 */
    /* 0x03ED20: op 0x0009 */
    
    if (!s->T) goto L_3ED26;
    /* 0x03ED22: op 0xE001 */
    s->r[0] = (uint32_t)(int32_t)(int8_t)0x01;
    /* 0x03ED24: mov.b r0,@r4 */
    *(volatile uint8_t*)0xFFFFC64B = s->r[0]; /* RAM 0xFFFFC64B */
    return; /* fallthrough */
}
