/* ROM: 60E0FC00 | Address: 0x3E0AC | Size: 46 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v7.py — ST (shared state) ABI,
 * leaf callee library (c/lib/f_<hex>.c). Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_3E0AC(ST *s)
{
    uint32_t fr0 = 0;
    uint32_t fr3 = 0;
    uint32_t fr4 = 0;
    uint32_t fr5 = 0;
    uint32_t fr6 = 0;
    /* 0x03E0AC: fldi0 fr3 */
    fr3 = 0u;
    /* 0x03E0AE: fcmp/eq fr3,fr5 */
    { union { uint32_t u; float f; } _a, _b; _a.u = fr5; _b.u = fr3; s->T = (_a.f == _b.f) ? 1u : 0u; }
    /* 0x03E0B0: bf.s 0x03E0D2 */
    /* 0x03E0B2: op 0x0009 */
    
    if (!s->T) goto L_3E0D2;
    /* 0x03E0B4: fcmp/eq fr3,fr4 */
    { union { uint32_t u; float f; } _a, _b; _a.u = fr4; _b.u = fr3; s->T = (_a.f == _b.f) ? 1u : 0u; }
    /* 0x03E0B6: bf.s 0x03E0BE */
    /* 0x03E0B8: op 0x0009 */
    
    if (!s->T) goto L_3E0BE;
    /* 0x03E0BA: bra 0x03E0D8 */
    /* 0x03E0BC: fldi0 fr6 */
    fr6 = 0u;
    goto L_3E0D8;
    L_3E0BE: ;
    /* 0x03E0BE: fldi0 fr3 */
    fr3 = 0u;
    /* 0x03E0C0: fcmp/gt fr3,fr4 */
    { union { uint32_t u; float f; } _a, _b; _a.u = fr4; _b.u = fr3; s->T = (_a.f > _b.f) ? 1u : 0u; }
    /* 0x03E0C2: bf.s 0x03E0CC */
    /* 0x03E0C4: op 0x0009 */
    
    if (!s->T) goto L_3E0CC;
    /* 0x03E0C6: op 0xC794 */
    s->r[0] = 0x0003E318u;
    /* 0x03E0C8: bra 0x03E0D8 */
    /* 0x03E0CA: fmov.s @r0,fr6 */
    fr6 = *(volatile uint32_t*)0x0003E318; /* ROM */
    goto L_3E0D8;
    L_3E0CC: ;
    /* 0x03E0CC: op 0xC793 */
    s->r[0] = 0x0003E31Cu;
    /* 0x03E0CE: bra 0x03E0D8 */
    /* 0x03E0D0: fmov.s @r0,fr6 */
    fr6 = *(volatile uint32_t*)0x0003E31C; /* ROM */
    goto L_3E0D8;
    L_3E0D2: ;
    /* 0x03E0D2: fmov fr4,fr6 */
    fr6 = fr4;
    /* 0x03E0D4: fdiv fr5,fr6 */
    { union { uint32_t u; float f; } _a, _b, _r; _a.u = fr6; _b.u = fr5; _r.f = _a.f / _b.f; fr6 = _r.u; }
    /* 0x03E0D6: fmov fr6,fr6 */
    fr6 = fr6;
    L_3E0D8: ;
    /* 0x03E0D8: rts */
    /* 0x03E0DA: fmov fr6,fr0 */
    fr0 = fr6;
    return;
    return; /* fallthrough */
}
