/* ROM: 60E1D400 | Address: 0x3E0 | Size: 22 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v7.py — ST (shared state) ABI,
 * leaf callee library (c/lib/f_<hex>.c). Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_3E0(ST *s)
{
    /* 0x0003E0: op 0x920E */
    s->r[2] = (uint32_t)(int32_t)(int16_t)0x0000DFB4u;
    /* 0x0003E2: mov.w @r2,r4 */
    uint32_t t2 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)0xFFFFDFB4; /* RAM 0xFFFFDFB4 */
    s->r[4] = t2;
    /* 0x0003E4: op 0x910E */
    s->r[1] = (uint32_t)(int32_t)(int16_t)0x0000DFB6u;
    /* 0x0003E6: op 0x644D */
    s->r[4] = s->r[4] & 0xFFFFu;
    /* 0x0003E8: mov.w @r1,r3 */
    uint32_t t4 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)0xFFFFDFB6; /* RAM 0xFFFFDFB6 */
    s->r[3] = t4;
    /* 0x0003EA: op 0x633D */
    s->r[3] = s->r[3] & 0xFFFFu;
    /* 0x0003EC: op 0x3438 */
    s->r[4] = s->r[4] - s->r[3];
    /* 0x0003EE: op 0x4411 */
    s->T = ((int32_t)s->r[4] >= 0) ? 1u : 0u;
    /* 0x0003F0: bt 0x0003F4 */
    if (s->T) goto L_3F4;
    /* 0x0003F2: op 0x7464 */
    s->r[4] = s->r[4] + (uint32_t)(int32_t)(int8_t)0x64;
    L_3F4: ;
    /* 0x0003F4: rts */
    /* 0x0003F6: op 0x6043 */
    s->r[0] = s->r[4];
    return;
    return; /* fallthrough */
}
