/* ROM: 60E0FC00 | Address: 0x42230 | Size: 102 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST callee (CFG).
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, vbr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_2068(ST *s);
void f_42230(ST *s)
{
    uint32_t local_3fc = 0;
    uint32_t fr0 = 0;
    uint32_t fr15 = 0;
    uint32_t fr4 = 0;
    /* 0x042230: fmov.s fr15,@-r15 (rt-base) */
    s->r[15] -= 4;
    *(volatile uint32_t*)s->r[15] = fr15;
    /* 0x042232: sts.l pr,@-r15 */
    local_3fc = s->pr;
    /* 0x042234: op 0x9362 */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0x0000AA2Cu;
    /* 0x042236: fmov.s @r3,fr15 */
    fr15 = *(volatile uint32_t*)0xFFFFAA2C; /* RAM 0xFFFFAA2C */
    /* 0x042238: op 0x9261 */
    s->r[2] = (uint32_t)(int32_t)(int16_t)0x0000AAC6u;
    /* 0x04223A: op 0x9161 */
    s->r[1] = (uint32_t)(int32_t)(int16_t)0x0000C946u;
    /* 0x04223C: mov.b @r1,r0 */
    uint32_t t2 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFC946; /* RAM 0xFFFFC946 */
    s->r[0] = t2;
    /* 0x04223E: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x042240: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x042242: bf.s 0x042254 */
    /* 0x042244: mov.b @r2,r4 */
    uint32_t t4 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFAAC6; /* RAM 0xFFFFAAC6 */
    s->r[4] = t4;
    if (!s->T) goto L_42254;
    /* 0x042246: op 0xD334 */
    s->r[3] = 0xFFFFC998u;
    /* 0x042248: op 0xD134 */
    s->r[1] = 0x0007A17Eu;
    /* 0x04224A: mov.b @r3,r0 */
    uint32_t t6 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)s->r[3]; /* RAM 0xFFFFC998 */
    s->r[0] = t6;
    /* 0x04224C: mov.b @r1,r2 */
    uint32_t t8 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)s->r[1]; /* ROM */
    s->r[2] = t8;
    /* 0x04224E: op 0x3022 */
    s->T = (s->r[0] >= s->r[2]) ? 1u : 0u;
    /* 0x042250: bf.s 0x04225C */
    /* 0x042252: op 0x0009 */
    
    if (!s->T) goto L_4225C;
    L_42254: ;
    /* 0x042254: op 0x604C */
    s->r[0] = s->r[4] & 0xFFu;
    /* 0x042256: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x042258: bf.s 0x042288 */
    /* 0x04225A: op 0x0009 */
    
    if (!s->T) goto L_42288;
    L_4225C: ;
    /* 0x04225C: op 0x9351 */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0x0000C948u;
    /* 0x04225E: mov.b @r3,r0 */
    uint32_t t10 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)s->r[3]; /* RAM 0xFFFFC948 */
    s->r[0] = t10;
    /* 0x042260: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x042262: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x042264: bt.s 0x042270 */
    /* 0x042266: op 0x0009 */
    
    if (s->T) goto L_42270;
    /* 0x042268: op 0x604C */
    s->r[0] = s->r[4] & 0xFFu;
    /* 0x04226A: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x04226C: bf.s 0x042276 */
    /* 0x04226E: op 0x0009 */
    
    if (!s->T) goto L_42276;
    L_42270: ;
    /* 0x042270: op 0x9348 */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0x0000C934u;
    /* 0x042272: bra 0x042288 */
    /* 0x042274: fmov.s fr15,@r3 */
    *(volatile uint32_t*)0xFFFFC934 = fr15; /* RAM 0xFFFFC934 */
    goto L_42288;
    L_42288: ;
    /* 0x042288: op 0x913E */
    s->r[1] = (uint32_t)(int32_t)(int16_t)0x0000C941u;
    /* 0x04228A: mov.b @r1,r3 */
    uint32_t t12 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)s->r[1]; /* RAM 0xFFFFC941 */
    s->r[3] = t12;
    /* 0x04228C: op 0xD022 */
    s->r[0] = 0xFFFFC998u;
    /* 0x04228E: mov.b r3,@r0 */
    *(volatile uint8_t*)0xFFFFC998 = s->r[3]; /* RAM 0xFFFFC998 */
    /* 0x042290: lds.l @r15+,pr */
    s->pr = local_3fc;
    /* 0x042292: rts */
    /* 0x042294: fmov.s @r15+,fr15 (rt-base) */
    fr15 = *(volatile uint32_t*)s->r[15];
    s->r[15] = s->r[15] + 4;
    return;
    L_42276: ;
    /* 0x042276: op 0x9146 */
    s->r[1] = (uint32_t)(int32_t)(int16_t)0x0000B594u;
    /* 0x042278: op 0xD429 */
    s->r[4] = 0x00069BB4u;
    /* 0x04227A: op 0xD32A */
    s->r[3] = 0x00002068u;
    /* 0x04227C: jsr @r3 */
    /* 0x04227E: fmov.s @r1,fr4 */
    s->pr = 0x00042280;
    fr4 = *(volatile uint32_t*)0xFFFFB594; /* RAM 0xFFFFB594 */
    f_2068(s);
    /* 0x042280: op 0x9240 */
    s->r[2] = (uint32_t)(int32_t)(int16_t)0x0000C934u;
    /* 0x042282: fmov fr0,fr4 */
    fr4 = fr0;
    /* 0x042284: fsub fr4,fr15 */
    { union { uint32_t u; float f; } _a, _b, _r; _a.u = fr15; _b.u = fr4; _r.f = _a.f - _b.f; fr15 = _r.u; }
    /* 0x042286: fmov.s fr15,@r2 */
    *(volatile uint32_t*)0xFFFFC934 = fr15; /* RAM 0xFFFFC934 */
    return; /* fallthrough */
}
