/* ROM: 60E1D400 | Address: 0x45B6C | Size: 72 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST callee (CFG).
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_213C(ST *s);
void f_45B6C(ST *s)
{
    uint32_t local_3f8 = 0;
    uint32_t local_3fc = 0;
    uint32_t fr4 = 0;
    uint32_t fr5 = 0;
    /* 0x045B6C: mov.l r14,@-r15 */
    local_3fc = s->r[14];
    /* 0x045B6E: sts.l pr,@-r15 */
    local_3f8 = s->pr;
    /* 0x045B70: op 0x9E53 */
    s->r[14] = (uint32_t)(int32_t)(int16_t)0x0000CBF0u;
    /* 0x045B72: op 0x9353 */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0x0000D201u;
    /* 0x045B74: mov.b @r3,r0 */
    uint32_t t2 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFD201; /* RAM 0xFFFFD201 */
    s->r[0] = t2;
    /* 0x045B76: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x045B78: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x045B7A: bf.s 0x045B84 */
    /* 0x045B7C: op 0x0009 */
    
    if (!s->T) goto L_45B84;
    /* 0x045B7E: op 0x914B */
    s->r[1] = (uint32_t)(int32_t)(int16_t)0x000003E8u;
    /* 0x045B80: bra 0x045BAE */
    /* 0x045B82: mov.w r1,@r14 */
    *(volatile uint16_t*)0xFFFFCBF0 = s->r[1]; /* RAM 0xFFFFCBF0 */
    goto L_45BAE;
    L_45B84: ;
    /* 0x045B84: op 0x924D */
    s->r[2] = (uint32_t)(int32_t)(int16_t)0x0000B70Cu;
    /* 0x045B86: mov.b @r2,r0 */
    uint32_t t4 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFB70C; /* RAM 0xFFFFB70C */
    s->r[0] = t4;
    /* 0x045B88: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x045B8A: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x045B8C: bf.s 0x045BAE */
    /* 0x045B8E: op 0x0009 */
    
    if (!s->T) goto L_45BAE;
    /* 0x045B90: op 0x9048 */
    s->r[0] = (uint32_t)(int32_t)(int16_t)0x0000B5B8u;
    /* 0x045B92: fmov.s @r0,fr5 */
    fr5 = *(volatile uint32_t*)0xFFFFB5B8; /* RAM 0xFFFFB5B8 */
    /* 0x045B94: op 0x9347 */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0x0000C12Cu;
    /* 0x045B96: op 0xD425 */
    s->r[4] = 0x0006C00Cu;
    /* 0x045B98: op 0xD225 */
    s->r[2] = 0x0000213Cu;
    /* 0x045B9A: jsr @r2 */
    s->pr = 0x00045B9E;
    fr4 = *(volatile uint32_t*)0xFFFFC12C; /* RAM 0xFFFFC12C */
    f_213C(s);
    /* 0x045B9E: op 0x6403 */
    s->r[4] = s->r[0];
    /* 0x045BA0: mov.w @r14,r2 */
    uint32_t t6 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)0xFFFFCBF0; /* RAM 0xFFFFCBF0 */
    s->r[2] = t6;
    /* 0x045BA2: op 0x634D */
    s->r[3] = s->r[4] & 0xFFFFu;
    /* 0x045BA4: op 0x622D */
    s->r[2] = s->r[2] & 0xFFFFu;
    /* 0x045BA6: op 0x3323 */
    s->T = ((int32_t)s->r[3] >= (int32_t)s->r[2]) ? 1u : 0u;
    /* 0x045BA8: bt.s 0x045BAE */
    /* 0x045BAA: op 0x0009 */
    
    if (s->T) goto L_45BAE;
    /* 0x045BAC: mov.w r4,@r14 */
    *(volatile uint16_t*)0xFFFFCBF0 = s->r[4]; /* RAM 0xFFFFCBF0 */
    L_45BAE: ;
    /* 0x045BAE: lds.l @r15+,pr */
    s->pr = local_3f8;
    /* 0x045BB0: rts */
    /* 0x045BB2: mov.l @r15+,r14 */
    s->r[14] = local_3fc;
    return;
    return; /* fallthrough */
}
