/* ROM: 60E0FC00 | Address: 0x46CC | Size: 116 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST callee (CFG).
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, vbr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_4740(ST *s);
void f_481C(ST *s);
void f_48C8(ST *s);
void f_46CC(ST *s)
{
    uint32_t local_3e0 = 0;
    uint32_t local_3fc = 0;
    uint32_t fr0 = 0;
    uint32_t fr4 = 0;
    /* 0x0046CC: sts.l pr,@-r15 */
    local_3fc = s->pr;
    /* 0x0046CE: op 0xE004 */
    s->r[0] = (uint32_t)(int32_t)(int8_t)0x04;
    /* 0x0046D0: op 0xD315 */
    s->r[3] = 0x000048C8u;
    /* 0x0046D2: op 0x7FF8 */
    s->r[15] = s->r[15] + (uint32_t)(int32_t)(int8_t)0xF8;
    /* 0x0046D4: fmov.s fr4,@(r0,r15) (rt-base) */
    *(volatile uint32_t*)(s->r[0] + s->r[15]) = fr4;
    /* 0x0046D6: op 0x7FF0 */
    s->r[15] = s->r[15] + (uint32_t)(int32_t)(int8_t)0xF0;
    /* 0x0046D8: jsr @r3 */
    /* 0x0046DA: mov.l r15,@-r15 */
    s->pr = 0x000046DC;
    local_3e0 = s->r[15];
    f_48C8(s);
    /* 0x0046DC: op 0xD313 */
    s->r[3] = 0x00004740u;
    /* 0x0046DE: op 0x7F04 */
    s->r[15] = s->r[15] + (uint32_t)(int32_t)(int8_t)0x04;
    /* 0x0046E0: op 0xE208 */
    s->r[2] = (uint32_t)(int32_t)(int8_t)0x08;
    /* 0x0046E2: op 0x32FC */
    s->r[2] = s->r[2] + s->r[15];
    /* 0x0046E4: jsr @r3 */
    /* 0x0046E6: mov.l r2,@-r15 */
    s->pr = 0x000046E8;
    local_3e0 = s->r[2];
    f_4740(s);
    /* 0x0046E8: op 0xD211 */
    s->r[2] = 0x0000481Cu;
    /* 0x0046EA: jsr @r2 */
    /* 0x0046EC: op 0x7F0C */
    s->pr = 0x000046EE;
    s->r[15] = s->r[15] + (uint32_t)(int32_t)(int8_t)0x0C;
    f_481C(s);
    /* 0x0046EE: op 0x7F08 */
    s->r[15] = s->r[15] + (uint32_t)(int32_t)(int8_t)0x08;
    /* 0x0046F0: op 0xD410 */
    s->r[4] = 0x7F800000u;
    /* 0x0046F2: op 0x63F3 */
    s->r[3] = s->r[15];
    /* 0x0046F4: fmov.s fr0,@r15 (rt-base) */
    *(volatile uint32_t*)s->r[15] = fr0;
    /* 0x0046F6: mov.l @r3,r2 (rt-base) */
    uint32_t t1 = *(volatile uint32_t*)s->r[3];
    s->r[2] = t1;
    /* 0x0046F8: op 0x2249 */
    s->r[2] &= s->r[4];
    /* 0x0046FA: op 0x3240 */
    s->T = (s->r[2] == s->r[4]) ? 1u : 0u;
    /* 0x0046FC: bf.s 0x00471A */
    /* 0x0046FE: op 0x0009 */
    
    if (!s->T) goto L_471A;
    /* 0x004700: op 0xD30D */
    s->r[3] = 0x007FFFFFu;
    /* 0x004702: op 0x62F3 */
    s->r[2] = s->r[15];
    /* 0x004704: mov.l @r2,r1 (rt-base) */
    uint32_t t2 = *(volatile uint32_t*)s->r[2];
    s->r[1] = t2;
    /* 0x004706: op 0x2138 */
    s->T = ((s->r[1] & s->r[3]) == 0u) ? 1u : 0u;
    /* 0x004708: bt.s 0x004714 */
    /* 0x00470A: op 0x0009 */
    
    if (s->T) goto L_4714;
    /* 0x00470C: op 0x900A */
    s->r[0] = (uint32_t)(int32_t)(int16_t)0x0000044Du;
    /* 0x00470E: op 0xD20B */
    s->r[2] = 0xFFFF768Cu;
    /* 0x004710: bra 0x00471A */
    /* 0x004712: mov.l r0,@r2 */
    *(volatile uint32_t*)s->r[2] = s->r[0]; /* RAM 0xFFFF768C */
    goto L_471A;
    L_471A: ;
    /* 0x00471A: fmov.s @r15,fr0 (rt-base) */
    fr0 = *(volatile uint32_t*)s->r[15];
    /* 0x00471C: op 0x7F08 */
    s->r[15] = s->r[15] + (uint32_t)(int32_t)(int8_t)0x08;
    /* 0x00471E: lds.l @r15+,pr */
    s->pr = local_3fc;
    /* 0x004720: rts */
    /* 0x004722: op 0x0009 */
    
    return;
    L_4714: ;
    /* 0x004714: op 0x9207 */
    s->r[2] = (uint32_t)(int32_t)(int16_t)0x0000044Cu;
    /* 0x004716: op 0xD109 */
    s->r[1] = 0xFFFF768Cu;
    /* 0x004718: mov.l r2,@r1 */
    *(volatile uint32_t*)0xFFFF768C = s->r[2]; /* RAM 0xFFFF768C */
    return; /* fallthrough */
}
