/* ROM: 60E1D400 | Address: 0x46DD2 | Size: 84 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST callee (CFG).
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_3ED3C(ST *s);
void f_6743C(ST *s);
void f_46DD2(ST *s)
{
    uint32_t local_3fc = 0;
    /* 0x046DD2: sts.l pr,@-r15 */
    local_3fc = s->pr;
    /* 0x046DD4: op 0xD319 */
    s->r[3] = 0x0006743Cu;
    /* 0x046DD6: jsr @r3 */
    s->pr = 0x00046DDA;
    s->r[4] = (uint32_t)(int32_t)(int8_t)0x46;
    f_6743C(s);
    /* 0x046DDA: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x046DDC: op 0x2008 */
    s->T = ((s->r[0] & s->r[0]) == 0u) ? 1u : 0u;
    /* 0x046DDE: bf.s 0x046E1A */
    /* 0x046DE0: op 0x0009 */
    
    if (!s->T) goto L_46E1A;
    /* 0x046DE2: op 0x9322 */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0x0000CD03u;
    /* 0x046DE4: mov.b @r3,r0 */
    uint32_t t2 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)s->r[3]; /* RAM 0xFFFFCD03 */
    s->r[0] = t2;
    /* 0x046DE6: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x046DE8: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x046DEA: bf.s 0x046E1A */
    /* 0x046DEC: op 0x0009 */
    
    if (!s->T) goto L_46E1A;
    /* 0x046DEE: op 0x941B */
    s->r[4] = (uint32_t)(int32_t)(int16_t)0x00008768u;
    /* 0x046DF0: op 0xD10F */
    s->r[1] = 0x0003ED3Cu;
    /* 0x046DF2: jsr @r1 */
    s->pr = 0x00046DF6;
    s->r[5] = (uint32_t)(int32_t)(int8_t)0x00;
    f_3ED3C(s);
    /* 0x046DF6: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x046DF8: op 0x2008 */
    s->T = ((s->r[0] & s->r[0]) == 0u) ? 1u : 0u;
    /* 0x046DFA: bf.s 0x046E1A */
    /* 0x046DFC: op 0x0009 */
    
    if (!s->T) goto L_46E1A;
    /* 0x046DFE: op 0x9315 */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0x0000CCFCu;
    /* 0x046E00: mov.b @r3,r2 */
    uint32_t t4 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)s->r[3]; /* RAM 0xFFFFCCFC */
    s->r[2] = t4;
    /* 0x046E02: op 0x2228 */
    s->T = ((s->r[2] & s->r[2]) == 0u) ? 1u : 0u;
    /* 0x046E04: bf.s 0x046E1A */
    /* 0x046E06: op 0x0009 */
    
    if (!s->T) goto L_46E1A;
    /* 0x046E08: op 0x9111 */
    s->r[1] = (uint32_t)(int32_t)(int16_t)0x0000CCFDu;
    /* 0x046E0A: mov.b @r1,r0 */
    uint32_t t6 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)s->r[1]; /* RAM 0xFFFFCCFD */
    s->r[0] = t6;
    /* 0x046E0C: op 0x2008 */
    s->T = ((s->r[0] & s->r[0]) == 0u) ? 1u : 0u;
    /* 0x046E0E: bf.s 0x046E1A */
    /* 0x046E10: op 0x0009 */
    
    if (!s->T) goto L_46E1A;
    /* 0x046E12: op 0xE301 */
    s->r[3] = (uint32_t)(int32_t)(int8_t)0x01;
    /* 0x046E14: op 0xD20A */
    s->r[2] = 0xFFFFCC68u;
    /* 0x046E16: bra 0x046E20 */
    /* 0x046E18: mov.b r3,@r2 */
    *(volatile uint8_t*)0xFFFFCC68 = s->r[3]; /* RAM 0xFFFFCC68 */
    goto L_46E20;
    L_46E1A: ;
    /* 0x046E1A: op 0xE000 */
    s->r[0] = (uint32_t)(int32_t)(int8_t)0x00;
    /* 0x046E1C: op 0xD108 */
    s->r[1] = 0xFFFFCC68u;
    /* 0x046E1E: mov.b r0,@r1 */
    *(volatile uint8_t*)s->r[1] = s->r[0]; /* RAM 0xFFFFCC68 */
    L_46E20: ;
    /* 0x046E20: lds.l @r15+,pr */
    s->pr = local_3fc;
    /* 0x046E22: rts */
    /* 0x046E24: op 0x0009 */
    
    return;
    return; /* fallthrough */
}
