/* ROM: 60E0FC00 | Address: 0x4602A | Size: 8 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v7.py — ST (shared state) ABI,
 * leaf callee library (c/lib/f_<hex>.c). Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_4602A(ST *s)
{
    /* 0x04602A: op 0x9472 */
    s->r[4] = (uint32_t)(int32_t)(int16_t)0x00008778u;
    /* 0x04602C: op 0xD33C */
    s->r[3] = 0x0003E1F8u;
    /* 0x04602E: jmp @r3 (tail) */
    /* 0x046030: op 0xE500 */
    s->r[5] = (uint32_t)(int32_t)(int8_t)0x00;
    return; /* fallthrough */
}
