/* ROM: 60E0FC00 | Address: 0x48F68 | Size: 216 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST callee (CFG).
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, vbr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_2460(ST *s);
void f_652F0(ST *s);
void f_48F68(ST *s)
{
    uint32_t local_3e4 = 0;
    uint32_t local_3e8 = 0;
    uint32_t local_3ec = 0;
    uint32_t local_3f0 = 0;
    uint32_t local_3f4 = 0;
    uint32_t local_3f8 = 0;
    uint32_t local_3fc = 0;
    /* 0x048F68: mov.l r14,@-r15 */
    local_3fc = s->r[14];
    /* 0x048F6A: mov.l r13,@-r15 */
    local_3f8 = s->r[13];
    /* 0x048F6C: mov.l r12,@-r15 */
    local_3f4 = s->r[12];
    /* 0x048F6E: mov.l r11,@-r15 */
    local_3f0 = s->r[11];
    /* 0x048F70: mov.l r10,@-r15 */
    local_3ec = s->r[10];
    /* 0x048F72: sts.l pr,@-r15 */
    local_3e8 = s->pr;
    /* 0x048F74: op 0xDB3C */
    s->r[11] = 0xFFFFCC38u;
    /* 0x048F76: op 0x7FFC */
    s->r[15] = s->r[15] + (uint32_t)(int32_t)(int8_t)0xFC;
    /* 0x048F78: op 0xDC3C */
    s->r[12] = 0xFFFFCC34u;
    /* 0x048F7A: op 0xDD3D */
    s->r[13] = 0xFFFFCC36u;
    /* 0x048F7C: op 0x926E */
    s->r[2] = (uint32_t)(int32_t)(int16_t)0x0000CFD9u;
    /* 0x048F7E: mov.b @r2,r3 */
    uint32_t t2 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFCFD9; /* RAM 0xFFFFCFD9 */
    s->r[3] = t2;
    /* 0x048F80: op 0x2338 */
    s->T = ((s->r[3] & s->r[3]) == 0u) ? 1u : 0u;
    /* 0x048F82: bf.s 0x04901A */
    /* 0x048F84: op 0xEE00 */
    s->r[14] = (uint32_t)(int32_t)(int8_t)0x00;
    if (!s->T) goto L_4901A;
    /* 0x048F86: op 0xD03B */
    s->r[0] = 0xFFFFA325u;
    /* 0x048F88: mov.b @r0,r3 */
    uint32_t t4 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFA325; /* RAM 0xFFFFA325 */
    s->r[3] = t4;
    /* 0x048F8A: mov.b r3,@r15 */
    local_3e4 = s->r[3] & 0xFF;
    /* 0x048F8C: op 0xD33A */
    s->r[3] = 0x000652F0u;
    /* 0x048F8E: jsr @r3 */
    /* 0x048F90: op 0xE422 */
    s->pr = 0x00048F92;
    s->r[4] = (uint32_t)(int32_t)(int8_t)0x22;
    f_652F0(s);
    /* 0x048F92: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x048F94: op 0x2008 */
    s->T = ((s->r[0] & s->r[0]) == 0u) ? 1u : 0u;
    /* 0x048F96: bf.s 0x049012 */
    /* 0x048F98: op 0x0009 */
    
    if (!s->T) goto L_49012;
    /* 0x048F9A: op 0xD337 */
    s->r[3] = 0x000652F0u;
    /* 0x048F9C: jsr @r3 */
    /* 0x048F9E: op 0xE423 */
    s->pr = 0x00048FA0;
    s->r[4] = (uint32_t)(int32_t)(int8_t)0x23;
    f_652F0(s);
    /* 0x048FA0: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x048FA2: op 0x2008 */
    s->T = ((s->r[0] & s->r[0]) == 0u) ? 1u : 0u;
    /* 0x048FA4: bf.s 0x049012 */
    /* 0x048FA6: op 0x0009 */
    
    if (!s->T) goto L_49012;
    /* 0x048FA8: op 0xDA34 */
    s->r[10] = 0x00002460u;
    /* 0x048FAA: mov.b @r15,r5 */
    s->r[5] = (uint32_t)(int32_t)(int8_t)(local_3e4 & 0xFFu);
    /* 0x048FAC: op 0x655C */
    s->r[5] = s->r[5] & 0xFFu;
    /* 0x048FAE: op 0x6053 */
    s->r[0] = s->r[5];
    /* 0x048FB0: op 0x8802 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x02) ? 1u : 0u;
    /* 0x048FB2: bf.s 0x048FD0 */
    /* 0x048FB4: op 0xE401 */
    s->r[4] = (uint32_t)(int32_t)(int8_t)0x01;
    if (!s->T) goto L_48FD0;
    /* 0x048FB6: mov.w @r13,r2 */
    uint32_t t6 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)0xFFFFCC36; /* RAM 0xFFFFCC36 */
    s->r[2] = t6;
    /* 0x048FB8: op 0xD131 */
    s->r[1] = 0x0007C2AEu;
    /* 0x048FBA: mov.w @r1,r3 */
    uint32_t t8 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)0x0007C2AE; /* ROM */
    s->r[3] = t8;
    /* 0x048FBC: op 0x3232 */
    s->T = (s->r[2] >= s->r[3]) ? 1u : 0u;
    /* 0x048FBE: bf.s 0x048FC6 */
    /* 0x048FC0: op 0xE501 */
    s->r[5] = (uint32_t)(int32_t)(int8_t)0x01;
    if (!s->T) goto L_48FC6;
    /* 0x048FC2: op 0x924C */
    s->r[2] = (uint32_t)(int32_t)(int16_t)0x0000CC31u;
    /* 0x048FC4: mov.b r4,@r2 */
    *(volatile uint8_t*)s->r[2] = s->r[4]; /* RAM 0xFFFFCC31 */
    L_48FC6: ;
    /* 0x048FC6: jsr @r10 */
    /* 0x048FC8: mov.w @r13,r4 */
    s->pr = 0x00048FCA;
    uint32_t t10 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)0xFFFFCC36; /* RAM 0xFFFFCC36 */
    s->r[4] = t10;
    f_2460(s);
    /* 0x048FCA: mov.w r0,@r13 */
    *(volatile uint16_t*)0xFFFFCC36 = s->r[0]; /* RAM 0xFFFFCC36 */
    /* 0x048FCC: bra 0x049016 */
    /* 0x048FCE: mov.w r14,@r12 */
    *(volatile uint16_t*)0xFFFFCC34 = s->r[14]; /* RAM 0xFFFFCC34 */
    goto L_49016;
    L_49016: ;
    /* 0x049016: bra 0x049030 */
    /* 0x049018: mov.w r14,@r11 */
    *(volatile uint16_t*)0xFFFFCC38 = s->r[14]; /* RAM 0xFFFFCC38 */
    goto L_49030;
    L_49030: ;
    /* 0x049030: op 0x7F04 */
    s->r[15] = s->r[15] + (uint32_t)(int32_t)(int8_t)0x04;
    /* 0x049032: lds.l @r15+,pr */
    s->pr = local_3e8;
    /* 0x049034: mov.l @r15+,r10 */
    s->r[10] = local_3ec;
    /* 0x049036: mov.l @r15+,r11 */
    s->r[11] = local_3f0;
    /* 0x049038: mov.l @r15+,r12 */
    s->r[12] = local_3f4;
    /* 0x04903A: mov.l @r15+,r13 */
    s->r[13] = local_3f8;
    /* 0x04903C: rts */
    /* 0x04903E: mov.l @r15+,r14 */
    s->r[14] = local_3fc;
    return;
    L_48FD0: ;
    /* 0x048FD0: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x048FD2: bf.s 0x048FF2 */
    /* 0x048FD4: op 0x0009 */
    
    if (!s->T) goto L_48FF2;
    /* 0x048FD6: mov.w @r11,r3 */
    uint32_t t12 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)0xFFFFCC38; /* RAM 0xFFFFCC38 */
    s->r[3] = t12;
    /* 0x048FD8: op 0xD12A */
    s->r[1] = 0x0007C2B0u;
    /* 0x048FDA: mov.w @r1,r2 */
    uint32_t t14 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)s->r[1]; /* ROM */
    s->r[2] = t14;
    /* 0x048FDC: op 0x3322 */
    s->T = (s->r[3] >= s->r[2]) ? 1u : 0u;
    /* 0x048FDE: bf.s 0x048FE6 */
    /* 0x048FE0: op 0xE501 */
    s->r[5] = (uint32_t)(int32_t)(int8_t)0x01;
    if (!s->T) goto L_48FE6;
    /* 0x048FE2: op 0x923D */
    s->r[2] = (uint32_t)(int32_t)(int16_t)0x0000CC33u;
    /* 0x048FE4: mov.b r4,@r2 */
    *(volatile uint8_t*)s->r[2] = s->r[4]; /* RAM 0xFFFFCC33 */
    L_48FE6: ;
    /* 0x048FE6: jsr @r10 */
    /* 0x048FE8: mov.w @r11,r4 */
    s->pr = 0x00048FEA;
    uint32_t t16 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)0xFFFFCC38; /* RAM 0xFFFFCC38 */
    s->r[4] = t16;
    f_2460(s);
    /* 0x048FEA: mov.w r0,@r11 */
    *(volatile uint16_t*)0xFFFFCC38 = s->r[0]; /* RAM 0xFFFFCC38 */
    /* 0x048FEC: mov.w r14,@r12 */
    *(volatile uint16_t*)0xFFFFCC34 = s->r[14]; /* RAM 0xFFFFCC34 */
    /* 0x048FEE: bra 0x049030 */
    /* 0x048FF0: mov.w r14,@r13 */
    *(volatile uint16_t*)0xFFFFCC36 = s->r[14]; /* RAM 0xFFFFCC36 */
    goto L_49030;
    L_48FF2: ;
    /* 0x048FF2: mov.w @r12,r2 */
    uint32_t t18 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)s->r[12]; /* RAM 0xFFFFCC34 */
    s->r[2] = t18;
    /* 0x048FF4: op 0xD124 */
    s->r[1] = 0x0007C2ACu;
    /* 0x048FF6: mov.w @r1,r3 */
    uint32_t t20 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)s->r[1]; /* ROM */
    s->r[3] = t20;
    /* 0x048FF8: op 0x3232 */
    s->T = (s->r[2] >= s->r[3]) ? 1u : 0u;
    /* 0x048FFA: bf.s 0x049006 */
    /* 0x048FFC: op 0xE501 */
    s->r[5] = (uint32_t)(int32_t)(int8_t)0x01;
    if (!s->T) goto L_49006;
    /* 0x048FFE: op 0x9230 */
    s->r[2] = (uint32_t)(int32_t)(int16_t)0x0000CC30u;
    /* 0x049000: op 0x9330 */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0x0000CC32u;
    /* 0x049002: mov.b r4,@r2 */
    *(volatile uint8_t*)s->r[2] = s->r[4]; /* RAM 0xFFFFCC30 */
    /* 0x049004: mov.b r4,@r3 */
    *(volatile uint8_t*)s->r[3] = s->r[4]; /* RAM 0xFFFFCC32 */
    L_49006: ;
    /* 0x049006: jsr @r10 */
    /* 0x049008: mov.w @r12,r4 */
    s->pr = 0x0004900A;
    uint32_t t22 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)0xFFFFCC34; /* RAM 0xFFFFCC34 */
    s->r[4] = t22;
    f_2460(s);
    /* 0x04900A: mov.w r0,@r12 */
    *(volatile uint16_t*)0xFFFFCC34 = s->r[0]; /* RAM 0xFFFFCC34 */
    /* 0x04900C: mov.w r14,@r13 */
    *(volatile uint16_t*)0xFFFFCC36 = s->r[14]; /* RAM 0xFFFFCC36 */
    /* 0x04900E: bra 0x049030 */
    /* 0x049010: mov.w r14,@r11 */
    *(volatile uint16_t*)0xFFFFCC38 = s->r[14]; /* RAM 0xFFFFCC38 */
    goto L_49030;
    L_49012: ;
    /* 0x049012: mov.w r14,@r12 */
    *(volatile uint16_t*)s->r[12] = s->r[14]; /* RAM 0xFFFFCC34 */
    /* 0x049014: mov.w r14,@r13 */
    *(volatile uint16_t*)0xFFFFCC36 = s->r[14]; /* RAM 0xFFFFCC36 */
    L_4901A: ;
    /* 0x04901A: op 0x9120 */
    s->r[1] = (uint32_t)(int32_t)(int16_t)0x0000CC31u;
    /* 0x04901C: op 0x9320 */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0x0000CC33u;
    /* 0x04901E: mov.b r14,@r1 */
    *(volatile uint8_t*)s->r[1] = s->r[14]; /* RAM 0xFFFFCC31 */
    /* 0x049020: mov.b r14,@r3 */
    *(volatile uint8_t*)s->r[3] = s->r[14]; /* RAM 0xFFFFCC33 */
    /* 0x049022: op 0x921E */
    s->r[2] = (uint32_t)(int32_t)(int16_t)0x0000CC30u;
    /* 0x049024: op 0x911E */
    s->r[1] = (uint32_t)(int32_t)(int16_t)0x0000CC32u;
    /* 0x049026: mov.b r14,@r2 */
    *(volatile uint8_t*)s->r[2] = s->r[14]; /* RAM 0xFFFFCC30 */
    /* 0x049028: mov.b r14,@r1 */
    *(volatile uint8_t*)s->r[1] = s->r[14]; /* RAM 0xFFFFCC32 */
    /* 0x04902A: mov.w r14,@r12 */
    *(volatile uint16_t*)0xFFFFCC34 = s->r[14]; /* RAM 0xFFFFCC34 */
    /* 0x04902C: mov.w r14,@r13 */
    *(volatile uint16_t*)0xFFFFCC36 = s->r[14]; /* RAM 0xFFFFCC36 */
    /* 0x04902E: mov.w r14,@r11 */
    *(volatile uint16_t*)0xFFFFCC38 = s->r[14]; /* RAM 0xFFFFCC38 */
    return; /* fallthrough */
}
