/* ROM: 60E0FC00 | Address: 0x49B5A | Size: 198 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST callee (CFG).
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_2478(ST *s);
void f_49B5A(ST *s)
{
    uint32_t local_3ec = 0;
    uint32_t local_3f0 = 0;
    uint32_t local_3f4 = 0;
    uint32_t local_3f8 = 0;
    uint32_t local_3fc = 0;
    /* 0x049B5A: mov.l r14,@-r15 */
    local_3fc = s->r[14];
    /* 0x049B5C: mov.l r13,@-r15 */
    local_3f8 = s->r[13];
    /* 0x049B5E: mov.l r12,@-r15 */
    local_3f4 = s->r[12];
    /* 0x049B60: mov.l r11,@-r15 */
    local_3f0 = s->r[11];
    /* 0x049B62: sts.l pr,@-r15 */
    local_3ec = s->pr;
    /* 0x049B64: op 0xD324 */
    s->r[3] = 0xFFFFCC8Eu;
    /* 0x049B66: mov.w @r3,r12 */
    uint32_t t2 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)0xFFFFCC8E; /* RAM 0xFFFFCC8E */
    s->r[12] = t2;
    /* 0x049B68: op 0xD226 */
    s->r[2] = 0xFFFFCC93u;
    /* 0x049B6A: mov.b @r2,r4 */
    uint32_t t4 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFCC93; /* RAM 0xFFFFCC93 */
    s->r[4] = t4;
    /* 0x049B6C: op 0x9141 */
    s->r[1] = (uint32_t)(int32_t)(int16_t)0x0000CFD9u;
    /* 0x049B6E: op 0x6D4C */
    s->r[13] = s->r[4] & 0xFFu;
    /* 0x049B70: op 0xDE25 */
    s->r[14] = 0xFFFFCC90u;
    /* 0x049B72: op 0x60D3 */
    s->r[0] = s->r[13];
    /* 0x049B74: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x049B76: bt.s 0x049B94 */
    /* 0x049B78: mov.b @r1,r11 */
    uint32_t t6 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFCFD9; /* RAM 0xFFFFCFD9 */
    s->r[11] = t6;
    if (s->T) goto L_49B94;
    /* 0x049B7A: op 0xD324 */
    s->r[3] = 0xFFFFCC98u;
    /* 0x049B7C: mov.w @r3,r0 */
    uint32_t t8 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)s->r[3]; /* RAM 0xFFFFCC98 */
    s->r[0] = t8;
    /* 0x049B7E: op 0x2008 */
    s->T = ((s->r[0] & s->r[0]) == 0u) ? 1u : 0u;
    /* 0x049B80: bt.s 0x049B8C */
    /* 0x049B82: op 0x0009 */
    
    if (s->T) goto L_49B8C;
    /* 0x049B84: op 0x62CD */
    s->r[2] = s->r[12] & 0xFFFFu;
    /* 0x049B86: op 0x2228 */
    s->T = ((s->r[2] & s->r[2]) == 0u) ? 1u : 0u;
    /* 0x049B88: bt.s 0x049B94 */
    /* 0x049B8A: op 0x0009 */
    
    if (s->T) goto L_49B94;
    L_49B8C: ;
    /* 0x049B8C: op 0x60BC */
    s->r[0] = s->r[11] & 0xFFu;
    /* 0x049B8E: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x049B90: bf.s 0x049B9A */
    /* 0x049B92: op 0x0009 */
    
    if (!s->T) goto L_49B9A;
    L_49B94: ;
    /* 0x049B94: op 0xE200 */
    s->r[2] = (uint32_t)(int32_t)(int8_t)0x00;
    /* 0x049B96: bra 0x049BB0 */
    /* 0x049B98: mov.b r2,@r14 */
    *(volatile uint8_t*)0xFFFFCC90 = s->r[2]; /* RAM 0xFFFFCC90 */
    goto L_49BB0;
    L_49BB0: ;
    /* 0x049BB0: op 0x9420 */
    s->r[4] = (uint32_t)(int32_t)(int16_t)0x0000CC8Cu;
    /* 0x049BB2: op 0x60D3 */
    s->r[0] = s->r[13];
    /* 0x049BB4: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x049BB6: bt.s 0x049BC2 */
    /* 0x049BB8: op 0x0009 */
    
    if (s->T) goto L_49BC2;
    /* 0x049BBA: op 0x60BC */
    s->r[0] = s->r[11] & 0xFFu;
    /* 0x049BBC: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x049BBE: bf.s 0x049BC8 */
    /* 0x049BC0: op 0x0009 */
    
    if (!s->T) goto L_49BC8;
    L_49BC2: ;
    /* 0x049BC2: op 0xE200 */
    s->r[2] = (uint32_t)(int32_t)(int8_t)0x00;
    /* 0x049BC4: bra 0x049BE2 */
    /* 0x049BC6: mov.b r2,@r4 */
    *(volatile uint8_t*)0xFFFFCC8C = s->r[2]; /* RAM 0xFFFFCC8C */
    goto L_49BE2;
    L_49BE2: ;
    /* 0x049BE2: op 0xD30A */
    s->r[3] = 0xFFFFCC98u;
    /* 0x049BE4: mov.w r12,@r3 */
    *(volatile uint16_t*)s->r[3] = s->r[12]; /* RAM 0xFFFFCC98 */
    /* 0x049BE6: lds.l @r15+,pr */
    s->pr = local_3ec;
    /* 0x049BE8: mov.l @r15+,r11 */
    s->r[11] = local_3f0;
    /* 0x049BEA: mov.l @r15+,r12 */
    s->r[12] = local_3f4;
    /* 0x049BEC: mov.l @r15+,r13 */
    s->r[13] = local_3f8;
    /* 0x049BEE: rts */
    /* 0x049BF0: mov.l @r15+,r14 */
    s->r[14] = local_3fc;
    return;
    L_49BC8: ;
    /* 0x049BC8: mov.b @r14,r1 */
    uint32_t t10 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)s->r[14]; /* RAM 0xFFFFCC90 */
    s->r[1] = t10;
    /* 0x049BCA: op 0xD213 */
    s->r[2] = 0x0007C2B6u;
    /* 0x049BCC: mov.b @r2,r3 */
    uint32_t t12 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)s->r[2]; /* ROM */
    s->r[3] = t12;
    /* 0x049BCE: op 0x3136 */
    s->T = (s->r[1] > s->r[3]) ? 1u : 0u;
    /* 0x049BD0: bf.s 0x049BE2 */
    /* 0x049BD2: op 0x0009 */
    
    if (!s->T) goto L_49BE2;
    /* 0x049BD4: op 0xD311 */
    s->r[3] = 0x0007C2B7u;
    /* 0x049BD6: mov.b @r3,r1 */
    uint32_t t14 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)s->r[3]; /* ROM */
    s->r[1] = t14;
    /* 0x049BD8: op 0x2118 */
    s->T = ((s->r[1] & s->r[1]) == 0u) ? 1u : 0u;
    /* 0x049BDA: bf.s 0x049BE2 */
    /* 0x049BDC: op 0x0009 */
    
    if (!s->T) goto L_49BE2;
    /* 0x049BDE: op 0xE201 */
    s->r[2] = (uint32_t)(int32_t)(int8_t)0x01;
    /* 0x049BE0: mov.b r2,@r4 */
    *(volatile uint8_t*)0xFFFFCC8C = s->r[2]; /* RAM 0xFFFFCC8C */
    L_49B9A: ;
    /* 0x049B9A: op 0xD31D */
    s->r[3] = 0xFFFF9FA2u;
    /* 0x049B9C: mov.b @r3,r0 */
    uint32_t t16 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)s->r[3]; /* RAM 0xFFFF9FA2 */
    s->r[0] = t16;
    /* 0x049B9E: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x049BA0: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x049BA2: bf.s 0x049BB0 */
    /* 0x049BA4: op 0x0009 */
    
    if (!s->T) goto L_49BB0;
    /* 0x049BA6: op 0xE501 */
    s->r[5] = (uint32_t)(int32_t)(int8_t)0x01;
    /* 0x049BA8: op 0xD11A */
    s->r[1] = 0x00002478u;
    /* 0x049BAA: jsr @r1 */
    s->pr = 0x00049BAE;
    uint32_t t18 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFCC90; /* RAM 0xFFFFCC90 */
    s->r[4] = t18;
    f_2478(s);
    /* 0x049BAE: mov.b r0,@r14 */
    *(volatile uint8_t*)0xFFFFCC90 = s->r[0]; /* RAM 0xFFFFCC90 */
    return; /* fallthrough */
}
