/* ROM: 60E1D400 | Address: 0x490F0 | Size: 8 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST callee (CFG).
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_3EE58(ST *s);
void f_490F0(ST *s)
{
    /* 0x0490F0: op 0x9447 */
    s->r[4] = (uint32_t)(int32_t)(int16_t)0x00008788u;
    /* 0x0490F2: op 0xD329 */
    s->r[3] = 0x0003EE58u;
    /* 0x0490F4: jmp @r3 (tail) */
    s->r[5] = (uint32_t)(int32_t)(int8_t)0x01;
    f_3EE58(s);
    return;
    return; /* fallthrough */
}
