/* ROM: 60E0FC00 | Address: 0x4B0F0 | Size: 6 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v7.py — ST (shared state) ABI,
 * leaf callee library (c/lib/f_<hex>.c). Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, vbr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_4B0F0(ST *s)
{
    /* 0x04B0F0: op 0xD11F */
    s->r[1] = 0xFFFFCD54u;
    /* 0x04B0F2: op 0xE300 */
    s->r[3] = (uint32_t)(int32_t)(int8_t)0x00;
    /* 0x04B0F4: rts */
    /* 0x04B0F6: mov.w r3,@r1 */
    *(volatile uint16_t*)0xFFFFCD54 = s->r[3]; /* RAM 0xFFFFCD54 */
    return;
    return; /* fallthrough */
}
