/* ROM: 60E1D400 | Address: 0x4B8E4 | Size: 32 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v7.py — ST (shared state) ABI,
 * leaf callee library (c/lib/f_<hex>.c). Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_4B8E4(ST *s)
{
    /* 0x04B8E4: op 0x9226 */
    s->r[2] = (uint32_t)(int32_t)(int16_t)0x0000CE1Cu;
    /* 0x04B8E6: mov.b @r2,r3 */
    uint32_t t2 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFCE1C; /* RAM 0xFFFFCE1C */
    s->r[3] = t2;
    /* 0x04B8E8: op 0x2338 */
    s->T = ((s->r[3] & s->r[3]) == 0u) ? 1u : 0u;
    /* 0x04B8EA: bf.s 0x04B902 */
    /* 0x04B8EC: op 0x0009 */
    
    if (!s->T) goto L_4B902;
    /* 0x04B8EE: op 0x9422 */
    s->r[4] = (uint32_t)(int32_t)(int16_t)0x0000CE1Au;
    /* 0x04B8F0: op 0x9119 */
    s->r[1] = (uint32_t)(int32_t)(int16_t)0x0000CE19u;
    /* 0x04B8F2: mov.b @r1,r3 */
    uint32_t t4 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFCE19; /* RAM 0xFFFFCE19 */
    s->r[3] = t4;
    /* 0x04B8F4: op 0x2338 */
    s->T = ((s->r[3] & s->r[3]) == 0u) ? 1u : 0u;
    /* 0x04B8F6: bf.s 0x04B8FE */
    /* 0x04B8F8: op 0x0009 */
    
    if (!s->T) goto L_4B8FE;
    /* 0x04B8FA: bra 0x04B900 */
    /* 0x04B8FC: op 0xE300 */
    s->r[3] = (uint32_t)(int32_t)(int8_t)0x00;
    goto L_4B900;
    L_4B8FE: ;
    /* 0x04B8FE: op 0xE301 */
    s->r[3] = (uint32_t)(int32_t)(int8_t)0x01;
    L_4B900: ;
    /* 0x04B900: mov.b r3,@r4 */
    *(volatile uint8_t*)s->r[4] = s->r[3]; /* RAM 0xFFFFCE1A */
    L_4B902: ;
    /* 0x04B902: rts */
    /* 0x04B904: op 0x0009 */
    
    return;
    return; /* fallthrough */
}
