/* ROM: 60E0FC00 | Address: 0x5182A | Size: 50 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST callee (CFG).
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, vbr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_3E1F8(ST *s);
void f_5182A(ST *s)
{
    /* 0x05182A: op 0xD310 */
    s->r[3] = 0x0003E1F8u;
    /* 0x05182C: jmp @r3 (tail) */
    /* 0x05182E: op 0xE500 */
    s->r[5] = (uint32_t)(int32_t)(int8_t)0x00;
    f_3E1F8(s);
    return;
    return; /* fallthrough */
}
