/* ROM: 60E0FC00 | Address: 0x52562 | Size: 62 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST callee (CFG).
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_5E644(ST *s);
void f_52562(ST *s)
{
    /* 0x052562: op 0x9313 */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0x0000CFC0u;
    /* 0x052564: mov.b @r3,r0 */
    uint32_t t2 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFCFC0; /* RAM 0xFFFFCFC0 */
    s->r[0] = t2;
    /* 0x052566: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x052568: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x05256A: bf.s 0x052576 */
    /* 0x05256C: op 0x0009 */
    
    if (!s->T) goto L_52576;
    /* 0x05256E: op 0xE501 */
    s->r[5] = (uint32_t)(int32_t)(int8_t)0x01;
    /* 0x052570: op 0xD10A */
    s->r[1] = 0x0005E644u;
    /* 0x052572: jmp @r1 (tail) */
    s->r[4] = (uint32_t)(int32_t)(int8_t)0x42;
    f_5E644(s);
    return;
    L_52576: ;
    /* 0x052576: op 0xE502 */
    s->r[5] = (uint32_t)(int32_t)(int8_t)0x02;
    /* 0x052578: op 0xD208 */
    s->r[2] = 0x0005E644u;
    /* 0x05257A: jmp @r2 (tail) */
    s->r[4] = (uint32_t)(int32_t)(int8_t)0x42;
    f_5E644(s);
    return;
    return; /* fallthrough */
}
