/* ROM: 60E0FC00 | Address: 0x5217A | Size: 28 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST callee (CFG).
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_5217A(ST *s)
{
    /* 0x05217A: op 0x9425 */
    s->r[4] = (uint32_t)(int32_t)(int16_t)0x0000CFB9u;
    /* 0x05217C: op 0x9220 */
    s->r[2] = (uint32_t)(int32_t)(int16_t)0x0000CFB8u;
    /* 0x05217E: mov.b @r2,r3 */
    uint32_t t2 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFCFB8; /* RAM 0xFFFFCFB8 */
    s->r[3] = t2;
    /* 0x052180: op 0x633C */
    s->r[3] = s->r[3] & 0xFFu;
    /* 0x052182: op 0x4315 */
    s->T = ((int32_t)s->r[3] > 0) ? 1u : 0u;
    /* 0x052184: bf.s 0x05218E */
    /* 0x052186: op 0x0009 */
    
    if (!s->T) goto L_5218E;
    /* 0x052188: op 0xE101 */
    s->r[1] = (uint32_t)(int32_t)(int8_t)0x01;
    /* 0x05218A: bra 0x052192 */
    /* 0x05218C: mov.b r1,@r4 */
    *(volatile uint8_t*)0xFFFFCFB9 = s->r[1]; /* RAM 0xFFFFCFB9 */
    goto L_52192;
    L_52192: ;
    /* 0x052192: rts */
    /* 0x052194: op 0x0009 */
    
    return;
    L_5218E: ;
    /* 0x05218E: op 0xE000 */
    s->r[0] = (uint32_t)(int32_t)(int8_t)0x00;
    /* 0x052190: mov.b r0,@r4 */
    *(volatile uint8_t*)0xFFFFCFB9 = s->r[0]; /* RAM 0xFFFFCFB9 */
    return; /* fallthrough */
}
