/* ROM: 60E0FC00 | Address: 0x54056 | Size: 6 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v7.py — ST (shared state) ABI,
 * leaf callee library (c/lib/f_<hex>.c). Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, vbr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_54056(ST *s)
{
    uint32_t local_408 = 0;
    /* 0x054056: op 0x7F08 */
    s->r[15] = s->r[15] + (uint32_t)(int32_t)(int8_t)0x08;
    /* 0x054058: lds.l @r15+,pr */
    s->pr = local_408;
    /* 0x05405A: rts */
    /* 0x05405C: op 0x0009 */
    
    return;
    return; /* fallthrough */
}
