/* ROM: 60E0FC00 | Address: 0x54ADE | Size: 38 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST callee (CFG).
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_52A5A(ST *s);
void f_54ADE(ST *s)
{
    /* 0x054ADE: op 0x9404 */
    s->r[4] = (uint32_t)(int32_t)(int16_t)0xB1u;
    /* 0x054AE0: op 0xD307 */
    s->r[3] = 0x00052A5Au;
    /* 0x054AE2: jmp @r3 (tail) */
    s->r[5] = (uint32_t)(int32_t)(int8_t)0x31;
    f_52A5A(s);
    return;
    return; /* fallthrough */
}
