/* ROM: 60E0FC00 | Address: 0x5405E | Size: 58 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v7.py — ST (shared state) ABI,
 * leaf callee library (c/lib/f_<hex>.c). Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_5405E(ST *s)
{
    uint32_t local_3f8 = 0;
    uint32_t local_3fc = 0;
    /* 0x05405E: sts.l pr,@-r15 */
    local_3fc = s->pr;
    /* 0x054060: op 0xD315 */
    s->r[3] = 0x00003920u;
    /* 0x054062: op 0x7FFC */
    s->r[15] = s->r[15] + (uint32_t)(int32_t)(int8_t)0xFC;
    /* 0x054064: jsr @r3 */
    /* 0x054066: op 0xE410 */
    s->r[4] = (uint32_t)(int32_t)(int8_t)0x10;
    /* 0x054068: mov.l r0,@r15 */
    local_3f8 = s->r[0];
    /* 0x05406A: op 0xD315 */
    s->r[3] = 0xFFFFCFE8u;
    /* 0x05406C: mov.b @r3,r0 */
    uint32_t t2 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFCFE8; /* RAM 0xFFFFCFE8 */
    s->r[0] = t2;
    /* 0x05406E: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x054070: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x054072: bf.s 0x05408C */
    /* 0x054074: op 0x0009 */
    
    if (!s->T) goto L_5408C;
    /* 0x054076: op 0xD211 */
    s->r[2] = 0xFFFFCFE6u;
    /* 0x054078: op 0x9012 */
    s->r[0] = (uint32_t)(int32_t)(int16_t)0x00000271u;
    /* 0x05407A: mov.w @r2,r1 */
    uint32_t t4 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)0xFFFFCFE6; /* RAM 0xFFFFCFE6 */
    s->r[1] = t4;
    /* 0x05407C: op 0x611D */
    s->r[1] = s->r[1] & 0xFFFFu;
    /* 0x05407E: op 0x3103 */
    s->T = ((int32_t)s->r[1] >= (int32_t)s->r[0]) ? 1u : 0u;
    /* 0x054080: bt.s 0x05408C */
    /* 0x054082: op 0x0009 */
    
    if (s->T) goto L_5408C;
    /* 0x054084: op 0xD40D */
    s->r[4] = 0xFFFFCFE6u;
    /* 0x054086: mov.w @r4,r2 */
    uint32_t t6 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)0xFFFFCFE6; /* RAM 0xFFFFCFE6 */
    s->r[2] = t6;
    /* 0x054088: op 0x7201 */
    s->r[2] = s->r[2] + (uint32_t)(int32_t)(int8_t)0x01;
    /* 0x05408A: mov.w r2,@r4 */
    *(volatile uint16_t*)0xFFFFCFE6 = s->r[2]; /* RAM 0xFFFFCFE6 */
    L_5408C: ;
    /* 0x05408C: op 0xD30D */
    s->r[3] = 0x00003934u;
    /* 0x05408E: jsr @r3 */
    /* 0x054090: mov.l @r15,r4 */
    s->r[4] = local_3f8;
    /* 0x054092: op 0x7F04 */
    s->r[15] = s->r[15] + (uint32_t)(int32_t)(int8_t)0x04;
    /* 0x054094: lds.l @r15+,pr */
    s->pr = local_3fc;
    /* 0x054096: rts */
    /* 0x054098: op 0x0009 */
    
    return;
    return; /* fallthrough */
}
