/* ROM: 60E0FC00 | Address: 0x54146 | Size: 4 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v7.py — ST (shared state) ABI,
 * leaf callee library (c/lib/f_<hex>.c). Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_54146(ST *s)
{
    /* 0x054146: op 0xD326 */
    s->r[3] = 0xFFFFCFE3u;
    /* 0x054148: rts */
    /* 0x05414A: mov.b @r3,r0 */
    uint32_t t2 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFCFE3; /* RAM 0xFFFFCFE3 */
    s->r[0] = t2;
    return;
    return; /* fallthrough */
}
