/* ROM: 60E0FC00 | Address: 0x540FE | Size: 72 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST callee (CFG).
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, vbr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_540FE(ST *s)
{
    /* 0x0540FE: op 0xD636 */
    s->r[6] = 0x0005D8C8u;
    /* 0x054100: bra 0x054106 */
    /* 0x054102: op 0xE500 */
    s->r[5] = (uint32_t)(int32_t)(int8_t)0x00;
    goto L_54106;
    L_54106: ;
    /* 0x054106: op 0x625C */
    s->r[2] = s->r[5] & 0xFFu;
    /* 0x054108: op 0x4208 */
    s->r[2] = (s->r[2] << 2);
    /* 0x05410A: op 0x326C */
    s->r[2] = s->r[2] + s->r[6];
    /* 0x05410C: mov.b @r2,r3 (rt-base) */
    uint32_t t1 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)s->r[2];
    s->r[3] = t1;
    /* 0x05410E: op 0x624C */
    s->r[2] = s->r[4] & 0xFFu;
    /* 0x054110: op 0x633C */
    s->r[3] = s->r[3] & 0xFFu;
    /* 0x054112: op 0x3320 */
    s->T = (s->r[3] == s->r[2]) ? 1u : 0u;
    /* 0x054114: bt.s 0x054122 */
    /* 0x054116: op 0x0009 */
    
    if (s->T) goto L_54122;
    /* 0x054118: op 0x625C */
    s->r[2] = s->r[5] & 0xFFu;
    /* 0x05411A: op 0xE305 */
    s->r[3] = (uint32_t)(int32_t)(int8_t)0x05;
    /* 0x05411C: op 0x3233 */
    s->T = ((int32_t)s->r[2] >= (int32_t)s->r[3]) ? 1u : 0u;
    /* 0x05411E: bf.s 0x054104 */
    /* 0x054120: op 0x0009 */
    
    if (!s->T) goto L_54104;
    L_54122: ;
    /* 0x054122: op 0xE405 */
    s->r[4] = (uint32_t)(int32_t)(int8_t)0x05;
    /* 0x054124: op 0x9152 */
    s->r[1] = (uint32_t)(int32_t)(int16_t)0x0000D1C8u;
    /* 0x054126: op 0x635C */
    s->r[3] = s->r[5] & 0xFFu;
    /* 0x054128: op 0x3343 */
    s->T = ((int32_t)s->r[3] >= (int32_t)s->r[4]) ? 1u : 0u;
    /* 0x05412A: bt.s 0x054142 */
    /* 0x05412C: mov.w @r1,r6 */
    uint32_t t3 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)0xFFFFD1C8; /* RAM 0xFFFFD1C8 */
    s->r[6] = t3;
    if (s->T) goto L_54142;
    /* 0x05412E: op 0x635C */
    s->r[3] = s->r[5] & 0xFFu;
    /* 0x054130: op 0xD02A */
    s->r[0] = 0x0005D8CAu;
    /* 0x054132: op 0x666D */
    s->r[6] = s->r[6] & 0xFFFFu;
    /* 0x054134: op 0x4308 */
    s->r[3] = (s->r[3] << 2);
    /* 0x054136: mov.w @(r3+r0),r2 (rt-base) */
    uint32_t t4 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)(s->r[3] + s->r[0]);
    s->r[2] = t4;
    /* 0x054138: op 0x622D */
    s->r[2] = s->r[2] & 0xFFFFu;
    /* 0x05413A: op 0x2268 */
    s->T = ((s->r[2] & s->r[6]) == 0u) ? 1u : 0u;
    /* 0x05413C: bf.s 0x054142 */
    /* 0x05413E: op 0x0009 */
    
    if (!s->T) goto L_54142;
    /* 0x054140: op 0x6543 */
    s->r[5] = s->r[4];
    L_54142: ;
    /* 0x054142: rts */
    /* 0x054144: op 0x6053 */
    s->r[0] = s->r[5];
    return;
    L_54104: ;
    /* 0x054104: op 0x7501 */
    s->r[5] = s->r[5] + (uint32_t)(int32_t)(int8_t)0x01;
    return; /* fallthrough */
}
