/* ROM: 60E1D400 | Address: 0x556A8 | Size: 58 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST callee (CFG).
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_3920(ST *s);
void f_3934(ST *s);
void f_556A8(ST *s)
{
    uint32_t local_3fc = 0;
    /* 0x0556A8: sts.l pr,@-r15 */
    local_3fc = s->pr;
    /* 0x0556AA: op 0xD31B */
    s->r[3] = 0x00003920u;
    /* 0x0556AC: jsr @r3 */
    s->pr = 0x000556B0;
    s->r[4] = (uint32_t)(int32_t)(int8_t)0x10;
    f_3920(s);
    /* 0x0556B0: op 0xD21A */
    s->r[2] = 0xFFFF9038u;
    /* 0x0556B2: op 0x6403 */
    s->r[4] = s->r[0];
    /* 0x0556B4: op 0xD71A */
    s->r[7] = 0xFFFF9010u;
    /* 0x0556B6: op 0xE600 */
    s->r[6] = (uint32_t)(int32_t)(int8_t)0x00;
    /* 0x0556B8: mov.b r6,@r2 */
    *(volatile uint8_t*)0xFFFF9038 = s->r[6]; /* RAM 0xFFFF9038 */
    /* 0x0556BA: op 0xE028 */
    s->r[0] = (uint32_t)(int32_t)(int8_t)0x28;
    /* 0x0556BC: op 0x6563 */
    s->r[5] = s->r[6];
    L_556BE: ;
    /* 0x0556BE: op 0x7501 */
    s->r[5] = s->r[5] + (uint32_t)(int32_t)(int8_t)0x01;
    /* 0x0556C0: mov.b r6,@r7 */
    *(volatile uint8_t*)0xFFFF9010 = s->r[6]; /* RAM 0xFFFF9010 */
    /* 0x0556C2: op 0x635C */
    s->r[3] = s->r[5] & 0xFFu;
    /* 0x0556C4: op 0x3303 */
    s->T = ((int32_t)s->r[3] >= (int32_t)s->r[0]) ? 1u : 0u;
    /* 0x0556C6: bf.s 0x0556BE */
    /* 0x0556C8: op 0x7701 */
    s->r[7] = s->r[7] + (uint32_t)(int32_t)(int8_t)0x01;
    if (!s->T) goto L_556BE;
    /* 0x0556CA: op 0xD616 */
    s->r[6] = 0xFFFF9039u;
    /* 0x0556CC: op 0xD217 */
    s->r[2] = 0xFFFF903Au;
    /* 0x0556CE: mov.b r5,@r6 */
    *(volatile uint8_t*)s->r[6] = s->r[5]; /* RAM 0xFFFF9039 */
    /* 0x0556D0: mov.b @r6,r3 */
    uint32_t t2 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)s->r[6]; /* RAM 0xFFFF9039 */
    s->r[3] = t2;
    /* 0x0556D2: op 0x633C */
    s->r[3] = s->r[3] & 0xFFu;
    /* 0x0556D4: mov.w r3,@r2 */
    *(volatile uint16_t*)s->r[2] = s->r[3]; /* RAM 0xFFFF903A */
    /* 0x0556D6: op 0x911D */
    s->r[1] = (uint32_t)(int32_t)(int16_t)0xA5u;
    /* 0x0556D8: op 0xD010 */
    s->r[0] = 0xFFFF9038u;
    /* 0x0556DA: mov.b r1,@r0 */
    *(volatile uint8_t*)s->r[0] = s->r[1]; /* RAM 0xFFFF9038 */
    /* 0x0556DC: op 0xD314 */
    s->r[3] = 0x00003934u;
    /* 0x0556DE: jmp @r3 (tail) */
    s->pr = local_3fc;
    f_3934(s);
    return;
    return; /* fallthrough */
}
