/* ROM: 60E1D400 | Address: 0x55FA6 | Size: 20 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v7.py — ST (shared state) ABI,
 * leaf callee library (c/lib/f_<hex>.c). Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_55FA6(ST *s)
{
    /* 0x055FA6: op 0x9371 */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0x0000A9E4u;
    /* 0x055FA8: mov.b @r3,r0 */
    uint32_t t2 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFA9E4; /* RAM 0xFFFFA9E4 */
    s->r[0] = t2;
    /* 0x055FAA: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x055FAC: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x055FAE: bf.s 0x055FB6 */
    /* 0x055FB0: op 0x0009 */
    
    if (!s->T) goto L_55FB6;
    /* 0x055FB2: bra 0x055FB8 */
    /* 0x055FB4: op 0xE401 */
    s->r[4] = (uint32_t)(int32_t)(int8_t)0x01;
    goto L_55FB8;
    L_55FB6: ;
    /* 0x055FB6: op 0xE404 */
    s->r[4] = (uint32_t)(int32_t)(int8_t)0x04;
    L_55FB8: ;
    /* 0x055FB8: rts */
    /* 0x055FBA: op 0x6043 */
    s->r[0] = s->r[4];
    return;
    return; /* fallthrough */
}
