/* ROM: 60E0FC00 | Address: 0x55152 | Size: 50 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST callee (CFG).
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_24C0(ST *s);
void f_52970(ST *s);
void f_55ECC(ST *s);
void f_55152(ST *s)
{
    uint32_t local_3f4 = 0;
    uint32_t local_3f8 = 0;
    uint32_t local_3fc = 0;
    uint32_t fr0 = 0;
    uint32_t fr15 = 0;
    uint32_t fr4 = 0;
    uint32_t fr5 = 0;
    uint32_t fr6 = 0;
    /* 0x055152: fmov.s fr15,@-r15 (rt-base) */
    s->r[15] -= 4;
    *(volatile uint32_t*)s->r[15] = fr15;
    /* 0x055154: op 0x936C */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0x0000ADC0u;
    /* 0x055156: fldi0 fr15 */
    fr15 = 0u;
    /* 0x055158: op 0xC738 */
    s->r[0] = 0x0005523Cu;
    /* 0x05515A: fmov fr15,fr5 */
    fr5 = fr15;
    /* 0x05515C: op 0xD238 */
    s->r[2] = 0x000024C0u;
    /* 0x05515E: sts.l pr,@-r15 */
    local_3fc = s->pr;
    /* 0x055160: op 0x7FF8 */
    s->r[15] = s->r[15] + (uint32_t)(int32_t)(int8_t)0xF8;
    /* 0x055162: mov.b r4,@r15 */
    local_3f4 = s->r[4];
    /* 0x055164: mov.w @r3,r4 */
    uint32_t t2 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)0xFFFFADC0; /* RAM 0xFFFFADC0 */
    s->r[4] = t2;
    /* 0x055166: jsr @r2 */
    s->pr = 0x0005516A;
    fr4 = *(volatile uint32_t*)0x0005523C; /* ROM */
    f_24C0(s);
    /* 0x05516A: fmov fr0,fr4 */
    fr4 = fr0;
    /* 0x05516C: op 0xC735 */
    s->r[0] = 0x00055244u;
    /* 0x05516E: fmov fr15,fr6 */
    fr6 = fr15;
    /* 0x055170: op 0xD335 */
    s->r[3] = 0x00052970u;
    /* 0x055172: jsr @r3 */
    s->pr = 0x00055176;
    fr5 = *(volatile uint32_t*)0x00055244; /* ROM */
    f_52970(s);
    /* 0x055176: op 0x6503 */
    s->r[5] = s->r[0];
    /* 0x055178: mov.w r0,@(0x4,r15) */
    local_3f8 = s->r[0];
    /* 0x05517A: mov.b @r15,r4 */
    s->r[4] = (uint32_t)(int32_t)(int8_t)(local_3f4 & 0xFFu);
    /* 0x05517C: op 0x7F08 */
    s->r[15] = s->r[15] + (uint32_t)(int32_t)(int8_t)0x08;
    /* 0x05517E: lds.l @r15+,pr */
    s->pr = local_3fc;
    /* 0x055180: bra 0x055ECC (tail) */
    fr15 = *(volatile uint32_t*)s->r[15];
    s->r[15] = s->r[15] + 4;
     { f_55ECC(s); return; }
    return; /* fallthrough */
}
