/* ROM: 60E0FC00 | Address: 0x55C14 | Size: 272 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST callee (CFG).
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_52A5A(ST *s);
void f_55D24(ST *s);
void f_66AAA(ST *s);
void f_55C14(ST *s)
{
    uint32_t local_3e0 = 0;
    uint32_t local_3e4 = 0;
    uint32_t local_3e8 = 0;
    uint32_t local_3ec = 0;
    uint32_t local_3f0 = 0;
    uint32_t local_3f4 = 0;
    uint32_t local_3f8 = 0;
    uint32_t local_3fc = 0;
    /* 0x055C14: mov.l r14,@-r15 */
    local_3fc = s->r[14];
    /* 0x055C16: op 0xE400 */
    s->r[4] = (uint32_t)(int32_t)(int8_t)0x00;
    /* 0x055C18: mov.l r13,@-r15 */
    local_3f8 = s->r[13];
    /* 0x055C1A: op 0x6E43 */
    s->r[14] = s->r[4];
    /* 0x055C1C: mov.l r12,@-r15 */
    local_3f4 = s->r[12];
    /* 0x055C1E: mov.l r11,@-r15 */
    local_3f0 = s->r[11];
    /* 0x055C20: mov.l r10,@-r15 */
    local_3ec = s->r[10];
    /* 0x055C22: mov.l r9,@-r15 */
    local_3e8 = s->r[9];
    /* 0x055C24: mov.l r8,@-r15 */
    local_3e4 = s->r[8];
    /* 0x055C26: op 0xE801 */
    s->r[8] = (uint32_t)(int32_t)(int8_t)0x01;
    /* 0x055C28: op 0xDA29 */
    s->r[10] = 0x00052A5Au;
    /* 0x055C2A: sts.l pr,@-r15 */
    local_3e0 = s->pr;
    /* 0x055C2C: op 0x9C48 */
    s->r[12] = (uint32_t)(int32_t)(int16_t)0x0000CFFCu;
    /* 0x055C2E: op 0xDD29 */
    s->r[13] = 0x0005D994u;
    /* 0x055C30: bra 0x055CEA */
    /* 0x055C32: op 0x6943 */
    s->r[9] = s->r[4];
    goto L_55CEA;
    L_55CEA: ;
    /* 0x055CEA: op 0x62EC */
    s->r[2] = s->r[14] & 0xFFu;
    /* 0x055CEC: op 0xD145 */
    s->r[1] = 0x0005DEBCu;
    /* 0x055CEE: mov.b @r1,r3 */
    uint32_t t2 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0x0005DEBC; /* ROM */
    s->r[3] = t2;
    /* 0x055CF0: op 0x633C */
    s->r[3] = s->r[3] & 0xFFu;
    /* 0x055CF2: op 0x3233 */
    s->T = ((int32_t)s->r[2] >= (int32_t)s->r[3]) ? 1u : 0u;
    /* 0x055CF4: bt.s 0x055D00 */
    /* 0x055CF6: op 0x0009 */
    
    if (s->T) goto L_55D00;
    /* 0x055CF8: op 0x629C */
    s->r[2] = s->r[9] & 0xFFu;
    /* 0x055CFA: op 0x2228 */
    s->T = ((s->r[2] & s->r[2]) == 0u) ? 1u : 0u;
    /* 0x055CFC: bt.s 0x055C34 */
    /* 0x055CFE: op 0x0009 */
    
    if (s->T) goto L_55C34;
    L_55D00: ;
    /* 0x055D00: op 0x699C */
    s->r[9] = s->r[9] & 0xFFu;
    /* 0x055D02: op 0x2998 */
    s->T = ((s->r[9] & s->r[9]) == 0u) ? 1u : 0u;
    /* 0x055D04: bf.s 0x055D10 */
    /* 0x055D06: op 0x0009 */
    
    if (!s->T) goto L_55D10;
    /* 0x055D08: op 0xE531 */
    s->r[5] = (uint32_t)(int32_t)(int8_t)0x31;
    /* 0x055D0A: jsr @r10 */
    s->pr = 0x00055D0E;
    s->r[4] = (uint32_t)(int32_t)(int8_t)0x22;
    f_52A5A(s);
    /* 0x055D0E: op 0x6B03 */
    s->r[11] = s->r[0];
    L_55D10: ;
    /* 0x055D10: lds.l @r15+,pr */
    s->pr = local_3e0;
    /* 0x055D12: op 0x60B3 */
    s->r[0] = s->r[11];
    /* 0x055D14: mov.l @r15+,r8 */
    s->r[8] = local_3e4;
    /* 0x055D16: mov.l @r15+,r9 */
    s->r[9] = local_3e8;
    /* 0x055D18: mov.l @r15+,r10 */
    s->r[10] = local_3ec;
    /* 0x055D1A: mov.l @r15+,r11 */
    s->r[11] = local_3f0;
    /* 0x055D1C: mov.l @r15+,r12 */
    s->r[12] = local_3f4;
    /* 0x055D1E: mov.l @r15+,r13 */
    s->r[13] = local_3f8;
    /* 0x055D20: rts */
    /* 0x055D22: mov.l @r15+,r14 */
    s->r[14] = local_3fc;
    return;
    L_55C34: ;
    /* 0x055C34: op 0xD128 */
    s->r[1] = 0xFFFFCFFEu;
    /* 0x055C36: op 0x64EC */
    s->r[4] = s->r[14] & 0xFFu;
    /* 0x055C38: op 0x6343 */
    s->r[3] = s->r[4];
    /* 0x055C3A: op 0x4400 */
    s->T = (s->r[4] >> 31) & 1u; s->r[4] = (s->r[4] << 1);
    /* 0x055C3C: op 0x343C */
    s->r[4] = s->r[4] + s->r[3];
    /* 0x055C3E: op 0x4408 */
    s->r[4] = (s->r[4] << 2);
    /* 0x055C40: mov.w @r1,r3 */
    uint32_t t4 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)s->r[1]; /* RAM 0xFFFFCFFE */
    s->r[3] = t4;
    /* 0x055C42: op 0x34DC */
    s->r[4] = s->r[4] + s->r[13];
    /* 0x055C44: mov.w @r4,r2 */
    uint32_t t6 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)s->r[4];
    s->r[2] = t6;
    /* 0x055C46: op 0x3230 */
    s->T = (s->r[2] == s->r[3]) ? 1u : 0u;
    /* 0x055C48: bf.s 0x055CE8 */
    /* 0x055C4A: op 0x0009 */
    
    if (!s->T) goto L_55CE8;
    /* 0x055C4C: mov.w @(0x4,r4),r0 */
    uint32_t t8 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)(s->r[4] + 4);
    s->r[0] = t8;
    /* 0x055C4E: op 0x9238 */
    s->r[2] = (uint32_t)(int32_t)(int16_t)0x0000D1C8u;
    /* 0x055C50: mov.w @r2,r3 */
    uint32_t t10 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)s->r[2]; /* RAM 0xFFFFD1C8 */
    s->r[3] = t10;
    /* 0x055C52: op 0x2039 */
    s->r[0] &= s->r[3];
    /* 0x055C54: op 0x600D */
    s->r[0] = s->r[0] & 0xFFFFu;
    /* 0x055C56: op 0x2008 */
    s->T = ((s->r[0] & s->r[0]) == 0u) ? 1u : 0u;
    /* 0x055C58: bt.s 0x055CE0 */
    /* 0x055C5A: op 0x6983 */
    s->r[9] = s->r[8];
    if (s->T) goto L_55CE0;
    /* 0x055C5C: mov.b @r12,r1 */
    uint32_t t12 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)s->r[12]; /* RAM 0xFFFFCFFC */
    s->r[1] = t12;
    /* 0x055C5E: op 0x611C */
    s->r[1] = s->r[1] & 0xFFu;
    /* 0x055C60: op 0x9030 */
    s->r[0] = (uint32_t)(int32_t)(int16_t)0x80u;
    /* 0x055C62: op 0x3100 */
    s->T = (s->r[1] == s->r[0]) ? 1u : 0u;
    /* 0x055C64: bt.s 0x055C6C */
    /* 0x055C66: op 0x0009 */
    
    if (s->T) goto L_55C6C;
    /* 0x055C68: bsr 0x55D24 */
    s->pr = 0x00055C6C;
    
    f_55D24(s);
    L_55C6C: ;
    /* 0x055C6C: op 0x63EC */
    s->r[3] = s->r[14] & 0xFFu;
    /* 0x055C6E: op 0x6233 */
    s->r[2] = s->r[3];
    /* 0x055C70: op 0x4300 */
    s->T = (s->r[3] >> 31) & 1u; s->r[3] = (s->r[3] << 1);
    /* 0x055C72: op 0x332C */
    s->r[3] = s->r[3] + s->r[2];
    /* 0x055C74: op 0x4308 */
    s->r[3] = (s->r[3] << 2);
    /* 0x055C76: op 0x33DC */
    s->r[3] = s->r[3] + s->r[13];
    /* 0x055C78: mov.l @r3,r1 (rt-base) */
    uint32_t t13 = *(volatile uint32_t*)(s->r[3] + 8);
    s->r[1] = t13;
    /* 0x055C7A: jsr @r1 (runtime) */
    s->r[4] = (uint32_t)(int32_t)(int8_t)0x22;
    s->pr = 0x00055C7E;
    ((void(*)(ST*))s->r[1])(s);
    /* 0x055C7E: mov.b @r12,r3 */
    uint32_t t15 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)s->r[12]; /* RAM 0xFFFFCFFC */
    s->r[3] = t15;
    /* 0x055C80: op 0x2338 */
    s->T = ((s->r[3] & s->r[3]) == 0u) ? 1u : 0u;
    /* 0x055C82: bf.s 0x055C9C */
    /* 0x055C84: op 0x0009 */
    
    if (!s->T) goto L_55C9C;
    /* 0x055C86: op 0x6BEC */
    s->r[11] = s->r[14] & 0xFFu;
    /* 0x055C88: op 0x63B3 */
    s->r[3] = s->r[11];
    /* 0x055C8A: op 0x4B00 */
    s->T = (s->r[11] >> 31) & 1u; s->r[11] = (s->r[11] << 1);
    /* 0x055C8C: op 0x3B3C */
    s->r[11] = s->r[11] + s->r[3];
    /* 0x055C8E: op 0x4B08 */
    s->r[11] = (s->r[11] << 2);
    /* 0x055C90: op 0x3BDC */
    s->r[11] = s->r[11] + s->r[13];
    /* 0x055C92: mov.b @r11,r0 (rt-base) */
    uint32_t t16 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)(s->r[11] + 2);
    s->r[0] = t16;
    /* 0x055C94: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x055C96: op 0x6B03 */
    s->r[11] = s->r[0];
    /* 0x055C98: bra 0x055CE8 */
    /* 0x055C9A: op 0x7B03 */
    s->r[11] = s->r[11] + (uint32_t)(int32_t)(int8_t)0x03;
    goto L_55CE8;
    L_55CE8: ;
    /* 0x055CE8: op 0x7E01 */
    s->r[14] = s->r[14] + (uint32_t)(int32_t)(int8_t)0x01;
    L_55C9C: ;
    /* 0x055C9C: mov.b @r12,r2 */
    uint32_t t18 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)s->r[12]; /* RAM 0xFFFFCFFC */
    s->r[2] = t18;
    /* 0x055C9E: op 0x622C */
    s->r[2] = s->r[2] & 0xFFu;
    /* 0x055CA0: op 0x9311 */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0xFFu;
    /* 0x055CA2: op 0x3230 */
    s->T = (s->r[2] == s->r[3]) ? 1u : 0u;
    /* 0x055CA4: bf.s 0x055CE8 */
    /* 0x055CA6: op 0x0009 */
    
    if (!s->T) goto L_55CE8;
    /* 0x055CA8: op 0xD10C */
    s->r[1] = 0x00066AAAu;
    /* 0x055CAA: jsr @r1 */
    s->pr = 0x00055CAE;
    s->r[4] = (uint32_t)(int32_t)(int8_t)0x22;
    f_66AAA(s);
    /* 0x055CAE: op 0xE522 */
    s->r[5] = (uint32_t)(int32_t)(int8_t)0x22;
    /* 0x055CB0: jsr @r10 */
    s->pr = 0x00055CB4;
    s->r[4] = s->r[5];
    f_52A5A(s);
    /* 0x055CB4: bra 0x055CE8 */
    /* 0x055CB6: op 0x6B03 */
    s->r[11] = s->r[0];
    goto L_55CE8;
    L_55CE0: ;
    /* 0x055CE0: op 0xE531 */
    s->r[5] = (uint32_t)(int32_t)(int8_t)0x31;
    /* 0x055CE2: jsr @r10 */
    s->pr = 0x00055CE6;
    s->r[4] = (uint32_t)(int32_t)(int8_t)0x22;
    f_52A5A(s);
    /* 0x055CE6: op 0x6B03 */
    s->r[11] = s->r[0];
    return; /* fallthrough */
}
