/* ROM: 60E0FC00 | Address: 0x57134 | Size: 60 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST callee (CFG).
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_577E8(ST *s);
void f_57134(ST *s)
{
    /* 0x057134: op 0xD40D */
    s->r[4] = 0xFFFF90DCu;
    /* 0x057136: bra 0x0577E8 (tail) */
    
     { f_577E8(s); return; }
    return; /* fallthrough */
}
