/* ROM: 60E0FC00 | Address: 0x57AD0 | Size: 110 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST callee (CFG).
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_57AD0(ST *s)
{
    /* 0x057AD0: op 0x9339 */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0x0000D064u;
    /* 0x057AD2: op 0x664C */
    s->r[6] = s->r[4] & 0xFFu;
    /* 0x057AD4: op 0x973C */
    s->r[7] = (uint32_t)(int32_t)(int16_t)0x0000D068u;
    /* 0x057AD6: op 0x6063 */
    s->r[0] = s->r[6];
    /* 0x057AD8: mov.b r4,@r3 */
    *(volatile uint8_t*)0xFFFFD064 = s->r[4]; /* RAM 0xFFFFD064 */
    /* 0x057ADA: op 0x8802 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x02) ? 1u : 0u;
    /* 0x057ADC: bf.s 0x057AE8 */
    /* 0x057ADE: op 0xE501 */
    s->r[5] = (uint32_t)(int32_t)(int8_t)0x01;
    if (!s->T) goto L_57AE8;
    /* 0x057AE0: mov.b r5,@r7 */
    *(volatile uint8_t*)0xFFFFD068 = s->r[5]; /* RAM 0xFFFFD068 */
    /* 0x057AE2: op 0x9131 */
    s->r[1] = (uint32_t)(int32_t)(int16_t)0x0000D075u;
    /* 0x057AE4: bra 0x057B0A */
    /* 0x057AE6: mov.b r5,@r1 */
    *(volatile uint8_t*)0xFFFFD075 = s->r[5]; /* RAM 0xFFFFD075 */
    goto L_57B0A;
    L_57B0A: ;
    /* 0x057B0A: mov.b @r7,r0 */
    uint32_t t2 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)s->r[7]; /* RAM 0xFFFFD068 */
    s->r[0] = t2;
    /* 0x057B0C: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x057B0E: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x057B10: bt.s 0x057B2C */
    /* 0x057B12: op 0x0009 */
    
    if (s->T) goto L_57B2C;
    /* 0x057B14: op 0x931D */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0x0000D069u;
    /* 0x057B16: mov.b @r3,r0 */
    uint32_t t4 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)s->r[3]; /* RAM 0xFFFFD069 */
    s->r[0] = t4;
    /* 0x057B18: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x057B1A: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x057B1C: bt.s 0x057B2C */
    /* 0x057B1E: op 0x0009 */
    
    if (s->T) goto L_57B2C;
    /* 0x057B20: op 0x9218 */
    s->r[2] = (uint32_t)(int32_t)(int16_t)0x0000D06Au;
    /* 0x057B22: mov.b @r2,r0 */
    uint32_t t6 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFD06A; /* RAM 0xFFFFD06A */
    s->r[0] = t6;
    /* 0x057B24: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x057B26: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x057B28: bf.s 0x057B3A */
    /* 0x057B2A: op 0x0009 */
    
    if (!s->T) goto L_57B3A;
    L_57B2C: ;
    /* 0x057B2C: op 0x9313 */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0x0000D06Eu;
    /* 0x057B2E: op 0xE200 */
    s->r[2] = (uint32_t)(int32_t)(int8_t)0x00;
    /* 0x057B30: op 0x9112 */
    s->r[1] = (uint32_t)(int32_t)(int16_t)0x0000D06Fu;
    /* 0x057B32: mov.b r5,@r3 */
    *(volatile uint8_t*)s->r[3] = s->r[5]; /* RAM 0xFFFFD06E */
    /* 0x057B34: mov.b r2,@r1 */
    *(volatile uint8_t*)s->r[1] = s->r[2]; /* RAM 0xFFFFD06F */
    /* 0x057B36: op 0x9010 */
    s->r[0] = (uint32_t)(int32_t)(int16_t)0x0000D070u;
    /* 0x057B38: mov.b r5,@r0 */
    *(volatile uint8_t*)0xFFFFD070 = s->r[5]; /* RAM 0xFFFFD070 */
    L_57B3A: ;
    /* 0x057B3A: rts */
    /* 0x057B3C: op 0x0009 */
    
    return;
    L_57AE8: ;
    /* 0x057AE8: op 0x902F */
    s->r[0] = (uint32_t)(int32_t)(int16_t)0x82u;
    /* 0x057AEA: op 0x3600 */
    s->T = (s->r[6] == s->r[0]) ? 1u : 0u;
    /* 0x057AEC: bf.s 0x057AFA */
    /* 0x057AEE: op 0x0009 */
    
    if (!s->T) goto L_57AFA;
    /* 0x057AF0: op 0x912F */
    s->r[1] = (uint32_t)(int32_t)(int16_t)0x0000D069u;
    /* 0x057AF2: mov.b r5,@r1 */
    *(volatile uint8_t*)s->r[1] = s->r[5]; /* RAM 0xFFFFD069 */
    /* 0x057AF4: op 0x932A */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0x0000D07Au;
    /* 0x057AF6: bra 0x057B0A */
    /* 0x057AF8: mov.b r5,@r3 */
    *(volatile uint8_t*)s->r[3] = s->r[5]; /* RAM 0xFFFFD07A */
    goto L_57B0A;
    L_57AFA: ;
    /* 0x057AFA: op 0x6063 */
    s->r[0] = s->r[6];
    /* 0x057AFC: op 0x880F */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x0F) ? 1u : 0u;
    /* 0x057AFE: bf.s 0x057B0A */
    /* 0x057B00: op 0x0009 */
    
    if (!s->T) goto L_57B0A;
    /* 0x057B02: op 0x9227 */
    s->r[2] = (uint32_t)(int32_t)(int16_t)0x0000D06Au;
    /* 0x057B04: op 0x9123 */
    s->r[1] = (uint32_t)(int32_t)(int16_t)0x0000D083u;
    /* 0x057B06: mov.b r5,@r2 */
    *(volatile uint8_t*)s->r[2] = s->r[5]; /* RAM 0xFFFFD06A */
    /* 0x057B08: mov.b r5,@r1 */
    *(volatile uint8_t*)s->r[1] = s->r[5]; /* RAM 0xFFFFD083 */
    return; /* fallthrough */
}
