/* ROM: 60E0FC00 | Address: 0x5991E | Size: 10 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v7.py — ST (shared state) ABI,
 * leaf callee library (c/lib/f_<hex>.c). Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_5991E(ST *s)
{
    /* 0x05991E: op 0xE400 */
    s->r[4] = (uint32_t)(int32_t)(int8_t)0x00;
    /* 0x059920: op 0xD315 */
    s->r[3] = 0xFFFFD0F8u;
    /* 0x059922: mov.b r4,@r3 */
    *(volatile uint8_t*)0xFFFFD0F8 = s->r[4]; /* RAM 0xFFFFD0F8 */
    /* 0x059924: op 0xD215 */
    s->r[2] = 0xFFFFD0FAu;
    /* 0x059926: rts */
    /* 0x059928: mov.w r4,@r2 */
    *(volatile uint16_t*)0xFFFFD0FA = s->r[4]; /* RAM 0xFFFFD0FA */
    return;
    return; /* fallthrough */
}
