/* ROM: 60E0FC00 | Address: 0x5A9F4 | Size: 224 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST callee (CFG).
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_5A9F4(ST *s)
{
    uint32_t local_3f4 = 0;
    uint32_t local_3f8 = 0;
    uint32_t local_3fc = 0;
    /* 0x05A9F4: mov.l r14,@-r15 */
    local_3fc = s->r[14];
    /* 0x05A9F6: op 0xEE01 */
    s->r[14] = (uint32_t)(int32_t)(int8_t)0x01;
    /* 0x05A9F8: op 0xD62F */
    s->r[6] = 0x0005E054u;
    /* 0x05A9FA: mov.l r13,@-r15 */
    local_3f8 = s->r[13];
    /* 0x05A9FC: op 0xD32D */
    s->r[3] = 0xFFFFD12Du;
    /* 0x05A9FE: op 0x7FFC */
    s->r[15] = s->r[15] + (uint32_t)(int32_t)(int8_t)0xFC;
    /* 0x05AA00: mov.b @r3,r5 */
    uint32_t t2 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFD12D; /* RAM 0xFFFFD12D */
    s->r[5] = t2;
    /* 0x05AA02: op 0x625C */
    s->r[2] = s->r[5] & 0xFFu;
    /* 0x05AA04: op 0x2228 */
    s->T = ((s->r[2] & s->r[2]) == 0u) ? 1u : 0u;
    /* 0x05AA06: bf.s 0x05AA62 */
    /* 0x05AA08: op 0xE700 */
    s->r[7] = (uint32_t)(int32_t)(int8_t)0x00;
    if (!s->T) goto L_5AA62;
    /* 0x05AA0A: mov.b @(0x8,r6),r0 */
    uint32_t t4 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0x0005E05C; /* ROM */
    s->r[0] = t4;
    /* 0x05AA0C: op 0x924F */
    s->r[2] = (uint32_t)(int32_t)(int16_t)0x0000D180u;
    /* 0x05AA0E: mov.b @r2,r13 */
    uint32_t t6 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFD180; /* RAM 0xFFFFD180 */
    s->r[13] = t6;
    /* 0x05AA10: op 0xD32B */
    s->r[3] = 0x0000E906u;
    /* 0x05AA12: op 0x2D09 */
    s->r[13] &= s->r[0];
    /* 0x05AA14: op 0xD029 */
    s->r[0] = 0xFFFFD128u;
    /* 0x05AA16: mov.w @r0,r1 */
    uint32_t t8 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)0xFFFFD128; /* RAM 0xFFFFD128 */
    s->r[1] = t8;
    /* 0x05AA18: op 0x611D */
    s->r[1] = s->r[1] & 0xFFFFu;
    /* 0x05AA1A: op 0x3130 */
    s->T = (s->r[1] == s->r[3]) ? 1u : 0u;
    /* 0x05AA1C: bf.s 0x05AA52 */
    /* 0x05AA1E: op 0x0009 */
    
    if (!s->T) goto L_5AA52;
    /* 0x05AA20: op 0x6DDC */
    s->r[13] = s->r[13] & 0xFFu;
    /* 0x05AA22: op 0x2DD8 */
    s->T = ((s->r[13] & s->r[13]) == 0u) ? 1u : 0u;
    /* 0x05AA24: bt.s 0x05AA4A */
    /* 0x05AA26: op 0x0009 */
    
    if (s->T) goto L_5AA4A;
    /* 0x05AA28: mov.l @(0xC,r6),r2 */
    uint32_t t10 = *(volatile uint32_t*)0x0005E060; /* ROM */
    s->r[2] = t10;
    /* 0x05AA2A: op 0xD326 */
    s->r[3] = 0xFFFFD12Cu;
    /* 0x05AA2C: mov.b @r3,r1 */
    uint32_t t12 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)s->r[3]; /* RAM 0xFFFFD12C */
    s->r[1] = t12;
    /* 0x05AA2E: mov.b r1,@r2 (rt-base) */
    *(volatile uint8_t*)s->r[2] = s->r[1];
    /* 0x05AA30: mov.b @r3,r0 */
    uint32_t t14 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)s->r[3]; /* RAM 0xFFFFD12C */
    s->r[0] = t14;
    /* 0x05AA32: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x05AA34: op 0x8807 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x07) ? 1u : 0u;
    /* 0x05AA36: bf.s 0x05AA5E */
    /* 0x05AA38: op 0x65E3 */
    s->r[5] = s->r[14];
    if (!s->T) goto L_5AA5E;
    /* 0x05AA3A: op 0xD123 */
    s->r[1] = 0xFFFFD14Du;
    /* 0x05AA3C: op 0xD023 */
    s->r[0] = 0xFFFFD12Au;
    /* 0x05AA3E: mov.w @r0,r2 */
    uint32_t t16 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)s->r[0]; /* RAM 0xFFFFD12A */
    s->r[2] = t16;
    /* 0x05AA40: op 0x622D */
    s->r[2] = s->r[2] & 0xFFFFu;
    /* 0x05AA42: op 0x4219 */
    s->r[2] = (s->r[2] >> 8);
    /* 0x05AA44: mov.b r2,@r1 */
    *(volatile uint8_t*)0xFFFFD14D = s->r[2]; /* RAM 0xFFFFD14D */
    /* 0x05AA46: bra 0x05AA5E */
    /* 0x05AA48: op 0x0009 */
    
    goto L_5AA5E;
    L_5AA5E: ;
    /* 0x05AA5E: op 0xD315 */
    s->r[3] = 0xFFFFD12Du;
    /* 0x05AA60: mov.b r5,@r3 */
    *(volatile uint8_t*)s->r[3] = s->r[5]; /* RAM 0xFFFFD12D */
    L_5AA62: ;
    /* 0x05AA62: op 0xD215 */
    s->r[2] = 0x0005E054u;
    /* 0x05AA64: op 0xD61A */
    s->r[6] = 0xFFFFD149u;
    /* 0x05AA66: mov.l @(0xC,r2),r3 */
    uint32_t t18 = *(volatile uint32_t*)(s->r[2] + 12); /* ROM */
    s->r[3] = t18;
    /* 0x05AA68: mov.b @r3,r1 (rt-base) */
    uint32_t t19 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)s->r[3];
    s->r[1] = t19;
    /* 0x05AA6A: mov.b r1,@r15 */
    local_3f4 = s->r[1];
    /* 0x05AA6C: mov.b @r15,r13 */
    s->r[13] = (uint32_t)(int32_t)(int8_t)(local_3f4 & 0xFFu);
    /* 0x05AA6E: op 0x6DDC */
    s->r[13] = s->r[13] & 0xFFu;
    /* 0x05AA70: op 0x2DD8 */
    s->T = ((s->r[13] & s->r[13]) == 0u) ? 1u : 0u;
    /* 0x05AA72: bf.s 0x05AA86 */
    /* 0x05AA74: op 0x6543 */
    s->r[5] = s->r[4];
    if (!s->T) goto L_5AA86;
    /* 0x05AA76: op 0x604C */
    s->r[0] = s->r[4] & 0xFFu;
    /* 0x05AA78: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x05AA7A: bf.s 0x05AA80 */
    /* 0x05AA7C: op 0x0009 */
    
    if (!s->T) goto L_5AA80;
    /* 0x05AA7E: op 0x67E3 */
    s->r[7] = s->r[14];
    L_5AA80: ;
    /* 0x05AA80: op 0x6073 */
    s->r[0] = s->r[7];
    /* 0x05AA82: bra 0x05AAA4 */
    /* 0x05AA84: mov.b r0,@(0x4,r6) */
    *(volatile uint8_t*)(s->r[6] + 4) = s->r[0]; /* RAM 0xFFFFD14D */
    goto L_5AAA4;
    L_5AAA4: ;
    /* 0x05AAA4: op 0x6053 */
    s->r[0] = s->r[5];
    /* 0x05AAA6: op 0x7F04 */
    s->r[15] = s->r[15] + (uint32_t)(int32_t)(int8_t)0x04;
    /* 0x05AAA8: mov.l @r15+,r13 */
    s->r[13] = local_3f8;
    /* 0x05AAAA: rts */
    /* 0x05AAAC: mov.l @r15+,r14 */
    s->r[14] = local_3fc;
    return;
    L_5AA86: ;
    /* 0x05AA86: op 0x60D3 */
    s->r[0] = s->r[13];
    /* 0x05AA88: op 0x8805 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x05) ? 1u : 0u;
    /* 0x05AA8A: bt.s 0x05AA96 */
    /* 0x05AA8C: op 0x0009 */
    
    if (s->T) goto L_5AA96;
    /* 0x05AA8E: op 0x60D3 */
    s->r[0] = s->r[13];
    /* 0x05AA90: op 0x8807 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x07) ? 1u : 0u;
    /* 0x05AA92: bf.s 0x05AAA4 */
    /* 0x05AA94: op 0x0009 */
    
    if (!s->T) goto L_5AAA4;
    L_5AA96: ;
    /* 0x05AA96: mov.b @(0x4,r6),r0 */
    uint32_t t21 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)(s->r[6] + 4); /* RAM 0xFFFFD14D */
    s->r[0] = t21;
    /* 0x05AA98: op 0x6403 */
    s->r[4] = s->r[0];
    /* 0x05AA9A: op 0x604C */
    s->r[0] = s->r[4] & 0xFFu;
    /* 0x05AA9C: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x05AA9E: bf.s 0x05AAA4 */
    /* 0x05AAA0: op 0x6573 */
    s->r[5] = s->r[7];
    if (!s->T) goto L_5AAA4;
    /* 0x05AAA2: op 0x65E3 */
    s->r[5] = s->r[14];
    L_5AA4A: ;
    /* 0x05AA4A: op 0xE502 */
    s->r[5] = (uint32_t)(int32_t)(int8_t)0x02;
    /* 0x05AA4C: mov.l @(0xC,r6),r2 */
    uint32_t t23 = *(volatile uint32_t*)(s->r[6] + 12); /* ROM */
    s->r[2] = t23;
    /* 0x05AA4E: bra 0x05AA5E */
    /* 0x05AA50: mov.b r7,@r2 (rt-base) */
    *(volatile uint8_t*)s->r[2] = s->r[7];
    goto L_5AA5E;
    L_5AA52: ;
    /* 0x05AA52: op 0x6DDC */
    s->r[13] = s->r[13] & 0xFFu;
    /* 0x05AA54: op 0x2DD8 */
    s->T = ((s->r[13] & s->r[13]) == 0u) ? 1u : 0u;
    /* 0x05AA56: bf.s 0x05AA5E */
    /* 0x05AA58: op 0x0009 */
    
    if (!s->T) goto L_5AA5E;
    /* 0x05AA5A: mov.l @(0xC,r6),r1 */
    uint32_t t25 = *(volatile uint32_t*)(s->r[6] + 12); /* ROM */
    s->r[1] = t25;
    /* 0x05AA5C: mov.b r7,@r1 (rt-base) */
    *(volatile uint8_t*)s->r[1] = s->r[7];
    return; /* fallthrough */
}
