/* ROM: 60E0FC00 | Address: 0x5A740 | Size: 76 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST callee (CFG).
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_5A740(ST *s)
{
    /* 0x05A740: op 0xD411 */
    s->r[4] = 0x0005E034u;
    /* 0x05A742: op 0xE600 */
    s->r[6] = (uint32_t)(int32_t)(int8_t)0x00;
    /* 0x05A744: op 0x6563 */
    s->r[5] = s->r[6];
    /* 0x05A746: op 0xE71A */
    s->r[7] = (uint32_t)(int32_t)(int8_t)0x1A;
    L_5A748: ;
    /* 0x05A748: mov.l @(0xC,r4),r3 */
    uint32_t t2 = *(volatile uint32_t*)(s->r[4] + 12); /* ROM */
    s->r[3] = t2;
    /* 0x05A74A: op 0x7501 */
    s->r[5] = s->r[5] + (uint32_t)(int32_t)(int8_t)0x01;
    /* 0x05A74C: mov.b r6,@r3 (rt-base) */
    *(volatile uint8_t*)s->r[3] = s->r[6];
    /* 0x05A74E: op 0x625C */
    s->r[2] = s->r[5] & 0xFFu;
    /* 0x05A750: op 0x3273 */
    s->T = ((int32_t)s->r[2] >= (int32_t)s->r[7]) ? 1u : 0u;
    /* 0x05A752: bf.s 0x05A748 */
    /* 0x05A754: op 0x7410 */
    s->r[4] = s->r[4] + (uint32_t)(int32_t)(int8_t)0x10;
    if (!s->T) goto L_5A748;
    /* 0x05A756: rts */
    /* 0x05A758: op 0x0009 */
    
    return;
    return; /* fallthrough */
}
