/* ROM: 60E0FC00 | Address: 0x5A65C | Size: 228 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST callee (CFG).
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_3920(ST *s);
void f_3934(ST *s);
void f_52A12(ST *s);
void f_52A5A(ST *s);
void f_66A14(ST *s);
void f_5A65C(ST *s)
{
    uint32_t local_3d4 = 0;
    uint32_t local_3d8 = 0;
    uint32_t local_3e4 = 0;
    uint32_t local_3e8 = 0;
    uint32_t local_3ec = 0;
    uint32_t local_3f0 = 0;
    uint32_t local_3f4 = 0;
    uint32_t local_3f8 = 0;
    uint32_t local_3fc = 0;
    /* 0x05A65C: mov.l r14,@-r15 */
    local_3fc = s->r[14];
    /* 0x05A65E: mov.l r13,@-r15 */
    local_3f8 = s->r[13];
    /* 0x05A660: mov.l r12,@-r15 */
    local_3f4 = s->r[12];
    /* 0x05A662: mov.l r11,@-r15 */
    local_3f0 = s->r[11];
    /* 0x05A664: mov.l r10,@-r15 */
    local_3ec = s->r[10];
    /* 0x05A666: mov.l r9,@-r15 */
    local_3e8 = s->r[9];
    /* 0x05A668: sts.l pr,@-r15 */
    local_3e4 = s->pr;
    /* 0x05A66A: op 0x7FF0 */
    s->r[15] = s->r[15] + (uint32_t)(int32_t)(int8_t)0xF0;
    /* 0x05A66C: op 0xD33B */
    s->r[3] = 0x00003920u;
    /* 0x05A66E: jsr @r3 */
    s->pr = 0x0005A672;
    s->r[4] = (uint32_t)(int32_t)(int8_t)0x10;
    f_3920(s);
    /* 0x05A672: mov.l r0,@r15 */
    local_3d4 = s->r[0];
    /* 0x05A674: op 0xDE3A */
    s->r[14] = 0xFFFFD128u;
    /* 0x05A676: mov.w @r14,r9 */
    uint32_t t2 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)0xFFFFD128; /* RAM 0xFFFFD128 */
    s->r[9] = t2;
    /* 0x05A678: op 0xDC3A */
    s->r[12] = 0xFFFFD12Du;
    /* 0x05A67A: mov.b @r12,r0 */
    uint32_t t4 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFD12D; /* RAM 0xFFFFD12D */
    s->r[0] = t4;
    /* 0x05A67C: op 0xD33A */
    s->r[3] = 0xFFFFD12Eu;
    /* 0x05A67E: mov.b r0,@(0x4,r15) */
    local_3d8 = s->r[0];
    /* 0x05A680: mov.b @r3,r13 */
    uint32_t t6 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)s->r[3]; /* RAM 0xFFFFD12E */
    s->r[13] = t6;
    /* 0x05A682: op 0x6ADC */
    s->r[10] = s->r[13] & 0xFFu;
    /* 0x05A684: op 0xD039 */
    s->r[0] = 0x0005E040u;
    /* 0x05A686: op 0x64DC */
    s->r[4] = s->r[13] & 0xFFu;
    /* 0x05A688: op 0xD239 */
    s->r[2] = 0xFFFFD149u;
    /* 0x05A68A: op 0x4A08 */
    s->r[10] = (s->r[10] << 2);
    /* 0x05A68C: op 0xD339 */
    s->r[3] = 0x00003934u;
    /* 0x05A68E: op 0x4400 */
    s->T = (s->r[4] >> 31) & 1u; s->r[4] = (s->r[4] << 1);
    /* 0x05A690: op 0x4A08 */
    s->r[10] = (s->r[10] << 2);
    /* 0x05A692: op 0x342C */
    s->r[4] = s->r[4] + s->r[2];
    /* 0x05A694: mov.l @(r10+r0),r10 (rt-base) */
    uint32_t t7 = *(volatile uint32_t*)(s->r[10] + s->r[0]);
    s->r[10] = t7;
    /* 0x05A696: mov.b @r10,r10 (rt-base) */
    uint32_t t8 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)s->r[10];
    s->r[10] = t8;
    /* 0x05A698: mov.b @r4,r11 */
    uint32_t t10 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)s->r[4];
    s->r[11] = t10;
    /* 0x05A69A: op 0x6BBC */
    s->r[11] = s->r[11] & 0xFFu;
    /* 0x05A69C: mov.b @(0x1,r4),r0 */
    uint32_t t12 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)(s->r[4] + 1);
    s->r[0] = t12;
    /* 0x05A69E: op 0x4B18 */
    s->r[11] = (s->r[11] << 8);
    /* 0x05A6A0: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x05A6A2: op 0x2B0B */
    s->r[11] |= s->r[0];
    /* 0x05A6A4: jsr @r3 */
    s->pr = 0x0005A6A8;
    s->r[4] = local_3d4;
    f_3934(s);
    /* 0x05A6A8: mov.b @(0x4,r15),r0 */
    s->r[0] = (uint32_t)(int32_t)(int8_t)(local_3d8 & 0xFFu);
    /* 0x05A6AA: op 0x6503 */
    s->r[5] = s->r[0];
    /* 0x05A6AC: op 0x655C */
    s->r[5] = s->r[5] & 0xFFu;
    /* 0x05A6AE: op 0x6053 */
    s->r[0] = s->r[5];
    /* 0x05A6B0: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x05A6B2: bf.s 0x05A714 */
    /* 0x05A6B4: op 0xE400 */
    s->r[4] = (uint32_t)(int32_t)(int8_t)0x00;
    if (!s->T) goto L_5A714;
    /* 0x05A6B6: op 0x609D */
    s->r[0] = s->r[9] & 0xFFFFu;
    /* 0x05A6B8: mov.w r4,@r14 */
    *(volatile uint16_t*)0xFFFFD128 = s->r[4]; /* RAM 0xFFFFD128 */
    /* 0x05A6BA: op 0x4019 */
    s->r[0] = (s->r[0] >> 8);
    /* 0x05A6BC: mov.b r4,@r12 */
    *(volatile uint8_t*)0xFFFFD12D = s->r[4]; /* RAM 0xFFFFD12D */
    /* 0x05A6BE: mov r15,r14 (frame pointer) */
    s->r[14] = s->r[15];
    /* 0x05A6C0: op 0xE46F */
    s->r[4] = (uint32_t)(int32_t)(int8_t)0x6F;
    /* 0x05A6C2: op 0x7E08 */
    s->r[14] = s->r[14] + (uint32_t)(int32_t)(int8_t)0x08;
    /* 0x05A6C4: mov.b r4,@r14 (rt-base) */
    *(volatile uint8_t*)s->r[14] = s->r[4];
    /* 0x05A6C6: op 0x64AC */
    s->r[4] = s->r[10] & 0xFFu;
    /* 0x05A6C8: mov.b r0,@r14 (rt-base) */
    *(volatile uint8_t*)(s->r[14] + 1) = s->r[0];
    /* 0x05A6CA: op 0x6093 */
    s->r[0] = s->r[9];
    /* 0x05A6CC: mov.b r0,@r14 (rt-base) */
    *(volatile uint8_t*)(s->r[14] + 2) = s->r[0];
    /* 0x05A6CE: op 0x60A3 */
    s->r[0] = s->r[10];
    /* 0x05A6D0: mov.b r0,@r14 (rt-base) */
    *(volatile uint8_t*)(s->r[14] + 3) = s->r[0];
    /* 0x05A6D2: op 0x60BD */
    s->r[0] = s->r[11] & 0xFFFFu;
    /* 0x05A6D4: op 0x4019 */
    s->r[0] = (s->r[0] >> 8);
    /* 0x05A6D6: mov.b r0,@r14 (rt-base) */
    *(volatile uint8_t*)(s->r[14] + 4) = s->r[0];
    /* 0x05A6D8: op 0x60B3 */
    s->r[0] = s->r[11];
    /* 0x05A6DA: mov.b r0,@r14 (rt-base) */
    *(volatile uint8_t*)(s->r[14] + 5) = s->r[0];
    /* 0x05A6DC: op 0x6043 */
    s->r[0] = s->r[4];
    /* 0x05A6DE: op 0x8805 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x05) ? 1u : 0u;
    /* 0x05A6E0: bt.s 0x05A6EC */
    /* 0x05A6E2: op 0x0009 */
    
    if (s->T) goto L_5A6EC;
    /* 0x05A6E4: op 0x6043 */
    s->r[0] = s->r[4];
    /* 0x05A6E6: op 0x8807 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x07) ? 1u : 0u;
    /* 0x05A6E8: bf.s 0x05A6FC */
    /* 0x05A6EA: op 0x0009 */
    
    if (!s->T) goto L_5A6FC;
    L_5A6EC: ;
    /* 0x05A6EC: op 0xD022 */
    s->r[0] = 0x0005E03Fu;
    /* 0x05A6EE: op 0x6CDC */
    s->r[12] = s->r[13] & 0xFFu;
    /* 0x05A6F0: op 0x4C08 */
    s->r[12] = (s->r[12] << 2);
    /* 0x05A6F2: op 0x4C08 */
    s->r[12] = (s->r[12] << 2);
    /* 0x05A6F4: mov.b @(r12+r0),r12 (rt-base) */
    uint32_t t13 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)(s->r[12] + s->r[0]);
    s->r[12] = t13;
    /* 0x05A6F6: op 0x6CCC */
    s->r[12] = s->r[12] & 0xFFu;
    /* 0x05A6F8: bra 0x05A6FE */
    /* 0x05A6FA: op 0x7C04 */
    s->r[12] = s->r[12] + (uint32_t)(int32_t)(int8_t)0x04;
    goto L_5A6FE;
    L_5A6FE: ;
    /* 0x05A6FE: op 0x66C3 */
    s->r[6] = s->r[12];
    /* 0x05A700: op 0xD21E */
    s->r[2] = 0x00066A14u;
    /* 0x05A702: op 0x65E3 */
    s->r[5] = s->r[14];
    /* 0x05A704: jsr @r2 */
    s->pr = 0x0005A708;
    s->r[4] = (uint32_t)(int32_t)(int8_t)0x2F;
    f_66A14(s);
    /* 0x05A708: op 0xD31D */
    s->r[3] = 0x00052A12u;
    /* 0x05A70A: op 0x65C3 */
    s->r[5] = s->r[12];
    /* 0x05A70C: jsr @r3 */
    s->pr = 0x0005A710;
    s->r[4] = (uint32_t)(int32_t)(int8_t)0x2F;
    f_52A12(s);
    /* 0x05A710: bra 0x05A72E */
    /* 0x05A712: op 0x0009 */
    
    goto L_5A72E;
    L_5A72E: ;
    /* 0x05A72E: op 0x7F10 */
    s->r[15] = s->r[15] + (uint32_t)(int32_t)(int8_t)0x10;
    /* 0x05A730: lds.l @r15+,pr */
    s->pr = local_3e4;
    /* 0x05A732: mov.l @r15+,r9 */
    s->r[9] = local_3e8;
    /* 0x05A734: mov.l @r15+,r10 */
    s->r[10] = local_3ec;
    /* 0x05A736: mov.l @r15+,r11 */
    s->r[11] = local_3f0;
    /* 0x05A738: mov.l @r15+,r12 */
    s->r[12] = local_3f4;
    /* 0x05A73A: mov.l @r15+,r13 */
    s->r[13] = local_3f8;
    /* 0x05A73C: rts */
    /* 0x05A73E: mov.l @r15+,r14 */
    s->r[14] = local_3fc;
    return;
    L_5A6FC: ;
    /* 0x05A6FC: op 0xEC04 */
    s->r[12] = (uint32_t)(int32_t)(int8_t)0x04;
    L_5A714: ;
    /* 0x05A714: op 0x8802 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x02) ? 1u : 0u;
    /* 0x05A716: bf.s 0x05A72E */
    /* 0x05A718: op 0x0009 */
    
    if (!s->T) goto L_5A72E;
    /* 0x05A71A: op 0xE522 */
    s->r[5] = (uint32_t)(int32_t)(int8_t)0x22;
    /* 0x05A71C: op 0xD219 */
    s->r[2] = 0x00052A5Au;
    /* 0x05A71E: mov.w r4,@r14 */
    *(volatile uint16_t*)0xFFFFD128 = s->r[4]; /* RAM 0xFFFFD128 */
    /* 0x05A720: mov.b r4,@r12 */
    *(volatile uint8_t*)s->r[12] = s->r[4]; /* RAM 0xFFFFD12D */
    /* 0x05A722: jsr @r2 */
    s->pr = 0x0005A726;
    s->r[4] = (uint32_t)(int32_t)(int8_t)0x2F;
    f_52A5A(s);
    /* 0x05A726: op 0x6503 */
    s->r[5] = s->r[0];
    /* 0x05A728: op 0xD315 */
    s->r[3] = 0x00052A12u;
    /* 0x05A72A: jsr @r3 */
    s->pr = 0x0005A72E;
    s->r[4] = (uint32_t)(int32_t)(int8_t)0x2F;
    f_52A12(s);
    return; /* fallthrough */
}
