/* ROM: 60E1D400 | Address: 0x5AF14 | Size: 184 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v7.py — ST (shared state) ABI,
 * leaf callee library (c/lib/f_<hex>.c). Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_5AF14(ST *s)
{
    uint32_t local_3f4 = 0;
    uint32_t local_3f8 = 0;
    uint32_t local_3fc = 0;
    /* 0x05AF14: mov.l r14,@-r15 */
    local_3fc = s->r[14];
    /* 0x05AF16: op 0xEE01 */
    s->r[14] = (uint32_t)(int32_t)(int8_t)0x01;
    /* 0x05AF18: op 0xD62F */
    s->r[6] = 0x0005E0B4u;
    /* 0x05AF1A: mov.l r13,@-r15 */
    local_3f8 = s->r[13];
    /* 0x05AF1C: op 0xD32D */
    s->r[3] = 0xFFFFD12Du;
    /* 0x05AF1E: op 0x7FFC */
    s->r[15] = s->r[15] + (uint32_t)(int32_t)(int8_t)0xFC;
    /* 0x05AF20: mov.b @r3,r5 */
    uint32_t t2 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFD12D; /* RAM 0xFFFFD12D */
    s->r[5] = t2;
    /* 0x05AF22: op 0x625C */
    s->r[2] = s->r[5] & 0xFFu;
    /* 0x05AF24: op 0x2228 */
    s->T = ((s->r[2] & s->r[2]) == 0u) ? 1u : 0u;
    /* 0x05AF26: bf.s 0x05AF82 */
    /* 0x05AF28: op 0xE700 */
    s->r[7] = (uint32_t)(int32_t)(int8_t)0x00;
    if (!s->T) goto L_5AF82;
    /* 0x05AF2A: mov.b @(0x8,r6),r0 */
    uint32_t t4 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0x0005E0BC; /* ROM */
    s->r[0] = t4;
    /* 0x05AF2C: op 0x924F */
    s->r[2] = (uint32_t)(int32_t)(int16_t)0x0000D180u;
    /* 0x05AF2E: mov.b @r2,r13 */
    uint32_t t6 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFD180; /* RAM 0xFFFFD180 */
    s->r[13] = t6;
    /* 0x05AF30: op 0x934E */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0x000017C3u;
    /* 0x05AF32: op 0x2D09 */
    s->r[13] &= s->r[0];
    /* 0x05AF34: op 0xD029 */
    s->r[0] = 0xFFFFD128u;
    /* 0x05AF36: mov.w @r0,r1 */
    uint32_t t8 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)0xFFFFD128; /* RAM 0xFFFFD128 */
    s->r[1] = t8;
    /* 0x05AF38: op 0x611D */
    s->r[1] = s->r[1] & 0xFFFFu;
    /* 0x05AF3A: op 0x3130 */
    s->T = (s->r[1] == s->r[3]) ? 1u : 0u;
    /* 0x05AF3C: bf.s 0x05AF72 */
    /* 0x05AF3E: op 0x0009 */
    
    if (!s->T) goto L_5AF72;
    /* 0x05AF40: op 0x6DDC */
    s->r[13] = s->r[13] & 0xFFu;
    /* 0x05AF42: op 0x2DD8 */
    s->T = ((s->r[13] & s->r[13]) == 0u) ? 1u : 0u;
    /* 0x05AF44: bt.s 0x05AF6A */
    /* 0x05AF46: op 0x0009 */
    
    if (s->T) goto L_5AF6A;
    /* 0x05AF48: mov.l @(0xC,r6),r2 */
    uint32_t t10 = *(volatile uint32_t*)0x0005E0C0; /* ROM */
    s->r[2] = t10;
    /* 0x05AF4A: op 0xD325 */
    s->r[3] = 0xFFFFD12Cu;
    /* 0x05AF4C: mov.b @r3,r1 */
    uint32_t t12 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFD12C; /* RAM 0xFFFFD12C */
    s->r[1] = t12;
    /* 0x05AF4E: mov.b r1,@r2 */
    *(volatile uint8_t*)s->r[2] = s->r[1]; /* RAM 0xFFFFD137 */
    /* 0x05AF50: mov.b @r3,r0 */
    uint32_t t14 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFD12C; /* RAM 0xFFFFD12C */
    s->r[0] = t14;
    /* 0x05AF52: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x05AF54: op 0x8807 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x07) ? 1u : 0u;
    /* 0x05AF56: bf.s 0x05AF7E */
    /* 0x05AF58: op 0x65E3 */
    s->r[5] = s->r[14];
    if (!s->T) goto L_5AF7E;
    /* 0x05AF5A: op 0xD122 */
    s->r[1] = 0xFFFFD159u;
    /* 0x05AF5C: op 0xD022 */
    s->r[0] = 0xFFFFD12Au;
    /* 0x05AF5E: mov.w @r0,r2 */
    uint32_t t16 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)0xFFFFD12A; /* RAM 0xFFFFD12A */
    s->r[2] = t16;
    /* 0x05AF60: op 0x622D */
    s->r[2] = s->r[2] & 0xFFFFu;
    /* 0x05AF62: op 0x4219 */
    s->r[2] = (s->r[2] >> 8);
    /* 0x05AF64: mov.b r2,@r1 */
    *(volatile uint8_t*)0xFFFFD159 = s->r[2]; /* RAM 0xFFFFD159 */
    /* 0x05AF66: bra 0x05AF7E */
    /* 0x05AF68: op 0x0009 */
    
    goto L_5AF7E;
    L_5AF6A: ;
    /* 0x05AF6A: op 0xE502 */
    s->r[5] = (uint32_t)(int32_t)(int8_t)0x02;
    /* 0x05AF6C: mov.l @(0xC,r6),r2 */
    uint32_t t18 = *(volatile uint32_t*)0x0005E0C0; /* ROM */
    s->r[2] = t18;
    /* 0x05AF6E: bra 0x05AF7E */
    /* 0x05AF70: mov.b r7,@r2 */
    *(volatile uint8_t*)s->r[2] = s->r[7]; /* RAM 0xFFFFD137 */
    goto L_5AF7E;
    L_5AF72: ;
    /* 0x05AF72: op 0x6DDC */
    s->r[13] = s->r[13] & 0xFFu;
    /* 0x05AF74: op 0x2DD8 */
    s->T = ((s->r[13] & s->r[13]) == 0u) ? 1u : 0u;
    /* 0x05AF76: bf.s 0x05AF7E */
    /* 0x05AF78: op 0x0009 */
    
    if (!s->T) goto L_5AF7E;
    /* 0x05AF7A: mov.l @(0xC,r6),r1 */
    uint32_t t20 = *(volatile uint32_t*)0x0005E0C0; /* ROM */
    s->r[1] = t20;
    /* 0x05AF7C: mov.b r7,@r1 */
    *(volatile uint8_t*)s->r[1] = s->r[7]; /* RAM 0xFFFFD137 */
    L_5AF7E: ;
    /* 0x05AF7E: op 0xD315 */
    s->r[3] = 0xFFFFD12Du;
    /* 0x05AF80: mov.b r5,@r3 */
    *(volatile uint8_t*)0xFFFFD12D = s->r[5]; /* RAM 0xFFFFD12D */
    L_5AF82: ;
    /* 0x05AF82: op 0xD215 */
    s->r[2] = 0x0005E0B4u;
    /* 0x05AF84: op 0xD619 */
    s->r[6] = 0xFFFFD149u;
    /* 0x05AF86: mov.l @(0xC,r2),r3 */
    uint32_t t22 = *(volatile uint32_t*)0x0005E0C0; /* ROM */
    s->r[3] = t22;
    /* 0x05AF88: mov.b @r3,r1 */
    uint32_t t24 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)s->r[3]; /* RAM 0xFFFFD137 */
    s->r[1] = t24;
    /* 0x05AF8A: mov.b r1,@r15 */
    local_3f4 = s->r[1];
    /* 0x05AF8C: mov.b @r15,r13 */
    s->r[13] = (uint32_t)(int32_t)(int8_t)(local_3f4 & 0xFFu);
    /* 0x05AF8E: op 0x6DDC */
    s->r[13] = s->r[13] & 0xFFu;
    /* 0x05AF90: op 0x2DD8 */
    s->T = ((s->r[13] & s->r[13]) == 0u) ? 1u : 0u;
    /* 0x05AF92: bf.s 0x05AFA4 */
    /* 0x05AF94: op 0x6543 */
    s->r[5] = s->r[4];
    if (!s->T) goto L_5AFA4;
    /* 0x05AF96: op 0x604C */
    s->r[0] = s->r[4] & 0xFFu;
    /* 0x05AF98: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x05AF9A: bf.s 0x05AFA0 */
    /* 0x05AF9C: op 0x7610 */
    s->r[6] = s->r[6] + (uint32_t)(int32_t)(int8_t)0x10;
    if (!s->T) goto L_5AFA0;
    /* 0x05AF9E: op 0x67E3 */
    s->r[7] = s->r[14];
    L_5AFA0: ;
    /* 0x05AFA0: bra 0x05AFC4 */
    /* 0x05AFA2: mov.b r7,@r6 */
    *(volatile uint8_t*)s->r[6] = s->r[7]; /* RAM 0xFFFFD159 */
    goto L_5AFC4;
    L_5AFA4: ;
    /* 0x05AFA4: op 0x60D3 */
    s->r[0] = s->r[13];
    /* 0x05AFA6: op 0x8805 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x05) ? 1u : 0u;
    /* 0x05AFA8: bt.s 0x05AFB4 */
    /* 0x05AFAA: op 0x0009 */
    
    if (s->T) goto L_5AFB4;
    /* 0x05AFAC: op 0x60D3 */
    s->r[0] = s->r[13];
    /* 0x05AFAE: op 0x8807 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x07) ? 1u : 0u;
    /* 0x05AFB0: bf.s 0x05AFC4 */
    /* 0x05AFB2: op 0x0009 */
    
    if (!s->T) goto L_5AFC4;
    L_5AFB4: ;
    /* 0x05AFB4: op 0x6463 */
    s->r[4] = s->r[6];
    /* 0x05AFB6: op 0x7410 */
    s->r[4] = s->r[4] + (uint32_t)(int32_t)(int8_t)0x10;
    /* 0x05AFB8: mov.b @r4,r4 */
    uint32_t t26 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)s->r[4]; /* RAM 0xFFFFD169 */
    s->r[4] = t26;
    /* 0x05AFBA: op 0x604C */
    s->r[0] = s->r[4] & 0xFFu;
    /* 0x05AFBC: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x05AFBE: bf.s 0x05AFC4 */
    /* 0x05AFC0: op 0x6573 */
    s->r[5] = s->r[7];
    if (!s->T) goto L_5AFC4;
    /* 0x05AFC2: op 0x65E3 */
    s->r[5] = s->r[14];
    L_5AFC4: ;
    /* 0x05AFC4: op 0x6053 */
    s->r[0] = s->r[5];
    /* 0x05AFC6: op 0x7F04 */
    s->r[15] = s->r[15] + (uint32_t)(int32_t)(int8_t)0x04;
    /* 0x05AFC8: mov.l @r15+,r13 */
    s->r[13] = local_3f8;
    /* 0x05AFCA: rts */
    /* 0x05AFCC: mov.l @r15+,r14 */
    s->r[14] = local_3fc;
    return;
    return; /* fallthrough */
}
