/* ROM: 60E0FC00 | Address: 0x5C3F6 | Size: 58 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST callee (CFG).
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_52A12(ST *s);
void f_52A5A(ST *s);
void f_5C3F6(ST *s)
{
    uint32_t local_3fc = 0;
    /* 0x05C3F6: op 0xE522 */
    s->r[5] = (uint32_t)(int32_t)(int8_t)0x22;
    /* 0x05C3F8: op 0xD30C */
    s->r[3] = 0x00052A5Au;
    /* 0x05C3FA: sts.l pr,@-r15 */
    local_3fc = s->pr;
    /* 0x05C3FC: op 0x7FFC */
    s->r[15] = s->r[15] + (uint32_t)(int32_t)(int8_t)0xFC;
    /* 0x05C3FE: jsr @r3 */
    s->pr = 0x0005C402;
    s->r[4] = (uint32_t)(int32_t)(int8_t)0x3B;
    f_52A5A(s);
    /* 0x05C402: op 0x6503 */
    s->r[5] = s->r[0];
    /* 0x05C404: op 0xD208 */
    s->r[2] = 0x00052A12u;
    /* 0x05C406: op 0xE43B */
    s->r[4] = (uint32_t)(int32_t)(int8_t)0x3B;
    /* 0x05C408: op 0x7F04 */
    s->r[15] = s->r[15] + (uint32_t)(int32_t)(int8_t)0x04;
    /* 0x05C40A: jmp @r2 (tail) */
    s->pr = local_3fc;
    f_52A12(s);
    return;
    return; /* fallthrough */
}
