/* ROM: 60E0FC00 | Address: 0x5CC0E | Size: 176 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST callee (CFG).
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_23B0(ST *s);
void f_3E1AA(ST *s);
void f_3E258(ST *s);
void f_5CC0E(ST *s)
{
    uint32_t local_3fc = 0;
    uint32_t local_400 = 0;
    uint32_t local_404 = 0;
    uint32_t fr0 = 0;
    uint32_t fr1 = 0;
    uint32_t fr14 = 0;
    uint32_t fr15 = 0;
    uint32_t fr2 = 0;
    uint32_t fr3 = 0;
    uint32_t fr4 = 0;
    uint32_t fr5 = 0;
    uint32_t fr6 = 0;
    uint32_t fr7 = 0;
    /* 0x05CC0E: fldi1 fr1 */
    fr1 = 0x3F800000u;
    /* 0x05CC10: op 0xC71B */
    s->r[0] = 0x0005CC80u;
    /* 0x05CC12: fmov.s fr15,@-r15 (rt-base) */
    s->r[15] -= 4;
    *(volatile uint32_t*)s->r[15] = fr15;
    /* 0x05CC14: fmov.s fr14,@-r15 (rt-base) */
    s->r[15] -= 4;
    *(volatile uint32_t*)s->r[15] = fr14;
    /* 0x05CC16: sts.l pr,@-r15 */
    local_3fc = s->pr;
    /* 0x05CC18: op 0x9324 */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0x0000B12Cu;
    /* 0x05CC1A: fmov.s @r3,fr3 */
    fr3 = *(volatile uint32_t*)0xFFFFB12C; /* RAM 0xFFFFB12C */
    /* 0x05CC1C: op 0x9223 */
    s->r[2] = (uint32_t)(int32_t)(int16_t)0x0000AE50u;
    /* 0x05CC1E: fmov.s @r2,fr2 */
    fr2 = *(volatile uint32_t*)0xFFFFAE50; /* RAM 0xFFFFAE50 */
    /* 0x05CC20: op 0x9222 */
    s->r[2] = (uint32_t)(int32_t)(int16_t)0x0000D066u;
    /* 0x05CC22: fadd fr3,fr2 */
    { union { uint32_t u; float f; } _a, _b, _r; _a.u = fr2; _b.u = fr3; _r.f = _a.f + _b.f; fr2 = _r.u; }
    /* 0x05CC24: mov.b @r2,r5 */
    uint32_t t2 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)s->r[2]; /* RAM 0xFFFFD066 */
    s->r[5] = t2;
    /* 0x05CC26: fneg fr1 */
    fr1 = fr1 ^ 0x80000000u;
    /* 0x05CC28: fmov fr2,fr15 */
    fr15 = fr2;
    /* 0x05CC2A: op 0x645C */
    s->r[4] = s->r[5] & 0xFFu;
    /* 0x05CC2C: fmov.s @r0,fr2 */
    fr2 = *(volatile uint32_t*)0x0005CC80; /* ROM */
    /* 0x05CC2E: fadd fr1,fr15 */
    { union { uint32_t u; float f; } _a, _b, _r; _a.u = fr15; _b.u = fr1; _r.f = _a.f + _b.f; fr15 = _r.u; }
    /* 0x05CC30: op 0x6043 */
    s->r[0] = s->r[4];
    /* 0x05CC32: op 0x8830 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x30) ? 1u : 0u;
    /* 0x05CC34: bf.s 0x05CC84 */
    /* 0x05CC36: fmul fr2,fr15 */
    { union { uint32_t u; float f; } _a, _b, _r; _a.u = fr15; _b.u = fr2; _r.f = _a.f * _b.f; fr15 = _r.u; }
    if (!s->T) goto L_5CC84;
    /* 0x05CC38: op 0x9407 */
    s->r[4] = (uint32_t)(int32_t)(int16_t)0x000091BCu;
    /* 0x05CC3A: fmov fr15,fr4 */
    fr4 = fr15;
    /* 0x05CC3C: lds.l @r15+,pr */
    s->pr = local_3fc;
    /* 0x05CC3E: fmov.s @r15+,fr14 (rt-base) */
    fr14 = *(volatile uint32_t*)s->r[15];
    s->r[15] = s->r[15] + 4;
    /* 0x05CC40: op 0xD10C */
    s->r[1] = 0x0003E258u;
    /* 0x05CC42: jmp @r1 (tail) */
    fr15 = *(volatile uint32_t*)s->r[15];
    s->r[15] = s->r[15] + 4;
    f_3E258(s);
    return;
    L_5CC84: ;
    /* 0x05CC84: op 0x8840 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x40) ? 1u : 0u;
    /* 0x05CC86: bf.s 0x05CCB6 */
    /* 0x05CC88: op 0x0009 */
    
    if (!s->T) goto L_5CCB6;
    /* 0x05CC8A: fldi1 fr14 */
    fr14 = 0x3F800000u;
    /* 0x05CC8C: op 0x9482 */
    s->r[4] = (uint32_t)(int32_t)(int16_t)0x000091BCu;
    /* 0x05CC8E: op 0xD148 */
    s->r[1] = 0x0007C2A4u;
    /* 0x05CC90: op 0xD348 */
    s->r[3] = 0x0003E1AAu;
    /* 0x05CC92: fmov.s @r1,fr3 */
    fr3 = *(volatile uint32_t*)0x0007C2A4; /* ROM */
    /* 0x05CC94: fsub fr3,fr14 */
    { union { uint32_t u; float f; } _a, _b, _r; _a.u = fr14; _b.u = fr3; _r.f = _a.f - _b.f; fr14 = _r.u; }
    /* 0x05CC96: jsr @r3 */
    s->pr = 0x0005CC9A;
    fr4 = 0u;
    f_3E1AA(s);
    /* 0x05CC9A: fmov fr0,fr5 */
    fr5 = fr0;
    /* 0x05CC9C: op 0xC746 */
    s->r[0] = 0x0005CDB8u;
    /* 0x05CC9E: fmov fr14,fr6 */
    fr6 = fr14;
    /* 0x05CCA0: op 0xD346 */
    s->r[3] = 0x000023B0u;
    /* 0x05CCA2: fmov.s @r0,fr7 */
    fr7 = *(volatile uint32_t*)0x0005CDB8; /* ROM */
    /* 0x05CCA4: jsr @r3 */
    s->pr = 0x0005CCA8;
    fr4 = fr15;
    f_23B0(s);
    /* 0x05CCA8: op 0x9474 */
    s->r[4] = (uint32_t)(int32_t)(int16_t)0x000091BCu;
    /* 0x05CCAA: fmov fr0,fr4 */
    fr4 = fr0;
    /* 0x05CCAC: lds.l @r15+,pr */
    s->pr = local_400;
    /* 0x05CCAE: fmov.s @r15+,fr14 (rt-base) */
    fr14 = *(volatile uint32_t*)s->r[15];
    s->r[15] = s->r[15] + 4;
    /* 0x05CCB0: op 0xD243 */
    s->r[2] = 0x0003E258u;
    /* 0x05CCB2: jmp @r2 (tail) */
    fr15 = *(volatile uint32_t*)s->r[15];
    s->r[15] = s->r[15] + 4;
    f_3E258(s);
    return;
    L_5CCB6: ;
    /* 0x05CCB6: lds.l @r15+,pr */
    s->pr = local_404;
    /* 0x05CCB8: fmov.s @r15+,fr14 (rt-base) */
    fr14 = *(volatile uint32_t*)s->r[15];
    s->r[15] = s->r[15] + 4;
    /* 0x05CCBA: rts */
    /* 0x05CCBC: fmov.s @r15+,fr15 (rt-base) */
    fr15 = *(volatile uint32_t*)s->r[15];
    s->r[15] = s->r[15] + 4;
    return;
    return; /* fallthrough */
}
