/* ROM: 60E1D400 | Address: 0x5D9B8 | Size: 184 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v7.py — ST (shared state) ABI,
 * leaf callee library (c/lib/f_<hex>.c). Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_5D9B8(ST *s)
{
    uint32_t local_3f4 = 0;
    uint32_t local_3f8 = 0;
    uint32_t local_3fc = 0;
    /* 0x05D9B8: mov.l r14,@-r15 */
    local_3fc = s->r[14];
    /* 0x05D9BA: op 0xEE01 */
    s->r[14] = (uint32_t)(int32_t)(int8_t)0x01;
    /* 0x05D9BC: op 0xD62E */
    s->r[6] = 0x00060274u;
    /* 0x05D9BE: mov.l r13,@-r15 */
    local_3f8 = s->r[13];
    /* 0x05D9C0: op 0xD32C */
    s->r[3] = 0xFFFFD355u;
    /* 0x05D9C2: op 0x7FFC */
    s->r[15] = s->r[15] + (uint32_t)(int32_t)(int8_t)0xFC;
    /* 0x05D9C4: mov.b @r3,r5 */
    uint32_t t2 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFD355; /* RAM 0xFFFFD355 */
    s->r[5] = t2;
    /* 0x05D9C6: op 0x625C */
    s->r[2] = s->r[5] & 0xFFu;
    /* 0x05D9C8: op 0x2228 */
    s->T = ((s->r[2] & s->r[2]) == 0u) ? 1u : 0u;
    /* 0x05D9CA: bf.s 0x05DA26 */
    /* 0x05D9CC: op 0xE700 */
    s->r[7] = (uint32_t)(int32_t)(int8_t)0x00;
    if (!s->T) goto L_5DA26;
    /* 0x05D9CE: mov.b @(0x8,r6),r0 */
    uint32_t t4 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0x0006027C; /* ROM */
    s->r[0] = t4;
    /* 0x05D9D0: op 0x924F */
    s->r[2] = (uint32_t)(int32_t)(int16_t)0x0000D3A8u;
    /* 0x05D9D2: mov.b @r2,r13 */
    uint32_t t6 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFD3A8; /* RAM 0xFFFFD3A8 */
    s->r[13] = t6;
    /* 0x05D9D4: op 0xD32A */
    s->r[3] = 0x0000E902u;
    /* 0x05D9D6: op 0x2D09 */
    s->r[13] &= s->r[0];
    /* 0x05D9D8: op 0xD028 */
    s->r[0] = 0xFFFFD350u;
    /* 0x05D9DA: mov.w @r0,r1 */
    uint32_t t8 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)0xFFFFD350; /* RAM 0xFFFFD350 */
    s->r[1] = t8;
    /* 0x05D9DC: op 0x611D */
    s->r[1] = s->r[1] & 0xFFFFu;
    /* 0x05D9DE: op 0x3130 */
    s->T = (s->r[1] == s->r[3]) ? 1u : 0u;
    /* 0x05D9E0: bf.s 0x05DA16 */
    /* 0x05D9E2: op 0x0009 */
    
    if (!s->T) goto L_5DA16;
    /* 0x05D9E4: op 0x6DDC */
    s->r[13] = s->r[13] & 0xFFu;
    /* 0x05D9E6: op 0x2DD8 */
    s->T = ((s->r[13] & s->r[13]) == 0u) ? 1u : 0u;
    /* 0x05D9E8: bt.s 0x05DA0E */
    /* 0x05D9EA: op 0x0009 */
    
    if (s->T) goto L_5DA0E;
    /* 0x05D9EC: mov.l @(0xC,r6),r2 */
    uint32_t t10 = *(volatile uint32_t*)0x00060280; /* ROM */
    s->r[2] = t10;
    /* 0x05D9EE: op 0xD325 */
    s->r[3] = 0xFFFFD354u;
    /* 0x05D9F0: mov.b @r3,r1 */
    uint32_t t12 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFD354; /* RAM 0xFFFFD354 */
    s->r[1] = t12;
    /* 0x05D9F2: mov.b r1,@r2 */
    *(volatile uint8_t*)s->r[2] = s->r[1]; /* RAM 0xFFFFD368 */
    /* 0x05D9F4: mov.b @r3,r0 */
    uint32_t t14 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFD354; /* RAM 0xFFFFD354 */
    s->r[0] = t14;
    /* 0x05D9F6: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x05D9F8: op 0x8807 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x07) ? 1u : 0u;
    /* 0x05D9FA: bf.s 0x05DA22 */
    /* 0x05D9FC: op 0x65E3 */
    s->r[5] = s->r[14];
    if (!s->T) goto L_5DA22;
    /* 0x05D9FE: op 0xD122 */
    s->r[1] = 0xFFFFD393u;
    /* 0x05DA00: op 0xD022 */
    s->r[0] = 0xFFFFD352u;
    /* 0x05DA02: mov.w @r0,r2 */
    uint32_t t16 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)0xFFFFD352; /* RAM 0xFFFFD352 */
    s->r[2] = t16;
    /* 0x05DA04: op 0x622D */
    s->r[2] = s->r[2] & 0xFFFFu;
    /* 0x05DA06: op 0x4219 */
    s->r[2] = (s->r[2] >> 8);
    /* 0x05DA08: mov.b r2,@r1 */
    *(volatile uint8_t*)0xFFFFD393 = s->r[2]; /* RAM 0xFFFFD393 */
    /* 0x05DA0A: bra 0x05DA22 */
    /* 0x05DA0C: op 0x0009 */
    
    goto L_5DA22;
    L_5DA0E: ;
    /* 0x05DA0E: op 0xE502 */
    s->r[5] = (uint32_t)(int32_t)(int8_t)0x02;
    /* 0x05DA10: mov.l @(0xC,r6),r2 */
    uint32_t t18 = *(volatile uint32_t*)0x00060280; /* ROM */
    s->r[2] = t18;
    /* 0x05DA12: bra 0x05DA22 */
    /* 0x05DA14: mov.b r7,@r2 */
    *(volatile uint8_t*)s->r[2] = s->r[7]; /* RAM 0xFFFFD368 */
    goto L_5DA22;
    L_5DA16: ;
    /* 0x05DA16: op 0x6DDC */
    s->r[13] = s->r[13] & 0xFFu;
    /* 0x05DA18: op 0x2DD8 */
    s->T = ((s->r[13] & s->r[13]) == 0u) ? 1u : 0u;
    /* 0x05DA1A: bf.s 0x05DA22 */
    /* 0x05DA1C: op 0x0009 */
    
    if (!s->T) goto L_5DA22;
    /* 0x05DA1E: mov.l @(0xC,r6),r1 */
    uint32_t t20 = *(volatile uint32_t*)0x00060280; /* ROM */
    s->r[1] = t20;
    /* 0x05DA20: mov.b r7,@r1 */
    *(volatile uint8_t*)s->r[1] = s->r[7]; /* RAM 0xFFFFD368 */
    L_5DA22: ;
    /* 0x05DA22: op 0xD314 */
    s->r[3] = 0xFFFFD355u;
    /* 0x05DA24: mov.b r5,@r3 */
    *(volatile uint8_t*)0xFFFFD355 = s->r[5]; /* RAM 0xFFFFD355 */
    L_5DA26: ;
    /* 0x05DA26: op 0xD214 */
    s->r[2] = 0x00060274u;
    /* 0x05DA28: op 0xD619 */
    s->r[6] = 0xFFFFD371u;
    /* 0x05DA2A: mov.l @(0xC,r2),r3 */
    uint32_t t22 = *(volatile uint32_t*)0x00060280; /* ROM */
    s->r[3] = t22;
    /* 0x05DA2C: mov.b @r3,r1 */
    uint32_t t24 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)s->r[3]; /* RAM 0xFFFFD368 */
    s->r[1] = t24;
    /* 0x05DA2E: mov.b r1,@r15 */
    local_3f4 = s->r[1];
    /* 0x05DA30: mov.b @r15,r13 */
    s->r[13] = (uint32_t)(int32_t)(int8_t)(local_3f4 & 0xFFu);
    /* 0x05DA32: op 0x6DDC */
    s->r[13] = s->r[13] & 0xFFu;
    /* 0x05DA34: op 0x2DD8 */
    s->T = ((s->r[13] & s->r[13]) == 0u) ? 1u : 0u;
    /* 0x05DA36: bf.s 0x05DA48 */
    /* 0x05DA38: op 0x6543 */
    s->r[5] = s->r[4];
    if (!s->T) goto L_5DA48;
    /* 0x05DA3A: op 0x604C */
    s->r[0] = s->r[4] & 0xFFu;
    /* 0x05DA3C: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x05DA3E: bf.s 0x05DA44 */
    /* 0x05DA40: op 0x7622 */
    s->r[6] = s->r[6] + (uint32_t)(int32_t)(int8_t)0x22;
    if (!s->T) goto L_5DA44;
    /* 0x05DA42: op 0x67E3 */
    s->r[7] = s->r[14];
    L_5DA44: ;
    /* 0x05DA44: bra 0x05DA68 */
    /* 0x05DA46: mov.b r7,@r6 */
    *(volatile uint8_t*)s->r[6] = s->r[7]; /* RAM 0xFFFFD393 */
    goto L_5DA68;
    L_5DA48: ;
    /* 0x05DA48: op 0x60D3 */
    s->r[0] = s->r[13];
    /* 0x05DA4A: op 0x8805 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x05) ? 1u : 0u;
    /* 0x05DA4C: bt.s 0x05DA58 */
    /* 0x05DA4E: op 0x0009 */
    
    if (s->T) goto L_5DA58;
    /* 0x05DA50: op 0x60D3 */
    s->r[0] = s->r[13];
    /* 0x05DA52: op 0x8807 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x07) ? 1u : 0u;
    /* 0x05DA54: bf.s 0x05DA68 */
    /* 0x05DA56: op 0x0009 */
    
    if (!s->T) goto L_5DA68;
    L_5DA58: ;
    /* 0x05DA58: op 0x6463 */
    s->r[4] = s->r[6];
    /* 0x05DA5A: op 0x7422 */
    s->r[4] = s->r[4] + (uint32_t)(int32_t)(int8_t)0x22;
    /* 0x05DA5C: mov.b @r4,r4 */
    uint32_t t26 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)s->r[4]; /* RAM 0xFFFFD3B5 */
    s->r[4] = t26;
    /* 0x05DA5E: op 0x604C */
    s->r[0] = s->r[4] & 0xFFu;
    /* 0x05DA60: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x05DA62: bf.s 0x05DA68 */
    /* 0x05DA64: op 0x6573 */
    s->r[5] = s->r[7];
    if (!s->T) goto L_5DA68;
    /* 0x05DA66: op 0x65E3 */
    s->r[5] = s->r[14];
    L_5DA68: ;
    /* 0x05DA68: op 0x6053 */
    s->r[0] = s->r[5];
    /* 0x05DA6A: op 0x7F04 */
    s->r[15] = s->r[15] + (uint32_t)(int32_t)(int8_t)0x04;
    /* 0x05DA6C: mov.l @r15+,r13 */
    s->r[13] = local_3f8;
    /* 0x05DA6E: rts */
    /* 0x05DA70: mov.l @r15+,r14 */
    s->r[14] = local_3fc;
    return;
    return; /* fallthrough */
}
