/* ROM: 60E0FC00 | Address: 0x5E5A4 | Size: 22 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST callee (CFG).
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, vbr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_5E5A4(ST *s)
{
    /* 0x05E5A4: op 0x9339 */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0x0000BAD9u;
    /* 0x05E5A6: mov.b @r3,r0 */
    uint32_t t2 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFBAD9; /* RAM 0xFFFFBAD9 */
    s->r[0] = t2;
    /* 0x05E5A8: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x05E5AA: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x05E5AC: bf.s 0x05E5B4 */
    /* 0x05E5AE: op 0x0009 */
    
    if (!s->T) goto L_5E5B4;
    /* 0x05E5B0: bra 0x05E5B6 */
    /* 0x05E5B2: op 0xE400 */
    s->r[4] = (uint32_t)(int32_t)(int8_t)0x00;
    goto L_5E5B6;
    L_5E5B6: ;
    /* 0x05E5B6: rts */
    /* 0x05E5B8: op 0x6043 */
    s->r[0] = s->r[4];
    return;
    L_5E5B4: ;
    /* 0x05E5B4: op 0xE401 */
    s->r[4] = (uint32_t)(int32_t)(int8_t)0x01;
    return; /* fallthrough */
}
