/* ROM: 60E0FC00 | Address: 0x5F404 | Size: 358 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST callee (CFG).
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_5F5C6(ST *s);
void f_5F6CC(ST *s);
void f_5F7F2(ST *s);
void f_5F848(ST *s);
void f_601E8(ST *s);
void f_60970(ST *s);
void f_609D8(ST *s);
void f_60A28(ST *s);
void f_60CA0(ST *s);
void f_60D10(ST *s);
void f_6118A(ST *s);
void f_611A8(ST *s);
void f_616C8(ST *s);
void f_616E8(ST *s);
void f_61916(ST *s);
void f_61988(ST *s);
void f_619FA(ST *s);
void f_5F404(ST *s)
{
    uint32_t local_3e0 = 0;
    uint32_t local_3e4 = 0;
    uint32_t local_3e8 = 0;
    uint32_t local_3ec = 0;
    uint32_t local_3f0 = 0;
    uint32_t local_3f4 = 0;
    uint32_t local_3f8 = 0;
    uint32_t local_3fc = 0;
    /* 0x05F404: mov.l r14,@-r15 */
    local_3fc = s->r[14];
    /* 0x05F406: mov.l r13,@-r15 */
    local_3f8 = s->r[13];
    /* 0x05F408: mov.l r12,@-r15 */
    local_3f4 = s->r[12];
    /* 0x05F40A: op 0x6D43 */
    s->r[13] = s->r[4];
    /* 0x05F40C: mov.l r11,@-r15 */
    local_3f0 = s->r[11];
    /* 0x05F40E: op 0xEC08 */
    s->r[12] = (uint32_t)(int32_t)(int8_t)0x08;
    /* 0x05F410: mov.l r10,@-r15 */
    local_3ec = s->r[10];
    /* 0x05F412: op 0x6B53 */
    s->r[11] = s->r[5];
    /* 0x05F414: mov.l r9,@-r15 */
    local_3e8 = s->r[9];
    /* 0x05F416: op 0x64BC */
    s->r[4] = s->r[11] & 0xFFu;
    /* 0x05F418: op 0xDA2E */
    s->r[10] = 0x000611A8u;
    /* 0x05F41A: op 0x6043 */
    s->r[0] = s->r[4];
    /* 0x05F41C: mov.l r8,@-r15 */
    local_3e4 = s->r[8];
    /* 0x05F41E: op 0x8803 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x03) ? 1u : 0u;
    /* 0x05F420: op 0xD92B */
    s->r[9] = 0x00061916u;
    /* 0x05F422: sts.l pr,@-r15 */
    local_3e0 = s->pr;
    /* 0x05F424: bf.s 0x05F474 */
    /* 0x05F426: op 0xEE00 */
    s->r[14] = (uint32_t)(int32_t)(int8_t)0x00;
    if (!s->T) goto L_5F474;
    /* 0x05F428: bsr 0x5F5C6 */
    s->pr = 0x0005F42C;
    s->r[4] = s->r[13];
    f_5F5C6(s);
    /* 0x05F42C: op 0xD32A */
    s->r[3] = 0x000601E8u;
    /* 0x05F42E: op 0x6E03 */
    s->r[14] = s->r[0];
    /* 0x05F430: op 0x66B3 */
    s->r[6] = s->r[11];
    /* 0x05F432: op 0x6503 */
    s->r[5] = s->r[0];
    /* 0x05F434: jsr @r3 */
    s->pr = 0x0005F438;
    s->r[4] = s->r[13];
    f_601E8(s);
    /* 0x05F438: op 0xD228 */
    s->r[2] = 0x00060D10u;
    /* 0x05F43A: op 0x6C03 */
    s->r[12] = s->r[0];
    /* 0x05F43C: jsr @r2 */
    s->pr = 0x0005F440;
    s->r[4] = s->r[0];
    f_60D10(s);
    /* 0x05F440: op 0x6403 */
    s->r[4] = s->r[0];
    /* 0x05F442: op 0x604C */
    s->r[0] = s->r[4] & 0xFFu;
    /* 0x05F444: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x05F446: bf.s 0x05F4C4 */
    /* 0x05F448: op 0x0009 */
    
    if (!s->T) goto L_5F4C4;
    /* 0x05F44A: op 0x65E3 */
    s->r[5] = s->r[14];
    /* 0x05F44C: bsr 0x5F6CC */
    s->pr = 0x0005F450;
    s->r[4] = s->r[13];
    f_5F6CC(s);
    /* 0x05F450: bsr 0x5F848 */
    s->pr = 0x0005F454;
    
    f_5F848(s);
    /* 0x05F454: op 0xD222 */
    s->r[2] = 0x00060A28u;
    /* 0x05F456: jsr @r2 */
    s->pr = 0x0005F45A;
    s->r[4] = s->r[13];
    f_60A28(s);
    /* 0x05F45A: op 0xE520 */
    s->r[5] = (uint32_t)(int32_t)(int8_t)0x20;
    /* 0x05F45C: bsr 0x5F7F2 */
    s->pr = 0x0005F460;
    s->r[4] = s->r[13];
    f_5F7F2(s);
    /* 0x05F460: op 0xD220 */
    s->r[2] = 0x000619FAu;
    /* 0x05F462: jsr @r2 */
    s->pr = 0x0005F466;
    s->r[4] = s->r[12];
    f_619FA(s);
    /* 0x05F466: jsr @r9 */
    s->pr = 0x0005F46A;
    s->r[4] = s->r[11];
    f_61916(s);
    /* 0x05F46A: op 0xD31F */
    s->r[3] = 0x00061988u;
    /* 0x05F46C: jsr @r3 */
    s->pr = 0x0005F470;
    s->r[4] = (uint32_t)(int32_t)(int8_t)0x01;
    f_61988(s);
    /* 0x05F470: bra 0x05F4C4 */
    /* 0x05F472: op 0x0009 */
    
    goto L_5F4C4;
    L_5F4C4: ;
    /* 0x05F4C4: jsr @r10 */
    s->pr = 0x0005F4C8;
    
    f_611A8(s);
    /* 0x05F4C8: bra 0x05F528 */
    /* 0x05F4CA: op 0x0009 */
    
    goto L_5F528;
    L_5F528: ;
    /* 0x05F528: op 0xD43B */
    s->r[4] = 0xFFFFD4CCu;
    /* 0x05F52A: op 0x60C3 */
    s->r[0] = s->r[12];
    /* 0x05F52C: op 0xD33B */
    s->r[3] = 0x00060CA0u;
    /* 0x05F52E: mov.b r0,@(0x4,r4) */
    *(volatile uint8_t*)(s->r[4] + 4) = s->r[0]; /* RAM 0xFFFFD4D0 */
    /* 0x05F530: op 0x60E3 */
    s->r[0] = s->r[14];
    /* 0x05F532: jsr @r3 */
    s->pr = 0x0005F536;
    *(volatile uint8_t*)(s->r[4] + 7) = s->r[0]; /* RAM 0xFFFFD4D3 */
    f_60CA0(s);
    /* 0x05F536: op 0x61DD */
    s->r[1] = s->r[13] & 0xFFFFu;
    /* 0x05F538: op 0xD339 */
    s->r[3] = 0xFFFFD4D4u;
    /* 0x05F53A: mov.w @r3,r2 */
    uint32_t t2 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)s->r[3]; /* RAM 0xFFFFD4D4 */
    s->r[2] = t2;
    /* 0x05F53C: op 0x622D */
    s->r[2] = s->r[2] & 0xFFFFu;
    /* 0x05F53E: op 0x3210 */
    s->T = (s->r[2] == s->r[1]) ? 1u : 0u;
    /* 0x05F540: bf.s 0x05F54C */
    /* 0x05F542: op 0x0009 */
    
    if (!s->T) goto L_5F54C;
    /* 0x05F544: op 0xD137 */
    s->r[1] = 0x00060970u;
    /* 0x05F546: op 0xE520 */
    s->r[5] = (uint32_t)(int32_t)(int8_t)0x20;
    /* 0x05F548: jsr @r1 */
    s->pr = 0x0005F54C;
    s->r[4] = s->r[13];
    f_60970(s);
    L_5F54C: ;
    /* 0x05F54C: op 0xD336 */
    s->r[3] = 0x000609D8u;
    /* 0x05F54E: op 0x66E3 */
    s->r[6] = s->r[14];
    /* 0x05F550: op 0xE520 */
    s->r[5] = (uint32_t)(int32_t)(int8_t)0x20;
    /* 0x05F552: jsr @r3 */
    s->pr = 0x0005F556;
    s->r[4] = s->r[13];
    f_609D8(s);
    /* 0x05F556: lds.l @r15+,pr */
    s->pr = local_3e0;
    /* 0x05F558: op 0xD234 */
    s->r[2] = 0x0006118Au;
    /* 0x05F55A: mov.l @r15+,r8 */
    s->r[8] = local_3e4;
    /* 0x05F55C: mov.l @r15+,r9 */
    s->r[9] = local_3e8;
    /* 0x05F55E: mov.l @r15+,r10 */
    s->r[10] = local_3ec;
    /* 0x05F560: mov.l @r15+,r11 */
    s->r[11] = local_3f0;
    /* 0x05F562: mov.l @r15+,r12 */
    s->r[12] = local_3f4;
    /* 0x05F564: mov.l @r15+,r13 */
    s->r[13] = local_3f8;
    /* 0x05F566: jmp @r2 (tail) */
    s->r[14] = local_3fc;
    f_6118A(s);
    return;
    L_5F474: ;
    /* 0x05F474: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x05F476: bf.s 0x05F4F4 */
    /* 0x05F478: op 0x0009 */
    
    if (!s->T) goto L_5F4F4;
    /* 0x05F47A: op 0xD21C */
    s->r[2] = 0x000616E8u;
    /* 0x05F47C: jsr @r2 */
    s->pr = 0x0005F480;
    s->r[4] = s->r[13];
    f_616E8(s);
    /* 0x05F480: op 0x9824 */
    s->r[8] = (uint32_t)(int32_t)(int16_t)0x80u;
    /* 0x05F482: op 0x6E03 */
    s->r[14] = s->r[0];
    /* 0x05F484: op 0x63EC */
    s->r[3] = s->r[14] & 0xFFu;
    /* 0x05F486: op 0x2389 */
    s->r[3] &= s->r[8];
    /* 0x05F488: op 0x3380 */
    s->T = (s->r[3] == s->r[8]) ? 1u : 0u;
    /* 0x05F48A: bt.s 0x05F490 */
    /* 0x05F48C: op 0x66B3 */
    s->r[6] = s->r[11];
    if (s->T) goto L_5F490;
    /* 0x05F48E: op 0xEE00 */
    s->r[14] = (uint32_t)(int32_t)(int8_t)0x00;
    L_5F490: ;
    /* 0x05F490: op 0xD311 */
    s->r[3] = 0x000601E8u;
    /* 0x05F492: op 0x65E3 */
    s->r[5] = s->r[14];
    /* 0x05F494: jsr @r3 */
    s->pr = 0x0005F498;
    s->r[4] = s->r[13];
    f_601E8(s);
    /* 0x05F498: op 0xD210 */
    s->r[2] = 0x00060D10u;
    /* 0x05F49A: op 0x6C03 */
    s->r[12] = s->r[0];
    /* 0x05F49C: jsr @r2 */
    s->pr = 0x0005F4A0;
    s->r[4] = s->r[0];
    f_60D10(s);
    /* 0x05F4A0: op 0x6403 */
    s->r[4] = s->r[0];
    /* 0x05F4A2: op 0x604C */
    s->r[0] = s->r[4] & 0xFFu;
    /* 0x05F4A4: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x05F4A6: bf.s 0x05F4C4 */
    /* 0x05F4A8: op 0x0009 */
    
    if (!s->T) goto L_5F4C4;
    /* 0x05F4AA: op 0x62EC */
    s->r[2] = s->r[14] & 0xFFu;
    /* 0x05F4AC: op 0x2289 */
    s->r[2] &= s->r[8];
    /* 0x05F4AE: op 0x3280 */
    s->T = (s->r[2] == s->r[8]) ? 1u : 0u;
    /* 0x05F4B0: bt.s 0x05F4C0 */
    /* 0x05F4B2: op 0x0009 */
    
    if (s->T) goto L_5F4C0;
    /* 0x05F4B4: op 0xD20E */
    s->r[2] = 0x000616C8u;
    /* 0x05F4B6: jsr @r2 */
    s->pr = 0x0005F4BA;
    s->r[4] = s->r[14];
    f_616C8(s);
    /* 0x05F4BA: op 0xD30A */
    s->r[3] = 0x000619FAu;
    /* 0x05F4BC: jsr @r3 */
    s->pr = 0x0005F4C0;
    s->r[4] = s->r[12];
    f_619FA(s);
    L_5F4C0: ;
    /* 0x05F4C0: jsr @r9 */
    s->pr = 0x0005F4C4;
    s->r[4] = s->r[11];
    f_61916(s);
    L_5F4F4: ;
    /* 0x05F4F4: op 0x6043 */
    s->r[0] = s->r[4];
    /* 0x05F4F6: op 0x8802 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x02) ? 1u : 0u;
    /* 0x05F4F8: bf.s 0x05F528 */
    /* 0x05F4FA: op 0x0009 */
    
    if (!s->T) goto L_5F528;
    /* 0x05F4FC: op 0xD243 */
    s->r[2] = 0x000616E8u;
    /* 0x05F4FE: jsr @r2 */
    s->pr = 0x0005F502;
    s->r[4] = s->r[13];
    f_616E8(s);
    /* 0x05F502: op 0x6E03 */
    s->r[14] = s->r[0];
    /* 0x05F504: op 0xD342 */
    s->r[3] = 0x000601E8u;
    /* 0x05F506: op 0x66B3 */
    s->r[6] = s->r[11];
    /* 0x05F508: op 0x6503 */
    s->r[5] = s->r[0];
    /* 0x05F50A: jsr @r3 */
    s->pr = 0x0005F50E;
    s->r[4] = s->r[13];
    f_601E8(s);
    /* 0x05F50E: op 0x6C03 */
    s->r[12] = s->r[0];
    /* 0x05F510: op 0xD240 */
    s->r[2] = 0x00060D10u;
    /* 0x05F512: jsr @r2 */
    s->pr = 0x0005F516;
    s->r[4] = s->r[0];
    f_60D10(s);
    /* 0x05F516: op 0x6403 */
    s->r[4] = s->r[0];
    /* 0x05F518: op 0x604C */
    s->r[0] = s->r[4] & 0xFFu;
    /* 0x05F51A: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x05F51C: bf.s 0x05F524 */
    /* 0x05F51E: op 0x0009 */
    
    if (!s->T) goto L_5F524;
    /* 0x05F520: jsr @r9 */
    s->pr = 0x0005F524;
    s->r[4] = s->r[11];
    f_61916(s);
    L_5F524: ;
    /* 0x05F524: jsr @r10 */
    s->pr = 0x0005F528;
    
    f_611A8(s);
    return; /* fallthrough */
}
