/* ROM: 60E0FC00 | Address: 0x60A28 | Size: 68 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST callee (CFG).
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, vbr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_6181E(ST *s);
void f_60A28(ST *s)
{
    /* 0x060A28: op 0xD20D */
    s->r[2] = 0xFFFF8920u;
    /* 0x060A2A: mov.w @r2,r3 */
    uint32_t t2 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)0xFFFF8920; /* RAM 0xFFFF8920 */
    s->r[3] = t2;
    /* 0x060A2C: op 0xD00D */
    s->r[0] = 0xFFFF87D6u;
    /* 0x060A2E: op 0x633D */
    s->r[3] = s->r[3] & 0xFFFFu;
    /* 0x060A30: op 0x4308 */
    s->r[3] = (s->r[3] << 2);
    /* 0x060A32: op 0x4308 */
    s->r[3] = (s->r[3] << 2);
    /* 0x060A34: mov.b @(r3+r0),r1 (rt-base) */
    uint32_t t3 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)(s->r[3] + s->r[0]);
    s->r[1] = t3;
    /* 0x060A36: op 0x611C */
    s->r[1] = s->r[1] & 0xFFu;
    /* 0x060A38: op 0x9307 */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0xC0u;
    /* 0x060A3A: op 0x3130 */
    s->T = (s->r[1] == s->r[3]) ? 1u : 0u;
    /* 0x060A3C: bf.s 0x060A46 */
    /* 0x060A3E: op 0x0009 */
    
    if (!s->T) goto L_60A46;
    /* 0x060A40: op 0xD109 */
    s->r[1] = 0x0006181Eu;
    /* 0x060A42: jmp @r1 (tail) */
    /* 0x060A44: op 0xE400 */
    s->r[4] = (uint32_t)(int32_t)(int8_t)0x00;
    f_6181E(s);
    return;
    L_60A46: ;
    /* 0x060A46: rts */
    /* 0x060A48: op 0x0009 */
    
    return;
    return; /* fallthrough */
}
