/* ROM: 60E1D400 | Address: 0x60786 | Size: 32 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v7.py — ST (shared state) ABI,
 * leaf callee library (c/lib/f_<hex>.c). Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_60786(ST *s)
{
    /* 0x060786: op 0x604C */
    s->r[0] = s->r[4] & 0xFFu;
    /* 0x060788: op 0xD530 */
    s->r[5] = 0xFFFFD6C4u;
    /* 0x06078A: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x06078C: bt.s 0x06079A */
    /* 0x06078E: op 0x0009 */
    
    if (s->T) goto L_6079A;
    /* 0x060790: op 0x8800 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x00) ? 1u : 0u;
    /* 0x060792: bt.s 0x0607A0 */
    /* 0x060794: op 0x0009 */
    
    if (s->T) goto L_607A0;
    /* 0x060796: bra 0x0607A4 */
    /* 0x060798: op 0x0009 */
    
    goto L_607A4;
    L_6079A: ;
    /* 0x06079A: op 0xE301 */
    s->r[3] = (uint32_t)(int32_t)(int8_t)0x01;
    /* 0x06079C: bra 0x0607A4 */
    /* 0x06079E: mov.b r3,@r5 */
    *(volatile uint8_t*)0xFFFFD6C4 = s->r[3]; /* RAM 0xFFFFD6C4 */
    goto L_607A4;
    L_607A0: ;
    /* 0x0607A0: op 0xE100 */
    s->r[1] = (uint32_t)(int32_t)(int8_t)0x00;
    /* 0x0607A2: mov.b r1,@r5 */
    *(volatile uint8_t*)0xFFFFD6C4 = s->r[1]; /* RAM 0xFFFFD6C4 */
    L_607A4: ;
    /* 0x0607A4: rts */
    /* 0x0607A6: op 0x0009 */
    
    return;
    return; /* fallthrough */
}
