/* ROM: 60E0FC00 | Address: 0x60AA6 | Size: 34 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST callee (CFG).
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, vbr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_6181E(ST *s);
void f_60AA6(ST *s)
{
    uint32_t local_400 = 0;
    uint32_t local_404 = 0;
    /* 0x060AA6: op 0x6E03 */
    s->r[14] = s->r[0];
    /* 0x060AA8: op 0xD031 */
    s->r[0] = 0x0007C852u;
    /* 0x060AAA: op 0x63EC */
    s->r[3] = s->r[14] & 0xFFu;
    /* 0x060AAC: mov.w @r4,r2 */
    uint32_t t2 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)s->r[4];
    s->r[2] = t2;
    /* 0x060AAE: op 0x622D */
    s->r[2] = s->r[2] & 0xFFFFu;
    /* 0x060AB0: mov.b @(r2+r0),r1 (rt-base) */
    uint32_t t3 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)(s->r[2] + s->r[0]);
    s->r[1] = t3;
    /* 0x060AB2: op 0x611C */
    s->r[1] = s->r[1] & 0xFFu;
    /* 0x060AB4: op 0x3313 */
    s->T = ((int32_t)s->r[3] >= (int32_t)s->r[1]) ? 1u : 0u;
    /* 0x060AB6: bt.s 0x060AC4 */
    /* 0x060AB8: op 0x0009 */
    
    if (s->T) goto L_60AC4;
    /* 0x060ABA: op 0x7E01 */
    s->r[14] = s->r[14] + (uint32_t)(int32_t)(int8_t)0x01;
    /* 0x060ABC: op 0xD22D */
    s->r[2] = 0x0006181Eu;
    /* 0x060ABE: op 0x64E3 */
    s->r[4] = s->r[14];
    /* 0x060AC0: jmp @r2 (tail) */
    /* 0x060AC2: mov.l @r15+,r14 */
    s->r[14] = local_400;
    f_6181E(s);
    return;
    L_60AC4: ;
    /* 0x060AC4: rts */
    /* 0x060AC6: mov.l @r15+,r14 */
    s->r[14] = local_404;
    return;
    return; /* fallthrough */
}
