/* ROM: 60E1D400 | Address: 0x61A50 | Size: 90 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST callee (CFG).
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_2034(ST *s);
void f_2044(ST *s);
void f_64F20(ST *s);
void f_66020(ST *s);
void f_61A50(ST *s)
{
    uint32_t local_3f8 = 0;
    uint32_t local_3fc = 0;
    /* 0x061A50: mov.l r14,@-r15 */
    local_3fc = s->r[14];
    /* 0x061A52: sts.l pr,@-r15 */
    local_3f8 = s->pr;
    /* 0x061A54: op 0xD37B */
    s->r[3] = 0x00066020u;
    /* 0x061A56: jsr @r3 */
    s->pr = 0x00061A5A;
    s->r[14] = (uint32_t)(int32_t)(int8_t)0x00;
    f_66020(s);
    /* 0x061A5A: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x061A5C: op 0x2008 */
    s->T = ((s->r[0] & s->r[0]) == 0u) ? 1u : 0u;
    /* 0x061A5E: bf.s 0x061AA0 */
    /* 0x061A60: op 0x0009 */
    
    if (!s->T) goto L_61AA0;
    /* 0x061A62: op 0xD379 */
    s->r[3] = 0x00064F20u;
    /* 0x061A64: jsr @r3 */
    s->pr = 0x00061A68;
    
    f_64F20(s);
    /* 0x061A68: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x061A6A: op 0x2008 */
    s->T = ((s->r[0] & s->r[0]) == 0u) ? 1u : 0u;
    /* 0x061A6C: bf.s 0x061AA0 */
    /* 0x061A6E: op 0x0009 */
    
    if (!s->T) goto L_61AA0;
    /* 0x061A70: op 0xD476 */
    s->r[4] = 0xFFFF87B0u;
    /* 0x061A72: op 0xD377 */
    s->r[3] = 0x00002034u;
    /* 0x061A74: jsr @r3 */
    s->pr = 0x00061A78;
    
    f_2034(s);
    /* 0x061A78: op 0x600D */
    s->r[0] = s->r[0] & 0xFFFFu;
    /* 0x061A7A: op 0x2008 */
    s->T = ((s->r[0] & s->r[0]) == 0u) ? 1u : 0u;
    /* 0x061A7C: bf.s 0x061AA0 */
    /* 0x061A7E: op 0x0009 */
    
    if (!s->T) goto L_61AA0;
    /* 0x061A80: op 0xD474 */
    s->r[4] = 0xFFFF87B4u;
    /* 0x061A82: op 0xD375 */
    s->r[3] = 0x00002044u;
    /* 0x061A84: jsr @r3 */
    s->pr = 0x00061A88;
    
    f_2044(s);
    /* 0x061A88: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x061A8A: op 0x2008 */
    s->T = ((s->r[0] & s->r[0]) == 0u) ? 1u : 0u;
    /* 0x061A8C: bf.s 0x061AA0 */
    /* 0x061A8E: op 0x0009 */
    
    if (!s->T) goto L_61AA0;
    /* 0x061A90: op 0xD472 */
    s->r[4] = 0xFFFF87ACu;
    /* 0x061A92: op 0xD36F */
    s->r[3] = 0x00002034u;
    /* 0x061A94: jsr @r3 */
    s->pr = 0x00061A98;
    
    f_2034(s);
    /* 0x061A98: op 0x600D */
    s->r[0] = s->r[0] & 0xFFFFu;
    /* 0x061A9A: op 0x2008 */
    s->T = ((s->r[0] & s->r[0]) == 0u) ? 1u : 0u;
    /* 0x061A9C: bt.s 0x061AA2 */
    /* 0x061A9E: op 0x0009 */
    
    if (s->T) goto L_61AA2;
    L_61AA0: ;
    /* 0x061AA0: op 0xEE01 */
    s->r[14] = (uint32_t)(int32_t)(int8_t)0x01;
    L_61AA2: ;
    /* 0x061AA2: op 0x60E3 */
    s->r[0] = s->r[14];
    /* 0x061AA4: lds.l @r15+,pr */
    s->pr = local_3f8;
    /* 0x061AA6: rts */
    /* 0x061AA8: mov.l @r15+,r14 */
    s->r[14] = local_3fc;
    return;
    return; /* fallthrough */
}
