/* ROM: 60E0FC00 | Address: 0x62A64 | Size: 192 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST callee (CFG).
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_616C8(ST *s);
void f_619FA(ST *s);
void f_62A64(ST *s)
{
    uint32_t local_3f0 = 0;
    uint32_t local_3f4 = 0;
    uint32_t local_3f8 = 0;
    uint32_t local_3fc = 0;
    uint32_t local_404 = 0;
    uint32_t local_408 = 0;
    uint32_t local_40c = 0;
    uint32_t local_414 = 0;
    uint32_t local_418 = 0;
    uint32_t local_41c = 0;
    /* 0x062A64: mov.l r14,@-r15 */
    local_3fc = s->r[14];
    /* 0x062A66: mov.l r13,@-r15 */
    local_3f8 = s->r[13];
    /* 0x062A68: sts.l pr,@-r15 */
    local_3f4 = s->pr;
    /* 0x062A6A: op 0x7FFC */
    s->r[15] = s->r[15] + (uint32_t)(int32_t)(int8_t)0xFC;
    /* 0x062A6C: op 0xD345 */
    s->r[3] = 0xFFFF8920u;
    /* 0x062A6E: mov.b @(0x6,r4),r0 */
    uint32_t t2 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)(s->r[4] + 6);
    s->r[0] = t2;
    /* 0x062A70: mov.w @r4,r7 */
    uint32_t t4 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)s->r[4];
    s->r[7] = t4;
    /* 0x062A72: op 0x6603 */
    s->r[6] = s->r[0];
    /* 0x062A74: mov.w @r3,r5 */
    uint32_t t6 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)0xFFFF8920; /* RAM 0xFFFF8920 */
    s->r[5] = t6;
    /* 0x062A76: op 0x677D */
    s->r[7] = s->r[7] & 0xFFFFu;
    /* 0x062A78: op 0xD243 */
    s->r[2] = 0xFFFF87D0u;
    /* 0x062A7A: op 0x6E6C */
    s->r[14] = s->r[6] & 0xFFu;
    /* 0x062A7C: op 0xD040 */
    s->r[0] = 0xFFFF8D74u;
    /* 0x062A7E: op 0x655D */
    s->r[5] = s->r[5] & 0xFFFFu;
    /* 0x062A80: op 0xDD42 */
    s->r[13] = 0x000616C8u;
    /* 0x062A82: op 0x4700 */
    s->T = (s->r[7] >> 31) & 1u; s->r[7] = (s->r[7] << 1);
    /* 0x062A84: mov.b @(r0,r7),r7 */
    uint32_t t8 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)(s->r[7] + s->r[0]);
    s->r[7] = t8;
    /* 0x062A86: op 0x4508 */
    s->r[5] = (s->r[5] << 2);
    /* 0x062A88: op 0x4508 */
    s->r[5] = (s->r[5] << 2);
    /* 0x062A8A: op 0x352C */
    s->r[5] = s->r[5] + s->r[2];
    /* 0x062A8C: mov.b @(0xA,r5),r0 */
    uint32_t t10 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)(s->r[5] + 10);
    s->r[0] = t10;
    /* 0x062A8E: mov.b r0,@r15 */
    local_3f0 = s->r[0];
    /* 0x062A90: op 0xE001 */
    s->r[0] = (uint32_t)(int32_t)(int8_t)0x01;
    /* 0x062A92: op 0x3E03 */
    s->T = ((int32_t)s->r[14] >= (int32_t)s->r[0]) ? 1u : 0u;
    /* 0x062A94: bf.s 0x062AC6 */
    /* 0x062A96: op 0x0009 */
    
    if (!s->T) goto L_62AC6;
    /* 0x062A98: op 0xE13F */
    s->r[1] = (uint32_t)(int32_t)(int8_t)0x3F;
    /* 0x062A9A: op 0x3E17 */
    s->T = ((int32_t)s->r[14] > (int32_t)s->r[1]) ? 1u : 0u;
    /* 0x062A9C: bt.s 0x062AC6 */
    /* 0x062A9E: op 0x0009 */
    
    if (s->T) goto L_62AC6;
    /* 0x062AA0: mov.b @r15,r2 */
    s->r[2] = (uint32_t)(int32_t)(int8_t)(local_3f0 & 0xFFu);
    /* 0x062AA2: op 0xE350 */
    s->r[3] = (uint32_t)(int32_t)(int8_t)0x50;
    /* 0x062AA4: op 0x622C */
    s->r[2] = s->r[2] & 0xFFu;
    /* 0x062AA6: op 0x3233 */
    s->T = ((int32_t)s->r[2] >= (int32_t)s->r[3]) ? 1u : 0u;
    /* 0x062AA8: bt.s 0x062AB4 */
    /* 0x062AAA: op 0x0009 */
    
    if (s->T) goto L_62AB4;
    /* 0x062AAC: op 0x607C */
    s->r[0] = s->r[7] & 0xFFu;
    /* 0x062AAE: op 0x8811 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x11) ? 1u : 0u;
    /* 0x062AB0: bf.s 0x062B1A */
    /* 0x062AB2: op 0x0009 */
    
    if (!s->T) goto L_62B1A;
    L_62AB4: ;
    /* 0x062AB4: jsr @r13 */
    s->pr = 0x00062AB8;
    s->r[4] = (uint32_t)(int32_t)(int8_t)0x00;
    f_616C8(s);
    /* 0x062AB8: op 0xD335 */
    s->r[3] = 0x000619FAu;
    /* 0x062ABA: op 0xE408 */
    s->r[4] = (uint32_t)(int32_t)(int8_t)0x08;
    /* 0x062ABC: op 0x7F04 */
    s->r[15] = s->r[15] + (uint32_t)(int32_t)(int8_t)0x04;
    /* 0x062ABE: lds.l @r15+,pr */
    s->pr = local_3f4;
    /* 0x062AC0: mov.l @r15+,r13 */
    s->r[13] = local_3f8;
    /* 0x062AC2: jmp @r3 (tail) */
    s->r[14] = local_3fc;
    f_619FA(s);
    return;
    L_62B1A: ;
    /* 0x062B1A: op 0x7F04 */
    s->r[15] = s->r[15] + (uint32_t)(int32_t)(int8_t)0x04;
    /* 0x062B1C: lds.l @r15+,pr */
    s->pr = local_404;
    /* 0x062B1E: mov.l @r15+,r13 */
    s->r[13] = local_408;
    /* 0x062B20: rts */
    /* 0x062B22: mov.l @r15+,r14 */
    s->r[14] = local_40c;
    return;
    L_62AC6: ;
    /* 0x062AC6: op 0x9358 */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0xC0u;
    /* 0x062AC8: op 0x3E30 */
    s->T = (s->r[14] == s->r[3]) ? 1u : 0u;
    /* 0x062ACA: bf.s 0x062AEC */
    /* 0x062ACC: op 0x0009 */
    
    if (!s->T) goto L_62AEC;
    /* 0x062ACE: op 0xD031 */
    s->r[0] = 0x0007C7C6u;
    /* 0x062AD0: mov.w @r4,r2 */
    uint32_t t12 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)s->r[4];
    s->r[2] = t12;
    /* 0x062AD2: op 0x622D */
    s->r[2] = s->r[2] & 0xFFFFu;
    /* 0x062AD4: mov.b @(r2+r0),r1 (rt-base) */
    uint32_t t13 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)(s->r[2] + s->r[0]);
    s->r[1] = t13;
    /* 0x062AD6: op 0x611C */
    s->r[1] = s->r[1] & 0xFFu;
    /* 0x062AD8: mov.b @(0x8,r5),r0 */
    uint32_t t15 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)(s->r[5] + 8);
    s->r[0] = t15;
    /* 0x062ADA: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x062ADC: op 0x3013 */
    s->T = ((int32_t)s->r[0] >= (int32_t)s->r[1]) ? 1u : 0u;
    /* 0x062ADE: bf.s 0x062B1A */
    /* 0x062AE0: op 0x0009 */
    
    if (!s->T) goto L_62B1A;
    /* 0x062AE2: op 0x944B */
    s->r[4] = (uint32_t)(int32_t)(int16_t)0xC1u;
    /* 0x062AE4: jsr @r13 */
    s->pr = 0x00062AE8;
    
    f_616C8(s);
    /* 0x062AE8: bra 0x062B1A */
    /* 0x062AEA: op 0x0009 */
    
    goto L_62B1A;
    L_62AEC: ;
    /* 0x062AEC: op 0x9246 */
    s->r[2] = (uint32_t)(int32_t)(int16_t)0xC1u;
    /* 0x062AEE: op 0x3E20 */
    s->T = (s->r[14] == s->r[2]) ? 1u : 0u;
    /* 0x062AF0: bf.s 0x062B1A */
    /* 0x062AF2: op 0x0009 */
    
    if (!s->T) goto L_62B1A;
    /* 0x062AF4: op 0xD028 */
    s->r[0] = 0x0007C852u;
    /* 0x062AF6: mov.w @r4,r1 */
    uint32_t t17 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)s->r[4];
    s->r[1] = t17;
    /* 0x062AF8: op 0x611D */
    s->r[1] = s->r[1] & 0xFFFFu;
    /* 0x062AFA: mov.b @(r1+r0),r3 (rt-base) */
    uint32_t t18 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)(s->r[1] + s->r[0]);
    s->r[3] = t18;
    /* 0x062AFC: mov.b @(0x9,r5),r0 */
    uint32_t t20 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)(s->r[5] + 9);
    s->r[0] = t20;
    /* 0x062AFE: op 0x633C */
    s->r[3] = s->r[3] & 0xFFu;
    /* 0x062B00: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x062B02: op 0x3033 */
    s->T = ((int32_t)s->r[0] >= (int32_t)s->r[3]) ? 1u : 0u;
    /* 0x062B04: bf.s 0x062B1A */
    /* 0x062B06: op 0x0009 */
    
    if (!s->T) goto L_62B1A;
    /* 0x062B08: jsr @r13 */
    s->pr = 0x00062B0C;
    s->r[4] = (uint32_t)(int32_t)(int8_t)0x00;
    f_616C8(s);
    /* 0x062B0C: op 0xD320 */
    s->r[3] = 0x000619FAu;
    /* 0x062B0E: op 0xE408 */
    s->r[4] = (uint32_t)(int32_t)(int8_t)0x08;
    /* 0x062B10: op 0x7F04 */
    s->r[15] = s->r[15] + (uint32_t)(int32_t)(int8_t)0x04;
    /* 0x062B12: lds.l @r15+,pr */
    s->pr = local_414;
    /* 0x062B14: mov.l @r15+,r13 */
    s->r[13] = local_418;
    /* 0x062B16: jmp @r3 (tail) */
    s->r[14] = local_41c;
    f_619FA(s);
    return;
    return; /* fallthrough */
}
