/* ROM: 60E0FC00 | Address: 0x647C0 | Size: 198 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST callee (CFG).
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_66A14(ST *s);
void f_647C0(ST *s)
{
    uint32_t local_3dc = 0;
    uint32_t local_3e8 = 0;
    uint32_t local_3ec = 0;
    uint32_t local_3f0 = 0;
    uint32_t local_3f4 = 0;
    uint32_t local_3f8 = 0;
    uint32_t local_3fc = 0;
    uint32_t local_40b = 0;
    /* 0x0647C0: mov.l r14,@-r15 */
    local_3fc = s->r[14];
    /* 0x0647C2: op 0xEE00 */
    s->r[14] = (uint32_t)(int32_t)(int8_t)0x00;
    /* 0x0647C4: op 0xD745 */
    s->r[7] = 0x0005D5E4u;
    /* 0x0647C6: op 0x66E3 */
    s->r[6] = s->r[14];
    /* 0x0647C8: mov.l r13,@-r15 */
    local_3f8 = s->r[13];
    /* 0x0647CA: op 0x6DE3 */
    s->r[13] = s->r[14];
    /* 0x0647CC: mov.l r12,@-r15 */
    local_3f4 = s->r[12];
    /* 0x0647CE: mov.l r10,@-r15 */
    local_3f0 = s->r[10];
    /* 0x0647D0: mov.l r9,@-r15 */
    local_3ec = s->r[9];
    /* 0x0647D2: sts.l pr,@-r15 */
    local_3e8 = s->pr;
    /* 0x0647D4: op 0xDA40 */
    s->r[10] = 0xFFFFD62Au;
    /* 0x0647D6: op 0x7FF4 */
    s->r[15] = s->r[15] + (uint32_t)(int32_t)(int8_t)0xF4;
    /* 0x0647D8: op 0x63F3 */
    s->r[3] = s->r[15];
    /* 0x0647DA: op 0x730B */
    s->r[3] = s->r[3] + (uint32_t)(int32_t)(int8_t)0x0B;
    /* 0x0647DC: mov.b r4,@r3 (rt-base) */
    *(volatile uint8_t*)s->r[3] = s->r[4];
    /* 0x0647DE: op 0x61F3 */
    s->r[1] = s->r[15];
    /* 0x0647E0: op 0x710A */
    s->r[1] = s->r[1] + (uint32_t)(int32_t)(int8_t)0x0A;
    /* 0x0647E2: op 0x64E3 */
    s->r[4] = s->r[14];
    /* 0x0647E4: mov.b r5,@r1 (rt-base) */
    *(volatile uint8_t*)s->r[1] = s->r[5];
    /* 0x0647E6: op 0x69F3 */
    s->r[9] = s->r[15];
    /* 0x0647E8: op 0x9174 */
    s->r[1] = (uint32_t)(int32_t)(int16_t)0xFFu;
    /* 0x0647EA: bra 0x064824 */
    /* 0x0647EC: op 0x7904 */
    s->r[9] = s->r[9] + (uint32_t)(int32_t)(int8_t)0x04;
    goto L_64824;
    L_64824: ;
    /* 0x064824: op 0x624C */
    s->r[2] = s->r[4] & 0xFFu;
    /* 0x064826: op 0x4200 */
    s->T = (s->r[2] >> 31) & 1u; s->r[2] = (s->r[2] << 1);
    /* 0x064828: op 0x327C */
    s->r[2] = s->r[2] + s->r[7];
    /* 0x06482A: mov.b @r2,r3 (rt-base) */
    uint32_t t1 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)s->r[2];
    s->r[3] = t1;
    /* 0x06482C: op 0x633C */
    s->r[3] = s->r[3] & 0xFFu;
    /* 0x06482E: op 0x3310 */
    s->T = (s->r[3] == s->r[1]) ? 1u : 0u;
    /* 0x064830: bt.s 0x06483E */
    /* 0x064832: op 0x0009 */
    
    if (s->T) goto L_6483E;
    /* 0x064834: op 0x636C */
    s->r[3] = s->r[6] & 0xFFu;
    /* 0x064836: op 0xE228 */
    s->r[2] = (uint32_t)(int32_t)(int8_t)0x28;
    /* 0x064838: op 0x3323 */
    s->T = ((int32_t)s->r[3] >= (int32_t)s->r[2]) ? 1u : 0u;
    /* 0x06483A: bf.s 0x0647EE */
    /* 0x06483C: op 0x0009 */
    
    if (!s->T) goto L_647EE;
    L_6483E: ;
    /* 0x06483E: op 0x61DC */
    s->r[1] = s->r[13] & 0xFFu;
    /* 0x064840: op 0x2118 */
    s->T = ((s->r[1] & s->r[1]) == 0u) ? 1u : 0u;
    /* 0x064842: bt.s 0x064876 */
    /* 0x064844: op 0x0009 */
    
    if (s->T) goto L_64876;
    /* 0x064846: op 0xE601 */
    s->r[6] = (uint32_t)(int32_t)(int8_t)0x01;
    /* 0x064848: op 0xDC25 */
    s->r[12] = 0x00066A14u;
    /* 0x06484A: op 0x65F3 */
    s->r[5] = s->r[15];
    /* 0x06484C: op 0x750B */
    s->r[5] = s->r[5] + (uint32_t)(int32_t)(int8_t)0x0B;
    /* 0x06484E: jsr @r12 */
    s->pr = 0x00064852;
    s->r[4] = (uint32_t)(int32_t)(int8_t)0x02;
    f_66A14(s);
    /* 0x064852: op 0xE601 */
    s->r[6] = (uint32_t)(int32_t)(int8_t)0x01;
    /* 0x064854: op 0x65F3 */
    s->r[5] = s->r[15];
    /* 0x064856: op 0x750A */
    s->r[5] = s->r[5] + (uint32_t)(int32_t)(int8_t)0x0A;
    /* 0x064858: jsr @r12 */
    s->pr = 0x0006485C;
    s->r[4] = (uint32_t)(int32_t)(int8_t)0x02;
    f_66A14(s);
    /* 0x06485C: op 0xDE21 */
    s->r[14] = 0xFFFFD628u;
    /* 0x06485E: op 0x66DC */
    s->r[6] = s->r[13] & 0xFFu;
    /* 0x064860: mov.w @r14,r2 */
    uint32_t t3 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)s->r[14]; /* RAM 0xFFFFD628 */
    s->r[2] = t3;
    /* 0x064862: op 0x6593 */
    s->r[5] = s->r[9];
    /* 0x064864: op 0x7202 */
    s->r[2] = s->r[2] + (uint32_t)(int32_t)(int8_t)0x02;
    /* 0x064866: mov.w r2,@r14 */
    *(volatile uint16_t*)s->r[14] = s->r[2]; /* RAM 0xFFFFD628 */
    /* 0x064868: mov.w r6,@r15 */
    local_3dc = s->r[6];
    /* 0x06486A: jsr @r12 */
    s->pr = 0x0006486E;
    s->r[4] = (uint32_t)(int32_t)(int8_t)0x02;
    f_66A14(s);
    /* 0x06486E: mov.w @r15,r3 */
    s->r[3] = (uint32_t)(int32_t)(int16_t)(local_3dc & 0xFFFFu);
    /* 0x064870: mov.w @r14,r2 */
    uint32_t t5 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)s->r[14]; /* RAM 0xFFFFD628 */
    s->r[2] = t5;
    /* 0x064872: op 0x323C */
    s->r[2] = s->r[2] + s->r[3];
    /* 0x064874: mov.w r2,@r14 */
    *(volatile uint16_t*)s->r[14] = s->r[2]; /* RAM 0xFFFFD628 */
    L_64876: ;
    /* 0x064876: op 0x7F0C */
    s->r[15] = s->r[15] + (uint32_t)(int32_t)(int8_t)0x0C;
    /* 0x064878: lds.l @r15+,pr */
    s->pr = local_3e8;
    /* 0x06487A: mov.l @r15+,r9 */
    s->r[9] = local_3ec;
    /* 0x06487C: mov.l @r15+,r10 */
    s->r[10] = local_3f0;
    /* 0x06487E: mov.l @r15+,r12 */
    s->r[12] = local_3f4;
    /* 0x064880: mov.l @r15+,r13 */
    s->r[13] = local_3f8;
    /* 0x064882: rts */
    /* 0x064884: mov.l @r15+,r14 */
    s->r[14] = local_3fc;
    return;
    L_647EE: ;
    /* 0x0647EE: op 0x6C4C */
    s->r[12] = s->r[4] & 0xFFu;
    /* 0x0647F0: op 0x4C00 */
    s->T = (s->r[12] >> 31) & 1u; s->r[12] = (s->r[12] << 1);
    /* 0x0647F2: op 0x3C7C */
    s->r[12] = s->r[12] + s->r[7];
    /* 0x0647F4: mov.b @r12,r0 (rt-base) */
    uint32_t t6 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)(s->r[12] + 1);
    s->r[0] = t6;
    /* 0x0647F6: op 0x6503 */
    s->r[5] = s->r[0];
    /* 0x0647F8: mov.b @r12,r3 (rt-base) */
    uint32_t t7 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)s->r[12];
    s->r[3] = t7;
    /* 0x0647FA: mov.b @(0xB,r15),r0 */
    s->r[0] = (uint32_t)(int32_t)(int8_t)(local_40b & 0xFFu);
    /* 0x0647FC: op 0x3300 */
    s->T = (s->r[3] == s->r[0]) ? 1u : 0u;
    /* 0x0647FE: bf.s 0x064820 */
    /* 0x064800: op 0x0009 */
    
    if (!s->T) goto L_64820;
    /* 0x064802: op 0x67E3 */
    s->r[7] = s->r[14];
    /* 0x064804: op 0x6D6C */
    s->r[13] = s->r[6] & 0xFFu;
    /* 0x064806: op 0x3DAC */
    s->r[13] = s->r[13] + s->r[10];
    /* 0x064808: op 0x665C */
    s->r[6] = s->r[5] & 0xFFu;
    /* 0x06480A: op 0x4615 */
    s->T = ((int32_t)s->r[6] > 0) ? 1u : 0u;
    /* 0x06480C: bf.s 0x06481C */
    /* 0x06480E: op 0x6493 */
    s->r[4] = s->r[9];
    if (!s->T) goto L_6481C;
    L_64810: ;
    /* 0x064810: mov.b @r13+,r3 (rt-base) */
    uint32_t t8 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)s->r[13];
    s->r[3] = t8;
    s->r[13] = s->r[13] + 1;
    /* 0x064812: op 0x7701 */
    s->r[7] = s->r[7] + (uint32_t)(int32_t)(int8_t)0x01;
    /* 0x064814: mov.b r3,@r4 */
    *(volatile uint8_t*)s->r[4] = s->r[3];
    /* 0x064816: op 0x3763 */
    s->T = ((int32_t)s->r[7] >= (int32_t)s->r[6]) ? 1u : 0u;
    /* 0x064818: bf.s 0x064810 */
    /* 0x06481A: op 0x7401 */
    s->r[4] = s->r[4] + (uint32_t)(int32_t)(int8_t)0x01;
    if (!s->T) goto L_64810;
    L_6481C: ;
    /* 0x06481C: bra 0x06483E */
    /* 0x06481E: op 0x6D53 */
    s->r[13] = s->r[5];
    goto L_6483E;
    L_64820: ;
    /* 0x064820: op 0x365C */
    s->r[6] = s->r[6] + s->r[5];
    /* 0x064822: op 0x7401 */
    s->r[4] = s->r[4] + (uint32_t)(int32_t)(int8_t)0x01;
    return; /* fallthrough */
}
