/* ROM: 60E1D400 | Address: 0x65E1C | Size: 160 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST callee (CFG).
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_63110(ST *s);
void f_63354(ST *s);
void f_65FD8(ST *s);
void f_68078(ST *s);
void f_680B0(ST *s);
void f_68104(ST *s);
void f_6811A(ST *s);
void f_685C4(ST *s);
void f_685F8(ST *s);
void f_68642(ST *s);
void f_68656(ST *s);
void f_686A0(ST *s);
void f_686B4(ST *s);
void f_65E1C(ST *s)
{
    uint32_t local_3ec = 0;
    uint32_t local_3f0 = 0;
    uint32_t local_3f4 = 0;
    uint32_t local_3f8 = 0;
    uint32_t local_3fc = 0;
    /* 0x065E1C: mov.l r14,@-r15 */
    local_3fc = s->r[14];
    /* 0x065E1E: op 0x6043 */
    s->r[0] = s->r[4];
    /* 0x065E20: op 0xD33E */
    s->r[3] = 0x00063110u;
    /* 0x065E22: op 0x6E53 */
    s->r[14] = s->r[5];
    /* 0x065E24: mov.l r13,@-r15 */
    local_3f8 = s->r[13];
    /* 0x065E26: sts.l pr,@-r15 */
    local_3f4 = s->pr;
    /* 0x065E28: op 0x7FF8 */
    s->r[15] = s->r[15] + (uint32_t)(int32_t)(int8_t)0xF8;
    /* 0x065E2A: mov.w r0,@(0x4,r15) */
    local_3f0 = s->r[0];
    /* 0x065E2C: mov.b r6,@r15 */
    local_3ec = s->r[6];
    /* 0x065E2E: jsr @r3 */
    s->pr = 0x00065E32;
    s->r[4] = (uint32_t)(int32_t)(int8_t)0x00;
    f_63110(s);
    /* 0x065E32: bsr 0x65FD8 */
    s->pr = 0x00065E36;
    s->r[4] = (uint32_t)(int32_t)(int8_t)(local_3ec & 0xFFu);
    f_65FD8(s);
    /* 0x065E36: mov.b r0,@r15 */
    local_3ec = s->r[0];
    /* 0x065E38: op 0xD339 */
    s->r[3] = 0x000686B4u;
    /* 0x065E3A: jsr @r3 */
    s->pr = 0x00065E3E;
    s->r[4] = (uint32_t)(int32_t)(int8_t)0x00;
    f_686B4(s);
    /* 0x065E3E: op 0x6D03 */
    s->r[13] = s->r[0];
    /* 0x065E40: op 0xD238 */
    s->r[2] = 0x000686A0u;
    /* 0x065E42: op 0x2DEB */
    s->r[13] |= s->r[14];
    /* 0x065E44: jsr @r2 */
    s->pr = 0x00065E48;
    s->r[4] = s->r[13];
    f_686A0(s);
    /* 0x065E48: mov.w @(0x4,r15),r0 */
    s->r[0] = (uint32_t)(int32_t)(int16_t)(local_3f0 & 0xFFFFu);
    /* 0x065E4A: op 0xD337 */
    s->r[3] = 0x0006811Au;
    /* 0x065E4C: jsr @r3 */
    s->pr = 0x00065E50;
    s->r[4] = s->r[0];
    f_6811A(s);
    /* 0x065E50: op 0xD236 */
    s->r[2] = 0x00068104u;
    /* 0x065E52: op 0x6403 */
    s->r[4] = s->r[0];
    /* 0x065E54: jsr @r2 */
    s->pr = 0x00065E58;
    s->r[4] |= s->r[14];
    f_68104(s);
    /* 0x065E58: op 0xD335 */
    s->r[3] = 0x00068656u;
    /* 0x065E5A: jsr @r3 */
    s->pr = 0x00065E5E;
    s->r[4] = (uint32_t)(int32_t)(int8_t)0x00;
    f_68656(s);
    /* 0x065E5E: op 0x640D */
    s->r[4] = s->r[0] & 0xFFFFu;
    /* 0x065E60: op 0x2448 */
    s->T = ((s->r[4] & s->r[4]) == 0u) ? 1u : 0u;
    /* 0x065E62: bf.s 0x065E6C */
    /* 0x065E64: op 0x0009 */
    
    if (!s->T) goto L_65E6C;
    /* 0x065E66: op 0xD333 */
    s->r[3] = 0x00068642u;
    /* 0x065E68: jsr @r3 */
    s->pr = 0x00065E6C;
    s->r[4] = s->r[14];
    f_68642(s);
    L_65E6C: ;
    /* 0x065E6C: mov.b @r15,r0 */
    s->r[0] = (uint32_t)(int32_t)(int8_t)(local_3ec & 0xFFu);
    /* 0x065E6E: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x065E70: op 0x8870 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x70) ? 1u : 0u;
    /* 0x065E72: bt.s 0x065E8A */
    /* 0x065E74: op 0x0009 */
    
    if (s->T) goto L_65E8A;
    /* 0x065E76: op 0x914F */
    s->r[1] = (uint32_t)(int32_t)(int16_t)0xC0u;
    /* 0x065E78: op 0x3010 */
    s->T = (s->r[0] == s->r[1]) ? 1u : 0u;
    /* 0x065E7A: bt.s 0x065E8A */
    /* 0x065E7C: op 0x0009 */
    
    if (s->T) goto L_65E8A;
    /* 0x065E7E: op 0x914C */
    s->r[1] = (uint32_t)(int32_t)(int16_t)0xC1u;
    /* 0x065E80: op 0x3010 */
    s->T = (s->r[0] == s->r[1]) ? 1u : 0u;
    /* 0x065E82: bt.s 0x065E8A */
    /* 0x065E84: op 0x0009 */
    
    if (s->T) goto L_65E8A;
    /* 0x065E86: bra 0x065EAE */
    /* 0x065E88: op 0x0009 */
    
    goto L_65EAE;
    L_65E8A: ;
    /* 0x065E8A: mov.w @(0x4,r15),r0 */
    s->r[0] = (uint32_t)(int32_t)(int16_t)(local_3f0 & 0xFFFFu);
    /* 0x065E8C: op 0xD32A */
    s->r[3] = 0x000680B0u;
    /* 0x065E8E: jsr @r3 */
    s->pr = 0x00065E92;
    s->r[4] = s->r[0];
    f_680B0(s);
    /* 0x065E92: op 0x6403 */
    s->r[4] = s->r[0];
    /* 0x065E94: op 0xD229 */
    s->r[2] = 0x00068078u;
    /* 0x065E96: jsr @r2 */
    s->pr = 0x00065E9A;
    s->r[4] |= s->r[14];
    f_68078(s);
    /* 0x065E9A: op 0xD329 */
    s->r[3] = 0x000685F8u;
    /* 0x065E9C: jsr @r3 */
    s->pr = 0x00065EA0;
    s->r[4] = (uint32_t)(int32_t)(int8_t)0x00;
    f_685F8(s);
    /* 0x065EA0: op 0x640D */
    s->r[4] = s->r[0] & 0xFFFFu;
    /* 0x065EA2: op 0x2448 */
    s->T = ((s->r[4] & s->r[4]) == 0u) ? 1u : 0u;
    /* 0x065EA4: bf.s 0x065EAE */
    /* 0x065EA6: op 0x0009 */
    
    if (!s->T) goto L_65EAE;
    /* 0x065EA8: op 0xD326 */
    s->r[3] = 0x000685C4u;
    /* 0x065EAA: jsr @r3 */
    s->pr = 0x00065EAE;
    s->r[4] = s->r[13];
    f_685C4(s);
    L_65EAE: ;
    /* 0x065EAE: op 0xE400 */
    s->r[4] = (uint32_t)(int32_t)(int8_t)0x00;
    /* 0x065EB0: op 0xD225 */
    s->r[2] = 0x00063354u;
    /* 0x065EB2: op 0x7F08 */
    s->r[15] = s->r[15] + (uint32_t)(int32_t)(int8_t)0x08;
    /* 0x065EB4: lds.l @r15+,pr */
    s->pr = local_3f4;
    /* 0x065EB6: mov.l @r15+,r13 */
    s->r[13] = local_3f8;
    /* 0x065EB8: jmp @r2 (tail) */
    s->r[14] = local_3fc;
    f_63354(s);
    return;
    return; /* fallthrough */
}
