/* ROM: 60E0FC00 | Address: 0x66DA4 | Size: 148 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST callee (CFG).
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_9630(ST *s);
void f_67412(ST *s);
void f_674B6(ST *s);
void f_6765A(ST *s);
void f_66DA4(ST *s)
{
    uint32_t local_3e4 = 0;
    uint32_t local_3e8 = 0;
    uint32_t local_3f8 = 0;
    uint32_t local_3fc = 0;
    /* 0x066DA4: mov.l r14,@-r15 */
    local_3fc = s->r[14];
    /* 0x066DA6: sts.l pr,@-r15 */
    local_3f8 = s->pr;
    /* 0x066DA8: op 0xDE1C */
    s->r[14] = 0xFFFFDBF6u;
    /* 0x066DAA: op 0x7FEC */
    s->r[15] = s->r[15] + (uint32_t)(int32_t)(int8_t)0xEC;
    /* 0x066DAC: mov.l r4,@r15 */
    local_3e4 = s->r[4];
    /* 0x066DAE: mov.b @(0x6,r14),r0 */
    uint32_t t2 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFDBFC; /* RAM 0xFFFFDBFC */
    s->r[0] = t2;
    /* 0x066DB0: bsr 0x67412 */
    s->pr = 0x00066DB4;
    s->r[4] = s->r[0];
    f_67412(s);
    /* 0x066DB4: op 0xD21B */
    s->r[2] = 0x000674B6u;
    /* 0x066DB6: op 0xE528 */
    s->r[5] = (uint32_t)(int32_t)(int8_t)0x28;
    /* 0x066DB8: jsr @r2 */
    s->pr = 0x00066DBC;
    s->r[4] = (uint32_t)(int32_t)(int8_t)0x01;
    f_674B6(s);
    /* 0x066DBC: op 0x922C */
    s->r[2] = (uint32_t)(int32_t)(int16_t)0x000007DFu;
    /* 0x066DBE: op 0x65F3 */
    s->r[5] = s->r[15];
    /* 0x066DC0: op 0x7508 */
    s->r[5] = s->r[5] + (uint32_t)(int32_t)(int8_t)0x08;
    /* 0x066DC2: op 0x6353 */
    s->r[3] = s->r[5];
    /* 0x066DC4: mov.l r3,@(0x4,r15) */
    local_3e8 = s->r[3];
    /* 0x066DC6: op 0xE600 */
    s->r[6] = (uint32_t)(int32_t)(int8_t)0x00;
    /* 0x066DC8: mov.b @(0x4,r14),r0 */
    uint32_t t4 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFDBFA; /* RAM 0xFFFFDBFA */
    s->r[0] = t4;
    /* 0x066DCA: op 0x6453 */
    s->r[4] = s->r[5];
    /* 0x066DCC: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x066DCE: mov.l r0,@r3 (rt-base) */
    *(volatile uint32_t*)s->r[3] = s->r[0];
    /* 0x066DD0: mov.w @r14,r3 */
    uint32_t t6 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)0xFFFFDBF6; /* RAM 0xFFFFDBF6 */
    s->r[3] = t6;
    /* 0x066DD2: op 0x633D */
    s->r[3] = s->r[3] & 0xFFFFu;
    /* 0x066DD4: mov.l r3,@(0x4,r5) */
    *(volatile uint32_t*)(s->r[5] + 4) = s->r[3];
    /* 0x066DD6: mov.l @r15,r3 */
    s->r[3] = local_3e4;
    /* 0x066DD8: op 0x3320 */
    s->T = (s->r[3] == s->r[2]) ? 1u : 0u;
    /* 0x066DDA: bf.s 0x066DE2 */
    /* 0x066DDC: op 0x7408 */
    s->r[4] = s->r[4] + (uint32_t)(int32_t)(int8_t)0x08;
    if (!s->T) goto L_66DE2;
    /* 0x066DDE: bra 0x066DE6 */
    /* 0x066DE0: mov.l r6,@r4 */
    *(volatile uint32_t*)s->r[4] = s->r[6];
    goto L_66DE6;
    L_66DE6: ;
    /* 0x066DE6: mov.b @(0x4,r14),r0 */
    uint32_t t8 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)(s->r[14] + 4); /* RAM 0xFFFFDBFA */
    s->r[0] = t8;
    /* 0x066DE8: op 0xD30F */
    s->r[3] = 0xFFFFDC09u;
    /* 0x066DEA: mov.b r0,@r3 */
    *(volatile uint8_t*)0xFFFFDC09 = s->r[0]; /* RAM 0xFFFFDC09 */
    /* 0x066DEC: op 0xD40F */
    s->r[4] = 0xFFFFDC05u;
    /* 0x066DEE: op 0x6063 */
    s->r[0] = s->r[6];
    /* 0x066DF0: op 0xD20F */
    s->r[2] = 0x0006765Au;
    /* 0x066DF2: mov.b r0,@(0x5,r14) */
    *(volatile uint8_t*)0xFFFFDBFB = s->r[0]; /* RAM 0xFFFFDBFB */
    /* 0x066DF4: mov.b @r4,r0 */
    uint32_t t10 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)s->r[4]; /* RAM 0xFFFFDC05 */
    s->r[0] = t10;
    /* 0x066DF6: op 0xCB40 */
    s->r[0] |= 0x40u;
    /* 0x066DF8: mov.b r0,@r4 */
    *(volatile uint8_t*)s->r[4] = s->r[0]; /* RAM 0xFFFFDC05 */
    /* 0x066DFA: mov.b @r4,r0 */
    uint32_t t12 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)s->r[4]; /* RAM 0xFFFFDC05 */
    s->r[0] = t12;
    /* 0x066DFC: op 0xC9FB */
    s->r[0] &= 0xFBu;
    /* 0x066DFE: mov.b r0,@r4 */
    *(volatile uint8_t*)s->r[4] = s->r[0]; /* RAM 0xFFFFDC05 */
    /* 0x066E00: mov.b @(0x4,r14),r0 */
    uint32_t t14 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFDBFA; /* RAM 0xFFFFDBFA */
    s->r[0] = t14;
    /* 0x066E02: jsr @r2 */
    s->pr = 0x00066E06;
    s->r[4] = s->r[0];
    f_6765A(s);
    /* 0x066E06: op 0xE500 */
    s->r[5] = (uint32_t)(int32_t)(int8_t)0x00;
    /* 0x066E08: op 0xD30A */
    s->r[3] = 0x00009630u;
    /* 0x066E0A: mov.l @(0x4,r15),r6 */
    s->r[6] = local_3e8;
    /* 0x066E0C: jsr @r3 */
    s->pr = 0x00066E10;
    s->r[4] = (uint32_t)(int32_t)(int8_t)0x02;
    f_9630(s);
    /* 0x066E10: op 0x7F14 */
    s->r[15] = s->r[15] + (uint32_t)(int32_t)(int8_t)0x14;
    /* 0x066E12: lds.l @r15+,pr */
    s->pr = local_3f8;
    /* 0x066E14: rts */
    /* 0x066E16: mov.l @r15+,r14 */
    s->r[14] = local_3fc;
    return;
    L_66DE2: ;
    /* 0x066DE2: op 0xE101 */
    s->r[1] = (uint32_t)(int32_t)(int8_t)0x01;
    /* 0x066DE4: mov.l r1,@r4 */
    *(volatile uint32_t*)s->r[4] = s->r[1];
    return; /* fallthrough */
}
