/* ROM: 60E0FC00 | Address: 0x6684 | Size: 34 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST callee (CFG).
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_9016(ST *s);
void f_C1F8(ST *s);
void f_CF74(ST *s);
void f_11CA2(ST *s);
void f_6684(ST *s)
{
    uint32_t local_3f8 = 0;
    uint32_t local_3fc = 0;
    /* 0x006684: mov.l r14,@-r15 */
    local_3fc = s->r[14];
    /* 0x006686: op 0x6E43 */
    s->r[14] = s->r[4];
    /* 0x006688: op 0xD327 */
    s->r[3] = 0x00009016u;
    /* 0x00668A: sts.l pr,@-r15 */
    local_3f8 = s->pr;
    /* 0x00668C: jsr @r3 */
    s->pr = 0x00006690;
    uint32_t t1 = *(volatile uint32_t*)s->r[14];
    s->r[4] = t1;
    f_9016(s);
    /* 0x006690: op 0xD226 */
    s->r[2] = 0x0000CF74u;
    /* 0x006692: jsr @r2 */
    s->pr = 0x00006696;
    uint32_t t2 = *(volatile uint32_t*)s->r[14];
    s->r[4] = t2;
    f_CF74(s);
    /* 0x006696: op 0xD326 */
    s->r[3] = 0x0000C1F8u;
    /* 0x006698: jsr @r3 */
    s->pr = 0x0000669C;
    
    f_C1F8(s);
    /* 0x00669C: mov.l @r14,r4 (rt-base) */
    uint32_t t3 = *(volatile uint32_t*)s->r[14];
    s->r[4] = t3;
    /* 0x00669E: lds.l @r15+,pr */
    s->pr = local_3f8;
    /* 0x0066A0: op 0xD224 */
    s->r[2] = 0x00011CA2u;
    /* 0x0066A2: jmp @r2 (tail) */
    s->r[14] = local_3fc;
    f_11CA2(s);
    return;
    return; /* fallthrough */
}
