/* ROM: 60E0FC00 | Address: 0x661A4 | Size: 104 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST callee (CFG).
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_661A4(ST *s)
{
    uint32_t local_3fc = 0;
    /* 0x0661A4: mov.l r14,@-r15 */
    local_3fc = s->r[14];
    /* 0x0661A6: op 0xE500 */
    s->r[5] = (uint32_t)(int32_t)(int8_t)0x00;
    /* 0x0661A8: op 0xD613 */
    s->r[6] = 0xFFFF8EA0u;
    /* 0x0661AA: op 0xE707 */
    s->r[7] = (uint32_t)(int32_t)(int8_t)0x07;
    /* 0x0661AC: op 0x6E53 */
    s->r[14] = s->r[5];
    L_661AE: ;
    /* 0x0661AE: op 0x6353 */
    s->r[3] = s->r[5];
    /* 0x0661B0: op 0x6253 */
    s->r[2] = s->r[5];
    /* 0x0661B2: op 0x4308 */
    s->r[3] = (s->r[3] << 2);
    /* 0x0661B4: op 0x332C */
    s->r[3] = s->r[3] + s->r[2];
    /* 0x0661B6: op 0x4308 */
    s->r[3] = (s->r[3] << 2);
    /* 0x0661B8: op 0x4300 */
    s->T = (s->r[3] >> 31) & 1u; s->r[3] = (s->r[3] << 1);
    /* 0x0661BA: op 0x336C */
    s->r[3] = s->r[3] + s->r[6];
    /* 0x0661BC: op 0xE020 */
    s->r[0] = (uint32_t)(int32_t)(int8_t)0x20;
    /* 0x0661BE: mov.w @(r3+r0),r1 (rt-base) */
    uint32_t t1 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)(s->r[3] + s->r[0]);
    s->r[1] = t1;
    /* 0x0661C0: op 0x611D */
    s->r[1] = s->r[1] & 0xFFFFu;
    /* 0x0661C2: op 0x634D */
    s->r[3] = s->r[4] & 0xFFFFu;
    /* 0x0661C4: op 0x3130 */
    s->T = (s->r[1] == s->r[3]) ? 1u : 0u;
    /* 0x0661C6: bf.s 0x0661EA */
    /* 0x0661C8: op 0x0009 */
    
    if (!s->T) goto L_661EA;
    /* 0x0661CA: op 0xD20C */
    s->r[2] = 0xFFFF8FB8u;
    /* 0x0661CC: mov.w @r2,r3 */
    uint32_t t3 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)0xFFFF8FB8; /* RAM 0xFFFF8FB8 */
    s->r[3] = t3;
    /* 0x0661CE: op 0x633D */
    s->r[3] = s->r[3] & 0xFFFFu;
    /* 0x0661D0: op 0x3350 */
    s->T = (s->r[3] == s->r[5]) ? 1u : 0u;
    /* 0x0661D2: bt.s 0x0661EA */
    /* 0x0661D4: op 0x0009 */
    
    if (s->T) goto L_661EA;
    /* 0x0661D6: op 0x6E53 */
    s->r[14] = s->r[5];
    /* 0x0661D8: op 0x6353 */
    s->r[3] = s->r[5];
    /* 0x0661DA: op 0x4E08 */
    s->r[14] = (s->r[14] << 2);
    /* 0x0661DC: op 0x3E3C */
    s->r[14] = s->r[14] + s->r[3];
    /* 0x0661DE: op 0x4E08 */
    s->r[14] = (s->r[14] << 2);
    /* 0x0661E0: op 0x4E00 */
    s->T = (s->r[14] >> 31) & 1u; s->r[14] = (s->r[14] << 1);
    /* 0x0661E2: op 0x3E6C */
    s->r[14] = s->r[14] + s->r[6];
    /* 0x0661E4: op 0xE026 */
    s->r[0] = (uint32_t)(int32_t)(int8_t)0x26;
    /* 0x0661E6: bra 0x0661F2 */
    /* 0x0661E8: mov.b @(r14+r0),r14 (rt-base) */
    uint32_t t4 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)(s->r[14] + s->r[0]);
    s->r[14] = t4;
    goto L_661F2;
    L_661F2: ;
    /* 0x0661F2: op 0x60E3 */
    s->r[0] = s->r[14];
    /* 0x0661F4: rts */
    /* 0x0661F6: mov.l @r15+,r14 */
    s->r[14] = local_3fc;
    return;
    L_661EA: ;
    /* 0x0661EA: op 0x7501 */
    s->r[5] = s->r[5] + (uint32_t)(int32_t)(int8_t)0x01;
    /* 0x0661EC: op 0x3573 */
    s->T = ((int32_t)s->r[5] >= (int32_t)s->r[7]) ? 1u : 0u;
    /* 0x0661EE: bf.s 0x0661AE */
    /* 0x0661F0: op 0x0009 */
    
    if (!s->T) goto L_661AE;
    return; /* fallthrough */
}
