/* ROM: 60E1D400 | Address: 0x6905C | Size: 58 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST callee (CFG).
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_2478(ST *s);
void f_68858(ST *s);
void f_69602(ST *s);
void f_69694(ST *s);
void f_6905C(ST *s)
{
    uint32_t local_3f8 = 0;
    uint32_t local_3fc = 0;
    /* 0x06905C: mov.l r14,@-r15 */
    local_3fc = s->r[14];
    /* 0x06905E: sts.l pr,@-r15 */
    local_3f8 = s->pr;
    /* 0x069060: op 0xD316 */
    s->r[3] = 0x00069694u;
    /* 0x069062: jsr @r3 */
    s->pr = 0x00069066;
    s->r[4] = (uint32_t)(int32_t)(int8_t)0x05;
    f_69694(s);
    /* 0x069066: op 0xE501 */
    s->r[5] = (uint32_t)(int32_t)(int8_t)0x01;
    /* 0x069068: op 0xD315 */
    s->r[3] = 0x00002478u;
    /* 0x06906A: op 0xDE0E */
    s->r[14] = 0xFFFFDE22u;
    /* 0x06906C: mov.w @(0x2,r14),r0 */
    uint32_t t2 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)0xFFFFDE24; /* RAM 0xFFFFDE24 */
    s->r[0] = t2;
    /* 0x06906E: op 0x7007 */
    s->r[0] = s->r[0] + (uint32_t)(int32_t)(int8_t)0x07;
    /* 0x069070: mov.w r0,@(0x2,r14) */
    *(volatile uint16_t*)0xFFFFDE24 = s->r[0]; /* RAM 0xFFFFDE24 */
    /* 0x069072: mov.b @(0x8,r14),r0 */
    uint32_t t4 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFDE2A; /* RAM 0xFFFFDE2A */
    s->r[0] = t4;
    /* 0x069074: jsr @r3 */
    s->pr = 0x00069078;
    s->r[4] = s->r[0];
    f_2478(s);
    /* 0x069078: mov.b r0,@(0x8,r14) */
    *(volatile uint8_t*)0xFFFFDE2A = s->r[0]; /* RAM 0xFFFFDE2A */
    /* 0x06907A: op 0xE004 */
    s->r[0] = (uint32_t)(int32_t)(int8_t)0x04;
    /* 0x06907C: op 0x950C */
    s->r[5] = (uint32_t)(int32_t)(int16_t)0x96u;
    /* 0x06907E: mov.b r0,@(0x5,r14) */
    *(volatile uint8_t*)0xFFFFDE27 = s->r[0]; /* RAM 0xFFFFDE27 */
    /* 0x069080: op 0xD30C */
    s->r[3] = 0x00069602u;
    /* 0x069082: jsr @r3 */
    s->pr = 0x00069086;
    s->r[4] = (uint32_t)(int32_t)(int8_t)0x05;
    f_69602(s);
    /* 0x069086: op 0xE607 */
    s->r[6] = (uint32_t)(int32_t)(int8_t)0x07;
    /* 0x069088: op 0xD507 */
    s->r[5] = 0xFFFFDE05u;
    /* 0x06908A: mov.b @(0x6,r14),r0 */
    uint32_t t6 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFDE28; /* RAM 0xFFFFDE28 */
    s->r[0] = t6;
    /* 0x06908C: lds.l @r15+,pr */
    s->pr = local_3f8;
    /* 0x06908E: op 0x6403 */
    s->r[4] = s->r[0];
    /* 0x069090: op 0xD306 */
    s->r[3] = 0x00068858u;
    /* 0x069092: jmp @r3 (tail) */
    s->r[14] = local_3fc;
    f_68858(s);
    return;
    return; /* fallthrough */
}
