/* ROM: 60E0FC00 | Address: 0x6A4C | Size: 68 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST callee (CFG).
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, vbr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_6A90(ST *s);
void f_6B94(ST *s);
void f_6C4C(ST *s);
void f_6CDC(ST *s);
void f_6A4C(ST *s)
{
    uint32_t local_3f4 = 0;
    uint32_t local_3f8 = 0;
    uint32_t local_3fc = 0;
    /* 0x006A4C: mov.l r14,@-r15 */
    local_3fc = s->r[14];
    /* 0x006A4E: mov.l r13,@-r15 */
    local_3f8 = s->r[13];
    /* 0x006A50: sts.l pr,@-r15 */
    local_3f4 = s->pr;
    /* 0x006A52: op 0x7FFC */
    s->r[15] = s->r[15] + (uint32_t)(int32_t)(int8_t)0xFC;
    /* 0x006A54: bsr 0x6B94 */
    /* 0x006A56: op 0x0009 */
    s->pr = 0x00006A58;
    
    f_6B94(s);
    /* 0x006A58: bsr 0x6C4C */
    /* 0x006A5A: op 0x0009 */
    s->pr = 0x00006A5C;
    
    f_6C4C(s);
    /* 0x006A5C: bsr 0x6CDC */
    /* 0x006A5E: op 0x0009 */
    s->pr = 0x00006A60;
    
    f_6CDC(s);
    /* 0x006A60: op 0xD523 */
    s->r[5] = 0xFFFF9EE0u;
    /* 0x006A62: op 0xD424 */
    s->r[4] = 0xFFFF9F28u;
    /* 0x006A64: mov.b @r4,r0 */
    uint32_t t2 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFF9F28; /* RAM 0xFFFF9F28 */
    s->r[0] = t2;
    /* 0x006A66: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x006A68: op 0x8802 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x02) ? 1u : 0u;
    /* 0x006A6A: bt.s 0x006A7E */
    /* 0x006A6C: op 0x0009 */
    
    if (s->T) goto L_6A7E;
    /* 0x006A6E: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x006A70: bt.s 0x006A84 */
    /* 0x006A72: op 0x0009 */
    
    if (s->T) goto L_6A84;
    /* 0x006A74: op 0x8800 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x00) ? 1u : 0u;
    /* 0x006A76: bt.s 0x006A8A */
    /* 0x006A78: op 0x0009 */
    
    if (s->T) goto L_6A8A;
    /* 0x006A7A: bra 0x006A90 (tail) */
    /* 0x006A7C: op 0x0009 */
    
     { f_6A90(s); return; }
    L_6A8A: ;
    /* 0x006A8A: mov.b @r5,r3 */
    uint32_t t4 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)s->r[5]; /* RAM 0xFFFF9EE0 */
    s->r[3] = t4;
    /* 0x006A8C: op 0x7301 */
    s->r[3] = s->r[3] + (uint32_t)(int32_t)(int8_t)0x01;
    /* 0x006A8E: mov.b r3,@r5 */
    *(volatile uint8_t*)0xFFFF9EE0 = s->r[3]; /* RAM 0xFFFF9EE0 */
    L_6A84: ;
    /* 0x006A84: mov.b @(0x1,r5),r0 */
    uint32_t t6 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)(s->r[5] + 1); /* RAM 0xFFFF9EE1 */
    s->r[0] = t6;
    /* 0x006A86: op 0x7001 */
    s->r[0] = s->r[0] + (uint32_t)(int32_t)(int8_t)0x01;
    /* 0x006A88: mov.b r0,@(0x1,r5) */
    *(volatile uint8_t*)0xFFFF9EE1 = s->r[0]; /* RAM 0xFFFF9EE1 */
    L_6A7E: ;
    /* 0x006A7E: mov.b @(0x2,r5),r0 */
    uint32_t t8 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)(s->r[5] + 2); /* RAM 0xFFFF9EE2 */
    s->r[0] = t8;
    /* 0x006A80: op 0x7001 */
    s->r[0] = s->r[0] + (uint32_t)(int32_t)(int8_t)0x01;
    /* 0x006A82: mov.b r0,@(0x2,r5) */
    *(volatile uint8_t*)0xFFFF9EE2 = s->r[0]; /* RAM 0xFFFF9EE2 */
    return; /* fallthrough */
}
