/* ROM: 60E0FC00 | Address: 0x7280 | Size: 10 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v7.py — ST (shared state) ABI,
 * leaf callee library (c/lib/f_<hex>.c). Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_7280(ST *s)
{
    /* 0x007280: op 0xD402 */
    s->r[4] = 0xFFFF9F52u;
    /* 0x007282: op 0xE300 */
    s->r[3] = (uint32_t)(int32_t)(int8_t)0x00;
    /* 0x007284: mov.w r3,@r4 */
    *(volatile uint16_t*)0xFFFF9F52 = s->r[3]; /* RAM 0xFFFF9F52 */
    /* 0x007286: op 0xE001 */
    s->r[0] = (uint32_t)(int32_t)(int8_t)0x01;
    /* 0x007288: rts */
    /* 0x00728A: mov.b r0,@(0xA,r4) */
    *(volatile uint8_t*)0xFFFF9F5C = s->r[0]; /* RAM 0xFFFF9F5C */
    return;
    return; /* fallthrough */
}
