/* ROM: 60E0FC00 | Address: 0x7668 | Size: 80 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST callee (CFG).
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, vbr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_7BDC(ST *s);
void f_7FB0(ST *s);
void f_A126(ST *s);
void f_7668(ST *s)
{
    uint32_t local_3f8 = 0;
    uint32_t local_3fc = 0;
    /* 0x007668: mov.l r14,@-r15 */
    local_3fc = s->r[14];
    /* 0x00766A: op 0x6E4C */
    s->r[14] = s->r[4] & 0xFFu;
    /* 0x00766C: sts.l pr,@-r15 */
    local_3f8 = s->pr;
    /* 0x00766E: op 0x60E3 */
    s->r[0] = s->r[14];
    /* 0x007670: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x007672: bf.s 0x00767E */
    /* 0x007674: op 0x0009 */
    
    if (!s->T) goto L_767E;
    /* 0x007676: bsr 0x7FB0 */
    /* 0x007678: op 0x0009 */
    s->pr = 0x0000767A;
    
    f_7FB0(s);
    /* 0x00767A: bra 0x007682 */
    /* 0x00767C: op 0x0009 */
    
    goto L_7682;
    L_7682: ;
    /* 0x007682: op 0x64E3 */
    s->r[4] = s->r[14];
    /* 0x007684: lds.l @r15+,pr */
    s->pr = local_3f8;
    /* 0x007686: op 0xD30A */
    s->r[3] = 0x0000D8C8u;
    /* 0x007688: mov.l @r3,r2 */
    uint32_t t2 = *(volatile uint32_t*)0x0000D8C8; /* ROM */
    s->r[2] = t2;
    /* 0x00768A: jmp @r2 (tail) */
    /* 0x00768C: mov.l @r15+,r14 */
    s->r[14] = local_3fc;
    f_A126(s);
    return;
    L_767E: ;
    /* 0x00767E: bsr 0x7BDC */
    /* 0x007680: op 0x0009 */
    s->pr = 0x00007682;
    
    f_7BDC(s);
    return; /* fallthrough */
}
