/* ROM: 60E0FC00 | Address: 0x7E3C | Size: 120 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST callee (CFG).
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_7E3C(ST *s)
{
    uint32_t local_3fc = 0;
    /* 0x007E3C: mov.l r13,@-r15 */
    local_3fc = s->r[13];
    /* 0x007E3E: op 0x674C */
    s->r[7] = s->r[4] & 0xFFu;
    /* 0x007E40: op 0x9518 */
    s->r[5] = (uint32_t)(int32_t)(int16_t)0xFFu;
    /* 0x007E42: op 0xED01 */
    s->r[13] = (uint32_t)(int32_t)(int8_t)0x01;
    /* 0x007E44: op 0xD612 */
    s->r[6] = 0xFFFF9FC7u;
    /* 0x007E46: op 0x2778 */
    s->T = ((s->r[7] & s->r[7]) == 0u) ? 1u : 0u;
    /* 0x007E48: bf.s 0x007E60 */
    /* 0x007E4A: op 0xE100 */
    s->r[1] = (uint32_t)(int32_t)(int8_t)0x00;
    if (!s->T) goto L_7E60;
    /* 0x007E4C: mov.b @r6,r2 */
    uint32_t t2 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFF9FC7; /* RAM 0xFFFF9FC7 */
    s->r[2] = t2;
    /* 0x007E4E: op 0x2228 */
    s->T = ((s->r[2] & s->r[2]) == 0u) ? 1u : 0u;
    /* 0x007E50: bt.s 0x007E70 */
    /* 0x007E52: op 0x0009 */
    
    if (s->T) goto L_7E70;
    /* 0x007E54: mov.b @r6,r3 */
    uint32_t t4 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFF9FC7; /* RAM 0xFFFF9FC7 */
    s->r[3] = t4;
    /* 0x007E56: op 0x2338 */
    s->T = ((s->r[3] & s->r[3]) == 0u) ? 1u : 0u;
    /* 0x007E58: bf.s 0x007E9E */
    /* 0x007E5A: op 0x0009 */
    
    if (!s->T) goto L_7E9E;
    /* 0x007E5C: bra 0x007E9E */
    /* 0x007E5E: op 0x65D3 */
    s->r[5] = s->r[13];
    goto L_7E9E;
    L_7E9E: ;
    /* 0x007E9E: op 0x625C */
    s->r[2] = s->r[5] & 0xFFu;
    /* 0x007EA0: op 0x9364 */
    s->r[3] = (uint32_t)(int32_t)(int16_t)0xFFu;
    /* 0x007EA2: op 0xD433 */
    s->r[4] = 0xFFFF9FCBu;
    /* 0x007EA4: op 0x3230 */
    s->T = (s->r[2] == s->r[3]) ? 1u : 0u;
    /* 0x007EA6: bf.s 0x007EAE */
    /* 0x007EA8: op 0x6053 */
    s->r[0] = s->r[5];
    if (!s->T) goto L_7EAE;
    /* 0x007EAA: bra 0x007EB0 */
    /* 0x007EAC: mov.b r13,@r4 */
    *(volatile uint8_t*)0xFFFF9FCB = s->r[13]; /* RAM 0xFFFF9FCB */
    goto L_7EB0;
    L_7EB0: ;
    /* 0x007EB0: rts */
    /* 0x007EB2: mov.l @r15+,r13 */
    s->r[13] = local_3fc;
    return;
    L_7EAE: ;
    /* 0x007EAE: mov.b r1,@r4 */
    *(volatile uint8_t*)s->r[4] = s->r[1]; /* RAM 0xFFFF9FCB */
    L_7E70: ;
    /* 0x007E70: bra 0x007E9E */
    /* 0x007E72: op 0x6513 */
    s->r[5] = s->r[1];
    goto L_7E9E;
    L_7E60: ;
    /* 0x007E60: op 0x6073 */
    s->r[0] = s->r[7];
    /* 0x007E62: op 0x8806 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x06) ? 1u : 0u;
    /* 0x007E64: bf.s 0x007E9E */
    /* 0x007E66: op 0x0009 */
    
    if (!s->T) goto L_7E9E;
    /* 0x007E68: mov.b @r6,r3 */
    uint32_t t6 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFF9FC7; /* RAM 0xFFFF9FC7 */
    s->r[3] = t6;
    /* 0x007E6A: op 0x2338 */
    s->T = ((s->r[3] & s->r[3]) == 0u) ? 1u : 0u;
    /* 0x007E6C: bf.s 0x007E94 */
    /* 0x007E6E: op 0x0009 */
    
    if (!s->T) goto L_7E94;
    L_7E94: ;
    /* 0x007E94: mov.b @r6,r2 */
    uint32_t t8 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)s->r[6]; /* RAM 0xFFFF9FC7 */
    s->r[2] = t8;
    /* 0x007E96: op 0x2228 */
    s->T = ((s->r[2] & s->r[2]) == 0u) ? 1u : 0u;
    /* 0x007E98: bf.s 0x007E9E */
    /* 0x007E9A: op 0x0009 */
    
    if (!s->T) goto L_7E9E;
    /* 0x007E9C: op 0x65D3 */
    s->r[5] = s->r[13];
    return; /* fallthrough */
}
