/* ROM: 60E0FC00 | Address: 0x8DAE | Size: 58 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST callee (CFG).
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_3920(ST *s);
void f_3934(ST *s);
void f_91C6(ST *s);
void f_8DAE(ST *s)
{
    uint32_t local_3f0 = 0;
    uint32_t local_3f8 = 0;
    uint32_t local_3fc = 0;
    uint32_t fr3 = 0;
    uint32_t fr4 = 0;
    /* 0x008DAE: op 0xE004 */
    s->r[0] = (uint32_t)(int32_t)(int8_t)0x04;
    /* 0x008DB0: op 0xD334 */
    s->r[3] = 0x00003920u;
    /* 0x008DB2: sts.l pr,@-r15 */
    local_3fc = s->pr;
    /* 0x008DB4: op 0x7FF4 */
    s->r[15] = s->r[15] + (uint32_t)(int32_t)(int8_t)0xF4;
    /* 0x008DB6: mov.b r4,@r15 */
    local_3f0 = s->r[4];
    /* 0x008DB8: fmov.s fr4,@(r0,r15) (rt-base) */
    *(volatile uint32_t*)(s->r[0] + s->r[15]) = fr4;
    /* 0x008DBA: jsr @r3 */
    s->pr = 0x00008DBE;
    s->r[4] = (uint32_t)(int32_t)(int8_t)0x10;
    f_3920(s);
    /* 0x008DBE: mov.l r0,@(0x8,r15) */
    local_3f8 = s->r[0];
    /* 0x008DC0: mov.b @r15,r4 */
    s->r[4] = (uint32_t)(int32_t)(int8_t)(local_3f0 & 0xFFu);
    /* 0x008DC2: op 0xE004 */
    s->r[0] = (uint32_t)(int32_t)(int8_t)0x04;
    /* 0x008DC4: op 0xD32E */
    s->r[3] = 0xFFFFA0D8u;
    /* 0x008DC6: op 0x644C */
    s->r[4] = s->r[4] & 0xFFu;
    /* 0x008DC8: fmov.s @(r0,r15),fr3 (rt-base) */
    fr3 = *(volatile uint32_t*)(s->r[0] + s->r[15]);
    /* 0x008DCA: op 0x4408 */
    s->r[4] = (s->r[4] << 2);
    /* 0x008DCC: op 0x4400 */
    s->T = (s->r[4] >> 31) & 1u; s->r[4] = (s->r[4] << 1);
    /* 0x008DCE: op 0x343C */
    s->r[4] = s->r[4] + s->r[3];
    /* 0x008DD0: fmov.s fr3,@r4 */
    *(volatile uint32_t*)(s->r[4] + 0) = fr3;
    /* 0x008DD2: op 0xE000 */
    s->r[0] = (uint32_t)(int32_t)(int8_t)0x00;
    /* 0x008DD4: mov.b r0,@(0x5,r4) */
    *(volatile uint8_t*)(s->r[4] + 5) = s->r[0];
    /* 0x008DD6: op 0xE002 */
    s->r[0] = (uint32_t)(int32_t)(int8_t)0x02;
    /* 0x008DD8: mov.b r0,@(0x4,r4) */
    *(volatile uint8_t*)(s->r[4] + 4) = s->r[0];
    /* 0x008DDA: bsr 0x91C6 */
    s->pr = 0x00008DDE;
    s->r[4] = (uint32_t)(int32_t)(int8_t)(local_3f0 & 0xFFu);
    f_91C6(s);
    /* 0x008DDE: mov.l @(0x8,r15),r4 */
    s->r[4] = local_3f8;
    /* 0x008DE0: op 0xD329 */
    s->r[3] = 0x00003934u;
    /* 0x008DE2: op 0x7F0C */
    s->r[15] = s->r[15] + (uint32_t)(int32_t)(int8_t)0x0C;
    /* 0x008DE4: jmp @r3 (tail) */
    s->pr = local_3fc;
    f_3934(s);
    return;
    return; /* fallthrough */
}
