/* ROM: 60E1D400 | Address: 0x9070 | Size: 132 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST callee (CFG).
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_2054(ST *s);
void f_2064(ST *s);
void f_914C(ST *s);
void f_91FE(ST *s);
void f_9070(ST *s)
{
    uint32_t local_3ec = 0;
    uint32_t local_3f0 = 0;
    uint32_t local_3f4 = 0;
    uint32_t local_3f8 = 0;
    uint32_t local_3fc = 0;
    uint32_t fr2 = 0;
    uint32_t fr3 = 0;
    /* 0x009070: mov.l r14,@-r15 */
    local_3fc = s->r[14];
    /* 0x009072: mov.l r13,@-r15 */
    local_3f8 = s->r[13];
    /* 0x009074: mov.l r12,@-r15 */
    local_3f4 = s->r[12];
    /* 0x009076: sts.l pr,@-r15 */
    local_3f0 = s->pr;
    /* 0x009078: op 0x953C */
    s->r[5] = (uint32_t)(int32_t)(int16_t)0xE0u;
    /* 0x00907A: op 0x7FFC */
    s->r[15] = s->r[15] + (uint32_t)(int32_t)(int8_t)0xFC;
    /* 0x00907C: op 0xD320 */
    s->r[3] = 0x00002054u;
    /* 0x00907E: jsr @r3 */
    s->pr = 0x00009082;
    s->r[4] = s->r[15];
    f_2054(s);
    /* 0x009082: op 0xD32A */
    s->r[3] = 0xFFFF9F98u;
    /* 0x009084: op 0xD22A */
    s->r[2] = 0xFFFFA0FCu;
    /* 0x009086: fmov.s @r3,fr3 */
    fr3 = *(volatile uint32_t*)0xFFFF9F98; /* RAM 0xFFFF9F98 */
    /* 0x009088: fmov.s fr3,@r2 */
    *(volatile uint32_t*)0xFFFFA0FC = fr3; /* RAM 0xFFFFA0FC */
    /* 0x00908A: op 0xD02A */
    s->r[0] = 0xFFFF9F9Cu;
    /* 0x00908C: op 0xD32A */
    s->r[3] = 0xFFFFA104u;
    /* 0x00908E: mov.l @r0,r1 */
    uint32_t t2 = *(volatile uint32_t*)0xFFFF9F9C; /* RAM 0xFFFF9F9C */
    s->r[1] = t2;
    /* 0x009090: op 0xD224 */
    s->r[2] = 0x00002064u;
    /* 0x009092: op 0x4109 */
    s->r[1] = (s->r[1] >> 2);
    /* 0x009094: op 0x4109 */
    s->r[1] = (s->r[1] >> 2);
    /* 0x009096: mov.w r1,@r3 */
    *(volatile uint16_t*)s->r[3] = s->r[1]; /* RAM 0xFFFFA104 */
    /* 0x009098: jsr @r2 */
    s->pr = 0x0000909C;
    s->r[4] = local_3ec;
    f_2064(s);
    /* 0x00909C: op 0xD227 */
    s->r[2] = 0xFFFF9F88u;
    /* 0x00909E: mov.l @r2,r3 */
    uint32_t t4 = *(volatile uint32_t*)s->r[2]; /* RAM 0xFFFF9F88 */
    s->r[3] = t4;
    /* 0x0090A0: op 0xC727 */
    s->r[0] = 0x00009140u;
    /* 0x0090A2: lds r3,fpul */
    s->fpul = s->r[3];
    /* 0x0090A4: fmov.s @r0,fr2 */
    fr2 = *(volatile uint32_t*)0x00009140; /* ROM */
    /* 0x0090A6: float fpul,fr3 */
    { union { uint32_t u; float f; } _r; _r.f = (float)(int32_t)s->fpul; fr3 = _r.u; }
    /* 0x0090A8: fdiv fr2,fr3 */
    { union { uint32_t u; float f; } _a, _b, _r; _a.u = fr3; _b.u = fr2; _r.f = _a.f / _b.f; fr3 = _r.u; }
    /* 0x0090AA: fmov fr3,fr3 */
    fr3 = fr3;
    /* 0x0090AC: ftrc fr3,fpul */
    { union { uint32_t u; float f; } _a; _a.u = fr3; if (_a.f != _a.f) s->fpul = 0x80000000u; else if (_a.f >= 2147483648.0f) s->fpul = 0x7FFFFFFFu; else if (_a.f < -2147483648.0f) s->fpul = 0x80000000u; else s->fpul = (uint32_t)(int32_t)_a.f; }
    /* 0x0090AE: op 0xED04 */
    s->r[13] = (uint32_t)(int32_t)(int8_t)0x04;
    /* 0x0090B0: op 0xD124 */
    s->r[1] = 0xFFFFA100u;
    /* 0x0090B2: op 0xEE00 */
    s->r[14] = (uint32_t)(int32_t)(int8_t)0x00;
    /* 0x0090B4: op 0xDC1C */
    s->r[12] = 0xFFFFA0D8u;
    /* 0x0090B6: sts fpul,r3 */
    s->r[3] = s->fpul;
    /* 0x0090B8: mov.l r3,@r1 */
    *(volatile uint32_t*)0xFFFFA100 = s->r[3]; /* RAM 0xFFFFA100 */
    L_90BA: ;
    /* 0x0090BA: op 0x64EC */
    s->r[4] = s->r[14] & 0xFFu;
    /* 0x0090BC: op 0x4408 */
    s->r[4] = (s->r[4] << 2);
    /* 0x0090BE: op 0x4400 */
    s->T = (s->r[4] >> 31) & 1u; s->r[4] = (s->r[4] << 1);
    /* 0x0090C0: op 0x34CC */
    s->r[4] = s->r[4] + s->r[12];
    /* 0x0090C2: mov.b @(0x4,r4),r0 */
    uint32_t t6 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)(s->r[4] + 4);
    s->r[0] = t6;
    /* 0x0090C4: op 0x600C */
    s->r[0] = s->r[0] & 0xFFu;
    /* 0x0090C6: op 0x8802 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x02) ? 1u : 0u;
    /* 0x0090C8: bf.s 0x0090D4 */
    /* 0x0090CA: op 0x0009 */
    
    if (!s->T) goto L_90D4;
    /* 0x0090CC: bsr 0x91FE */
    s->pr = 0x000090D0;
    s->r[4] = s->r[14];
    f_91FE(s);
    /* 0x0090D0: bra 0x0090DE */
    /* 0x0090D2: op 0x0009 */
    
    goto L_90DE;
    L_90DE: ;
    /* 0x0090DE: op 0x7E01 */
    s->r[14] = s->r[14] + (uint32_t)(int32_t)(int8_t)0x01;
    /* 0x0090E0: op 0x63EC */
    s->r[3] = s->r[14] & 0xFFu;
    /* 0x0090E2: op 0x33D3 */
    s->T = ((int32_t)s->r[3] >= (int32_t)s->r[13]) ? 1u : 0u;
    /* 0x0090E4: bf.s 0x0090BA */
    /* 0x0090E6: op 0x0009 */
    
    if (!s->T) goto L_90BA;
    /* 0x0090E8: op 0x7F04 */
    s->r[15] = s->r[15] + (uint32_t)(int32_t)(int8_t)0x04;
    /* 0x0090EA: lds.l @r15+,pr */
    s->pr = local_3f0;
    /* 0x0090EC: mov.l @r15+,r12 */
    s->r[12] = local_3f4;
    /* 0x0090EE: mov.l @r15+,r13 */
    s->r[13] = local_3f8;
    /* 0x0090F0: rts */
    /* 0x0090F2: mov.l @r15+,r14 */
    s->r[14] = local_3fc;
    return;
    L_90D4: ;
    /* 0x0090D4: op 0x8801 */
    s->T = ((int32_t)s->r[0] == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x0090D6: bf.s 0x0090DE */
    /* 0x0090D8: op 0x0009 */
    
    if (!s->T) goto L_90DE;
    /* 0x0090DA: bsr 0x914C */
    s->pr = 0x000090DE;
    s->r[4] = s->r[14];
    f_914C(s);
    return; /* fallthrough */
}
