/* ROM: 60E0FC00 | Address: 0x99B0 | Size: 276 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST callee (CFG).
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_3920(ST *s);
void f_3934(ST *s);
void f_CCDA(ST *s);
void f_CEE8(ST *s);
void f_CF12(ST *s);
void f_99B0(ST *s)
{
    uint32_t local_3e8 = 0;
    uint32_t local_3ec = 0;
    uint32_t local_3f0 = 0;
    uint32_t local_3f4 = 0;
    uint32_t local_3f8 = 0;
    uint32_t local_3fc = 0;
    /* 0x0099B0: mov.l r14,@-r15 */
    local_3fc = s->r[14];
    /* 0x0099B2: op 0x6E43 */
    s->r[14] = s->r[4];
    /* 0x0099B4: op 0xD34D */
    s->r[3] = 0x00003920u;
    /* 0x0099B6: mov.l r13,@-r15 */
    local_3f8 = s->r[13];
    /* 0x0099B8: mov.l r12,@-r15 */
    local_3f4 = s->r[12];
    /* 0x0099BA: mov.l r8,@-r15 */
    local_3f0 = s->r[8];
    /* 0x0099BC: sts.l pr,@-r15 */
    local_3ec = s->pr;
    /* 0x0099BE: op 0x7FFC */
    s->r[15] = s->r[15] + (uint32_t)(int32_t)(int8_t)0xFC;
    /* 0x0099C0: op 0x9490 */
    s->r[4] = (uint32_t)(int32_t)(int16_t)0x90u;
    /* 0x0099C2: jsr @r3 */
    s->pr = 0x000099C6;
    
    f_3920(s);
    /* 0x0099C6: mov.l r0,@r15 */
    local_3e8 = s->r[0];
    /* 0x0099C8: op 0xDC49 */
    s->r[12] = 0x0000CEE8u;
    /* 0x0099CA: op 0xDD4A */
    s->r[13] = 0x0000CF12u;
    /* 0x0099CC: op 0x958B */
    s->r[5] = (uint32_t)(int32_t)(int16_t)0x0000E406u;
    /* 0x0099CE: mov.b @r14,r0 (rt-base) */
    uint32_t t1 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)(s->r[14] + 5);
    s->r[0] = t1;
    /* 0x0099D0: jsr @r12 */
    s->pr = 0x000099D4;
    s->r[4] = s->r[0];
    f_CEE8(s);
    /* 0x0099D4: mov.w @r0,r3 (rt-base) */
    uint32_t t2 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)s->r[0];
    s->r[3] = t2;
    /* 0x0099D6: op 0x683D */
    s->r[8] = s->r[3] & 0xFFFFu;
    /* 0x0099D8: mov.b @r14,r0 (rt-base) */
    uint32_t t3 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)(s->r[14] + 5);
    s->r[0] = t3;
    /* 0x0099DA: jsr @r13 */
    s->pr = 0x000099DE;
    s->r[4] = s->r[0];
    f_CF12(s);
    /* 0x0099DE: op 0x600D */
    s->r[0] = s->r[0] & 0xFFFFu;
    /* 0x0099E0: op 0x2808 */
    s->T = ((s->r[8] & s->r[0]) == 0u) ? 1u : 0u;
    /* 0x0099E2: bf.s 0x009A1E */
    /* 0x0099E4: op 0x0009 */
    
    if (!s->T) goto L_9A1E;
    /* 0x0099E6: op 0x957F */
    s->r[5] = (uint32_t)(int32_t)(int16_t)0x0000E40Au;
    /* 0x0099E8: mov.b @r14,r0 (rt-base) */
    uint32_t t4 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)(s->r[14] + 5);
    s->r[0] = t4;
    /* 0x0099EA: jsr @r12 */
    s->pr = 0x000099EE;
    s->r[4] = s->r[0];
    f_CEE8(s);
    /* 0x0099EE: op 0x6803 */
    s->r[8] = s->r[0];
    /* 0x0099F0: mov.b @r14,r0 (rt-base) */
    uint32_t t5 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)(s->r[14] + 5);
    s->r[0] = t5;
    /* 0x0099F2: jsr @r13 */
    s->pr = 0x000099F6;
    s->r[4] = s->r[0];
    f_CF12(s);
    /* 0x0099F6: op 0xE600 */
    s->r[6] = (uint32_t)(int32_t)(int8_t)0x00;
    /* 0x0099F8: op 0xD33F */
    s->r[3] = 0x0000CCDAu;
    /* 0x0099FA: mov.w r0,@r8 (rt-base) */
    *(volatile uint16_t*)s->r[8] = s->r[0];
    /* 0x0099FC: mov.l @r14,r7 (rt-base) */
    uint32_t t6 = *(volatile uint32_t*)(s->r[14] + 8);
    s->r[7] = t6;
    /* 0x0099FE: mov.b @r14,r0 (rt-base) */
    uint32_t t7 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)(s->r[14] + 6);
    s->r[0] = t7;
    /* 0x009A00: op 0x6503 */
    s->r[5] = s->r[0];
    /* 0x009A02: mov.b @r14,r0 (rt-base) */
    uint32_t t8 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)(s->r[14] + 5);
    s->r[0] = t8;
    /* 0x009A04: jsr @r3 */
    s->pr = 0x00009A08;
    s->r[4] = s->r[0];
    f_CCDA(s);
    /* 0x009A08: op 0x956D */
    s->r[5] = (uint32_t)(int32_t)(int16_t)0x0000E406u;
    /* 0x009A0A: mov.b @r14,r0 (rt-base) */
    uint32_t t9 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)(s->r[14] + 5);
    s->r[0] = t9;
    /* 0x009A0C: jsr @r12 */
    s->pr = 0x00009A10;
    s->r[4] = s->r[0];
    f_CEE8(s);
    /* 0x009A10: op 0x6803 */
    s->r[8] = s->r[0];
    /* 0x009A12: mov.b @r14,r0 (rt-base) */
    uint32_t t10 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)(s->r[14] + 5);
    s->r[0] = t10;
    /* 0x009A14: jsr @r13 */
    s->pr = 0x00009A18;
    s->r[4] = s->r[0];
    f_CF12(s);
    /* 0x009A18: mov.w r0,@r8 (rt-base) */
    *(volatile uint16_t*)s->r[8] = s->r[0];
    /* 0x009A1A: bra 0x009A20 */
    /* 0x009A1C: op 0xEE00 */
    s->r[14] = (uint32_t)(int32_t)(int8_t)0x00;
    goto L_9A20;
    L_9A20: ;
    /* 0x009A20: op 0xD336 */
    s->r[3] = 0x00003934u;
    /* 0x009A22: jsr @r3 */
    s->pr = 0x00009A26;
    s->r[4] = local_3e8;
    f_3934(s);
    /* 0x009A26: op 0x60E3 */
    s->r[0] = s->r[14];
    /* 0x009A28: op 0x7F04 */
    s->r[15] = s->r[15] + (uint32_t)(int32_t)(int8_t)0x04;
    /* 0x009A2A: lds.l @r15+,pr */
    s->pr = local_3ec;
    /* 0x009A2C: mov.l @r15+,r8 */
    s->r[8] = local_3f0;
    /* 0x009A2E: mov.l @r15+,r12 */
    s->r[12] = local_3f4;
    /* 0x009A30: mov.l @r15+,r13 */
    s->r[13] = local_3f8;
    /* 0x009A32: rts */
    /* 0x009A34: mov.l @r15+,r14 */
    s->r[14] = local_3fc;
    return;
    L_9A1E: ;
    /* 0x009A1E: op 0xEE01 */
    s->r[14] = (uint32_t)(int32_t)(int8_t)0x01;
    return; /* fallthrough */
}
