/* ROM: 60E0FC00 | Address: 0xC9CE | Size: 176 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v8.py — ST callee (CFG).
 * Never replaces c/*.c. */
#include <stdint.h>
typedef struct {
    uint32_t r[16];
    uint32_t pr, T, Q, M, macl, mach, sr, vbr, gbr, fpul, fpscr;
    uint32_t fr[16];   /* FPU bit patterns (IEEE-754) */
    uint32_t ram_base; /* bank base (0 for 60E1D400-style flat test) */
} ST;

void f_BB2E(ST *s);
void f_C9CE(ST *s)
{
    uint32_t fr6 = 0;
    /* 0x00C9CE: op 0xE204 */
    s->r[2] = (uint32_t)(int32_t)(int8_t)0x04;
    /* 0x00C9D2: fmov.s @(r0,r6),fr6 (rt-base) */
    fr6 = *(volatile uint32_t*)(s->r[0] + s->r[6]);
    /* 0x00C9D4: mov.l r0,@r0 (rt-base) */
    *(volatile uint32_t*)s->r[0] = s->r[0];
    /* 0x00C9D6: fmov.s @r5,fr6 */
    fr6 = *(volatile uint32_t*)(s->r[5] + 0);
    /* 0x00C9DE: op 0x3920 */
    s->T = (s->r[9] == s->r[2]) ? 1u : 0u;
    /* 0x00C9E2: bra 0x00BB2E (tail) */
    /* 0x00C9E4: op 0x0000 */
    /* delay slot 0x0000 — opaque */
     { /* f_BB2E: callee lib not generated — early return */ return; }
    return; /* fallthrough */
}
