/* ROM: 60E1D400 | Address: 0x21A18 | Size: 76 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v3.py — not human-verified.
 * v3: branches + delay slots + v4 FPU (frN bit-pattern locals; fpul/fpscr). */
#include <stdint.h>
#include <math.h>
uint32_t air_fuel_ratio_check_21A18_21a18(uint32_t r4, uint32_t r5, uint32_t r6, uint32_t r7)
{
    /* params (possibly) */
    uint32_t r0 = 0;
    uint32_t r1 = 0;
    uint32_t r2 = 0;
    uint32_t r3 = 0;
    uint32_t T = 0;
    uint32_t fr2 = 0;
    uint32_t fr3 = 0;
    /* 0x021A18: op 0x946F */
    r4 = (uint32_t)(int32_t)(int16_t)0x0000B2F4u;
    /* 0x021A1A: op 0xD33F */
    r3 = 0x00070054u;
    /* 0x021A1C: op 0x926E */
    r2 = (uint32_t)(int32_t)(int16_t)0x0000ADC8u;
    /* 0x021A1E: fmov.s @r3,fr3 */
    fr3 = *(volatile uint32_t*)0x00070054; /* ROM */
    /* 0x021A20: fmov.s @r2,fr2 */
    fr2 = *(volatile uint32_t*)0xFFFFADC8; /* RAM 0xFFFFADC8 */
    /* 0x021A22: fcmp/gt fr2,fr3 */
    { union { uint32_t u; float f; } _a, _b; _a.u = fr3; _b.u = fr2; T = (_a.f > _b.f) ? 1u : 0u; }
    /* 0x021A24: bt.s 0x021A5C */
    /* 0x021A26: op 0x0009 */
    
    if (T) goto L_21A5C;
    /* 0x021A28: op 0x9169 */
    r1 = (uint32_t)(int32_t)(int16_t)0x0000B2E0u;
    /* 0x021A2A: mov.b @r1,r0 */
    uint32_t t2 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFB2E0; /* RAM 0xFFFFB2E0 */
    r0 = t2;
    /* 0x021A2C: op 0xD33B */
    r3 = 0x00070050u;
    /* 0x021A2E: mov.b @r3,r2 */
    uint32_t t4 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0x00070050; /* ROM */
    r2 = t4;
    /* 0x021A30: op 0x3022 */
    T = (r0 >= r2) ? 1u : 0u;
    /* 0x021A32: bt.s 0x021A5C */
    /* 0x021A34: op 0x0009 */
    
    if (T) goto L_21A5C;
    /* 0x021A36: op 0x9263 */
    r2 = (uint32_t)(int32_t)(int16_t)0x0000AADAu;
    /* 0x021A38: mov.b @r2,r0 */
    uint32_t t6 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFAADA; /* RAM 0xFFFFAADA */
    r0 = t6;
    /* 0x021A3A: op 0x2008 */
    T = ((r0 & r0) == 0u) ? 1u : 0u;
    /* 0x021A3C: bf.s 0x021A5C */
    /* 0x021A3E: op 0x0009 */
    
    if (!T) goto L_21A5C;
    /* 0x021A40: op 0x935F */
    r3 = (uint32_t)(int32_t)(int16_t)0x0000A428u;
    /* 0x021A42: mov.b @r3,r0 */
    uint32_t t8 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFA428; /* RAM 0xFFFFA428 */
    r0 = t8;
    /* 0x021A44: op 0x600C */
    r0 = r0 & 0xFFu;
    /* 0x021A46: op 0x8801 */
    T = ((int32_t)r0 == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x021A48: bf.s 0x021A5C */
    /* 0x021A4A: op 0x0009 */
    
    if (!T) goto L_21A5C;
    /* 0x021A4C: op 0x925A */
    r2 = (uint32_t)(int32_t)(int16_t)0x0000C656u;
    /* 0x021A4E: mov.b @r2,r0 */
    uint32_t t10 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFC656; /* RAM 0xFFFFC656 */
    r0 = t10;
    /* 0x021A50: op 0x2008 */
    T = ((r0 & r0) == 0u) ? 1u : 0u;
    /* 0x021A52: bf.s 0x021A5C */
    /* 0x021A54: op 0x0009 */
    
    if (!T) goto L_21A5C;
    /* 0x021A56: op 0xE101 */
    r1 = (uint32_t)(int32_t)(int8_t)0x01;
    /* 0x021A58: bra 0x021A60 */
    /* 0x021A5A: mov.b r1,@r4 */
    *(volatile uint8_t*)0xFFFFB2F4 = r1; /* RAM 0xFFFFB2F4 */
    goto L_21A60;
    L_21A5C: ;
    /* 0x021A5C: op 0xE200 */
    r2 = (uint32_t)(int32_t)(int8_t)0x00;
    /* 0x021A5E: mov.b r2,@r4 */
    *(volatile uint8_t*)0xFFFFB2F4 = r2; /* RAM 0xFFFFB2F4 */
    L_21A60: ;
    /* 0x021A60: rts */
    /* 0x021A62: op 0x0009 */
    
    return r0;
    return r0; /* fallthrough */
}
