/* ROM: 60E1D400 | Address: 0x29EC6 | Size: 40 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v3.py — not human-verified.
 * v3: branches + delay slots. */
#include <stdint.h>
uint32_t can231SetupTx_29ec6(uint32_t r4, uint32_t r5, uint32_t r6, uint32_t r7)
{
    /* params (possibly) */
    uint32_t r0 = 0;
    uint32_t r1 = 0;
    uint32_t r2 = 0;
    uint32_t r3 = 0;
    /* 0x029EC6: op 0xD43A */
    r4 = 0xFFFFBB48u;
    /* 0x029EC8: op 0x9262 */
    r2 = (uint32_t)(int32_t)(int16_t)0x0000BB4Du;
    /* 0x029ECA: mov.b @r4,r3 */
    uint32_t t2 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFBB48; /* RAM 0xFFFFBB48 */
    r3 = t2;
    /* 0x029ECC: op 0xD139 */
    r1 = 0xFFFFBB59u;
    /* 0x029ECE: mov.b r3,@r2 */
    *(volatile uint8_t*)0xFFFFBB4D = r3; /* RAM 0xFFFFBB4D */
    /* 0x029ED0: mov.b @(0x1,r4),r0 */
    uint32_t t4 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFBB49; /* RAM 0xFFFFBB49 */
    r0 = t4;
    /* 0x029ED2: mov.b r0,@r1 */
    *(volatile uint8_t*)0xFFFFBB59 = r0; /* RAM 0xFFFFBB59 */
    /* 0x029ED4: mov.b @(0x2,r4),r0 */
    uint32_t t6 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFBB4A; /* RAM 0xFFFFBB4A */
    r0 = t6;
    /* 0x029ED6: op 0x600C */
    r0 = r0 & 0xFFu;
    /* 0x029ED8: op 0x925B */
    r2 = (uint32_t)(int32_t)(int16_t)0x0000BB4Eu;
    /* 0x029EDA: op 0x4018 */
    r0 = (r0 << 8);
    /* 0x029EDC: op 0x6303 */
    r3 = r0;
    /* 0x029EDE: mov.b @(0x3,r4),r0 */
    uint32_t t8 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFBB4B; /* RAM 0xFFFFBB4B */
    r0 = t8;
    /* 0x029EE0: op 0x600C */
    r0 = r0 & 0xFFu;
    /* 0x029EE2: op 0x330C */
    r3 = r3 + r0;
    /* 0x029EE4: op 0xD034 */
    r0 = 0xFFFFBB5Au;
    /* 0x029EE6: mov.w r3,@r0 */
    *(volatile uint16_t*)0xFFFFBB5A = r3; /* RAM 0xFFFFBB5A */
    /* 0x029EE8: mov.b @(0x4,r4),r0 */
    uint32_t t10 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFBB4C; /* RAM 0xFFFFBB4C */
    r0 = t10;
    /* 0x029EEA: rts */
    /* 0x029EEC: mov.b r0,@r2 */
    *(volatile uint8_t*)0xFFFFBB4E = r0; /* RAM 0xFFFFBB4E */
    return r0;
    return r0; /* fallthrough */
}
