/* ROM: 60E1D400 | Address: 0x2BFD2 | Size: 44 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v3.py — not human-verified.
 * v3: branches + delay slots. */
#include <stdint.h>
uint32_t check_table_threshold_flag_2BFD2_2bfd2(uint32_t r4, uint32_t r5, uint32_t r6, uint32_t r7)
{
    /* params (possibly) */
    uint32_t r0 = 0;
    uint32_t r1 = 0;
    uint32_t r2 = 0;
    uint32_t r3 = 0;
    uint32_t T = 0;
    /* 0x02BFD2: op 0x9443 */
    r4 = (uint32_t)(int32_t)(int16_t)0x0000BC22u;
    /* 0x02BFD4: op 0x9243 */
    r2 = (uint32_t)(int32_t)(int16_t)0x0000BC16u;
    /* 0x02BFD6: mov.w @r2,r3 */
    uint32_t t2 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)0xFFFFBC16; /* RAM 0xFFFFBC16 */
    r3 = t2;
    /* 0x02BFD8: op 0xD127 */
    r1 = 0x0000FFFFu;
    /* 0x02BFDA: op 0x633D */
    r3 = r3 & 0xFFFFu;
    /* 0x02BFDC: op 0x3310 */
    T = (r3 == r1) ? 1u : 0u;
    /* 0x02BFDE: bt.s 0x02BFF0 */
    /* 0x02BFE0: op 0x0009 */
    
    if (T) goto L_2BFF0;
    /* 0x02BFE2: op 0xD326 */
    r3 = 0xFFFFBC26u;
    /* 0x02BFE4: op 0xD126 */
    r1 = 0x0007BA1Cu;
    /* 0x02BFE6: mov.w @r3,r0 */
    uint32_t t4 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)0xFFFFBC26; /* RAM 0xFFFFBC26 */
    r0 = t4;
    /* 0x02BFE8: mov.w @r1,r2 */
    uint32_t t6 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)0x0007BA1C; /* ROM */
    r2 = t6;
    /* 0x02BFEA: op 0x3022 */
    T = (r0 >= r2) ? 1u : 0u;
    /* 0x02BFEC: bf.s 0x02BFF6 */
    /* 0x02BFEE: op 0x0009 */
    
    if (!T) goto L_2BFF6;
    L_2BFF0: ;
    /* 0x02BFF0: op 0xE301 */
    r3 = (uint32_t)(int32_t)(int8_t)0x01;
    /* 0x02BFF2: bra 0x02BFFA */
    /* 0x02BFF4: mov.b r3,@r4 */
    *(volatile uint8_t*)0xFFFFBC22 = r3; /* RAM 0xFFFFBC22 */
    goto L_2BFFA;
    L_2BFF6: ;
    /* 0x02BFF6: op 0xE100 */
    r1 = (uint32_t)(int32_t)(int8_t)0x00;
    /* 0x02BFF8: mov.b r1,@r4 */
    *(volatile uint8_t*)0xFFFFBC22 = r1; /* RAM 0xFFFFBC22 */
    L_2BFFA: ;
    /* 0x02BFFA: rts */
    /* 0x02BFFC: op 0x0009 */
    
    return r0;
    return r0; /* fallthrough */
}
