/* ROM: 60E0FC00 | Address: 0x3EABA | Size: 66 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v3.py — not human-verified.
 * v3: branches + delay slots + v4 FPU (frN bit-pattern locals; fpul/fpscr). */
#include <stdint.h>
#include <math.h>
uint32_t coolantTempModelBooleans_3eaba(uint32_t r4, uint32_t r5, uint32_t r6, uint32_t r7)
{
    /* params (possibly) */
    uint32_t r0 = 0;
    uint32_t r1 = 0;
    uint32_t r2 = 0;
    uint32_t r3 = 0;
    uint32_t T = 0;
    uint32_t fr2 = 0;
    uint32_t fr3 = 0;
    uint32_t fr4 = 0;
    /* 0x03EABA: op 0xE501 */
    r5 = (uint32_t)(int32_t)(int8_t)0x01;
    /* 0x03EABC: op 0xD22C */
    r2 = 0x00079C78u;
    /* 0x03EABE: op 0x933B */
    r3 = (uint32_t)(int32_t)(int16_t)0x0000C63Cu;
    /* 0x03EAC0: op 0x963F */
    r6 = (uint32_t)(int32_t)(int16_t)0x0000C648u;
    /* 0x03EAC2: fmov.s @r3,fr4 */
    fr4 = *(volatile uint32_t*)0xFFFFC63C; /* RAM 0xFFFFC63C */
    /* 0x03EAC4: fmov.s @r2,fr3 */
    fr3 = *(volatile uint32_t*)0x00079C78; /* ROM */
    /* 0x03EAC6: fcmp/gt fr4,fr3 */
    { union { uint32_t u; float f; } _a, _b; _a.u = fr3; _b.u = fr4; T = (_a.f > _b.f) ? 1u : 0u; }
    /* 0x03EAC8: bf.s 0x03EAD0 */
    /* 0x03EACA: op 0xE400 */
    r4 = (uint32_t)(int32_t)(int8_t)0x00;
    if (!T) goto L_3EAD0;
    /* 0x03EACC: bra 0x03EADC */
    /* 0x03EACE: mov.b r4,@r6 */
    *(volatile uint8_t*)0xFFFFC648 = r4; /* RAM 0xFFFFC648 */
    goto L_3EADC;
    L_3EAD0: ;
    /* 0x03EAD0: op 0xD128 */
    r1 = 0x00079C74u;
    /* 0x03EAD2: fmov.s @r1,fr2 */
    fr2 = *(volatile uint32_t*)0x00079C74; /* ROM */
    /* 0x03EAD4: fcmp/gt fr2,fr4 */
    { union { uint32_t u; float f; } _a, _b; _a.u = fr4; _b.u = fr2; T = (_a.f > _b.f) ? 1u : 0u; }
    /* 0x03EAD6: bf.s 0x03EADC */
    /* 0x03EAD8: op 0x0009 */
    
    if (!T) goto L_3EADC;
    /* 0x03EADA: mov.b r5,@r6 */
    *(volatile uint8_t*)0xFFFFC648 = r5; /* RAM 0xFFFFC648 */
    L_3EADC: ;
    /* 0x03EADC: op 0x9632 */
    r6 = (uint32_t)(int32_t)(int16_t)0x0000C649u;
    /* 0x03EADE: op 0xD326 */
    r3 = 0x00079C80u;
    /* 0x03EAE0: fmov.s @r3,fr3 */
    fr3 = *(volatile uint32_t*)0x00079C80; /* ROM */
    /* 0x03EAE2: fcmp/gt fr4,fr3 */
    { union { uint32_t u; float f; } _a, _b; _a.u = fr3; _b.u = fr4; T = (_a.f > _b.f) ? 1u : 0u; }
    /* 0x03EAE4: bf.s 0x03EAEC */
    /* 0x03EAE6: op 0x0009 */
    
    if (!T) goto L_3EAEC;
    /* 0x03EAE8: bra 0x03EAF8 */
    /* 0x03EAEA: mov.b r4,@r6 */
    *(volatile uint8_t*)0xFFFFC649 = r4; /* RAM 0xFFFFC649 */
    goto L_3EAF8;
    L_3EAEC: ;
    /* 0x03EAEC: op 0xD223 */
    r2 = 0x00079C7Cu;
    /* 0x03EAEE: fmov.s @r2,fr2 */
    fr2 = *(volatile uint32_t*)0x00079C7C; /* ROM */
    /* 0x03EAF0: fcmp/gt fr2,fr4 */
    { union { uint32_t u; float f; } _a, _b; _a.u = fr4; _b.u = fr2; T = (_a.f > _b.f) ? 1u : 0u; }
    /* 0x03EAF2: bf.s 0x03EAF8 */
    /* 0x03EAF4: op 0x0009 */
    
    if (!T) goto L_3EAF8;
    /* 0x03EAF6: mov.b r5,@r6 */
    *(volatile uint8_t*)0xFFFFC649 = r5; /* RAM 0xFFFFC649 */
    L_3EAF8: ;
    /* 0x03EAF8: rts */
    /* 0x03EAFA: op 0x0009 */
    
    return r0;
    return r0; /* fallthrough */
}
