/* ROM: 60E1D400 | Address: 0x4F81E | Size: 104 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v3.py — not human-verified.
 * v3: branches + delay slots. */
#include <stdint.h>
uint32_t coolant_temp_monitor_0x4F81E_4f81e(uint32_t r4, uint32_t r5, uint32_t r6, uint32_t r7)
{
    /* params (possibly) */
    uint32_t r0 = 0;
    uint32_t r1 = 0;
    uint32_t r2 = 0;
    uint32_t r3 = 0;
    uint32_t r14 = 0;
    uint32_t T = 0;
    uint32_t local_3fc = 0;
    /* 0x04F81E: mov.l r14,@-r15 */
    local_3fc = r14;
    /* 0x04F820: op 0x9363 */
    r3 = (uint32_t)(int32_t)(int16_t)0x0000CFF9u;
    /* 0x04F822: mov.b @r3,r5 */
    uint32_t t2 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFCFF9; /* RAM 0xFFFFCFF9 */
    r5 = t2;
    /* 0x04F824: op 0x9762 */
    r7 = (uint32_t)(int32_t)(int16_t)0x0000CFF6u;
    /* 0x04F826: op 0x665C */
    r6 = r5 & 0xFFu;
    /* 0x04F828: op 0xDE33 */
    r14 = 0xFFFFD00Eu;
    /* 0x04F82A: op 0x6063 */
    r0 = r6;
    /* 0x04F82C: op 0x8801 */
    T = ((int32_t)r0 == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x04F82E: bf.s 0x04F852 */
    /* 0x04F830: op 0xE400 */
    r4 = (uint32_t)(int32_t)(int8_t)0x00;
    if (!T) goto L_4F852;
    /* 0x04F832: mov.b @r14,r1 */
    uint32_t t4 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFD00E; /* RAM 0xFFFFD00E */
    r1 = t4;
    /* 0x04F834: op 0x2118 */
    T = ((r1 & r1) == 0u) ? 1u : 0u;
    /* 0x04F836: bf.s 0x04F840 */
    /* 0x04F838: op 0x0009 */
    
    if (!T) goto L_4F840;
    /* 0x04F83A: op 0xE001 */
    r0 = (uint32_t)(int32_t)(int8_t)0x01;
    /* 0x04F83C: bra 0x04F854 */
    /* 0x04F83E: mov.b r0,@r7 */
    *(volatile uint8_t*)0xFFFFCFF6 = r0; /* RAM 0xFFFFCFF6 */
    goto L_4F854;
    L_4F840: ;
    /* 0x04F840: op 0x9255 */
    r2 = (uint32_t)(int32_t)(int16_t)0x0000CFE8u;
    /* 0x04F842: mov.b @r2,r1 */
    uint32_t t6 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFCFE8; /* RAM 0xFFFFCFE8 */
    r1 = t6;
    /* 0x04F844: op 0xD32D */
    r3 = 0x0007D0C8u;
    /* 0x04F846: mov.b @r3,r0 */
    uint32_t t8 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0x0007D0C8; /* ROM */
    r0 = t8;
    /* 0x04F848: op 0x3100 */
    T = (r1 == r0) ? 1u : 0u;
    /* 0x04F84A: bf.s 0x04F854 */
    /* 0x04F84C: op 0x0009 */
    
    if (!T) goto L_4F854;
    /* 0x04F84E: bra 0x04F854 */
    /* 0x04F850: mov.b r4,@r7 */
    *(volatile uint8_t*)0xFFFFCFF6 = r4; /* RAM 0xFFFFCFF6 */
    goto L_4F854;
    L_4F852: ;
    /* 0x04F852: mov.b r4,@r7 */
    *(volatile uint8_t*)0xFFFFCFF6 = r4; /* RAM 0xFFFFCFF6 */
    L_4F854: ;
    /* 0x04F854: op 0x974C */
    r7 = (uint32_t)(int32_t)(int16_t)0x0000CFF7u;
    /* 0x04F856: op 0x2668 */
    T = ((r6 & r6) == 0u) ? 1u : 0u;
    /* 0x04F858: bf.s 0x04F87E */
    /* 0x04F85A: op 0x0009 */
    
    if (!T) goto L_4F87E;
    /* 0x04F85C: mov.b @r14,r0 */
    uint32_t t10 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFD00E; /* RAM 0xFFFFD00E */
    r0 = t10;
    /* 0x04F85E: op 0x600C */
    r0 = r0 & 0xFFu;
    /* 0x04F860: op 0x8801 */
    T = ((int32_t)r0 == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x04F862: bf.s 0x04F86C */
    /* 0x04F864: op 0x0009 */
    
    if (!T) goto L_4F86C;
    /* 0x04F866: op 0xE201 */
    r2 = (uint32_t)(int32_t)(int8_t)0x01;
    /* 0x04F868: bra 0x04F880 */
    /* 0x04F86A: mov.b r2,@r7 */
    *(volatile uint8_t*)0xFFFFCFF7 = r2; /* RAM 0xFFFFCFF7 */
    goto L_4F880;
    L_4F86C: ;
    /* 0x04F86C: op 0x9341 */
    r3 = (uint32_t)(int32_t)(int16_t)0x0000CFEAu;
    /* 0x04F86E: mov.b @r3,r1 */
    uint32_t t12 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFCFEA; /* RAM 0xFFFFCFEA */
    r1 = t12;
    /* 0x04F870: op 0xD022 */
    r0 = 0x0007D0C8u;
    /* 0x04F872: mov.b @r0,r2 */
    uint32_t t14 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0x0007D0C8; /* ROM */
    r2 = t14;
    /* 0x04F874: op 0x3120 */
    T = (r1 == r2) ? 1u : 0u;
    /* 0x04F876: bf.s 0x04F880 */
    /* 0x04F878: op 0x0009 */
    
    if (!T) goto L_4F880;
    /* 0x04F87A: bra 0x04F880 */
    /* 0x04F87C: mov.b r4,@r7 */
    *(volatile uint8_t*)0xFFFFCFF7 = r4; /* RAM 0xFFFFCFF7 */
    goto L_4F880;
    L_4F87E: ;
    /* 0x04F87E: mov.b r4,@r7 */
    *(volatile uint8_t*)0xFFFFCFF7 = r4; /* RAM 0xFFFFCFF7 */
    L_4F880: ;
    /* 0x04F880: mov.b r5,@r14 */
    *(volatile uint8_t*)0xFFFFD00E = r5; /* RAM 0xFFFFD00E */
    /* 0x04F882: rts */
    /* 0x04F884: mov.l @r15+,r14 */
    r14 = local_3fc;
    return r0;
    return r0; /* fallthrough */
}
