/* ROM: 60E1D400 | Address: 0x59B68 | Size: 56 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v3.py — not human-verified.
 * v3: branches + delay slots. */
#include <stdint.h>
uint32_t ctrl_maintenance_59b68_59b68(uint32_t r4, uint32_t r5, uint32_t r6, uint32_t r7)
{
    /* params (possibly) */
    uint32_t r0 = 0;
    uint32_t r1 = 0;
    uint32_t r2 = 0;
    uint32_t r3 = 0;
    uint32_t T = 0;
    /* 0x059B68: op 0x9726 */
    r7 = (uint32_t)(int32_t)(int16_t)0x0000D27Eu;
    /* 0x059B6A: op 0x9526 */
    r5 = (uint32_t)(int32_t)(int16_t)0x0000D27Cu;
    /* 0x059B6C: op 0x9223 */
    r2 = (uint32_t)(int32_t)(int16_t)0x0000A41Cu;
    /* 0x059B6E: mov.b @r2,r3 */
    uint32_t t2 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFA41C; /* RAM 0xFFFFA41C */
    r3 = t2;
    /* 0x059B70: op 0x2338 */
    T = ((r3 & r3) == 0u) ? 1u : 0u;
    /* 0x059B72: bf.s 0x059B7A */
    /* 0x059B74: op 0xE400 */
    r4 = (uint32_t)(int32_t)(int8_t)0x00;
    if (!T) goto L_59B7A;
    /* 0x059B76: bra 0x059B92 */
    /* 0x059B78: mov.w r4,@r5 */
    *(volatile uint16_t*)0xFFFFD27C = r4; /* RAM 0xFFFFD27C */
    goto L_59B92;
    L_59B7A: ;
    /* 0x059B7A: op 0xD610 */
    r6 = 0xFFFFD27Fu;
    /* 0x059B7C: mov.b @r6,r0 */
    uint32_t t4 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFD27F; /* RAM 0xFFFFD27F */
    r0 = t4;
    /* 0x059B7E: op 0x600C */
    r0 = r0 & 0xFFu;
    /* 0x059B80: op 0x8801 */
    T = ((int32_t)r0 == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x059B82: bf.s 0x059B92 */
    /* 0x059B84: op 0x0009 */
    
    if (!T) goto L_59B92;
    /* 0x059B86: op 0xE101 */
    r1 = (uint32_t)(int32_t)(int8_t)0x01;
    /* 0x059B88: op 0xD00E */
    r0 = 0x0007DAE0u;
    /* 0x059B8A: mov.b r4,@r6 */
    *(volatile uint8_t*)0xFFFFD27F = r4; /* RAM 0xFFFFD27F */
    /* 0x059B8C: mov.b r1,@r7 */
    *(volatile uint8_t*)0xFFFFD27E = r1; /* RAM 0xFFFFD27E */
    /* 0x059B8E: mov.w @r0,r3 */
    uint32_t t6 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)0x0007DAE0; /* ROM */
    r3 = t6;
    /* 0x059B90: mov.w r3,@r5 */
    *(volatile uint16_t*)0xFFFFD27C = r3; /* RAM 0xFFFFD27C */
    L_59B92: ;
    /* 0x059B92: mov.w @r5,r2 */
    uint32_t t8 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)0xFFFFD27C; /* RAM 0xFFFFD27C */
    r2 = t8;
    /* 0x059B94: op 0x2228 */
    T = ((r2 & r2) == 0u) ? 1u : 0u;
    /* 0x059B96: bf.s 0x059B9C */
    /* 0x059B98: op 0x0009 */
    
    if (!T) goto L_59B9C;
    /* 0x059B9A: mov.b r4,@r7 */
    *(volatile uint8_t*)0xFFFFD27E = r4; /* RAM 0xFFFFD27E */
    L_59B9C: ;
    /* 0x059B9C: rts */
    /* 0x059B9E: op 0x0009 */
    
    return r0;
    return r0; /* fallthrough */
}
