/* ROM: 60E1D400 | Address: 0x5AB9E | Size: 38 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v3.py — not human-verified.
 * v3: branches + delay slots. */
#include <stdint.h>
uint32_t diag_airbag_5ab9e_5ab9e(uint32_t r4, uint32_t r5, uint32_t r6, uint32_t r7)
{
    /* params (possibly) */
    uint32_t r0 = 0;
    uint32_t r1 = 0;
    uint32_t r2 = 0;
    uint32_t r3 = 0;
    uint32_t T = 0;
    /* 0x05AB9E: op 0x934F */
    r3 = (uint32_t)(int32_t)(int16_t)0x0000A41Cu;
    /* 0x05ABA0: mov.b @r3,r4 */
    uint32_t t2 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFA41C; /* RAM 0xFFFFA41C */
    r4 = t2;
    /* 0x05ABA2: op 0x644C */
    r4 = r4 & 0xFFu;
    /* 0x05ABA4: op 0x2448 */
    T = ((r4 & r4) == 0u) ? 1u : 0u;
    /* 0x05ABA6: bf.s 0x05ABC0 */
    /* 0x05ABA8: op 0x0009 */
    
    if (!T) goto L_5ABC0;
    /* 0x05ABAA: op 0x924A */
    r2 = (uint32_t)(int32_t)(int16_t)0x0000D2C0u;
    /* 0x05ABAC: op 0xD028 */
    r0 = 0x0000FFFFu;
    /* 0x05ABAE: mov.w @r2,r1 */
    uint32_t t4 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)0xFFFFD2C0; /* RAM 0xFFFFD2C0 */
    r1 = t4;
    /* 0x05ABB0: op 0x611D */
    r1 = r1 & 0xFFFFu;
    /* 0x05ABB2: op 0x3100 */
    T = (r1 == r0) ? 1u : 0u;
    /* 0x05ABB4: bt.s 0x05ABC0 */
    /* 0x05ABB6: op 0x0009 */
    
    if (T) goto L_5ABC0;
    /* 0x05ABB8: op 0x9443 */
    r4 = (uint32_t)(int32_t)(int16_t)0x0000D2C0u;
    /* 0x05ABBA: mov.w @r4,r2 */
    uint32_t t6 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)0xFFFFD2C0; /* RAM 0xFFFFD2C0 */
    r2 = t6;
    /* 0x05ABBC: op 0x7201 */
    r2 = r2 + (uint32_t)(int32_t)(int8_t)0x01;
    /* 0x05ABBE: mov.w r2,@r4 */
    *(volatile uint16_t*)0xFFFFD2C0 = r2; /* RAM 0xFFFFD2C0 */
    L_5ABC0: ;
    /* 0x05ABC0: rts */
    /* 0x05ABC2: op 0x0009 */
    
    return r0;
    return r0; /* fallthrough */
}
