/* ROM: 60E1D400 | Address: 0x2C5B0 | Size: 30 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v3.py — not human-verified.
 * v3: branches + delay slots. */
#include <stdint.h>
uint32_t DSC_checkIfMode_x20_a_2c5b0(uint32_t r4, uint32_t r5, uint32_t r6, uint32_t r7)
{
    /* params (possibly) */
    uint32_t r0 = 0;
    uint32_t r1 = 0;
    uint32_t r3 = 0;
    uint32_t T = 0;
    /* 0x02C5B0: op 0x9456 */
    r4 = (uint32_t)(int32_t)(int16_t)0x0000BC35u;
    /* 0x02C5B2: op 0xD32E */
    r3 = 0xFFFFBC5Eu;
    /* 0x02C5B4: mov.b @r3,r0 */
    uint32_t t2 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFBC5E; /* RAM 0xFFFFBC5E */
    r0 = t2;
    /* 0x02C5B6: op 0x600C */
    r0 = r0 & 0xFFu;
    /* 0x02C5B8: op 0xC920 */
    r0 &= 0x20u;
    /* 0x02C5BA: op 0x8820 */
    T = ((int32_t)r0 == (int32_t)(int8_t)0x20) ? 1u : 0u;
    /* 0x02C5BC: bf.s 0x02C5C6 */
    /* 0x02C5BE: op 0x0009 */
    
    if (!T) goto L_2C5C6;
    /* 0x02C5C0: op 0xE101 */
    r1 = (uint32_t)(int32_t)(int8_t)0x01;
    /* 0x02C5C2: bra 0x02C5CA */
    /* 0x02C5C4: mov.b r1,@r4 */
    *(volatile uint8_t*)0xFFFFBC35 = r1; /* RAM 0xFFFFBC35 */
    goto L_2C5CA;
    L_2C5C6: ;
    /* 0x02C5C6: op 0xE000 */
    r0 = (uint32_t)(int32_t)(int8_t)0x00;
    /* 0x02C5C8: mov.b r0,@r4 */
    *(volatile uint8_t*)0xFFFFBC35 = r0; /* RAM 0xFFFFBC35 */
    L_2C5CA: ;
    /* 0x02C5CA: rts */
    /* 0x02C5CC: op 0x0009 */
    
    return r0;
    return r0; /* fallthrough */
}
