/* ROM: 60E1D400 | Address: 0x22D20 | Size: 10 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift.py - not human-verified.
 * Pure straight-line function: no calls, no memory side effects. */
#include <stdint.h>
uint32_t evap_purge_flow_calc_22d20(uint32_t r4, uint32_t r5, uint32_t r6, uint32_t r7)
{
    /* params (possibly) */
    uint32_t r0 = 0;
    uint32_t r2 = 0;
    uint32_t T = 0;
    uint32_t Q = 0;
    uint32_t M = 0;
    uint32_t macl = 0;
    uint32_t mach = 0;
    /* 0x022D20: op 0x0007 */
    macl = (uint32_t)((int32_t)r0 * (int32_t)r0);
    /* 0x022D22: op 0x3724 */
    { uint32_t _t0 = (r7 >> 31) & 1u; r7 = (r7 << 1) | (T & 1u); uint32_t _t1 = (Q ^ M) & 1u; _t1 = (_t1 - 1u) & 0xFFFFFFFFu; uint32_t _t2 = (0u - r2) & 0xFFFFFFFFu; if (_t1 == 0u) _t2 = r2; uint64_t _lo = (uint64_t)r7 + _t2; r7 = (uint32_t)_lo; uint32_t _carry = (uint32_t)(_lo >> 32) & 1u; _t1 = (_t1 + _carry) & 1u; _t1 ^= _t0; T = (_t1 ^ 1u) & 1u; Q = (M ^ _t1) & 1u; }
    /* 0x022D24: op 0x0007 */
    macl = (uint32_t)((int32_t)r0 * (int32_t)r0);
    /* 0x022D26: op 0x3725 */
    { uint64_t _p = (uint64_t)r2 * r7; mach = (uint32_t)(_p >> 32); macl = (uint32_t)_p; }
    /* 0x022D28: op 0x0007 */
    macl = (uint32_t)((int32_t)r0 * (int32_t)r0);
    return r0;
}
