/* ROM: 60E0FC00 | Address: 0x4A5A4 | Size: 28 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v3.py — not human-verified.
 * v3: branches + delay slots. */
#include <stdint.h>
uint32_t fault_flag_invert_store_cf9c_to_cce0_4a5a4(uint32_t r4, uint32_t r5, uint32_t r6, uint32_t r7)
{
    /* params (possibly) */
    uint32_t r0 = 0;
    uint32_t r1 = 0;
    uint32_t r3 = 0;
    uint32_t T = 0;
    /* 0x04A5A4: op 0x945B */
    r4 = (uint32_t)(int32_t)(int16_t)0x0000CCE0u;
    /* 0x04A5A6: op 0x935B */
    r3 = (uint32_t)(int32_t)(int16_t)0x0000CF9Cu;
    /* 0x04A5A8: mov.b @r3,r0 */
    uint32_t t2 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFCF9C; /* RAM 0xFFFFCF9C */
    r0 = t2;
    /* 0x04A5AA: op 0x600C */
    r0 = r0 & 0xFFu;
    /* 0x04A5AC: op 0x8801 */
    T = ((int32_t)r0 == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x04A5AE: bf.s 0x04A5B8 */
    /* 0x04A5B0: op 0x0009 */
    
    if (!T) goto L_4A5B8;
    /* 0x04A5B2: op 0xE100 */
    r1 = (uint32_t)(int32_t)(int8_t)0x00;
    /* 0x04A5B4: bra 0x04A5BC */
    /* 0x04A5B6: mov.b r1,@r4 */
    *(volatile uint8_t*)0xFFFFCCE0 = r1; /* RAM 0xFFFFCCE0 */
    goto L_4A5BC;
    L_4A5B8: ;
    /* 0x04A5B8: op 0xE001 */
    r0 = (uint32_t)(int32_t)(int8_t)0x01;
    /* 0x04A5BA: mov.b r0,@r4 */
    *(volatile uint8_t*)0xFFFFCCE0 = r0; /* RAM 0xFFFFCCE0 */
    L_4A5BC: ;
    /* 0x04A5BC: rts */
    /* 0x04A5BE: op 0x0009 */
    
    return r0;
    return r0; /* fallthrough */
}
