/* ROM: 60E1D400 | Address: 0x5A7BC | Size: 24 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v3.py — not human-verified.
 * v3: branches + delay slots. */
#include <stdint.h>
uint32_t fuel_control_5a7bc_5a7bc(uint32_t r4, uint32_t r5, uint32_t r6, uint32_t r7)
{
    uint32_t r0 = 0;
    uint32_t r1 = 0;
    uint32_t r2 = 0;
    uint32_t r3 = 0;
    uint32_t T = 0;
    /* 0x05A7BC: op 0x9269 */
    r2 = (uint32_t)(int32_t)(int16_t)0x0000D28Eu;
    /* 0x05A7BE: mov.b @r2,r3 */
    uint32_t t2 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFD28E; /* RAM 0xFFFFD28E */
    r3 = t2;
    /* 0x05A7C0: op 0x9168 */
    r1 = (uint32_t)(int32_t)(int16_t)0x80u;
    /* 0x05A7C2: op 0x633C */
    r3 = r3 & 0xFFu;
    /* 0x05A7C4: op 0x3310 */
    T = (r3 == r1) ? 1u : 0u;
    /* 0x05A7C6: bf.s 0x05A7D0 */
    /* 0x05A7C8: op 0x0009 */
    
    if (!T) goto L_5A7D0;
    /* 0x05A7CA: op 0xE001 */
    r0 = (uint32_t)(int32_t)(int8_t)0x01;
    /* 0x05A7CC: op 0x9363 */
    r3 = (uint32_t)(int32_t)(int16_t)0x0000D2A3u;
    /* 0x05A7CE: mov.b r0,@r3 */
    *(volatile uint8_t*)0xFFFFD2A3 = r0; /* RAM 0xFFFFD2A3 */
    L_5A7D0: ;
    /* 0x05A7D0: rts */
    /* 0x05A7D2: op 0x0009 */
    
    return r0;
    return r0; /* fallthrough */
}
