/* ROM: 60E1D400 | Address: 0xE07E | Size: 10 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift.py - not human-verified.
 * Pure straight-line function: no calls, no memory side effects. */
#include <stdint.h>
uint32_t fuel_trim_channel_inputs_map_e07e(uint32_t r4, uint32_t r5, uint32_t r6, uint32_t r7)
{
    /* params (possibly) */
    uint32_t r0 = 0;
    uint32_t r10 = 0;
    uint32_t r11 = 0;
    uint32_t r12 = 0;
    uint32_t r13 = 0;
    /* 0x00E07E: op 0xEB00 */
    r11 = (uint32_t)(int32_t)(int8_t)0x00;
    /* 0x00E080: op 0xD441 */
    r4 = 0x0004E960u;
    /* 0x00E082: op 0xEA10 */
    r10 = (uint32_t)(int32_t)(int8_t)0x10;
    /* 0x00E084: op 0xDC41 */
    r12 = 0x00009CC6u;
    /* 0x00E086: op 0x6D43 */
    r13 = r4;
    return r0;
}
