/* ROM: 60E0FC00 | Address: 0x10EAC | Size: 38 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v3.py — not human-verified.
 * v3: branches + delay slots. */
#include <stdint.h>
uint32_t fuel_cut_bits_merge_10eac(uint32_t r4, uint32_t r5, uint32_t r6, uint32_t r7)
{
    /* params (possibly) */
    uint32_t r0 = 0;
    uint32_t r1 = 0;
    uint32_t r2 = 0;
    uint32_t r3 = 0;
    uint32_t T = 0;
    /* 0x010EAC: op 0x9379 */
    r3 = (uint32_t)(int32_t)(int16_t)0x0000A5D8u;
    /* 0x010EAE: op 0xD541 */
    r5 = 0xFFFFA578u;
    /* 0x010EB0: mov.b @r5,r2 */
    uint32_t t2 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFA578; /* RAM 0xFFFFA578 */
    r2 = t2;
    /* 0x010EB2: op 0x2228 */
    T = ((r2 & r2) == 0u) ? 1u : 0u;
    /* 0x010EB4: bf.s 0x010EBE */
    /* 0x010EB6: mov.w @r3,r4 */
    uint32_t t4 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)0xFFFFA5D8; /* RAM 0xFFFFA5D8 */
    r4 = t4;
    if (!T) goto L_10EBE;
    /* 0x010EB8: op 0x9174 */
    r1 = (uint32_t)(int32_t)(int16_t)0x0000A5DAu;
    /* 0x010EBA: mov.w @r1,r0 */
    uint32_t t6 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)0xFFFFA5DA; /* RAM 0xFFFFA5DA */
    r0 = t6;
    /* 0x010EBC: op 0x240B */
    r4 |= r0;
    L_10EBE: ;
    /* 0x010EBE: op 0xE02C */
    r0 = (uint32_t)(int32_t)(int8_t)0x2C;
    /* 0x010EC0: mov.b @(r0,r5),r3 */
    uint32_t t8 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)(0xFFFFA578 + r0); /* RAM 0xFFFFA578 */
    r3 = t8;
    /* 0x010EC2: op 0x2338 */
    T = ((r3 & r3) == 0u) ? 1u : 0u;
    /* 0x010EC4: bf.s 0x010ECE */
    /* 0x010EC6: op 0x0009 */
    
    if (!T) goto L_10ECE;
    /* 0x010EC8: op 0x926D */
    r2 = (uint32_t)(int32_t)(int16_t)0x0000A5DCu;
    /* 0x010ECA: mov.w @r2,r1 */
    uint32_t t10 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)0xFFFFA5DC; /* RAM 0xFFFFA5DC */
    r1 = t10;
    /* 0x010ECC: op 0x241B */
    r4 |= r1;
    L_10ECE: ;
    /* 0x010ECE: rts */
    /* 0x010ED0: op 0x6043 */
    r0 = r4;
    return r0;
    return r0; /* fallthrough */
}
