/* ROM: 60E1D400 | Address: 0x22BBA | Size: 12 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v3.py — not human-verified.
 * End: estimated (next_addr 0x022BC6)
 * v3: branches + delay slots. */
#include <stdint.h>
uint32_t FUN_00022bba_22bba(uint32_t r4, uint32_t r5, uint32_t r6, uint32_t r7)
{
    /* params (possibly) */
    uint32_t r0 = 0;
    /* 0x022BBA: op 0x0009 */
    
    /* 0x022BBC: bra 0x022BC2 */
    /* 0x022BBE: mov.b r5,@r6 */
    *(volatile uint8_t*)r6 = r5;
    goto L_22BC2;
    /* 0x022BC0: mov.b r4,@r6 */
    *(volatile uint8_t*)r6 = r4;
    L_22BC2: ;
    /* 0x022BC2: rts */
    /* 0x022BC4: op 0x0009 */
    
    return r0;
    return r0; /* fallthrough */
}
