/* ROM: 60E1D400 | Address: 0x64746 | Size: 12 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift.py - not human-verified.
 * Pure straight-line function: no calls, no memory side effects. */
#include <stdint.h>
uint32_t FUN_00064746_64746(uint32_t r4, uint32_t r5, uint32_t r6, uint32_t r7)
{
    /* params (possibly) */
    uint32_t r0 = 0;
    uint32_t r2 = 0;
    uint32_t r3 = 0;
    uint32_t r9 = 0;
    uint32_t r12 = 0;
    uint32_t r13 = 0;
    uint32_t macl = 0;
    /* 0x064746: op 0x676C */
    r7 = r6 & 0xFFu;
    /* 0x064748: op 0x0D97 */
    macl = (uint32_t)((int32_t)r13 * (int32_t)r9);
    /* 0x06474A: op 0x624C */
    r2 = r4 & 0xFFu;
    /* 0x06474C: op 0xD31C */
    r3 = 0xFFFF8930u;
    /* 0x06474E: op 0x0C1A */
    r12 = macl;
    /* 0x064750: op 0x3C3C */
    r12 = r12 + r3;
    return r0;
}
