/* ROM: 60E1D400 | Address: 0x4B260 | Size: 46 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v3.py — not human-verified.
 * End: estimated (next_addr 0x04B28E)
 * v3: branches + delay slots. */
#include <stdint.h>
uint32_t FUN_0004b260_4b260(uint32_t r4, uint32_t r5, uint32_t r6, uint32_t r7)
{
    /* params (possibly) */
    uint32_t r0 = 0;
    uint32_t r2 = 0;
    uint32_t r3 = 0;
    uint32_t T = 0;
    /* 0x04B260: bra 0x04B266 */
    /* 0x04B262: mov.b r7,@r6 */
    *(volatile uint8_t*)r6 = r7;
    goto L_4B266;
    /* 0x04B264: mov.b r4,@r6 */
    *(volatile uint8_t*)r6 = r4;
    L_4B266: ;
    /* 0x04B266: op 0x9329 */
    r3 = (uint32_t)(int32_t)(int16_t)0x0000CDBCu;
    /* 0x04B268: mov.b @r3,r0 */
    uint32_t t2 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFCDBC; /* RAM 0xFFFFCDBC */
    r0 = t2;
    /* 0x04B26A: op 0x600C */
    r0 = r0 & 0xFFu;
    /* 0x04B26C: op 0x8801 */
    T = ((int32_t)r0 == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x04B26E: bt.s 0x04B27E */
    /* 0x04B270: op 0x0009 */
    
    if (T) goto L_4B27E;
    /* 0x04B272: op 0x9224 */
    r2 = (uint32_t)(int32_t)(int16_t)0x0000CDBEu;
    /* 0x04B274: mov.b @r2,r0 */
    uint32_t t4 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFCDBE; /* RAM 0xFFFFCDBE */
    r0 = t4;
    /* 0x04B276: op 0x600C */
    r0 = r0 & 0xFFu;
    /* 0x04B278: op 0x8801 */
    T = ((int32_t)r0 == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x04B27A: bf.s 0x04B282 */
    /* 0x04B27C: op 0x0009 */
    
    if (!T) goto L_4B282;
    L_4B27E: ;
    /* 0x04B27E: bra 0x04B28A */
    /* 0x04B280: mov.b r7,@r5 */
    *(volatile uint8_t*)r5 = r7;
    goto L_4B28A;
    L_4B282: ;
    /* 0x04B282: bra 0x04B28A */
    /* 0x04B284: mov.b r4,@r5 */
    *(volatile uint8_t*)r5 = r4;
    goto L_4B28A;
    /* 0x04B286: mov.b r4,@r6 */
    *(volatile uint8_t*)r6 = r4;
    /* 0x04B288: mov.b r4,@r5 */
    *(volatile uint8_t*)r5 = r4;
    L_4B28A: ;
    /* 0x04B28A: rts */
    /* 0x04B28C: op 0x0009 */
    
    return r0;
    return r0; /* fallthrough */
}
