/* ROM: 60E0FC00 | Address: 0x5CDE8 | Size: 24 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v3.py — not human-verified.
 * v3: branches + delay slots. */
#include <stdint.h>
uint32_t get_braking_or_in_neutral_5cde8(uint32_t r4, uint32_t r5, uint32_t r6, uint32_t r7)
{
    uint32_t r0 = 0;
    uint32_t r1 = 0;
    uint32_t r2 = 0;
    uint32_t r3 = 0;
    /* 0x05CDE8: op 0x9130 */
    r1 = (uint32_t)(int32_t)(int16_t)0x0000D19Cu;
    /* 0x05CDEA: mov.b @r1,r2 */
    uint32_t t2 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFD19C; /* RAM 0xFFFFD19C */
    r2 = t2;
    /* 0x05CDEC: op 0xD01A */
    r0 = 0xFFFFD1A4u;
    /* 0x05CDEE: mov.b r2,@r0 */
    *(volatile uint8_t*)0xFFFFD1A4 = r2; /* RAM 0xFFFFD1A4 */
    /* 0x05CDF0: op 0x922D */
    r2 = (uint32_t)(int32_t)(int16_t)0x0000D19Du;
    /* 0x05CDF2: op 0xE010 */
    r0 = (uint32_t)(int32_t)(int8_t)0x10;
    /* 0x05CDF4: op 0xD119 */
    r1 = 0xFFFFD1A5u;
    /* 0x05CDF6: mov.b @r2,r3 */
    uint32_t t4 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFD19D; /* RAM 0xFFFFD19D */
    r3 = t4;
    /* 0x05CDF8: mov.b r3,@r1 */
    *(volatile uint8_t*)0xFFFFD1A5 = r3; /* RAM 0xFFFFD1A5 */
    /* 0x05CDFA: op 0xD319 */
    r3 = 0xFFFFD1A6u;
    /* 0x05CDFC: rts */
    /* 0x05CDFE: mov.b r0,@r3 */
    *(volatile uint8_t*)0xFFFFD1A6 = r0; /* RAM 0xFFFFD1A6 */
    return r0;
    return r0; /* fallthrough */
}
