/* ROM: 60E0FC00 | Address: 0x15D60 | Size: 22 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v3.py — not human-verified.
 * v3: branches + delay slots + v4 FPU (frN bit-pattern locals; fpul/fpscr). */
#include <stdint.h>
#include <math.h>
uint32_t idle_corr_sum_add_a884_15d60(uint32_t r4, uint32_t r5, uint32_t r6, uint32_t r7)
{
    uint32_t r0 = 0;
    uint32_t r1 = 0;
    uint32_t r2 = 0;
    uint32_t r3 = 0;
    uint32_t fr2 = 0;
    uint32_t fr3 = 0;
    /* 0x015D60: op 0x9306 */
    r3 = (uint32_t)(int32_t)(int16_t)0x0000A7A4u;
    /* 0x015D62: fmov.s @r3,fr3 */
    fr3 = *(volatile uint32_t*)0xFFFFA7A4; /* RAM 0xFFFFA7A4 */
    /* 0x015D64: op 0x9205 */
    r2 = (uint32_t)(int32_t)(int16_t)0x0000A8C8u;
    /* 0x015D66: fmov.s @r2,fr2 */
    fr2 = *(volatile uint32_t*)0xFFFFA8C8; /* RAM 0xFFFFA8C8 */
    /* 0x015D68: op 0x9104 */
    r1 = (uint32_t)(int32_t)(int16_t)0x0000A884u;
    /* 0x015D6A: fadd fr3,fr2 */
    { union { uint32_t u; float f; } _a, _b, _r; _a.u = fr2; _b.u = fr3; _r.f = _a.f + _b.f; fr2 = _r.u; }
    /* 0x015D6C: rts */
    /* 0x015D6E: fmov.s fr2,@r1 */
    *(volatile uint32_t*)0xFFFFA884 = fr2; /* RAM 0xFFFFA884 */
    return r0;
    return r0; /* fallthrough */
}
