/* ROM: 60E0FC00 | Address: 0x4D532 | Size: 10 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v3.py — not human-verified.
 * v3: branches + delay slots + v4 FPU (frN bit-pattern locals; fpul/fpscr). */
#include <stdint.h>
#include <math.h>
uint32_t init_const_float_ce10_4d532(uint32_t r4, uint32_t r5, uint32_t r6, uint32_t r7)
{
    uint32_t r0 = 0;
    uint32_t r3 = 0;
    uint32_t fr3 = 0;
    /* 0x04D532: op 0xC71A */
    r0 = 0x0004D59Cu;
    /* 0x04D534: op 0x9319 */
    r3 = (uint32_t)(int32_t)(int16_t)0x0000CE10u;
    /* 0x04D536: fmov.s @r0,fr3 */
    fr3 = *(volatile uint32_t*)0x0004D59C; /* ROM */
    /* 0x04D538: rts */
    /* 0x04D53A: fmov.s fr3,@r3 */
    *(volatile uint32_t*)0xFFFFCE10 = fr3; /* RAM 0xFFFFCE10 */
    return r0;
    return r0; /* fallthrough */
}
