/* ROM: 60E1D400 | Address: 0x5E878 | Size: 24 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v3.py — not human-verified.
 * v3: branches + delay slots. */
#include <stdint.h>
uint32_t interrupt_state_update_5E878_5e878(uint32_t r4, uint32_t r5, uint32_t r6, uint32_t r7)
{
    /* params (possibly) */
    uint32_t r0 = 0;
    uint32_t r1 = 0;
    uint32_t r2 = 0;
    uint32_t r3 = 0;
    uint32_t T = 0;
    /* 0x05E878: op 0xD20A */
    r2 = 0xFFFFD3B6u;
    /* 0x05E87A: mov.w @r2,r3 */
    uint32_t t2 = (uint32_t)(int32_t)(int16_t)*(volatile uint16_t*)0xFFFFD3B6; /* RAM 0xFFFFD3B6 */
    r3 = t2;
    /* 0x05E87C: op 0x9108 */
    r1 = (uint32_t)(int32_t)(int16_t)0x00000271u;
    /* 0x05E87E: op 0x633D */
    r3 = r3 & 0xFFFFu;
    /* 0x05E880: op 0x3313 */
    T = ((int32_t)r3 >= (int32_t)r1) ? 1u : 0u;
    /* 0x05E882: bf.s 0x05E88A */
    /* 0x05E884: op 0x0009 */
    
    if (!T) goto L_5E88A;
    /* 0x05E886: bra 0x05E88C */
    /* 0x05E888: op 0xE400 */
    r4 = (uint32_t)(int32_t)(int8_t)0x00;
    goto L_5E88C;
    L_5E88A: ;
    /* 0x05E88A: op 0xE401 */
    r4 = (uint32_t)(int32_t)(int8_t)0x01;
    L_5E88C: ;
    /* 0x05E88C: rts */
    /* 0x05E88E: op 0x6043 */
    r0 = r4;
    return r0;
    return r0; /* fallthrough */
}
