/* ROM: 60E1D400 | Address: 0x3CF08 | Size: 64 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v3.py — not human-verified.
 * v3: branches + delay slots. */
#include <stdint.h>
uint32_t isr_config_3cf08_3cf08(uint32_t r4, uint32_t r5, uint32_t r6, uint32_t r7)
{
    /* params (possibly) */
    uint32_t r0 = 0;
    uint32_t r1 = 0;
    uint32_t r2 = 0;
    uint32_t r3 = 0;
    uint32_t T = 0;
    /* 0x03CF08: op 0x9665 */
    r6 = (uint32_t)(int32_t)(int16_t)0x0000C627u;
    /* 0x03CF0A: op 0x9565 */
    r5 = (uint32_t)(int32_t)(int16_t)0x0000C628u;
    /* 0x03CF0C: op 0x9365 */
    r3 = (uint32_t)(int32_t)(int16_t)0x0000D201u;
    /* 0x03CF0E: mov.b @r3,r0 */
    uint32_t t2 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFD201; /* RAM 0xFFFFD201 */
    r0 = t2;
    /* 0x03CF10: op 0x600C */
    r0 = r0 & 0xFFu;
    /* 0x03CF12: op 0x8801 */
    T = ((int32_t)r0 == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x03CF14: bf.s 0x03CF1E */
    /* 0x03CF16: op 0xE400 */
    r4 = (uint32_t)(int32_t)(int8_t)0x00;
    if (!T) goto L_3CF1E;
    /* 0x03CF18: mov.b r4,@r6 */
    *(volatile uint8_t*)0xFFFFC627 = r4; /* RAM 0xFFFFC627 */
    /* 0x03CF1A: bra 0x03CF44 */
    /* 0x03CF1C: mov.b r4,@r5 */
    *(volatile uint8_t*)0xFFFFC628 = r4; /* RAM 0xFFFFC628 */
    goto L_3CF44;
    L_3CF1E: ;
    /* 0x03CF1E: op 0x915D */
    r1 = (uint32_t)(int32_t)(int16_t)0x0000C615u;
    /* 0x03CF20: mov.b @r1,r2 */
    uint32_t t4 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFC615; /* RAM 0xFFFFC615 */
    r2 = t4;
    /* 0x03CF22: op 0x2228 */
    T = ((r2 & r2) == 0u) ? 1u : 0u;
    /* 0x03CF24: bf.s 0x03CF2A */
    /* 0x03CF26: op 0xE701 */
    r7 = (uint32_t)(int32_t)(int8_t)0x01;
    if (!T) goto L_3CF2A;
    /* 0x03CF28: mov.b r7,@r5 */
    *(volatile uint8_t*)0xFFFFC628 = r7; /* RAM 0xFFFFC628 */
    L_3CF2A: ;
    /* 0x03CF2A: mov.b @r5,r0 */
    uint32_t t6 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFC628; /* RAM 0xFFFFC628 */
    r0 = t6;
    /* 0x03CF2C: op 0x600C */
    r0 = r0 & 0xFFu;
    /* 0x03CF2E: op 0x8801 */
    T = ((int32_t)r0 == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x03CF30: bf.s 0x03CF38 */
    /* 0x03CF32: op 0x0009 */
    
    if (!T) goto L_3CF38;
    /* 0x03CF34: bra 0x03CF44 */
    /* 0x03CF36: mov.b r4,@r6 */
    *(volatile uint8_t*)0xFFFFC627 = r4; /* RAM 0xFFFFC627 */
    goto L_3CF44;
    L_3CF38: ;
    /* 0x03CF38: op 0x9251 */
    r2 = (uint32_t)(int32_t)(int16_t)0x0000C614u;
    /* 0x03CF3A: mov.b @r2,r3 */
    uint32_t t8 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFC614; /* RAM 0xFFFFC614 */
    r3 = t8;
    /* 0x03CF3C: op 0x2338 */
    T = ((r3 & r3) == 0u) ? 1u : 0u;
    /* 0x03CF3E: bf.s 0x03CF44 */
    /* 0x03CF40: op 0x0009 */
    
    if (!T) goto L_3CF44;
    /* 0x03CF42: mov.b r7,@r6 */
    *(volatile uint8_t*)0xFFFFC627 = r7; /* RAM 0xFFFFC627 */
    L_3CF44: ;
    /* 0x03CF44: rts */
    /* 0x03CF46: op 0x0009 */
    
    return r0;
    return r0; /* fallthrough */
}
