/* ROM: 60E1D400 | Address: 0x54E4E | Size: 20 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v3.py — not human-verified.
 * End: estimated (next_addr 0x054E62)
 * v3: branches + delay slots. */
#include <stdint.h>
uint32_t obd_pid_emit_53804_54e4e(uint32_t r4, uint32_t r5, uint32_t r6, uint32_t r7)
{
    /* params (possibly) */
    uint32_t r0 = 0;
    uint32_t r1 = 0;
    uint32_t r2 = 0;
    uint32_t r15 = 0;
    uint32_t T = 0;
    uint32_t pr = 0xEEEE0000u;
    uint32_t local_404 = 0;
    /* 0x054E4E: op 0x611C */
    r1 = r1 & 0xFFu;
    /* 0x054E50: op 0x3120 */
    T = (r1 == r2) ? 1u : 0u;
    /* 0x054E52: bt.s 0x054E5A */
    /* 0x054E54: op 0x0009 */
    
    if (T) goto L_54E5A;
    /* 0x054E56: op 0xE001 */
    r0 = (uint32_t)(int32_t)(int8_t)0x01;
    /* 0x054E58: mov.b r0,@r4 */
    *(volatile uint8_t*)r4 = r0;
    L_54E5A: ;
    /* 0x054E5A: op 0x7F04 */
    r15 = r15 + (uint32_t)(int32_t)(int8_t)0x04;
    /* 0x054E5C: lds.l @r15+,pr */
    pr = local_404;
    /* 0x054E5E: rts */
    /* 0x054E60: op 0x0009 */
    
    return r0;
    return r0; /* fallthrough */
}
