/* ROM: 60E0FC00 | Address: 0xE044 | Size: 8 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v3.py — not human-verified.
 * End: estimated (next_addr 0x00E04C)
 * v3: branches + delay slots. */
#include <stdint.h>
uint32_t setCANRXBool_e044(uint32_t r4, uint32_t r5, uint32_t r6, uint32_t r7)
{
    uint32_t r0 = 0;
    uint32_t r3 = 0;
    /* 0x00E044: op 0x900B */
    r0 = (uint32_t)(int32_t)(int16_t)0x0000A406u;
    /* 0x00E046: op 0xE301 */
    r3 = (uint32_t)(int32_t)(int8_t)0x01;
    /* 0x00E048: rts */
    /* 0x00E04A: mov.b r3,@r0 */
    *(volatile uint8_t*)0xFFFFA406 = r3; /* RAM 0xFFFFA406 */
    return r0;
    return r0; /* fallthrough */
}
