/* ROM: 60E0FC00 | Address: 0x2C8AC | Size: 102 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v3.py — not human-verified.
 * End: estimated (next_addr 0x02C912)
 * v3: branches + delay slots. */
#include <stdint.h>
uint32_t setGearBools_2c8ac(uint32_t r4, uint32_t r5, uint32_t r6, uint32_t r7)
{
    /* params (possibly) */
    uint32_t r0 = 0;
    uint32_t r1 = 0;
    uint32_t r2 = 0;
    uint32_t r3 = 0;
    uint32_t T = 0;
    /* 0x02C8AC: op 0x9369 */
    r3 = (uint32_t)(int32_t)(int16_t)0x0000C61Au;
    /* 0x02C8AE: op 0xE400 */
    r4 = (uint32_t)(int32_t)(int8_t)0x00;
    /* 0x02C8B0: mov.b @r3,r0 */
    uint32_t t2 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFC61A; /* RAM 0xFFFFC61A */
    r0 = t2;
    /* 0x02C8B2: op 0x6543 */
    r5 = r4;
    /* 0x02C8B4: op 0x6643 */
    r6 = r4;
    /* 0x02C8B6: op 0x6743 */
    r7 = r4;
    /* 0x02C8B8: op 0x600C */
    r0 = r0 & 0xFFu;
    /* 0x02C8BA: op 0x8801 */
    T = ((int32_t)r0 == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x02C8BC: bt.s 0x02C8FA */
    /* 0x02C8BE: op 0xE401 */
    r4 = (uint32_t)(int32_t)(int8_t)0x01;
    if (T) goto L_2C8FA;
    /* 0x02C8C0: op 0x9260 */
    r2 = (uint32_t)(int32_t)(int16_t)0x0000B580u;
    /* 0x02C8C2: mov.b @r2,r0 */
    uint32_t t4 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFB580; /* RAM 0xFFFFB580 */
    r0 = t4;
    /* 0x02C8C4: op 0x600C */
    r0 = r0 & 0xFFu;
    /* 0x02C8C6: op 0x8801 */
    T = ((int32_t)r0 == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x02C8C8: bf.s 0x02C904 */
    /* 0x02C8CA: op 0x0009 */
    
    if (!T) goto L_2C904;
    /* 0x02C8CC: op 0x915B */
    r1 = (uint32_t)(int32_t)(int16_t)0x0000BC74u;
    /* 0x02C8CE: mov.b @r1,r0 */
    uint32_t t6 = (uint32_t)(int32_t)(int8_t)*(volatile uint8_t*)0xFFFFBC74; /* RAM 0xFFFFBC74 */
    r0 = t6;
    /* 0x02C8D0: op 0x600C */
    r0 = r0 & 0xFFu;
    /* 0x02C8D2: op 0x8801 */
    T = ((int32_t)r0 == (int32_t)(int8_t)0x01) ? 1u : 0u;
    /* 0x02C8D4: bt.s 0x02C8FA */
    /* 0x02C8D6: op 0x0009 */
    
    if (T) goto L_2C8FA;
    /* 0x02C8D8: op 0x8802 */
    T = ((int32_t)r0 == (int32_t)(int8_t)0x02) ? 1u : 0u;
    /* 0x02C8DA: bt.s 0x02C8FA */
    /* 0x02C8DC: op 0x0009 */
    
    if (T) goto L_2C8FA;
    /* 0x02C8DE: op 0x8803 */
    T = ((int32_t)r0 == (int32_t)(int8_t)0x03) ? 1u : 0u;
    /* 0x02C8E0: bt.s 0x02C8FE */
    /* 0x02C8E2: op 0x0009 */
    
    if (T) goto L_2C8FE;
    /* 0x02C8E4: op 0x8804 */
    T = ((int32_t)r0 == (int32_t)(int8_t)0x04) ? 1u : 0u;
    /* 0x02C8E6: bt.s 0x02C8FE */
    /* 0x02C8E8: op 0x0009 */
    
    if (T) goto L_2C8FE;
    /* 0x02C8EA: op 0x8805 */
    T = ((int32_t)r0 == (int32_t)(int8_t)0x05) ? 1u : 0u;
    /* 0x02C8EC: bt.s 0x02C902 */
    /* 0x02C8EE: op 0x0009 */
    
    if (T) goto L_2C902;
    /* 0x02C8F0: op 0x8806 */
    T = ((int32_t)r0 == (int32_t)(int8_t)0x06) ? 1u : 0u;
    /* 0x02C8F2: bt.s 0x02C902 */
    /* 0x02C8F4: op 0x0009 */
    
    if (T) goto L_2C902;
    /* 0x02C8F6: bra 0x02C904 */
    /* 0x02C8F8: op 0x0009 */
    
    goto L_2C904;
    L_2C8FA: ;
    /* 0x02C8FA: bra 0x02C904 */
    /* 0x02C8FC: op 0x6543 */
    r5 = r4;
    goto L_2C904;
    L_2C8FE: ;
    /* 0x02C8FE: bra 0x02C904 */
    /* 0x02C900: op 0x6643 */
    r6 = r4;
    goto L_2C904;
    L_2C902: ;
    /* 0x02C902: op 0x6743 */
    r7 = r4;
    L_2C904: ;
    /* 0x02C904: op 0x9240 */
    r2 = (uint32_t)(int32_t)(int16_t)0x0000BC76u;
    /* 0x02C906: mov.b r5,@r2 */
    *(volatile uint8_t*)0xFFFFBC76 = r5; /* RAM 0xFFFFBC76 */
    /* 0x02C908: op 0x933F */
    r3 = (uint32_t)(int32_t)(int16_t)0x0000BC77u;
    /* 0x02C90A: mov.b r6,@r3 */
    *(volatile uint8_t*)0xFFFFBC77 = r6; /* RAM 0xFFFFBC77 */
    /* 0x02C90C: op 0x913E */
    r1 = (uint32_t)(int32_t)(int16_t)0x0000BC78u;
    /* 0x02C90E: rts */
    /* 0x02C910: mov.b r7,@r1 */
    *(volatile uint8_t*)0xFFFFBC78 = r7; /* RAM 0xFFFFBC78 */
    return r0;
    return r0; /* fallthrough */
}
