/* ROM: 60E0FC00 | Address: 0x4315C | Size: 12 bytes | STATUS: DRAFT
 * Auto-generated by tools/gen_c_lift_v3.py — not human-verified.
 * End: estimated (next_addr 0x043168)
 * v3: branches + delay slots + v4 FPU (frN bit-pattern locals; fpul/fpscr). */
#include <stdint.h>
#include <math.h>
uint32_t throttleLiftInitStuff_4315c(uint32_t r4, uint32_t r5, uint32_t r6, uint32_t r7)
{
    uint32_t r0 = 0;
    uint32_t r2 = 0;
    uint32_t r3 = 0;
    uint32_t fr4 = 0;
    /* 0x04315C: op 0xD340 */
    r3 = 0xFFFFC9A8u;
    /* 0x04315E: fldi0 fr4 */
    fr4 = 0u;
    /* 0x043160: op 0x9277 */
    r2 = (uint32_t)(int32_t)(int16_t)0x0000C9A0u;
    /* 0x043162: fmov.s fr4,@r3 */
    *(volatile uint32_t*)0xFFFFC9A8 = fr4; /* RAM 0xFFFFC9A8 */
    /* 0x043164: rts */
    /* 0x043166: fmov.s fr4,@r2 */
    *(volatile uint32_t*)0xFFFFC9A0 = fr4; /* RAM 0xFFFFC9A0 */
    return r0;
    return r0; /* fallthrough */
}
